### ISSUE TITLE
[BanyanDB][Bug] TimestampRange query throws an exception if no data in this time range.

### ISSUE THREAD

**Issue by wankai123** [apache/skywalking#10003]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

TimestampRange query throws an exception if no data in this time range.

```shell
2022-11-22 16:40:40,031 org.apache.skywalking.oap.query.zipkin.handler.ZipkinQueryExceptionHandler 41 [armeria-eventloop-nio-5-7] ERROR [] - [9.3.0-SNAPSHOT-e5950cc] fail to query stream
java.io.IOException: fail to query stream
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.query(BanyanDBStorageClient.java:104) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.stream.AbstractBanyanDBDAO.query(AbstractBanyanDBDAO.java:71) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBZipkinQueryDAO.getTraceIds(BanyanDBZipkinQueryDAO.java:248) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBZipkinQueryDAO.getTraces(BanyanDBZipkinQueryDAO.java:184) ~[classes/:?]
	at org.apache.skywalking.oap.query.zipkin.handler.ZipkinQueryHandler.getTraces(ZipkinQueryHandler.java:214) ~[classes/:?]
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:413) ~[armeria-1.18.0.jar:?]
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$8(AnnotatedService.java:382) ~[armeria-1.18.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_292]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_292]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:566) ~[armeria-1.18.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.81.Final.jar:4.1.81.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: org.apache.skywalking.banyandb.v1.client.grpc.exception.UnknownException: io.grpc.StatusRuntimeException: UNKNOWN: execute the query plan for stream zipkin_span: there is no data in such time range: invalid query message
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBApiExceptionFactory.createException(BanyanDBApiExceptionFactory.java:61) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.create(BanyanDBGrpcApiExceptionFactory.java:53) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.createException(BanyanDBGrpcApiExceptionFactory.java:41) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:47) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.query(BanyanDBClient.java:261) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.query(BanyanDBStorageClient.java:99) ~[classes/:?]
	... 19 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: execute the query plan for stream zipkin_span: there is no data in such time range: invalid query message
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.49.0.jar:1.49.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.49.0.jar:1.49.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.49.0.jar:1.49.0]
	at org.apache.skywalking.banyandb.stream.v1.StreamServiceGrpc$StreamServiceBlockingStub.query(StreamServiceGrpc.java:210) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.lambda$query$0(BanyanDBClient.java:264) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:45) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.query(BanyanDBClient.java:261) ~[banyandb-java-client-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.query(BanyanDBStorageClient.java:99) ~[classes/:?]
	... 19 more
```

### What you expected to happen

response 0 results set, rather than throw an exception.

### How to reproduce

make a time range query and no data in this range.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
Fixed by https://github.com/apache/skywalking-banyandb/commit/46b57a4eb42685a107a2394f859ac938bacdcd4b#diff-444142c02d585cc859622f24c6ee708bd7e78936546b7fed24b05811ad91dbbeR117
