### ISSUE TITLE
skywalking v9.3: no data in k8s service  

### ISSUE THREAD

**Issue by geniuslc11** [apache/skywalking#10230]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Hi skywalking team,
  Recently I am researching the new features in skywalking v9.3,and found it has datas in cluster but no data in service when monitoring k8s node and endpoints, and found some error messages in OAP logs,please help to fix this issue,thanks.

I used showcase configurations to monitor it.

k8s version :1.20.* and 1.21.*
otel collector version: I tried version 0.50.0 and 0.68.0 etc, all failed.

```
2023-01-05 08:24:02,037 - org.apache.skywalking.oap.meter.analyzer.dsl.Expression - 89 [grpcServerPool-1-thread-1] ERROR [] - failed to run "(container_memory_working_set_bytes.tagNotEqual('container' , '').tagNotEqual('pod' , '').retagByK8sMeta('service' , K8sRetagType.Pod2Service , 'pod' , 'namespace').tagNotEqual('service' , '').sum(['cluster' , 'service' , 'pod'])).service(['cluster' , 'service'], '::', Layer.K8S_SERVICE)"
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.kubernetes.client.openapi.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.kubernetes.client.openapi.models.V1Pod
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2317) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2283) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.1-jre.jar:?]
        at org.apache.skywalking.oap.meter.analyzer.k8s.K8sInfoRegistry.findServiceName(K8sInfoRegistry.java:122) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.dsl.tagOpt.K8sRetagType$1.lambda$execute$0(K8sRetagType.java:40) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_261]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_261]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_261]
        at org.apache.skywalking.oap.meter.analyzer.dsl.tagOpt.K8sRetagType$1.execute(K8sRetagType.java:49) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily.retagByK8sMeta(SampleFamily.java:368) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily$retagByK8sMeta$9.call(Unknown Source) ~[?:?]
        at Script1.run(Script1.groovy:1) ~[?:?]
        at org.apache.skywalking.oap.meter.analyzer.dsl.Expression.run(Expression.java:78) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.Analyzer.analyse(Analyzer.java:133) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.MetricConvert.toMeter(MetricConvert.java:93) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.prometheus.PrometheusMetricConverter.toMeter(PrometheusMetricConverter.java:84) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.receiver.otel.otlp.OpenTelemetryMetricHandler.lambda$null$7(OpenTelemetryMetricHandler.java:128) ~[otel-receiver-plugin-9.3.0.jar:9.3.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
        at org.apache.skywalking.oap.server.receiver.otel.otlp.OpenTelemetryMetricHandler.lambda$export$8(OpenTelemetryMetricHandler.java:128) ~[otel-receiver-plugin-9.3.0.jar:9.3.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_261]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) [?:1.8.0_261]
        at org.apache.skywalking.oap.server.receiver.otel.otlp.OpenTelemetryMetricHandler.export(OpenTelemetryMetricHandler.java:110) [otel-receiver-plugin-9.3.0.jar:9.3.0]
        at io.opentelemetry.proto.collector.metrics.v1.MetricsServiceGrpc$MethodHandlers.invoke(MetricsServiceGrpc.java:246) [receiver-proto-9.3.0.jar:9.3.0]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [grpc-stub-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.49.0.jar:1.49.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.util.concurrent.ExecutionException: io.kubernetes.client.openapi.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.kubernetes.client.openapi.models.V1Pod
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113) ~[guava-31.1-jre.jar:?]
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2317) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2283) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.1-jre.jar:?]
        at org.apache.skywalking.library.kubernetes.KubernetesPods.findByObjectID(KubernetesPods.java:81) ~[library-kubernetes-support-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.meter.analyzer.k8s.K8sInfoRegistry.lambda$new$14(K8sInfoRegistry.java:80) ~[meter-analyzer-9.3.0.jar:9.3.0]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.1-jre.jar:?]
        ... 37 more
```

![cluster](https://user-images.githubusercontent.com/40260032/210677961-6bb78bcd-731e-4e3c-abf5-0d4daa4f6717.png)

![service](https://user-images.githubusercontent.com/40260032/210677968-34791b84-ef9e-4d50-a057-56341debfae6.png)

### What you expected to happen

there should collecting datas in k8s service.

### How to reproduce

steps refered by link https://skywalking.apache.org/docs/main/v9.3.0/en/setup/backend/backend-k8s-monitoring/ and https://github.com/apache/skywalking-showcase/tree/main/deploy/platform/kubernetes/feature-kubernetes-monitor

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
The demo.skywalking.apache.org is using this showcase without change. So, generally, showcase should be good.

From the logs, this should be key
> Caused by: java.util.concurrent.ExecutionException: io.kubernetes.client.openapi.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.kubernetes.client.openapi.models.V1Pod

Maybe your k8s is too old?

**Comment by geniuslc11** [comment]
Thanks so much for your quick reply.
Our k8s version are 1.20.6 ,1.21.7 and 1.17.4 ,they all failed with the same errors.
Maybe v1.17.4 is too old ,but I think the versions above 1.20.* is not too old.

**Comment by wu-sheng** [comment]
We are using 1.23.12-gke.1600 at Google Cloud, and everything works. Also, we tested AWS EKS, it works well too.

**Comment by wu-sheng** [comment]
If you check the k8s website, 1.22 is the oldest version, I am afraid. 

https://kubernetes.io/docs/home/supported-doc-versions/

**Comment by geniuslc11** [comment]
Just now I tried k8s v1.24.3 ,still failed with the same error,it is very strange.please check the following screenshots.

1\ k8s version
![k8s](https://user-images.githubusercontent.com/40260032/210720532-97c2bbb8-6407-42ff-8c57-a4def2d25312.png)

2\kube state metrics collecting datas.
![ksm](https://user-images.githubusercontent.com/40260032/210720510-3d026152-36bf-4e1b-b98c-9f0b0b6fde2e.png)

3\ skywalking ui 
![sk1](https://user-images.githubusercontent.com/40260032/210720587-b18975bb-c227-42d4-ab19-2fc52bf06e7c.png)
![sk2](https://user-images.githubusercontent.com/40260032/210720863-46c9d9c3-d269-46d0-a463-2d59168df18a.png)

4\oap logs
![sk3](https://user-images.githubusercontent.com/40260032/210724105-520decbb-3c9c-4683-ad3d-09e5d57b4d93.png)

**Comment by geniuslc11** [comment]
This is my otel collector configurations.
![cm](https://user-images.githubusercontent.com/40260032/210725842-d4135a03-d309-4136-a884-863370e8101e.png)

**Comment by wu-sheng** [comment]
What is the vendor of your k8s? Maybe you could ask them why they show differently from us.
Or, you could use KinD to test with official k8s locally. We did, and it works.

**Comment by geniuslc11** [comment]
We install k8s cluster by RKE in rancher v2.6,I will test KinD in our environment.

**Comment by liyongxian** [comment]
I meet the same prolem.
Skywalking Version: 9.3.0
![image](https://user-images.githubusercontent.com/18571576/220300465-20c2bad7-65bb-437c-b5ee-cee2f818d823.png)
K8s is installed by kubeadm.
Deployed by https://github.com/apache/skywalking-showcase/tree/main/deploy/platform/kubernetes/feature-kubernetes-monitor.
![image](https://user-images.githubusercontent.com/18571576/220301023-42b7bc74-8dbb-4cdf-8179-d34dbd24cfc3.png)
Thanks.

**Comment by liyongxian** [comment]
@geniuslc11  KIND Is OK ??

**Comment by geniuslc11** [comment]
@liyongxian ,  Not yet test in KIND due to busy in  some other important things, but I think it is no matter which method to create K8S, finally it should communicate with K8S api ,I have tried k8s version 1.24.6 still no data for K8S service. so I think there is some bug in skywalking. your error message in OAP logs is the same with me?

**Comment by innerpeacez** [comment]
I also encountered this problem, and finally found out that the clusterRole was missing during install. I tried to fix it. https://github.com/apache/skywalking-kubernetes/pull/111. but I still find that oap often throws this exception. And at least found that the service data is incomplete. 

I tried to debug this code KubernetesServices.list() got the complete service list. 
and I see missing the service through kube-state-metrics:8080/metrics I don't see the service in SkyWalking UI (nor in ES storage).

I'm now confused as to where could be the problem. The strange thing is that some services have it, and some services don't.

opentelemetry-collector:0.72.0
kube-state-metrics:v2.8.0
skywalking:9.3.0

Can you give me some ideas, let me continue to investigate this problem. @wu-sheng @kezhenxu94

**Comment by wu-sheng** [comment]
You could try showcase, and compare the version and deployment difference.

**Comment by innerpeacez** [comment]
> I also encountered this problem, and finally found out that the clusterRole was missing during install. I tried to fix it. [apache/skywalking-kubernetes#111](https://github.com/apache/skywalking-kubernetes/pull/111). but I still find that oap often throws this exception. And at least found that the service data is incomplete.

Sorry, I didn't find it and continue to throws this exception. But the service data is indeed incomplete.

> You could try showcase, and compare the version and deployment difference.

I'll switch versions and give it a try. thx.

**Comment by wu-sheng** [comment]
Including versions of apl components, otel collector was breaking many times.

**Comment by innerpeacez** [comment]
The problem of missing service is due to cache wrong, independent of `opentelemetry-collector` and `kube-state-metrics` version.（At least the version I tested）. see https://github.com/apache/skywalking/pull/10568

**Comment by innerpeacez** [comment]
Two reasons：
1. Lack of clusterRole during install causes oap to call k8s api without permission.
2. Some K8s services are missing due to service cache wroing.

**Comment by geniuslc11** [comment]
@innerpeacez ,so I need upgrade the skywalking version to v9.5? when will skywalking v9.5 be released?

**Comment by geniuslc11** [comment]
@innerpeacez Is there any workaround now to fix it?

**Comment by geniuslc11** [comment]
@innerpeacez BTW,my skywalking OAP is intalled by binary package in centos 7,not depolyed in K8S
