### ISSUE TITLE
[Bug] 9.3.0 start exception

### ISSUE THREAD

**Issue by JavaLionLi** [apache/skywalking#10283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Docker start skywalking-oap exception
Which step is incorrect, hope to guide

skywalking 9.3.0
elasticsearch 7.17.6

docker config
```
version: '3'

services:
  sky-oap-9:
    image: apache/skywalking-oap-server:9.3.0
    container_name: sky-oap-9
    environment:
      JAVA_OPTS: -Xmx4G
      #记录数据的有效期，单位天
      SW_CORE_RECORD_DATA_TTL: 7
      #分析指标数据的有效期，单位天
      SW_CORE_METRICS_DATA_TTL: 7
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 127.0.0.1:9200
      TZ: Asia/Shanghai
    network_mode: "host"
```

error info
```
2023-01-16 17:49:00,233 org.apache.skywalking.library.elasticsearch.client.TemplateClient 139 [armeria-eventloop-epoll-5-4] ERROR [] - [9.3.0-7ad0406] Failed to create / update index template sw_zipkin_span
2023-01-16T09:49:00.244701248Z java.util.concurrent.CompletionException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.244708306Z 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244710484Z 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244712157Z 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244713745Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244715272Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244716792Z 	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244718340Z 	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:103) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244719930Z 	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244724836Z 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244726445Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244727940Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.244729481Z 	at com.linecorp.armeria.common.stream.DeferredStreamMessage.lambda$delegate$0(DeferredStreamMessage.java:132) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244731985Z 	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:?]
2023-01-16T09:49:00.244733524Z 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:?]
2023-01-16T09:49:00.244735013Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?]
2023-01-16T09:49:00.244736495Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) [?:?]
2023-01-16T09:49:00.244737987Z 	at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244739594Z 	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:258) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244741166Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244742758Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244744278Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244745849Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244747396Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244748965Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244750554Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:436) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244752137Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:336) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244753681Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:373) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244755225Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:319) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244756775Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:309) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244758558Z 	at com.linecorp.armeria.client.Http1ResponseDecoder.channelRead(Http1ResponseDecoder.java:244) [armeria-1.18.0.jar:?]
2023-01-16T09:49:00.244761013Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244762618Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244764203Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244765829Z 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244767442Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) [netty-codec-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244768988Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) [netty-codec-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244770537Z 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244772074Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244773654Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244775197Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244776754Z 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) [netty-handler-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244778298Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244780262Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244781880Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244783476Z 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [netty-handler-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244785023Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244786584Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244788141Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244790668Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244792309Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244793881Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244795432Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244797061Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244798641Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) [netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244800181Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) [netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244801691Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244803537Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244805110Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.244806652Z 	at java.lang.Thread.run(Unknown Source) [?:?]
2023-01-16T09:49:00.244808145Z Caused by: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.244811388Z 	at org.apache.skywalking.library.elasticsearch.client.TemplateClient.lambda$null$9(TemplateClient.java:135) ~[library-elasticsearch-client-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.244812969Z 	... 57 more
2023-01-16T09:49:00.247724326Z 2023-01-16 17:49:00,244 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 60 [main] ERROR [] - [9.3.0-7ad0406] java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.247748092Z org.apache.skywalking.oap.server.library.module.ModuleStartException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.247752886Z 	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:250) ~[storage-elasticsearch-plugin-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247754910Z 	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) ~[library-module-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247756566Z 	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247760709Z 	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247762461Z 	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247764070Z Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.247767462Z 	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247768978Z 	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247770527Z 	at org.apache.skywalking.library.elasticsearch.client.TemplateClient.createOrUpdate(TemplateClient.java:146) ~[library-elasticsearch-client-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247772136Z 	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createOrUpdateTemplate(ElasticSearchClient.java:245) ~[library-client-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247774962Z 	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTimeSeriesTable(StorageEsInstaller.java:186) ~[storage-elasticsearch-plugin-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247776690Z 	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:130) ~[storage-elasticsearch-plugin-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247778312Z 	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:55) ~[server-core-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247780005Z 	at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:132) ~[server-core-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247781595Z 	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:248) ~[storage-elasticsearch-plugin-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247783239Z 	... 4 more
2023-01-16T09:49:00.247784713Z Caused by: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid"}],"type":"illegal_argument_exception","reason":"composable template [sw_zipkin_span] template after composition is invalid","caused_by":{"type":"illegal_argument_exception","reason":"invalid composite mappings for [sw_zipkin_span]","caused_by":{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [oap_analyzer] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [oap_analyzer] has not been configured in mappings"}}}},"status":400}
2023-01-16T09:49:00.247788001Z 	at org.apache.skywalking.library.elasticsearch.client.TemplateClient.lambda$null$9(TemplateClient.java:135) ~[library-elasticsearch-client-9.3.0.jar:9.3.0]
2023-01-16T09:49:00.247789577Z 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247791084Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247792572Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247794048Z 	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247795577Z 	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:103) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247797095Z 	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247798580Z 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247800076Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247801564Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247803274Z 	at com.linecorp.armeria.common.stream.DeferredStreamMessage.lambda$delegate$0(DeferredStreamMessage.java:132) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247804858Z 	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247807040Z 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247808546Z 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247810015Z 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
2023-01-16T09:49:00.247811503Z 	at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247813051Z 	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:258) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247814610Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247816187Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247817740Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247819293Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247820816Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247822348Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247823874Z 	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:436) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247825565Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:336) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247827157Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:373) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247828702Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:319) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247830574Z 	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:309) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247832147Z 	at com.linecorp.armeria.client.Http1ResponseDecoder.channelRead(Http1ResponseDecoder.java:244) ~[armeria-1.18.0.jar:?]
2023-01-16T09:49:00.247833682Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247835241Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247836792Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247854727Z 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247857613Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247859246Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247860773Z 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247862313Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247863876Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247865448Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247867060Z 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[netty-handler-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247868586Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247870364Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247871962Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247873505Z 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247875036Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247876590Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247878136Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247879710Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247881266Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247882831Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247885823Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247887390Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247888995Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247890529Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247892245Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247893870Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247895399Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.81.Final.jar:4.1.81.Final]
2023-01-16T09:49:00.247896942Z 	at java.lang.Thread.run(Unknown Source) ~[?:?]

```

### What you expected to happen

start success

### How to reproduce

start success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You need to remove all existing old templates.

**Comment by JavaLionLi** [comment]
> You need to remove all existing old templates.

ES is new and has nothing

**Comment by JavaLionLi** [comment]
> You need to remove all existing old templates.

Just change the computer and download es again.

**Comment by wu-sheng** [comment]
Sorry, we don't know what causes this. And we never faced this in testing(all CI tasks) and deployments, including the demo env you saw.
