### ISSUE TITLE
Performance analysis without data

### ISSUE THREAD

**Issue by JavaLionLi** [apache/skywalking#10337]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/31852897/216558750-b75c4875-c533-4ab1-85a9-dc1a0bd6a02a.png)
![image](https://user-images.githubusercontent.com/31852897/216558930-e09146b7-f1ba-4231-ba79-3fe0a617d8e5.png)
![image](https://user-images.githubusercontent.com/31852897/216559089-1c7c78de-6792-4fd1-82c6-4e82ac6a1e0a.png)

Performance analysis without data
I have requested more than 10 times, but there is still no data.
The service has not been restarted in the middle.
sky 9.3.0
agent 8.13.0
es 7.17.6

### What you expected to happen

Hope to have data

### How to reproduce

new task, request interface

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JavaLionLi** [comment]
agent error log

```

ERROR 2023-02-03 17:01:01.390 main StaticMethodsInter : class[class org.apache.dubbo.common.bytecode.Wrapper] before static method[makeWrapper] intercept failure 
java.lang.RuntimeException: org.apache.dubbo.common.bytecode.ClassGenerator.toClass()Ljava/lang/Class;
	at org.apache.skywalking.apm.plugin.asf.dubbo3.patch.MakeWrapperInterceptor.makeWrapper(MakeWrapperInterceptor.java:265)
	at org.apache.skywalking.apm.plugin.asf.dubbo3.patch.MakeWrapperInterceptor.beforeMethod(MakeWrapperInterceptor.java:49)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:73)
	at org.apache.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:122)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory.getInvoker(JavassistProxyFactory.java:67)
	at org.apache.dubbo.rpc.proxy.wrapper.StubProxyFactoryWrapper.getInvoker(StubProxyFactoryWrapper.java:120)
	at org.apache.dubbo.rpc.ProxyFactory$Adaptive.getInvoker(ProxyFactory$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:691)
	at org.apache.dubbo.config.ServiceConfig.exportLocal(ServiceConfig.java:711)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:597)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:423)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:407)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:369)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:241)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:350)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:322)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:158)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:139)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.ruoyi.system.RuoYiSystemApplication.main(RuoYiSystemApplication.java:19)
Caused by: java.lang.NoSuchMethodError: org.apache.dubbo.common.bytecode.ClassGenerator.toClass()Ljava/lang/Class;
	at org.apache.skywalking.apm.plugin.asf.dubbo3.patch.MakeWrapperInterceptor.makeWrapper(MakeWrapperInterceptor.java:252)
	... 34 more
```

**Comment by wu-sheng** [comment]
There is no more I can say about profiling.
That error usually means this Dubbo version is not supported.
Shadow trace dump is either super long trace or plugin bug.

Please don't repeat submittint issues. Issue is only tracking known bugs that someone will work on. Others are kept in discussion.
