### ISSUE TITLE
[Bug] Skywalking-java enhanced jdk thread pool failed

### ISSUE THREAD

**Issue by Zwl0113** [apache/skywalking#10374]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When moving apm-jdk-threadpool-plugin-8.11.0.jar in bootstrap plugins to plugins,The service will fail to start

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.util.ServiceConfigurationError: org.apache.skywalking.apm.agent.core.boot.BootService: Provider org.apache.skywalking.apm.agent.core.profile.ProfileTaskExecutionService could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.load(ServiceManager.java:144)
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.loadAllServices(ServiceManager.java:62)
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.boot(ServiceManager.java:42)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:136)
	... 6 more
Caused by: java.lang.ClassCircularityError: java/util/concurrent/ThreadPoolExecutor
	at java.util.concurrent.Executors.newSingleThreadScheduledExecutor(Executors.java:272)
	at org.apache.skywalking.apm.agent.core.profile.ProfileTaskExecutionService.<clinit>(ProfileTaskExecutionService.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 12 more
FATAL ERROR in native method: processing of -javaagent failed
Disconnected from the target VM, address: '127.0.0.1:50466', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

### What you expected to happen

Is it possible that skywalking uses jdk's native thread pool internally, resulting in loop enhancement?

### How to reproduce

When moving apm-jdk-threadpool-plugin-8.11.0.jar in bootstrap plugins to plugins,The service will fail to start

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Sorry, we don't know why this happens. We tested it with OpenJDK, it works. 
Maybe something special on your side


This is how we tested. It works for every commit.

https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/jdk-threadpool-scenario

**Comment by Zwl0113** [comment]
The thread pool plug-in itself is OK, but this problem will occur when the package is moved from bootstrap-plugins to plugins and other plugins, so your single test is passed

**Comment by Zwl0113** [comment]
Have you moved this plugin from bootstrap-plugins to plugins for testing or demo service start?

**Comment by Zwl0113** [comment]
The plugin name is bootstrap-plugins/jdk-threadpool-plugin
