### ISSUE TITLE
[Bug] after include the apm-jdk-threading-plugin, the Java application in the garden encountered a NoClassDefFoundError error?

### ISSUE THREAD

**Issue by haoyongdong** [apache/skywalking#10653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

when I include the apm-jdk-threading-plugin, application error by NoClassDefFoundError. I have confirmed that the class "DataSourceClassLoaderFactory" can be found in the classpath.
--------------------------------------------------------------
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nox.executor.classloader.DataSourceClassLoaderFactory
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

### What you expected to happen

Could you please help to check what caused the issue? It seems that the failure to load the class was caused by the introduction of the multi-threading plugin.

### How to reproduce

...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haoyongdong** [comment]
The latest version of the agent that I am using. 8.14.0
