### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded  Because adding/etc/rc.d/rc.local to the system

### ISSUE THREAD

**Issue by houxinlin** [apache/skywalking#10667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I used Centos and added the startup.sh file to `/etc/rc.d/rc.local`. When I restarted my computer, I got the following error.
But I manually execute startup.sh, which is normal
```java
023-04-11 14:56:17,024 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 90 [main] INFO  [] - Prepare the default provider in receiver-browser module.
2023-04-11 14:56:17,027 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 90 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
2023-04-11 14:56:17,205 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 90 [main] INFO  [] - Prepare the standalone provider in cluster module.
2023-04-11 14:56:17,208 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 90 [main] INFO  [] - Prepare the default provider in core module.
2023-04-11 14:57:38,588 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 60 [main] ERROR [] - GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664) ~[?:1.8.0_121]
        at java.lang.String.<init>(String.java:207) ~[?:1.8.0_121]
        at java.lang.String.substring(String.java:1933) ~[?:1.8.0_121]
        at java.io.File.getName(File.java:456) ~[?:1.8.0_121]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:536) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$LocationInfo.scanDirectory(ClassPath.java:540) ~[guava-31.1-jre.jar:?]

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We are using folder scan. Don't use it in this way.

**Comment by houxinlin** [comment]
> 我们正在使用文件夹扫描。不要以这种方式使用它。

thank

**Comment by houxinlin** [comment]
> 我们正在使用文件夹扫描。不要以这种方式使用它。

I don't understand what caused this, but it interests me. Could you please spend a few minutes explaining in detail what the reason is? Thank you very much.

**Comment by houxinlin** [comment]
> We are using folder scan. Don't use it in this way.

Or provide a minimal reproduction environment, and I try to understand it

**Comment by houxinlin** [comment]
> We are using folder scan. Don't use it in this way.

I may know this is the reason for the system startup environment, but my knowledge is not enough to make me
