### ISSUE TITLE
SkyWalking supports JDK11 HTTPCLIENT [Bug] 

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#10670]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

The skywalking-agent version is: 8.4.0
If agent.is_cache_enhanced_class=true, the following exception is reported:

Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class sun.net.www.http.HttpClient (in module java.base) cannot access class org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance (in unnamed module @0x70dd7e15) because module java.base does not read unnamed module @0x70dd7e15
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at com.example.demo.skywalking.JDKHttpClient.main(JDKHttpClient.java:33)

### What you expected to happen

class sun.net.www.http.HttpClient (in module java.base) cannot access class 

### How to reproduce

agent.is_cache_enhanced_class=true,

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class sun.net.www.http.HttpClient (in module java.base) cannot access class

This is a JDK9 module system error. You need to open this access by yourself.

**Comment by wu-sheng** [comment]
If you have questions, use the `Discussion` panel rather than an error.

**Comment by HackerRookie** [comment]
ok
