### ISSUE TITLE
[Bug] Processing of -javaagent failed Caused by: java.lang.ClassCircularityError: java/util/concurrent/ScheduledThreadPoolExecutor

### ISSUE THREAD

**Issue by yqjdcyy** [apache/skywalking#10685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

- to support for tracing in threadpool, we move /bootstrap-plugins/apm-jdk-threadpool-plugin-8.14.0.jar& apm-jdk-threadpool-plugin-8.14.0.jar to /plugins
- it works on my computer(windows& mac)，but fail on the other(mac+ linux for test)
- it's hard to reproduce, and we had scan the list of issue(like to [[Bug] Skywalking-java enhanced jdk thread pool failed](https://github.com/apache/skywalking/issues/10374)) with no effect. 
- try to support more information or thought in this issue

### What you expected to happen

- Short Log
```log
DEBUG 2023-04-13 16:23:37.369 main AgentPackagePath : The beacon class location is jar:file:/usr/local/springboot/ccccp/sky/agent/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class. 
INFO 2023-04-13 16:23:37.371 main SnifferConfigInitializer : Config file found in /usr/local/springboot/ccccp/sky/agent/config/agent.config. 
INFO 2023-04-13 16:23:37.397 main SnifferConfigInitializer : SnifferConfigInitializer url:jar:file:/usr/local/springboot/ccccp/web-0.0.1-SNAPSHOT.jar!/META-INF/MANIFEST.MF 
INFO 2023-04-13 16:23:37.398 main SnifferConfigInitializer : SnifferConfigInitializer url:jar:file:/usr/local/springboot/ccccp/sky/agent/skywalking-agent.jar!/META-INF/MANIFEST.MF 

INFO 2023-04-13 16:23:37.508 main AgentClassLoader : /usr/local/springboot/ccccp/sky/agent/plugins/apm-jdk-threading-plugin-8.14.0.jar loaded. 
INFO 2023-04-13 16:23:37.508 main AgentClassLoader : /usr/local/springboot/ccccp/sky/agent/plugins/apm-jdk-threadpool-plugin-8.14.0.jar loaded. 
INFO 2023-04-13 16:23:37.582 main PluginResourcesResolver : find skywalking plugin define in jar:file:/usr/local/springboot/ccccp/sky/agent/plugins/apm-jdk-threading-plugin-8.14.0.jar!/skywalking-plugin.def 
INFO 2023-04-13 16:23:37.582 main PluginResourcesResolver : find skywalking plugin define in jar:file:/usr/local/springboot/ccccp/sky/agent/plugins/apm-jdk-threadpool-plugin-8.14.0.jar!/skywalking-plugin.def 
DEBUG 2023-04-13 16:23:37.918 main PluginBootstrap : loading plugin class org.apache.skywalking.apm.plugin.jdk.threading.define.RunnableInstrumentation. 
DEBUG 2023-04-13 16:23:37.921 main PluginBootstrap : loading plugin class org.apache.skywalking.apm.plugin.jdk.threading.define.CallableInstrumentation. 
 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.util.ServiceConfigurationError: org.apache.skywalking.apm.agent.core.boot.BootService: Provider org.apache.skywalking.apm.agent.core.profile.ProfileTaskExecutionService could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.skywalking.apm.agent.core.boot.ServiceManager.load(ServiceManager.java:144)
        at org.apache.skywalking.apm.agent.core.boot.ServiceManager.loadAllServices(ServiceManager.java:62)
        at org.apache.skywalking.apm.agent.core.boot.ServiceManager.boot(ServiceManager.java:42)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:141)
        ... 6 more
Caused by: java.lang.ClassCircularityError: java/util/concurrent/ScheduledThreadPoolExecutor
        at java.util.concurrent.Executors.newSingleThreadScheduledExecutor(Executors.java:272)
        at org.apache.skywalking.apm.agent.core.profile.ProfileTaskExecutionService.<clinit>(ProfileTaskExecutionService.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 12 more
FATAL ERROR in native method: processing of -javaagent failed
```

- Full Log
    - [log.txt](https://github.com/apache/skywalking/files/11227889/zck-upload-1681375758298abc.txt)

### How to reproduce

- ENV
    - Linux version 4.18.1-1.el7.elrepo.x86_64
- JDK
     - java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
- it's hard to reproduce. but we try to support more when you need

### Anything else

- success on my computer( windows) and part colleague's(mac)
    - me: java version "1.8.0_65" + Windows 10 22H2
- fail on part colleague's(mac) and test machine(linux)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Search existing before submit a new.
Short version, agent kernel uses this, so, you can't instrument.
