### ISSUE TITLE
[Bug] SQLServer write data intercept failure

### ISSUE THREAD

**Issue by sky-dawn** [apache/skywalking#10741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

ERROR 2023-04-27 03:00:27.566 http-nio-8085-exec-2 InstMethodsInter : class[class com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement] before method[setObject] intercept failure 
java.lang.ClassCastException: com.microsoft.sqlserver.jdbc.Parameter cannot be cast to java.lang.Integer
	at org.apache.skywalking.apm.plugin.jdbc.JDBCPreparedStatementSetterInterceptor.beforeMethod(JDBCPreparedStatementSetterInterceptor.java:34)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setNull$original$zlYk2Jdr(SQLServerPreparedStatement.java:888)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setNull$original$zlYk2Jdr$accessor$SGUKmmTt(SQLServerPreparedStatement.java)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$auxiliary$pyn6dt6J.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setNull(SQLServerPreparedStatement.java)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setNull(DruidPooledPreparedStatement.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:67)

#### Issue source code
 
org.apache.skywalking.apm.plugin.jdbc.JDBCPreparedStatementSetterInterceptor
```
    @Override
    public final void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments,
        Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        final StatementEnhanceInfos statementEnhanceInfos = (StatementEnhanceInfos) objInst.getSkyWalkingDynamicField();
        if (statementEnhanceInfos != null) {
          final int index = (Integer) allArguments[0];
          final Object parameter = allArguments[1];
          statementEnhanceInfos.setParameter(index, parameter);
        }
    }
```

this problem caused by  `final int index = (Integer) allArguments[0];` , when sw intercepted setObject method of SQLServerPreparedStatement , which is a un public method and it first param is not int.
the mothod code is:
```
final void setObject(Parameter param, Object obj, JavaType javaType, JDBCType jdbcType, Integer scale,
            Integer precision, boolean forceEncrypt, int parameterIndex, String tvpName) throws SQLServerException 
```

### What you expected to happen

hope agent to run normally

### How to reproduce

just insert data to sqlserver

### Anything else

I have found the problem and solved it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Could you update the title for your issue?
I can assign this to you as you said, you have known the issue and fixed locally.

**Comment by mattwmj** [comment]
We are facing the same issue and looking forward @sky-dawn 's fixing. Thanks!

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/524. Pending on next release.
