### ISSUE TITLE
[Bug] Dubbo3.0.12 NoSuchFieldException: executor

### ISSUE THREAD

**Issue by sky-dawn** [apache/skywalking#10763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

java.lang.NoSuchFieldException: executor
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.apache.skywalking.apm.plugin.asf.dubbo.AbstractServerConstructorInterceptor.onConstruct(AbstractServerConstructorInterceptor.java:38)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter.intercept(ConstructorInter.java:65)
	at org.apache.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java)
	at org.apache.dubbo.remoting.transport.netty4.NettyServer.<init>(NettyServer.java:86)
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.bind(NettyTransporter.java:35)
	at org.apache.dubbo.remoting.Transporter$Adaptive.bind(Transporter$Adaptive.java)
	at org.apache.dubbo.remoting.Transporters.bind(Transporters.java:55)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.bind(HeaderExchanger.java:44)
	at org.apache.dubbo.remoting.exchange.Exchangers.bind(Exchangers.java:69)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:376)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:343)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:325)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$2(RegistryProtocol.java:294)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:292)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:239)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)

### What you expected to happen

run with no exception

### How to reproduce

When you use dubbo 3.0.12, the problem can reproduce.

### Anything else

The cause of this problem is dubbo removed the executor field, and replace with executors, in order to resole executor rewrite problem.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We only have 3.0.2 tested.
https://github.com/apache/skywalking-java/blob/main/test/plugin/scenarios/dubbo-3.x-scenario/support-version.list

We can't guarantee the new versions are always supported.

**Comment by sky-dawn** [comment]
ok, it only be repaired by myself locally.

**Comment by wu-sheng** [comment]
If you want to contribute upstream, you could follow the plugin dev doc and finish the relative tests through a pull request.

**Comment by tisonkun** [comment]
@sky-dawn Do you try out dubbo-plugin-3.x? From the error message it seems you're using dubbo-plugin-2.7.x.

**Comment by sky-dawn** [comment]
> If you want to contribute upstream, you could follow the plugin dev doc and finish the relative tests through a pull request.

ok.

**Comment by sky-dawn** [comment]
> @sky-dawn Do you try out dubbo-plugin-3.x? From the error message it seems you're using dubbo-plugin-2.7.x.

no. sw java use dubbo-3.0.0, and you can check the source code is

```
public abstract class AbstractServer extends AbstractEndpoint implements RemotingServer {
  ExecutorService executor;
```

but dubbo-3.0.12 is:
```
public abstract class AbstractServer extends AbstractEndpoint implements RemotingServer {
    
    private Set<ExecutorService> executors = new ConcurrentHashSet<>();
```

**Comment by sky-dawn** [comment]
> @sky-dawn Do you try out dubbo-plugin-3.x? From the error message it seems you're using dubbo-plugin-2.7.x.

uh, you are right. The error msg reported by dubbo-plugin-2.7x, but my project use dubbo-3.0.12.

**Comment by sky-dawn** [comment]
> @sky-dawn Do you try out dubbo-plugin-3.x? From the error message it seems you're using dubbo-plugin-2.7.x.

uh, you are right. The error msg reported by dubbo-plugin-2.7x, but my project use dubbo-3.0.12.
is this a bug?

**Comment by sky-dawn** [comment]
> @sky-dawn Do you try out dubbo-plugin-3.x? From the error message it seems you're using dubbo-plugin-2.7.x.

uh, you are right. The error msg reported by dubbo-plugin-2.7x, but my project use dubbo-3.0.12.
it means i shoud remove apm-dubbo-2.7.x-plugin-xx.jar from plugins directory.

**Comment by wu-sheng** [comment]
Check the witness class and instrumentation points. It could be both.

**Comment by sky-dawn** [comment]
ok.
