### ISSUE TITLE
[Bug] Can not locate agent jar file

### ISSUE THREAD

**Issue by rechardguo** [apache/skywalking#10770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

config agent in jboss-eap-7.4.0/bin/standalone.conf.bat
`
 set MODULE_OPTS="-javaagent:D:\dev-tool\jboss-eap-7.4.0\skywalking-agent\skywalking-agent.jar"
`
click standalone.bat and error occur as below:

20:43:46,477 INFO  [org.jboss.modules] (main) JBoss Modules version 1.11.0.Final-redhat-00001
ERROR 2023-05-07 20:43:46:555 main AgentPackagePath : Can not locate agent jar file.
ERROR 2023-05-07 20:43:46:555 main SnifferConfigInitializer : Failed to read the config file, skywalking is going to run in default config.
org.apache.skywalking.apm.agent.core.boot.AgentPackageNotFoundException: Can not locate agent jar file.
        at org.apache.skywalking.apm.agent.core.boot.AgentPackagePath.findPath(AgentPackagePath.java:81)
        at org.apache.skywalking.apm.agent.core.boot.AgentPackagePath.getPath(AgentPackagePath.java:40)
        at org.apache.skywalking.apm.agent.core.conf.SnifferConfigInitializer.loadConfig(SnifferConfigInitializer.java:202)
        at org.apache.skywalking.apm.agent.core.conf.SnifferConfigInitializer.initializeCoreConfig(SnifferConfigInitializer.java:65)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.modules.Main.main(Main.java:540)

### What you expected to happen

jboss start normally 

### How to reproduce

1. download skywalking-agent from offical site and extract 
2. config agent in jboss-eap-7.4.0/bin/standalone.conf.bat
`
 set MODULE_OPTS="-javaagent:D:\dev-tool\jboss-eap-7.4.0\skywalking-agent\skywalking-agent.jar"
`
2.  click standalone.bat to start jboss

### Anything else

the root cause is jboss use moduleClassloader to load SkyWalkingAgent.java
see org.jboss.modules.Main.main
`

if (preMainClassName != null) {
                   // classLoader herer is ModuleClassLoader to find classname preMainClassName=SkyWalkingAgent
                    final Class<?> preMainClass = Class.forName(preMainClassName, true, classLoader);
                    Object[] premainArgs;
                    Method premain;
                    try {
                        premain = preMainClass.getDeclaredMethod("premain", String.class, Instrumentation.class);
                        premainArgs = new Object[] {agentArgs, instrumentation};
                    } catch (NoSuchMethodException ignore) {
                      //...
                    }
                    try {
                        premain.invoke(null, premainArgs);
                    } catch (InvocationTargetException e) {
                     // ...
                    }
                } else {
                   //...
                }
`

and in AgentPackagePath
`
private static File findPath() throws AgentPackageNotFoundException {
        String classResourcePath = AgentPackagePath.class.getName().replaceAll("\\.", "/") + ".class";
        URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath);
}
`
ClassLoader.getSystemClassLoader() is appClassloader not moduleClassloader . so resource is null.
so better it change to 
`
URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath);
if(resource ==null){
 resource = AgentPackagePath.class.getSystemClassLoader().getResource(classResourcePath);
}
`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@rechardguo Are you going to send a pull request? (As you checked for this)

**Comment by rechardguo** [comment]
yes, give me some time.

**Comment by rechardguo** [comment]
@wu-sheng Yes, it is easy for debug and see. 
![image](https://user-images.githubusercontent.com/5202588/236723353-e7264115-8d56-4091-b795-05ad5a1b9de4.png)
![image](https://user-images.githubusercontent.com/5202588/236723412-7c03c8e2-d36e-408c-86ba-3adcf4ff6990.png)


But how to  write test case. Please give me some time for it.
I want to mock appClassloader which class.path is not point to agent.jar.
but MyClassLoader  point to that.

I thinking as below , but it not work. Can you give some suggetion? 
`
public class AgentPackagePathTest {
    static class MyClassLoader extends ClassLoader {
        public final Class<?> loadClass(final String className) throws ClassNotFoundException {
            if (className.equals(AgentPackagePath.class.getName())) {
                byte[] data;
                try (final InputStream is = AgentPackagePath.class.getClassLoader()
                        .getResourceAsStream(AgentPackagePath.class.getName().replace('.', '/') + ".class");
                     final ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                    int ch;
                    while ((ch = is.read()) != -1) {
                        baos.write(ch);
                    }
                    data = baos.toByteArray();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                return defineClass(className, data, 0, data.length);
            } else {
                return super.loadClass(className);
            }

        }
    }

    @Test
    public void testGetPathNotNull() throws ClassNotFoundException, IllegalAccessException, NoSuchMethodException, InvocationTargetException, IOException {
        ClassLoader spy = spy(ClassLoader.getSystemClassLoader());
        Mockito.doReturn(null)
                .when(spy)
                .getResource("org.apache.skywalking.apm.agent.core.boot.AgentPackagePath".replace('.', '/') + ".class");
        MyClassLoader classLoader = new MyClassLoader();
        Class<?> agentPackagePath = (Class<?>) Class.forName("org.apache.skywalking.apm.agent.core.boot.AgentPackagePath", true, classLoader);
        Object path =  agentPackagePath.getDeclaredMethod("getPath").invoke(null);
        assert path != null;
    }

`

**Comment by wu-sheng** [comment]
Could you reproduce this error on JBoss(Open Source version?

**Comment by rechardguo** [comment]
@wu-sheng I also clone jboss code from https://github.com/jboss-modules/jboss-modules/tree/1.11  (my local jdk is 1.8 so use version 1.11)
and open that code in idea.

by add remote debug setting to jboss  file standalone.conf

set "JAVA_OPTS=%JAVA_OPTS% -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y"

start jboss, i can debug jboss in idea, it show that 

![image](https://user-images.githubusercontent.com/5202588/236815047-c6b1b9c7-33f7-4f0a-8bcf-e3e4b69fcc45.png)

use moudleClassLoader to load SkyWalkingAgent.

and in AgentPackagePath

`
URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath);
`

 ClassLoader.getSystemClassLoader() which is not moudleClassLoader , so getResource() is null.


you can see 
https://github.com/jboss-modules/jboss-modules/blob/1.11/src/main/java/org/jboss/modules/Main.java
line start from 523 is how to process agent logic

**Comment by wu-sheng** [comment]
I can see your case. The point of my asking is, how to test jboss in the CI.
Currently, we have tomcat and jar based container tests.

**Comment by rechardguo** [comment]
@wu-sheng Not understand your point of test jboss in the CI.
Do you mean  integrate tomcat and test, Could you give me some code or any guide document.

Anyway i am just create pr.  Pls review and give suggestion. 
The testcase can not put in apm-agent-core because systemclassloader will alway find SkyWalkingAgent.class.
So i create apm-agent-test project to test that. Probaly you don't like that, but I don't have better way.
