### ISSUE TITLE
[Bug] cant't find data on skywalking UI

### ISSUE THREAD

**Issue by Hello-Linux** [apache/skywalking#11016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

the oap service show warn
```
2023-06-30 09:47:26,535 - graphql.execution.SimpleDataFetcherExceptionHandler -454784 [qtp19578363-34] WARN  [] - Exception while fetching data (/topo) : Service id is empty
org.apache.skywalking.oap.server.core.UnexpectedException: Service id is empty
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.query.TopologyQueryEsDAO.loadSpecifiedClientSideServiceRelations(TopologyQueryEsDAO.java:73) ~[storage-elasticsearch-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.core.query.TopologyQueryService.getServiceTopology(TopologyQueryService.java:106) ~[server-core-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.query.graphql.resolver.TopologyQuery.getServicesTopology(TopologyQuery.java:68) ~[query-graphql-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.query.graphql.resolver.TopologyQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:7.0.0]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
```
<img width="902" alt="000" src="https://github.com/apache/skywalking/assets/17851645/8fae8afd-118e-45de-8bf4-8e711f37870b">

and my tomcat already connect to oap server
```
DEBUG 2023-06-30 09:46:40:826 SkywalkingAgent-7-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2023-06-30 09:46:43:826 SkywalkingAgent-7-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2023-06-30 09:46:46:826 SkywalkingAgent-7-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2023-06-30 09:46:49:826 SkywalkingAgent-7-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2023-06-30 09:46:52:826 SkywalkingAgent-7-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
```
but the dashborad no data，and endpoint have number，other is empty！
<img width="951" alt="001" src="https://github.com/apache/skywalking/assets/17851645/e94ad31b-2fb9-4b28-92ec-0d0d41f8af38">
<img width="887" alt="002" src="https://github.com/apache/skywalking/assets/17851645/517f3464-0384-460d-8de3-c8d5db0cea16">

### What you expected to happen

the dashboard should hava some data

### How to reproduce

I use docker build the skywalking
```
docker run --name skywalking-oap \
--restart always \
-p 11800:11800 -p 12800:12800 -d \
-e TZ=Asia/Shanghai \
-e SW_ES_USER= \
-e SW_ES_PASSWORD= \
-e SW_STORAGE=elasticsearch7 \
-e SW_STORAGE_ES_CLUSTER_NODES=192.168.23.128:9200 \
-v /etc/localtime:/etc/localtime:ro \
apache/skywalking-oap-server:7.0.0-es7

docker run -d \
--name skywalking-ui \
--restart always \
-p 9898:8080 \
--link skywalking-oap:skywalking-oap \
-e TZ=Asia/Shanghai \
-e SW_OAP_ADDRESS=skywalking-oap:12800 \
-v /etc/localtime:/etc/localtime:ro \
apache/skywalking-ui:7.0.0

docker run -d \
-p 9200:9200 \
-p 9300:9300 \
--name='elasticsearch' \
-e "discovery.type=single-node" \
-e ES_JAVA_OPTS="-Xms512m -Xmx512m" \
-e TZ=Asia/Shanghai \
-v /etc/localtime:/etc/localtime:ro \
elasticsearch:7.6.2
```

and use tomcat8.5.50 connect the oap server

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
v8 is dead for years.

**Comment by wu-sheng** [comment]
v7 is older.
We don't have time to even read them.

**Comment by Hello-Linux** [comment]
Can this help with analysis? Thank you so much

**Comment by wu-sheng** [comment]
No, we won't, official announcement has declared https://skywalking.apache.org/events/v8-eol/
