### ISSUE TITLE
PHP[Bug] 

### ISSUE THREAD

**Issue by mckue** [apache/skywalking#11041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Environment: mac os ventura
PHP: php8.1
web framework: laravel9:v9.52.10
Execution command: php artisan interact:sync-lazada-shop
question:

1. display
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/plugin/plugin_redis.rs:361:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2. Display [1] 22464 segmentation fault php artisan interact:sync-lazada-shop

![image](https://github.com/apache/skywalking/assets/29243171/3c1bbf47-b80c-46b6-a4be-0c097532df40)

This is not a special case, any command will produce such a problem

### What you expected to happen

fix error

### How to reproduce

PHP: php8.1
web framework: laravel9:v9.52.10
php artisan xxx

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
Please set environment variable `export RUST_BACKTRACE=1` and try again, then put the backtrace here.

**Comment by mckue** [comment]
> 请设置环境变量`export RUST_BACKTRACE=1`并重试，然后将回溯放在这里。

 ~/www/yc-publish-api   lazada ✚ ● ? ⍟3  php artisan interact:sync-lazada-shop                                                                                                                                                                                                       ✔
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/plugin/plugin_redis.rs:361:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: std::panicking::try
   5: skywalking_agent::util::catch_unwind_result
   6: skywalking_agent::execute::execute_internal
   7: _xdebug_execute_internal
   8: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
   9: _execute_ex
  10: skywalking_agent::execute::execute_ex
  11: _xdebug_execute_ex
  12: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  13: _execute_ex
  14: skywalking_agent::execute::execute_ex
  15: _xdebug_execute_ex
  16: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  17: _execute_ex
  18: skywalking_agent::execute::execute_ex
  19: _xdebug_execute_ex
  20: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  21: _execute_ex
  22: skywalking_agent::execute::execute_ex
  23: _xdebug_execute_ex
  24: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  25: _execute_ex
  26: skywalking_agent::execute::execute_ex
  27: _xdebug_execute_ex
  28: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  29: _execute_ex
  30: skywalking_agent::execute::execute_ex
  31: _xdebug_execute_ex
  32: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  33: _execute_ex
  34: skywalking_agent::execute::execute_ex
  35: _xdebug_execute_ex
  36: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  37: _execute_ex
  38: skywalking_agent::execute::execute_ex
  39: _xdebug_execute_ex
  40: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  41: _execute_ex
  42: skywalking_agent::execute::execute_ex
  43: _xdebug_execute_ex
  44: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  45: _execute_ex
  46: skywalking_agent::execute::execute_ex
  47: _xdebug_execute_ex
  48: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  49: _execute_ex
  50: skywalking_agent::execute::execute_ex
  51: _xdebug_execute_ex
  52: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  53: _execute_ex
  54: skywalking_agent::execute::execute_ex
  55: _xdebug_execute_ex
  56: _ZEND_CALL_TRAMPOLINE_SPEC_OBSERVER_HANDLER
  57: _execute_ex
  58: skywalking_agent::execute::execute_ex
  59: _xdebug_execute_ex
  60: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  61: _execute_ex
  62: skywalking_agent::execute::execute_ex
  63: _xdebug_execute_ex
  64: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  65: _execute_ex
  66: skywalking_agent::execute::execute_ex
  67: _xdebug_execute_ex
  68: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  69: _execute_ex
  70: skywalking_agent::execute::execute_ex
  71: _xdebug_execute_ex
  72: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  73: _execute_ex
  74: skywalking_agent::execute::execute_ex
  75: _xdebug_execute_ex
  76: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  77: _execute_ex
  78: skywalking_agent::execute::execute_ex
  79: _xdebug_execute_ex
  80: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  81: _execute_ex
  82: skywalking_agent::execute::execute_ex
  83: _xdebug_execute_ex
  84: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  85: _execute_ex
  86: skywalking_agent::execute::execute_ex
  87: _xdebug_execute_ex
  88: _ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER
  89: _execute_ex
  90: skywalking_agent::execute::execute_ex
  91: _xdebug_execute_ex
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
"SQL: select * from `pb_lazada_shops` limit 1" // app/Providers/AppServiceProvider.php:129
[1]    92757 segmentation fault  php artisan interact:sync-lazada-shop

**Comment by jmjoy** [comment]
> thread '' panicked at 'called Result::unwrap() on an Err value: Any { .. }', src/plugin/plugin_redis.rs:361:44

This will fix later.

> [1] 92757 segmentation fault php artisan interact:sync-lazada-shop

Try to make `ulimit -s` bigger?
