### ISSUE TITLE
[Bug] Withess classes selection error in springmvc-annotation-5.x-plugin

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#11053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When using spring 3.1.4.RELEASE , springmvc-annotation-5.x-plugin throws java.lang.NoSuchMethodError.
Error log:
```
java.lang.NoSuchMethodError: org.springframework.web.context.request.ServletRequestAttributes.getResponse()Ljavax/servlet/http/HttpServletResponse;
   at org.apache.skywalking.apm.plugin.spring.mvc.v5.GetBeanInterceptor.afterMethod(GetBeanInterceptor.java:56)
   at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
   at org.springframework.web.method.HandlerMethod.getBean(HandlerMethod.java)
   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.createRequestMappingMethod(RequestMappingHandlerAdapter.java:640)
   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:610)
   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:900)
   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827)
   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
   at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
...
```
` springmvc-annotation-5.x-plugin`  selected withess class is `org.springframework.beans.annotation.AnnotationBeanUtils` , and `org.springframework.beans.annotation.AnnotationBeanUtils`  also exists in spring3

### What you expected to happen

No response

### How to reproduce

No response

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't we have Spring3 plugin test for this? This should not happen.

**Comment by wu-sheng** [comment]
Then what is missed? AFAIK, if this fails, some information should miss, otherwise, why need these codes?

**Comment by xzyJavaX** [comment]
These codes should only take effect in spring5, but they are now incorrectly taking effect in spring3.

**Comment by wu-sheng** [comment]
OK, got your point. Please go ahead. Thanks.
