### ISSUE TITLE
[Bug]  Skywalking oap v6.6.0 The table cannot be created automatically

### ISSUE THREAD

**Issue by SCodefarm** [apache/skywalking#11085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalking oap v6.6.0  The table cannot be created automatically
2023-07-13 11:14:24,759 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 106 [pool-10-thread-1] DEBUG [] - execute query with result: SELECT * FROM instance_jvm_old_gc_count WHERE id in ('202307131114_2')
2023-07-13 11:14:24,759 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker - 136 [pool-10-thread-1] ERROR [] - Table 'sw_test_6.instance_jvm_old_gc_count' doesn't exist
java.io.IOException: Table 'sw_test_6.instance_jvm_old_gc_count' doesn't exist
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2SQLExecutor.getByIDs(H2SQLExecutor.java:65) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2MetricsDAO.multiGet(H2MetricsDAO.java:43) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.syncStorageToCache(MetricsPersistentWorker.java:185) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:121) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:76) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:95) ~[classes/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:89) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:67) ~[classes/:?]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table 'sw_test_6.instance_jvm_old_gc_count' doesn't exist
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:121) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2SQLExecutor.getByIDs(H2SQLExecutor.java:51) ~[classes/:?]
	... 17 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'sw_test_6.instance_jvm_old_gc_count' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:112) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2SQLExecutor.getByIDs(H2SQLExecutor.java:51) ~[classes/:?]
	... 17 more

### What you expected to happen

Automatic table creation

### How to reproduce

storage:
  mysql:
    properties:
      jdbcUrl: ${SW_JDBC_URL:"jdbc:mysql://localhost:3306/sw_test_6"}
      dataSource.user: ${SW_DATA_SOURCE_USER:root}
      dataSource.password: ${SW_DATA_SOURCE_PASSWORD:123}
      dataSource.cachePrepStmts: ${SW_DATA_SOURCE_CACHE_PREP_STMTS:true}
      dataSource.prepStmtCacheSize: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE:250}
      dataSource.prepStmtCacheSqlLimit: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
      dataSource.useServerPrepStmts: ${SW_DATA_SOURCE_USE_SERVER_PREP_STMTS:true}
    metadataQueryMaxSize: ${SW_STORAGE_MYSQL_QUERY_MAX_SIZE:5000}

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
6.6 dead for 3 years, we don't have interest to follow up.
