### ISSUE TITLE
[Bug] NoClassDefFoundError: Could not initialize class java.util.concurrent.ThreadLocalRandom

### ISSUE THREAD

**Issue by shichaoyuan** [apache/skywalking#11199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

netty start failed, because of ` java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.ThreadLocalRandom`.

in skywalking agent log file:
```
ERROR 2023-08-09 11:34:42.783 SkywalkingAgent-14-GRPCChannelManager-0 GRPCChannelManager : Create channel to  fail.
java.lang.NullPointerException
        at org.apache.skywalking.apm.agent.core.remote.GRPCChannelManager.run(GRPCChannelManager.java:152)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

ERROR 2023-08-09 11:35:12.774 SkywalkingAgent-8-ServiceManagementClientKafkaProducer-0 KafkaServiceManagementServiceClient : unexpected exception.
java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.ThreadLocalRandom
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.internals.StickyPartitionCache.nextPartition(StickyPartitionCache.java:61)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.internals.DefaultPartitioner.onNewBatch(DefaultPartitioner.java:69)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:933)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
        at org.apache.skywalking.apm.agent.core.kafka.KafkaServiceManagementServiceClient.run(KafkaServiceManagementServiceClient.java:107)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

in stdout
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.ThreadLocalRandom
        at io.netty.util.internal.PlatformDependent$2.current(PlatformDependent.java:137)
        at io.netty.util.internal.PlatformDependent.threadLocalRandom(PlatformDependent.java:981)
        at io.netty.channel.DefaultChannelId.<init>(DefaultChannelId.java:179)
        at io.netty.channel.DefaultChannelId.newInstance(DefaultChannelId.java:55)
        at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:101)
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:73)
        at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:33)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:312)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at 
```

### What you expected to happen

no NoClassDefFoundError

### How to reproduce

difficult to reproduce, occasionally

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shichaoyuan** [comment]
may be similar to https://github.com/DataDog/dd-trace-java/pull/4865

**Comment by wu-sheng** [comment]
That issue you are referring is about `ClassCircularityError`. But I can't see the same case here from your stack.
We have a lot of tests about the agent, no one reports this.

You should narrow the case.
