### ISSUE TITLE
[Bug] Data truncation: Data too long for column 'alarm_message' 'message'

### ISSUE THREAD

**Issue by vtroisWhite** [apache/skywalking#11325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

skywalking-oap-server.log

```
2023-09-13 16:39:23,008 - org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO - 88 [DataCarrier.H2_ASYNCHRONOUS_BATCH_PERSISTENT.Consumer.2.Thread] ERROR [] - Data truncation: Data too long for column 'alarm_message' at row 1
java.sql.BatchUpdateException: Data truncation: Data too long for column 'alarm_message' at row 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_221]
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:385) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:796) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.executeBatch(BatchSQLExecutor.java:78) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:67) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.lambda$flush$1(JDBCBatchDAO.java:85) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_221]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.flush(JDBCBatchDAO.java:81) [storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO$H2BatchConsumer.consume(JDBCBatchDAO.java:120) [storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:75) [library-datacarrier-queue-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:53) [library-datacarrier-queue-9.3.0.jar:9.3.0]
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'alarm_message' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:357) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        ... 12 more


2023-09-13 16:40:10,026 - org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO - 88 [pool-4-thread-1] ERROR [] - Data truncation: Data too long for column 'message' at row 1
java.sql.BatchUpdateException: Data truncation: Data too long for column 'message' at row 1
        at sun.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_221]
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:385) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:796) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.executeBatch(BatchSQLExecutor.java:78) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:67) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.lambda$flush$1(JDBCBatchDAO.java:85) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_221]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.flush(JDBCBatchDAO.java:81) ~[storage-jdbc-hikaricp-plugin-9.3.0.jar:9.3.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$null$3(PersistenceTimer.java:135) ~[server-core-9.3.0.jar:9.3.0]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'message' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:357) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        ... 14 more

```

### What you expected to happen

I think save data too long.

storage:
  selector: ${SW_STORAGE:mysql}

mysql-version: MySQL 5.7.17-log

apm-version: apache-skywalking-apm-9.3.0

agent-version: apache-skywalking-java-agent-8.15.0

### How to reproduce

~

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heyanlong** [comment]
It seems that the number of bytes you wrote exceeds the field length.

**Comment by wu-sheng** [comment]
Please try the latest. Your version is hard of a year ago.

**Comment by vtroisWhite** [comment]
> Please try the latest. Your version is hard of a year ago.

But my company's server environment uses JDK8. I noticed that version 9.4.0+ no longer supports JDK8, so I will ignore this issue. 
thanks

**Comment by vtroisWhite** [comment]
> 



> It seems that the number of bytes you wrote exceeds the field length.

I understand the cause of the error, I just wanted to know if it can be resolved by modifying the configuration file.

**Comment by wu-sheng** [comment]
Your company is not my concern. We don't have ideas of the errors. Every release includes contributions from 50-100 people around the world. No one has the idea which is fixed or changed.

**Comment by ibingdian** [comment]
> > 
> 
> > It seems that the number of bytes you wrote exceeds the field length.
> 
> I understand the cause of the error, I just wanted to know if it can be resolved by modifying the configuration file.

What is the reason for this problem？
