### ISSUE TITLE
[Bug] ERROR [] - Table "events_20231218" not found; SQL statement:

### ISSUE THREAD

**Issue by 56600535** [apache/skywalking#11678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I started with the default configuration,The following exception occurs.Version 9.7.0
```
2023-12-19 16:20:49,387 - org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO - 81 [pool-3-thread-2] ERROR [] - Table "events_20231218" not found; SQL statement:
INSERT INTO events_20231218(id,table_name,uuid,service,service_instance,endpoint,name,type,message,parameters,start_time,end_time,layer,time_bucket) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) [42102-212]
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "events_20231218" not found; SQL statement:
INSERT INTO events_20231218(id,table_name,uuid,service,service_instance,endpoint,name,type,message,parameters,start_time,end_time,layer,time_bucket) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) [42102-212]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8376) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8347) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.readTableOrView(Parser.java:8336) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.readTableOrView(Parser.java:8306) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.parseInsert(Parser.java:1641) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.parsePrepared(Parser.java:814) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.parse(Parser.java:691) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.parse(Parser.java:661) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.command.Parser.prepareCommand(Parser.java:568) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92) ~[h2-2.1.212.jar:2.1.212]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[h2-2.1.212.jar:2.1.212]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:54) ~[storage-jdbc-hikaricp-plugin-9.7.0.jar:9.7.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.lambda$flush$1(JDBCBatchDAO.java:78) ~[storage-jdbc-hikaricp-plugin-9.7.0.jar:9.7.0]
        at java.util.HashMap.forEach(HashMap.java:1337) ~[?:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.flush(JDBCBatchDAO.java:75) ~[storage-jdbc-hikaricp-plugin-9.7.0.jar:9.7.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$3(PersistenceTimer.java:135) ~[server-core-9.7.0.jar:9.7.0]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

```

### What you expected to happen

normal operation

### How to reproduce

Version 9.7.0. run `bin\startup.sh`.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you using a new env? Or reboot from a cold env?

**Comment by 56600535** [comment]
> Are you using a new env? Or reboot from a cold env?

new env

**Comment by wu-sheng** [comment]
Then why do you insert data for 2 days ago?

**Comment by wu-sheng** [comment]
We didn't create tables for passed days, and don't expect data for that old being reported into the system.
So, the error could show up.

**Comment by 56600535** [comment]
> We didn't create tables for passed days, and don't expect data for that old being reported into the system. So, the error could show up.
I will try again with a new environment, Check to see if there is a problem.
JDK Version: 11.0.8
SkyWalking APM Version: 9.7.0
JAVA agent Version: 9.1.0

**Comment by wu-sheng** [comment]
Make sure the clock of your VM is correct. If this is not from a cold down env back to work, most likely this is your timezone or time setup/sync issue

**Comment by 56600535** [comment]
When I run `oapService.sh` and `webappService.sh` respectively, the system starts normally, but service displays normally in UI, but trace has no data. Log normal.

param : -javaagent:D:\skywalking-agent.jar -Dskywalking.agent.service_name=staging -Dskywalking.collector.backend_service=192.168.110.59:11800

![Snipaste_2023-12-20_15-43-02](https://github.com/apache/skywalking/assets/49943200/8ab42af1-584e-404a-9b9b-3a0af4f8c513)

**Comment by wu-sheng** [comment]
This question is too general, I don't know how to answer that. I could only say, that if service, instance, and JVM metrics of instance are there, the system is working well. 
If there is no more metric, maybe, you don't have any traffic to be chanced. Metrics are from traces mostly, and logs require configurations on your log4j, please read docs for more details.
