### ISSUE TITLE
[JDBC Storage] The query time range on the logs page could be null.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#11754]
It seems that the time parameter is not passed when the page queries the log according to the TraceId, but it is used in the JDBC query without giving default values.
```
2024-01-11 20:31:28,726 - notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler - 46 [armeria-eventloop-epoll-5-55] WARN  [] - Exception while fetching data (/queryLogs) : Cannot invoke "org.apache.skywalking.oap.server.core.query.input.Duration.getStartTimeBucket()" because "duration" is null
java.lang.NullPointerException: Cannot invoke "org.apache.skywalking.oap.server.core.query.input.Duration.getStartTimeBucket()" because "duration" is null
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCLogQueryDAO.queryLogs(JDBCLogQueryDAO.java:107) ~[storage-jdbc-hikaricp-plugin-9.6.0.jar:9.6.0]
        at org.apache.skywalking.oap.server.core.query.LogQueryService.queryLogs(LogQueryService.java:82) ~[server-core-9.6.0.jar:9.6.0]
        at org.apache.skywalking.oap.query.graphql.resolver.LogQuery.queryLogs(LogQuery.java:84) ~[query-graphql-plugin-9.6.0.jar:9.6.0]
        at jdk.internal.reflect.GeneratedMethodAccessor225.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at graphql.kickstart.tools.resolver.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:282) ~[graphql-java-tools-13.0.1.jar:?]
        at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:311) ~[graphql-java-21.0.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:287) ~[graphql-java-21.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:213) ~[graphql-java-21.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) ~[graphql-java-21.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:161) ~[graphql-java-21.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:103) ~[graphql-java-21.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:565) ~[graphql-java-21.0.jar:?]
        at graphql.GraphQL.lambda$parseValidateAndExecute$12(GraphQL.java:484) ~[graphql-java-21.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:479) ~[graphql-java-21.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:438) ~[graphql-java-21.0.jar:?]
        at com.linecorp.armeria.server.graphql.DefaultGraphqlService.execute(DefaultGraphqlService.java:108) ~[armeria-graphql-1.24.3.jar:?]
        at com.linecorp.armeria.server.graphql.DefaultGraphqlService.executeGraphql(DefaultGraphqlService.java:99) ~[armeria-graphql-1.24.3.jar:?]
        at com.linecorp.armeria.server.graphql.protocol.AbstractGraphqlService.lambda$doPost$1(AbstractGraphqlService.java:159) ~[armeria-graphql-protocol-1.24.3.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.linecorp.armeria.common.stream.AggregationSupport.lambda$aggregate$2(AggregationSupport.java:133) ~[armeria-1.24.3.jar:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.CancellableStreamMessage$CloseEvent.notifySubscriber(CancellableStreamMessage.java:258) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:303) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:295) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:432) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:375) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:278) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:260) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.CancellableStreamMessage$SubscriptionImpl.request(CancellableStreamMessage.java:211) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.StreamMessageCollector.onSubscribe(StreamMessageCollector.java:52) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:152) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:138) ~[armeria-1.24.3.jar:?]
        at com.linecorp.armeria.common.DefaultContextAwareRunnable.run(DefaultContextAwareRunnable.java:45) [armeria-1.24.3.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.86.Final.jar:4.1.86.Final]
        at java.lang.Thread.run(Thread.java:842) [?:?]

```

_Originally posted by @CzyerChen in https://github.com/apache/skywalking/discussions/11683#discussioncomment-8094666_

**Comment by wu-sheng** [comment]
The case is, when we use trace ID oriented query, the duration is not required.  

@CzyerChen This is from your comments, do you plan to fix this? cc @kezhenxu94 This was added when we support tables in the day-rotation mode

**Comment by CzyerChen** [comment]
> his was added when we support tables in the day-rotation mode

when query by related traceId, how to set default query time range(not including too many tables ) properly? 

```java
    final var tables = tableHelper.getTablesForRead(
            LogRecord.INDEX_NAME,
            duration.getStartTimeBucket(),      //=====> duration null
            duration.getEndTimeBucket()
        );
```

**Comment by wu-sheng** [comment]
I think we could set the widest range. Such as `TableHelper#getTablesWithinTTL`?

**Comment by CzyerChen** [comment]
> widest range.

> I think we could set the widest range. Such as `TableHelper#getTablesWithinTTL`?

if duiration  is null. get tables from `tableHelper.getTablesWithinTTL(LogRecord.INDEX_NAME)`

**Comment by wu-sheng** [comment]
This is my understanding. You could try. This happens when you use MySQL/PG, and jump to logs page from trace page by clicking trace ID.
