### ISSUE TITLE
skywalking oap server to use elasticsearch ：id is too long, must be no longer than 512 bytes but was: 528;3:

### ISSUE THREAD

**Issue by liucx1201** [apache/skywalking#11794]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

2024-01-18 08:24:37,475 org.apache.skywalking.oap.server.core.storage.PersistenceTimer 91 [pool-7-thread-1] ERROR [] - [9.2.0-cb8845a] Extract data and save failure.
java.util.concurrent.CompletionException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 552;2: id is too long, must be no longer than 512 bytes but was: 528;3: id is too long, must be no longer than 512 bytes but was: 516;4: id is too long, must be no longer than 512 bytes but was: 526;5: id is too long, must be no longer than 512 bytes but was: 550;6: id is too long, must be no longer than 512 bytes but was: 514;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 552;2: id is too long, must be no longer than 512 bytes but was: 528;3: id is too long, must be no longer than 512 bytes but was: 516;4: id is too long, must be no longer than 512 bytes but was: 526;5: id is too long, must be no longer than 512 bytes but was: 550;6: id is too long, must be no longer than 512 bytes but was: 514;"},"status":400}
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:103) ~[armeria-1.16.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.lambda$delegate$0(DeferredStreamMessage.java:132) ~[armeria-1.16.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:258) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:436) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:335) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:370) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:318) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:308) ~[armeria-1.16.0.jar:?]
	at com.linecorp.armeria.client.Http1ResponseDecoder.channelRead(Http1ResponseDecoder.java:245) ~[armeria-1.16.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 552;2: id is too long, must be no longer than 512 bytes but was: 528;3: id is too long, must be no longer than 512 bytes but was: 516;4: id is too long, must be no longer than 512 bytes but was: 526;5: id is too long, must be no longer than 512 bytes but was: 550;6: id is too long, must be no longer than 512 bytes but was: 514;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 552;2: id is too long, must be no longer than 512 bytes but was: 528;3: id is too long, must be no longer than 512 bytes but was: 516;4: id is too long, must be no longer than 512 bytes but was: 526;5: id is too long, must be no longer than 512 bytes but was: 550;6: id is too long, must be no longer than 512 bytes but was: 514;"},"status":400}
	at org.apache.skywalking.library.elasticsearch.bulk.BulkProcessor.lambda$null$3(BulkProcessor.java:144) ~[library-elasticsearch-client-9.2.0.jar:9.2.0]
	... 57 more

May I ask how to solve it?
Kafka consumption is slow and disk usage is high

### What you expected to happen

Hope to solve this problem

### How to reproduce

![skywalking](https://github.com/apache/skywalking/assets/40434832/528509d1-fa80-443a-bb01-f24f582a8e44)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There were several fixes after 9.2 and configuration discussion are there. The last one is #11686, discussion source, https://github.com/apache/skywalking/discussions/11680

**Comment by liucx1201** [comment]
> 9.2 之后有一些修复和配置讨论。最后一篇是#11686，讨论源，#11680

@wu-sheng I just upgraded to 9.5.0 and still reported this issue
![20240118111409](https://github.com/apache/skywalking/assets/40434832/c4f879de-9c38-406a-a1d5-008f4cecd833)

**Comment by comqx** [comment]
Caused by: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [instance_client_sidecar_internal_resp_latency_nanos_20250205_Z2VpcC1yZXBsYXk6Om1lc3NhZ2Utc2VydmljZQ==.1_bWVzc2FnZS1zZXJ2aWNlLTc2NzlkYzc0NTktcGo3aHQuMTAuMTk0LjM0LjU0-ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=.0_ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=] is too long, must be no longer than 512 bytes but was: 752;2: id [instance_client_sidecar_internal_req_latency_nanos_2025020509_Z2VpcC1yZXBsYXk6Om1lc3NhZ2Utc2VydmljZQ==.1_bWVzc2FnZS1zZXJ2aWNlLTc2NzlkYzc0NTktcGo3aHQuMTAuMTk0LjM0LjU0-ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=.0_ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=] is too long, must be no longer than 512 bytes but was: 753;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [instance_client_sidecar_internal_resp_latency_nanos_20250205_Z2VpcC1yZXBsYXk6Om1lc3NhZ2Utc2VydmljZQ==.1_bWVzc2FnZS1zZXJ2aWNlLTc2NzlkYzc0NTktcGo3aHQuMTAu
MTk0LjM0LjU0-ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=.0_ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=] is too long, must be no longer than 512 bytes but was: 752;2: id [instance_client_sidecar_internal_req_latency_nanos_2025020509_Z2VpcC1yZXBsYXk6Om1lc3NhZ2Utc2VydmljZQ==.1_bWVzc2FnZS1zZXJ2aWNlLTc2NzlkYzc0NTktcGo3aHQuMTAuMTk0LjM0LjU0-ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=.0_ZWxhc3RpY3NlYXJjaC1tYXN0ZXItMC5lbGFzdGljc2VhcmNoLW1hc3Rlci1oZWFkbGVzcy5wdWJsaWMtc2VydmljZTo5MjAwLGVsYXN0aWNzZWFyY2gtbWFzdGVyLTEuZWxhc3RpY3NlYXJjaC1tYXN0ZXItaGVhZGxlc3MucHVibGljLXNlcnZpY2U6OTIwMCxlbGFzdGljc2VhcmNoLW1hc3Rlci0yLmVsYXN0aWNzZWFyY2gtbWFzdGVyLWhlYWRsZXNzLnB1YmxpYy1zZXJ2aWNlOjkyMDA=] is too long, must be no longer than 512 bytes but was: 753;"},"status":400}
		at org.apache.skywalking.library.elasticsearch.bulk.BulkProcessor.lambda$doFlush$3(BulkProcessor.java:180) ~[library-elasticsearch-client-10.1.0.jar:10.1.0]
		... 56 more
