### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jerex-zh** [apache/skywalking#11836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

启动一个程序使用了agent的程序，并使用修改过的skywalking-agent.jar替换agent中的jar包，如果再请求自己的程序，会因为skywalking找不到skywalking-agent.jar中的class，从而报错影响程序运行

2024-01-27 16:03:11.216 [XNIO-1 I/O-7] ERROR TID:N/A io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ GET /test}
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/context/ContextCarrier
	at org.apache.skywalking.apm.plugin.undertow.v2x.handler.TracingHandler.handleRequest(TracingHandler.java:50)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
Caused by: java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.agent.core.context.ContextCarrier
	at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 14 common frames omitted

### What you expected to happen

是否可以对文件进行锁定，从而更明显的提醒用户在程序运行时不建议替换skywalking-agent.jar

### How to reproduce

启动使用agent的程序之后，使用修改过的skywalking-agent.jar替换skywalking-agent.jar,然后请求自己的程序

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
English only on GitHub. 
Once you changed the codes, you are on your own.
