### ISSUE TITLE
[Bug] java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces

### ISSUE THREAD

**Issue by dengbaikun** [apache/skywalking#11876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

ERROR 2024-02-08 17:34:44.462 main SkyWalkingAgent : index=0, batch=[class ch.qos.logback.classic.spi.LoggingEvent], types=[class ch.qos.logback.classic.spi.LoggingEvent] 
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces

 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.12.RELEASE</version>
        <relativePath/> 
    </parent>

 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR12</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

加上了
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>reactor-core</artifactId>
                    <groupId>io.projectreactor</groupId>
                </exclusion>
            </exclusions>
        </dependency>
就没事 
怀疑是这个io.projectreactor 导致
skywalking 9.1.0 版本

### What you expected to happen

![Uploading QQ截图20240208174121.png…]()

### How to reproduce

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>gateway</artifactId>
    <version>1.0-SNAPSHOT</version>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.12.RELEASE</version>
        <relativePath/> 
    </parent>
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <skywalking.version>9.1.0</skywalking.version>
        <spring-cloud.version>Hoxton.SR12</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
    </dependencies>
   <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dengbaikun** [comment]
![QQ截图20240208174121](https://github.com/apache/skywalking/assets/48817023/5373b450-c823-4e25-b4d2-5f776d879c53)

**Comment by dengbaikun** [comment]
![微信截图_20240208174316](https://github.com/apache/skywalking/assets/48817023/7df140f9-3b85-4db6-97fd-807cf05e7472)

**Comment by wu-sheng** [comment]
Please use English if you need to discuss on GitHub. Chinese is welcome on slack CN channel.

**Comment by wu-sheng** [comment]
About toolkit, you should use versions compatible with the version we used for compiling

**Comment by dengbaikun** [comment]
> About toolkit, you should use versions compatible with the version we used for compiling

<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.3.17</version>
        </dependency>

Introducing this lib will cause this issue
skywalking-agent version 9.1.0
-javaagent:E:\skywalking-agent\skywalking-agent.jar
-Dskywalking.agent.service_name=skywalking-account-service

**Comment by wu-sheng** [comment]
We can't guarantee for the libraries we didn't test or use. 
You could try to cross check and source codes, there may be some methods changed. It is happened and will happen again.

**Comment by Scarecrow12138** [comment]
@dengbaikun Hello! May I ask how it was resolved in the end?? I have followed your method,Even commented out all the code,But it's still the case.
![image](https://github.com/apache/skywalking/assets/47475395/a9003c18-e986-49f8-81ed-64527a10f796)

**Comment by dengbaikun** [comment]
I also couldn't solve it either发自我的 iPhone在 2024年2月15日，下午10:19，Scarecrow12138 ***@***.***> 写道：﻿
@dengbaikun Hello! May I ask how it was resolved in the end?? I have followed your method,Even commented out all the code,But it's still the case.
image.png (view on web)

**Comment by wy150150** [comment]
I'm having the same issue. It does not seem to affect data reporting

env：
apache-skywalking-apm-9.3.0
apache-skywalking-java-agent-9.2.0


![无标题](https://github.com/user-attachments/assets/360458c8-7eba-4a15-80a6-c33934d83842)

**Comment by dengbaikun** [comment]
> I'm having the same issue. It does not seem to affect data reporting
> 
> env： apache-skywalking-apm-9.3.0 apache-skywalking-java-agent-9.2.0
> 
> ![无标题](https://private-user-images.githubusercontent.com/39988489/351990851-360458c8-7eba-4a15-80a6-c33934d83842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODk5MzUsIm5iZiI6MTcyMTg4OTYzNSwicGF0aCI6Ii8zOTk4ODQ4OS8zNTE5OTA4NTEtMzYwNDU4YzgtN2ViYS00YTE1LTgwYTYtYzMzOTM0ZDgzODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA2NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyM2ZmMzM4OTQ4MTY0NGVlZGZjY2M2MDMxOGUwODY4NGUyNjE1ZDE1MzY1NzYyNjgwZmRmZTY3NzQ0OTFlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHqJ6nNqDaWTgXDDq4mykp6EwEVFxt1eOaAbBn4F42E)

yes

**Comment by mofee** [comment]
I had the same problem：
 apache-skywalking-java-agent-9.3.0
ERROR 2024-08-20 18:20:34.670 main SkyWalkingAgent : index=0, batch=[class ch.qos.logback.classic.spi.LoggingEvent], types=[class ch.qos.logback.classic.spi.LoggingEvent] 
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.$Proxy32.retransformClasses(Unknown Source)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:8336)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:8151)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:5848)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:11462)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:11362)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.installClassTransformer(SkyWalkingAgent.java:152)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:105)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)

**Comment by dengbaikun** [comment]
> I had the same problem： apache-skywalking-java-agent-9.3.0 ERROR 2024-08-20 18:20:34.670 main SkyWalkingAgent : index=0, batch=[class ch.qos.logback.classic.spi.LoggingEvent], types=[class ch.qos.logback.classic.spi.LoggingEvent] java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.$Proxy32.retransformClasses(Unknown Source) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:8336) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:8151) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:5848) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:11462) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:11362) at org.apache.skywalking.apm.agent.SkyWalkingAgent.installClassTransformer(SkyWalkingAgent.java:152) at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:105) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560) at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)

jar  io.projectreactor reactor-core causing problems

**Comment by mofee** [comment]
> > I had the same problem： apache-skywalking-java-agent-9.3.0 ERROR 2024-08-20 18:20:34.670 main SkyWalkingAgent : index=0, batch=[class ch.qos.logback.classic.spi.LoggingEvent], types=[class ch.qos.logback.classic.spi.LoggingEvent] java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032) at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.$Proxy32.retransformClasses(Unknown Source) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:8336) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:8151) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:5848) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:11462) at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:11362) at org.apache.skywalking.apm.agent.SkyWalkingAgent.installClassTransformer(SkyWalkingAgent.java:152) at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:105) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560) at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
> 
> jar io.projectreactor reactor-core causing problems

No, i found that it seems that the debug agent of IDEA conflicts with bytebuddy of skywalking java agent. It is OK to run without IDEA, or run （not debug）in IDEA does not report this error.

**Comment by yasuo-deng** [comment]
How to solve it

**Comment by dengbaikun** [comment]
I don't know
