### ISSUE TITLE
[Bug] exception in afterMethod  of dubbo3 plugin

### ISSUE THREAD

**Issue by focuse8** [apache/skywalking#11962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

org.apache.skywalking.apm.plugin.asf.dubbo3.DubboInterceptor#afterMethod don't be executed completely,  because exception occurs when responseFuture of AsyncRpcResult has a exception  in Dubbo3 plugin

ERROR 2024-02-20 16:36:12.940 DubboServerHandler-thread-400 InstMethodsInter : class[class org.apache.dubbo.monitor.support.MonitorClusterFilter] after method[invoke] intercept failure 
org.apache.dubbo.rpc.RpcException:  cause: Timeout after 2000ms waiting for result.
	at org.apache.dubbo.rpc.AsyncRpcResult.getAppResponse(AsyncRpcResult.java:180)
	at org.apache.dubbo.rpc.AsyncRpcResult.getException(AsyncRpcResult.java:131)
	at org.apache.skywalking.apm.plugin.asf.dubbo3.DubboInterceptor.afterMethod(DubboInterceptor.java:118)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsClusterFilter.invoke(MetricsClusterFilter.java:57)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
	at org.apache.dubbo.rpc.cluster.filter.support.ObservationSenderFilter.invoke(ObservationSenderFilter.java:62)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)

### What you expected to happen

org.apache.skywalking.apm.plugin.asf.dubbo3.DubboInterceptor#afterMethod should be executed completely, whatever happens

### How to reproduce

step1: app using dubbo3
step2:  build a custom filter  which wrap exception with AsyncRpcResult  and  make the Filter after MonitorFilter.  For example
     try {
            Result result = invoker.invoke(invocation);
            return result;
        } catch (Throwable e) {
            return AsyncRpcResult.newDefaultAsyncResult(e, invocation);
        }
step3: make a interface call timeout

### Anything else

public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
                              Object ret) throws Throwable {
        Result result = (Result) ret;
try {
        if (result != null && result.getException() != null) {
            dealException(result.getException());
        }
return ret;
}finally {

        ContextManager.stopSpan();
}
        
    }

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Hi, please reach out to the Dubbo community, we accepted this plugin from them and hosted them. But we don't have maintainers watching this specific plugin. 

I am closing this as it is not a kernel level bug. You could link to this if there is a fix from Dubbo side.

Note, I am not saying this should be fixed by Dubbo maintainer, it is that more people are there to watch Dubbo eco relative things.

**Comment by wu-sheng** [comment]
This is the plugin test scenario we used when we accepted the plugin.

https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/dubbo-3.x-scenario
