### ISSUE TITLE
Complex span info for AsyncHttpClient and exception 

### ISSUE THREAD

**Issue by candyleer** [apache/skywalking#1196]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  master latest
- Which company or project?

- What happen?
#### Improvement
 If I send a request with `Async Http Client`,it will generate 5 span info and these make me confused what does these span mean ,maybe end users only concern the main cost for the http request.
below the image show one request that the async http client generate.

![image](https://user-images.githubusercontent.com/11530760/39804131-c59fedba-53a5-11e8-9bf1-6c7d29d4be84.png)
#### Exception
 another issue

some times it will throw some exception but not every time and I cannot pinpoint the reason when I read the code
```
ERROR 2018-05-09 15:52:38 InstMethodsInter :  class[class org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor] after method[processEvent] intercept failure
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:155)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:159)
	at org.apache.skywalking.apm.plugin.httpasyncclient.v4.DefaultConnectingIOReactorIterceptor.afterMethod(DefaultConnectingIOReactorIterceptor.java:51)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)

ERROR 2018-05-09 15:52:38 InstMethodsInter :  class[class org.apache.http.impl.nio.conn.CPool] before method[requestCompleted] intercept failure
java.lang.IllegalArgumentException: ContextSnapshot can't be null.
	at org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:147)
	at org.apache.skywalking.apm.plugin.httpasyncclient.v4.SuccessInterceptor.beforeMethod(SuccessInterceptor.java:46)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestCompleted(AbstractNIOConnPool.java)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.completed(AbstractNIOConnPool.java:836)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.completed(SessionRequestImpl.java:135)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processNewChannels(AbstractIOReactor.java:424)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:287)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
1. `#activeSpan` 's NPE is always triggered by the span started in another thread.
1. ContextSnapshot missing may be caused by some methods are not intercepted.

I agree this graph makes me confuse too. And I think the contributed async http client plugin is not good enough. Could you consider to provide a new one?

**Comment by wu-sheng** [comment]
In ideal, one local span in main thread(segment) represents the prepare async http, another exit span in sub thread(segment) with ref, which points to the prev local span, represents the real http request(including the duration)

**Comment by candyleer** [comment]
for current version ,one request contains 2 exit span and 3 local span
for above image. I think `AsyncThread/excute` and `/test` is enough (one local and one exit)

**Comment by wu-sheng** [comment]
> for current version ,one request contains 2 exit span and 3 local span
for above image. I think AsyncThread/excute and /test are enough (one local and one exit)

Yes, agree. And be advised, local span should be in main thread, exit span should match the real HTTP request.

**Comment by candyleer** [comment]
@wu-sheng  the work flow of `Async http client` can be drawed as:
![image](https://user-images.githubusercontent.com/11530760/39812286-98832838-53be-11e8-9358-488f5299cc2d.png)

there are 3 thread to work ,so it's hard to start the local span in main thread ,the data is transfer by queue but not `new Thread()` directly, so do you have any proposal for this to trace? I can trace `thread-3` ,but it's hard to trace `main` to `thread-3`.

**Comment by candyleer** [comment]
the result may be 

---main-----
                         ------------------thread-3------------------
                            ----------------request span-------------

the different is thread-3 is not started in main thread(not like cross thread) at least they can related each other

**Comment by wu-sheng** [comment]
This is a very typical across-thread scenario, whether cross two or three threads. You should find a way hold **Snapshot** created in main thread, and ref it in the send thread. In the send thread, you also create a new segment and new Exit span with the hold **Snapshot**.

**Comment by candyleer** [comment]
understand,I have some solution

**Comment by candyleer** [comment]
pr has  been merged, close this
