### ISSUE TITLE
[Bug]NPE in jdk-threadpool-plugin 

### ISSUE THREAD

**Issue by ForrestWang123** [apache/skywalking#12128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

NPE in jdk-threadpool-plugin 

java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:184)
	at org.apache.skywalking.apm.plugin.AbstractThreadingPoolInterceptor.handleMethodException(AbstractThreadingPoolInterceptor.java:66)
	at org.apache.skywalking.apm.plugin.ThreadPoolExecuteMethodInterceptor_internal.intercept(InstanceMethodInterWithOverrideArgsTemplate.java:92)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)

### What you expected to happen

Should not have NPE 

### How to reproduce

1. beforeMethod of AbstractThreadingPoolInterceptor didn't create any span.
2. exception occur in execution body of the Runnable/Callable 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Follow up through https://github.com/apache/skywalking-java/pull/681
