### ISSUE TITLE
[Bug] SkyWalking agent failed to start if using kafka protocol with sasl_mechanism=PLAIN.

### ISSUE THREAD

**Issue by tsonglew** [apache/skywalking#12131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

SkyWalking agent failed to start if using kafka protocol with sasl_mechanism=PLAIN.

### What you expected to happen

SkyWalking agent starts successfully when using kafka protocol with sasl_mechanism=PLAIN.

### How to reproduce

run a gunicorn app with a command like

```sh
SW_AGENT_PROTOCOL=kafka \
SW_KAFKA_BOOTSTRAP_SERVERS=localhost:9092 \
SW_KAFKA_REPORTER_CONFIG_security_protocol=SASL_PLAINTEXT  \
SW_KAFKA_REPORTER_CONFIG_sasl_mechanism=PLAIN  \
SW_KAFKA_REPORTER_CONFIG_sasl_plain_username=************ \
SW_KAFKA_REPORTER_CONFIG_sasl_plain_password=************  \
SW_AGENT_NAME=demo::gunicorn \
sw-python -d run -p gunicorn main:app
```

### Anything else

The agent failed to start with AttributeError: 'SkyWalkingAgent' object has no attribute '_SkyWalkingAgent__log_queue'

Using kafka protocol with sasl_mechanism=PLAIN leads to "log.warning('%s: Sending username and password in the clear', self)".
https://github.com/dpkp/kafka-python/blob/a6d0579d3cadd3826dd364b01bc12a2173139abc/kafka/conn.py#L624

the logging module was replaced by sw_logging, but __log_queue was not initialized yet

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please send a pull request when you are ready.

**Comment by zyk888333** [comment]
@tsonglew  i encounter the error “NameError: name 'KafkaConfigDuplicated' is not defined” in an environment same to you，have you ever encountered this error？
[ERROR] SkyWalking Python Agent failed to start, please inspect your package installation.Report issue if you think this is a bug, along with the log produced by specifying the -d debug flag.
Traceback (most recent call last):
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/bootstrap/loader/sitecustomize.py", line 169, in <module>
    agent.start()  # CHECK: Not sure what happens when supervisor + gunicorn is used? Will it even work?
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/__init__.py", line 310, in start
    self.__bootstrap()  # calls init_threading
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/__init__.py", line 133, in __bootstrap
    from skywalking.agent.protocol.kafka import KafkaProtocol
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/protocol/kafka.py", line 24, in <module>
    from skywalking.client.kafka import KafkaServiceManagementClient, KafkaTraceSegmentReportService, \
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/client/kafka.py", line 55, in <module>
    __init_kafka_configs()
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/client/kafka.py", line 52, in __init_kafka_configs
    raise KafkaConfigDuplicated(key)
NameError: name 'KafkaConfigDuplicated' is not defined

**Comment by zyk888333** [comment]
@tsonglew   did the bug solved?  i got a new error with a command like:
export SW_AGENT_NAME='FlaskService'
export SW_AGENT_PROTOCOL='kafka'
export SW_KAFKA_BOOTSTRAP_SERVERS='192.168.2.167:19092'
export SW_KAFKA_REPORTER_CONFIG_security_protocol=SASL_PLAINTEXT
export SW_KAFKA_REPORTER_CONFIG_sasl_mechanism=PLAIN
export SW_KAFKA_REPORTER_CONFIG_sasl_plain_username='client'
export SW_KAFKA_REPORTER_CONFIG_sasl_plain_password='xxxx'
export SW_AGENT_INSTANCE_PROPERTIES_JSON='{"licence":"OTEL-APM-20230627"}'
nohup sw-python -d run python3 flask-t1.py &


2024-09-14 17:06:37,373 kafka.conn [pid:2271] [MainThread] [ERROR] Connect attempt to <BrokerConnection node_id=bootstrap-0 host=192.168.2.167:19092 <connecting> [IPv4 ('192.168.2.167', 19092)]> returned error 111. Disconnecting.
skywalking-loader [pid:2271] [MainThread] [ERROR] SkyWalking Python Agent failed to start, please inspect your package installation.Report issue if you think this is a bug, along with the log produced by specifying the -d debug flag.
Traceback (most recent call last):
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/bootstrap/loader/sitecustomize.py", line 169, in <module>
    agent.start()  # CHECK: Not sure what happens when supervisor + gunicorn is used? Will it even work?
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/__init__.py", line 310, in start
    self.__bootstrap()  # calls init_threading
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/__init__.py", line 134, in __bootstrap
    self.__protocol = KafkaProtocol()
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/protocol/kafka.py", line 40, in __init__
    self.service_management = KafkaServiceManagementClient()
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/client/kafka.py", line 65, in __init__
    self.producer = KafkaProducer(**kafka_configs)
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

**Comment by zyk888333** [comment]
@tsonglew did the bug solved? i got a new error with a command like:
export SW_AGENT_NAME='FlaskService'
export SW_AGENT_PROTOCOL='kafka'
export SW_KAFKA_BOOTSTRAP_SERVERS='192.168.2.167:19092'
export SW_KAFKA_REPORTER_CONFIG_security_protocol=SASL_PLAINTEXT
export SW_KAFKA_REPORTER_CONFIG_sasl_mechanism=PLAIN
export SW_KAFKA_REPORTER_CONFIG_sasl_plain_username='client'
export SW_KAFKA_REPORTER_CONFIG_sasl_plain_password='xxxx'
export SW_AGENT_INSTANCE_PROPERTIES_JSON='{"licence":"xxxx"}'
nohup sw-python -d run python3 flask-t1.py &

2024-09-14 17:06:37,373 kafka.conn [pid:2271] [MainThread] [ERROR] Connect attempt to <BrokerConnection node_id=bootstrap-0 host=192.168.2.167:19092 [IPv4 ('192.168.2.167', 19092)]> returned error 111. Disconnecting.
skywalking-loader [pid:2271] [MainThread] [ERROR] SkyWalking Python Agent failed to start, please inspect your package installation.Report issue if you think this is a bug, along with the log produced by specifying the -d debug flag.
Traceback (most recent call last):
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/bootstrap/loader/sitecustomize.py", line 169, in
agent.start() # CHECK: Not sure what happens when supervisor + gunicorn is used? Will it even work?
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/init.py", line 310, in start
self.__bootstrap() # calls init_threading
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/init.py", line 134, in __bootstrap
self.__protocol = KafkaProtocol()
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/agent/protocol/kafka.py", line 40, in init
self.service_management = KafkaServiceManagementClient()
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/skywalking/client/kafka.py", line 65, in init
self.producer = KafkaProducer(**kafka_configs)
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in init
client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/client_async.py", line 244, in init
self.config['api_version'] = self.check_version(timeout=check_timeout)
File "/root/training/Python-3.9.4/lib/python3.9/site-packages/kafka/client_async.py", line 900, in check_version
raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
