### ISSUE TITLE
skywalking-oap 无法启动

### ISSUE THREAD

**Issue by qianghong000** [apache/skywalking#12228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

2024-05-15 12:09:33,125 org.apache.skywalking.library.elasticsearch.ElasticSearchBuilder 95 [armeria-eventloop-epoll-8-1] WARN  [] - [creqId=f7b95117][http://es-quickstart-es-http:9200/_cluster/health#GET] Request: {startTime=2024-05-15T12:09:32.952Z(1715774972952729), length=0B, duration=171ms(171712070ns), cause=com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.common.ClosedSessionException, scheme=none+http, name=health-check, headers=[:method=GET, :authority=es-quickstart-es-http:9200, :path=/_cluster/health]}
2024-05-15 12:09:33,125 org.apache.skywalking.library.elasticsearch.ElasticSearchBuilder 156 [armeria-eventloop-epoll-8-1] WARN  [] - [creqId=f7b95117][http://es-quickstart-es-http:9200/_cluster/health#GET] Response: {startTime=2024-05-15T12:09:33.122Z(1715774973122696), length=0B, duration=0ns, totalDuration=172ms(172065868ns), cause=com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.common.ClosedSessionException, headers=[:status=0]}
com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.common.ClosedSessionException
        at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpChannelPool.notifyConnect(HttpChannelPool.java:599) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpChannelPool.lambda$connect$1(HttpChannelPool.java:422) ~[armeria-1.25.0.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:476) [armeria-1.25.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:441) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:328) [netty-codec-http-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206) [netty-handler-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) [netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.linecorp.armeria.common.ClosedSessionException
        at com.linecorp.armeria.common.ClosedSessionException.get(ClosedSessionException.java:35) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpSessionHandler.maybeGetPendingException(HttpSessionHandler.java:504) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:477) ~[armeria-1.25.0.jar:?]
        ... 33 more
2024-05-15 12:09:33,131 com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroup 180 [armeria-eventloop-epoll-8-1] WARN  [] - The first health check failed for all endpoints. numCandidates: 1 candidates: [Endpoint{es-quickstart-es-http:9200, weight=1000}]
java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.common.ClosedSessionException
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.join(Unknown Source) ~[?:?]
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:87) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckContextGroup.lambda$initialize$2(HealthCheckContextGroup.java:87) ~[armeria-1.25.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at com.linecorp.armeria.client.endpoint.healthcheck.DefaultHealthCheckerContext.updateHealth(DefaultHealthCheckerContext.java:183) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.endpoint.healthcheck.HttpHealthChecker$HealthCheckResponseSubscriber.updateHealth(HttpHealthChecker.java:321) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.endpoint.healthcheck.HttpHealthChecker$HealthCheckResponseSubscriber.onError(HttpHealthChecker.java:248) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.CancellableStreamMessage$CloseEvent.notifySubscriber(CancellableStreamMessage.java:269) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:303) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:295) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:432) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:375) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:331) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:317) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.tryClose(DefaultStreamMessage.java:461) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpClientDelegate.lambda$acquireConnectionAndExecute0$3(HttpClientDelegate.java:188) ~[armeria-1.25.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at com.linecorp.armeria.client.HttpChannelPool$ChannelAcquisitionFuture.completeExceptionally(HttpChannelPool.java:914) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpChannelPool.notifyConnect(HttpChannelPool.java:599) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpChannelPool.lambda$connect$1(HttpChannelPool.java:422) ~[armeria-1.25.0.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:476) [armeria-1.25.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:441) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) [netty-codec-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:328) [netty-codec-http-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206) [netty-handler-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) [netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.common.ClosedSessionException
        at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45) ~[armeria-1.25.0.jar:?]
        ... 42 more
Caused by: com.linecorp.armeria.common.ClosedSessionException
        at com.linecorp.armeria.common.ClosedSessionException.get(ClosedSessionException.java:35) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpSessionHandler.maybeGetPendingException(HttpSessionHandler.java:504) ~[armeria-1.25.0.jar:?]
        at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:477) ~[armeria-1.25.0.jar:?]
        ... 33 more
2024-05-15 12:09:33,135 org.apache.skywalking.oap.server.telemetry.api.HealthCheckMetrics 50 [armeria-eventloop-epoll-8-1] WARN  [] - Health check fails. reason: No healthy endpoint
2024-05-15 12:09:33,135 org.apache.skywalking.oap.server.telemetry.api.HealthCheckMetrics 50 [armeria-eventloop-epoll-8-1] WARN  [] - Health check fails. reason: No healthy endpoint

### What you expected to happen

外部ES集群开启了 xpack.security.http.ssl.enabled，我如何才能将检测地址修改为：https://es-quickstart-es-http:9200/_cluster/health

### How to reproduce

我目前的启动命令如下：
helm install "${SKYWALKING_RELEASE_NAME}" \
  oci://registry-1.docker.io/apache/skywalking-helm \
  --version "${SKYWALKING_RELEASE_VERSION}" \
  -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=9.7.0 \
  --set oap.storageType=elasticsearch \
  --set ui.image.tag=9.7.0 \
  --set oap.replicas=1 \
  --set elasticsearch.protocol=https \
  --set elasticsearch.enabled=false \
  --set elasticsearch.config.scheme=https \
  --set elasticsearch.config.host=es-quickstart-es-http \
  --set elasticsearch.config.port.http=9200 \
  --set elasticsearch.config.user='elastic' \
  --set elasticsearch.config.password='g7xxxxxxxxxxxxxxxxx6' \
  --create-namespace

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No Chinese on GitHub. Use the slack CN channel or use English here. 

You are posting a QA, move to the discussion in English.
