### ISSUE TITLE
[Bug] go-agent grpc, interface {} is *transport.http2Server, not *transport.Stream,

### ISSUE THREAD

**Issue by songboyu** [apache/skywalking#12248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Go Agent (apache/skywalking-go)

### What happened

2024-05-24 06:00:06.200 ERROR   tracer.go:189   execute interceptor before invoke error, instrument name: grpc, interceptor name: ServerSendResponseInterceptor, function ID: google_golang_org_grpc_ServersendResponse, error: interface conversion: interface {} is *transport.http2Server, not *transport.Stream, stack: goroutine 111 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/apache/skywalking-go/agent/core.(*Tracer).DebugStack(0x47d4f8?)
        tracing.go:42 +0xf
google.golang.org/grpc.skywalking_operatorStaticMethodTracingDebugStack()
        skywalking_agent_core_tracing_api.go:144 +0x28
google.golang.org/grpc.skywalking_enhance_google_golang_org_grpc_ServersendResponse.func1()
        skywalking_delegator.go:18 +0x38
panic({0xf0fd00?, 0xc000226960?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
google.golang.org/grpc.(*skywalking_operatorTypeGrpcServerSendResponseInterceptor).BeforeInvoke(0x843?, {0x11f1470, 0xc00057b080})
        skywalking_enhance_grpc_server_sendresponse_interceptor.go:31 +0x2ad
google.golang.org/grpc.skywalking_enhance_google_golang_org_grpc_ServersendResponse(0xc0003eb8c0, 0xc0001f25c0, 0xc0001f25d0, 0xc000119d08, 0xc0001f25e0, 0xc0001f25f0, 0xc000119d10, 0xc0001f2600)
        skywalking_delegator.go:72 +0x4a5
google.golang.org/grpc.(*Server).sendResponse(0xc000468200, {0x11eda40, 0xc0001f5c80}, {0x11f3018, 0xc000002900}, 0xc000325c20, {0xf79540, 0xc000226840}, {0x0, 0x0}, ...)
        /home/turingera/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1140 +0x2b8
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000468200, {0x11eda40, 0xc0001f5b60}, {0x11f3018, 0xc000002900}, 0xc000325c20, 0xc0000abce0, 0x1901680, 0x0)
        /home/turingera/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1426 +0x11cd
google.golang.org/grpc.(*Server).handleStream(0xc000468200, {0x11f3018, 0xc000002900}, 0xc000325c20)
        /home/turingera/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1790 +0x11a6
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/turingera/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 67
        /home/turingera/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1040 +0x135
        {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,a018be1a194f11efb8396045bd1b53a7.107.39282552058460001,a018be1a194f11efb8396045bd1b53a7.111.39282552058460001,0]"}
2024-05-24 06:00:06.200 ERROR   tracer.go:189   send segment error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:00:06.200 ERROR   tracer.go:189   send closing error rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR    {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:00:25.093 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:00:45.093 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:01:05.094 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:01:25.095 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:01:45.096 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 06:02:05.097 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,a0194547194f11efb8396045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}

### What you expected to happen

no error and send metrics ok

### How to reproduce

fix that

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrproliu** [comment]
For now, the gRPC plugin does not support the newer version of the gRPC framework. Have you tried to downgrade to `1.57.0`?

**Comment by songboyu** [comment]
I downgrade to 1.55.0, that works, but this two problem still remain, what cause that ?

2024-05-24 11:44:07.126 ERROR   tracer.go:189   send closing error rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR    {"SW": "[spellguru-svr,060fbfb4195c11efa00c6045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}
2024-05-24 11:44:10.696 ERROR   tracer.go:189   send metrics error EOF  {"SW": "[spellguru-svr,060fbfb4195c11efa00c6045bd1b53a7@10.0.0.6,N/A,N/A,-1]"}

<img width="1538" alt="image" src="https://github.com/apache/skywalking/assets/2916633/1092805d-c3d9-4e67-bf42-72fc15903639">

**Comment by mrproliu** [comment]
It's looks like related to your configuration of the backend connection. Please check the backend address is correct.

**Comment by wu-sheng** [comment]
As this reports the unsupported version. I am closing this for now.

**Comment by wu-sheng** [comment]
Contributed through https://github.com/apache/skywalking-go/pull/183
