### ISSUE TITLE
[Bug] ERROR: value too long for type character varying(250)

### ISSUE THREAD

**Issue by friendlytkyj** [apache/skywalking#12364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

2024-06-21 22:17:23,830 - org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO - 81 [pool-6-thread-1] ERROR [] - Batch entry 96 INSERT INTO endpoint_relation_server_side_20240621(id,table_name,source_endpoint,dest_endpoint,component_id,entity_id,time_bucket) VALUES (('202406212216_VXNlcg==.0-VXNlcg==-cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1-SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('endpoint_relation_server_side'),('VXNlcg==.0_VXNlcg=='),('cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1_SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('1'::int4),('VXNlcg==.0-VXNlcg==-cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1-SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('202406212216'::int8)) was aborted: ERROR: value too long for type character varying(250)  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 96 INSERT INTO endpoint_relation_server_side_20240621(id,table_name,source_endpoint,dest_endpoint,component_id,entity_id,time_bucket) VALUES (('202406212216_VXNlcg==.0-VXNlcg==-cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1-SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('endpoint_relation_server_side'),('VXNlcg==.0_VXNlcg=='),('cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1_SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('1'::int4),('VXNlcg==.0-VXNlcg==-cHJlcmVsZWFzZTo6bS1yZXNvdXJjZXMtY2VudGVyfHZ4aWFvfA==.1-SEVBRDovY29tbW9ucy9maWxlL2xvY2FsRmlsZVBhdGg6L3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL0FwcGxpY2F0aW9uL0YzNTU2QjUwLTRDRjgtNEVCQS1BMjlELThFODIwM0EzNUI3Ni9Eb2N1bWVudHMvMTAwMTA5NTE3MTUvcmVmSW1hZ2VQYXRoL29yaWdp'),('202406212216'::int8)) was aborted: ERROR: value too long for type character varying(250)  Call getNextException to see other errors in the batch.
   at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684) ~[postgresql-42.4.4.jar:42.4.4]
   at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.1.0.jar:?]
   at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
   at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.executeBatch(BatchSQLExecutor.java:85) ~[storage-jdbc-hikaricp-plugin-10.0.1.jar:10.0.1]
   at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:74) ~[storage-jdbc-hikaricp-plugin-10.0.1.jar:10.0.1]
   at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.lambda$flush$1(JDBCBatchDAO.java:78) ~[storage-jdbc-hikaricp-plugin-10.0.1.jar:10.0.1]
   at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
   at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.dao.JDBCBatchDAO.flush(JDBCBatchDAO.java:75) ~[storage-jdbc-hikaricp-plugin-10.0.1.jar:10.0.1]
   at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$3(PersistenceTimer.java:135) ~[server-core-10.0.1.jar:10.0.1]
   at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
   at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(250)
   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.4.4.jar:42.4.4]
   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560) ~[postgresql-42.4.4.jar:42.4.4]
   ... 15 more

### What you expected to happen

when i check oap log, find the error.

### How to reproduce

it's auto collect by agent-java, oap use PostgreSQL.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You could use length control to add a more strict lengh limitation.

```
    # The max length of service + instance names should be less than 200
    serviceNameMaxLength: ${SW_SERVICE_NAME_MAX_LENGTH:70}
    # The period(in seconds) of refreshing the service cache. Default value is 10s.
    serviceCacheRefreshInterval: ${SW_SERVICE_CACHE_REFRESH_INTERVAL:10}
    instanceNameMaxLength: ${SW_INSTANCE_NAME_MAX_LENGTH:70}
    # The max length of service + endpoint names should be less than 240
    endpointNameMaxLength: ${SW_ENDPOINT_NAME_MAX_LENGTH:150}
```

application.yml and [docs](https://skywalking.apache.org/docs/main/latest/en/setup/backend/configuration-vocabulary/) have provided explanation.
