### ISSUE TITLE
K8S deploys SkyWalking MySQL Connection, but an error is reported in the log 

### ISSUE THREAD

**Issue by zxz-hash** [apache/skywalking#12487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

K8S deploys SkyWalking MySQL Connection

### Use case

but an error is reported in the log

### Related issues

2024-07-30 06:15:02,757 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO -100722817 [pool-4-thread-1] ERROR [] - Duplicate entry '202407300615' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '202407300615' for key 'PRIMARY'
        at jdk.internal.reflect.GeneratedConstructorAccessor48.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254) ~[mysql-connector-java-5.1.49.jar:5.1.49]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:53) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.synchronous(H2BatchDAO.java:72) [storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$3(PersistenceTimer.java:135) [server-core-8.5.0.jar:8.5.0]

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
8.5 is a year ago. Pick latest.

**Comment by zxz-hash** [comment]
I'm using the dockerfile as an image, copying the mysql driver JDBC to oap-libs/ and defining the variables that connect to mysql in k8s env

**Comment by zxz-hash** [comment]
> 8.5 是一年前。选择最新的。

hi Does the latest version fix this

**Comment by wu-sheng** [comment]
We don't. Mysql as storage is not popular and recommended for large scale. It just works mostly from official perspective.

**Comment by zxz-hash** [comment]
> 不知道。Mysql作为存储并不受欢迎，建议用于大规模。它只是主要从官方的角度来看工作。

For the time being, I don't consider using ES because I don't have too much effort to maintain ES, so I use AWS MySQL

**Comment by wu-sheng** [comment]
You could use any storage you prefer. But as ID conflicts thing is complex. We fixed some in the previous versions, but can't tell whether all are good.

**Comment by zxz-hash** [comment]
> 您可以使用您喜欢的任何存储。但是由于ID冲突，事情就很复杂了。我们在以前的版本中修复了一些问题，但无法判断是否所有问题都很好。
Does this error have any effect on the data or how can I fix it?

**Comment by wu-sheng** [comment]
Again. I don't whether this is fixed.

**Comment by wu-sheng** [comment]
You even didn't try new versions. But keep asking things from years ago.
Can't see the point of this conversation.

**Comment by zxz-hash** [comment]
I'll try the new version first
