### ISSUE TITLE
[Bug] 连接0.6.1失败

### ISSUE THREAD

**Issue by kekekekekeshi** [apache/skywalking#12490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

org.apache.skywalking.banyandb.v1.client.grpc.exception.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBApiExceptionFactory.createException(BanyanDBApiExceptionFactory.java:50) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.create(BanyanDBGrpcApiExceptionFactory.java:53) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.createException(BanyanDBGrpcApiExceptionFactory.java:41) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:47) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) [storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) [storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) [library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:75) [library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:52) [server-starter-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-10.0.1.jar:10.0.1]
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.63.0.jar:1.63.0]
	at org.apache.skywalking.banyandb.database.v1.GroupRegistryServiceGrpc$GroupRegistryServiceBlockingStub.create(GroupRegistryServiceGrpc.java:396) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.lambda$create$0(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:45) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	... 9 more
2024-07-30 13:28:36,581 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 64 [main] ERROR [] - [10.0.1-6a9d727] fail to define group
org.apache.skywalking.oap.server.library.module.ModuleStartException: fail to define group
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:183) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) ~[library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:75) ~[library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:52) [server-starter-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-10.0.1.jar:10.0.1]
Caused by: java.io.IOException: fail to define group
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:210) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more
Caused by: org.apache.skywalking.banyandb.v1.client.grpc.exception.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBApiExceptionFactory.createException(BanyanDBApiExceptionFactory.java:50) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.create(BanyanDBGrpcApiExceptionFactory.java:53) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.createException(BanyanDBGrpcApiExceptionFactory.java:41) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:47) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.63.0.jar:1.63.0]
	at org.apache.skywalking.banyandb.database.v1.GroupRegistryServiceGrpc$GroupRegistryServiceBlockingStub.create(GroupRegistryServiceGrpc.java:396) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.lambda$create$0(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:45) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more

### What you expected to happen

不报错

### How to reproduce

version: '3'
services:
  oap:
    container_name: oap
    image: apache/skywalking-oap-server:10.0.1
    platform: linux/amd64 
    environment:
    - SW_STORAGE=banyandb
    #- SW_STORAGE_BANYANDB_TARGETS=host.docker.internal:17912
    - SW_STORAGE_BANYANDB_TARGETS=10.211.55.21:17912
    ports:
    - '11800:11800'
    - '12800:12800'

### Anything else

 /usr/bin/banyand-server data         --etcd-endpoints=https://10.211.55.21:2379,https://10.211.55.22:2379,https://10.211.55.23:2379  --etcd-tls-ca-file=/etc/etcd/tls/ca.pem         --etcd-tls-cert-file=/etc/etcd/tls/etcd.pem     --etcd-tls-key-file=/etc/etcd/tls/etcd-key.pem  --etcd-username=root    --etcd-password=root --grpc-host=10.211.55.21 --grpc-port=17912  --logging-level=debug

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No Chinese on GitHub. If you need to discuss in Chinese, use slack CN channel.
