### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kekekekekeshi** [apache/skywalking#12491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

2024-07-30 13:28:36,575 org.apache.skywalking.oap.server.telemetry.api.HealthCheckMetrics 44 [main] ERROR [] - [10.0.1-6a9d727] Health check fails
org.apache.skywalking.banyandb.v1.client.grpc.exception.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBApiExceptionFactory.createException(BanyanDBApiExceptionFactory.java:50) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.create(BanyanDBGrpcApiExceptionFactory.java:53) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.createException(BanyanDBGrpcApiExceptionFactory.java:41) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:47) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) [storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) [storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) [library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:75) [library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:52) [server-starter-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-10.0.1.jar:10.0.1]
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.63.0.jar:1.63.0]
	at org.apache.skywalking.banyandb.database.v1.GroupRegistryServiceGrpc$GroupRegistryServiceBlockingStub.create(GroupRegistryServiceGrpc.java:396) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.lambda$create$0(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:45) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	... 9 more
2024-07-30 13:28:36,581 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 64 [main] ERROR [] - [10.0.1-6a9d727] fail to define group
org.apache.skywalking.oap.server.library.module.ModuleStartException: fail to define group
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:183) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) ~[library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:75) ~[library-module-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:52) [server-starter-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-10.0.1.jar:10.0.1]
Caused by: java.io.IOException: fail to define group
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:210) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more
Caused by: org.apache.skywalking.banyandb.v1.client.grpc.exception.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBApiExceptionFactory.createException(BanyanDBApiExceptionFactory.java:50) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.create(BanyanDBGrpcApiExceptionFactory.java:53) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.exception.BanyanDBGrpcApiExceptionFactory.createException(BanyanDBGrpcApiExceptionFactory.java:41) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:47) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service banyandb.database.v1.GroupRegistryService
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.63.0.jar:1.63.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.63.0.jar:1.63.0]
	at org.apache.skywalking.banyandb.database.v1.GroupRegistryServiceGrpc$GroupRegistryServiceBlockingStub.create(GroupRegistryServiceGrpc.java:396) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.lambda$create$0(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.HandleExceptionsWith.callAndTranslateApiException(HandleExceptionsWith.java:45) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.grpc.MetadataClient.execute(MetadataClient.java:100) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.metadata.GroupMetadataRegistry.create(GroupMetadataRegistry.java:40) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.banyandb.v1.client.BanyanDBClient.define(BanyanDBClient.java:410) ~[banyandb-java-client-0.6.0.jar:0.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageClient.defineIfEmpty(BanyanDBStorageClient.java:204) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.banyandb.BanyanDBStorageProvider.start(BanyanDBStorageProvider.java:178) ~[storage-banyandb-plugin-10.0.1.jar:10.0.1]
	... 4 more

### What you expected to happen

Health check success

### How to reproduce

version: '3'
services:
  oap:
    container_name: oap
    image: apache/skywalking-oap-server:10.0.1
    platform: linux/amd64 
    environment:
    - SW_STORAGE=banyandb
    - SW_STORAGE_BANYANDB_TARGETS=10.211.55.21:17912
    ports:
    - '11800:11800'
    - '12800:12800'

### Anything else

 /usr/bin/banyand-server data         --etcd-endpoints=https://10.211.55.21:2379,https://10.211.55.22:2379,https://10.211.55.23:2379  --etcd-tls-ca-file=/etc/etcd/tls/ca.pem         --etcd-tls-cert-file=/etc/etcd/tls/etcd.pem     --etcd-tls-key-file=/etc/etcd/tls/etcd-key.pem  --etcd-username=root    --etcd-password=root --grpc-host=10.211.55.21 --grpc-port=17912  --logging-level=debug

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kekekekekeshi** [comment]
banyand-server --version
{"level":"debug","module":"STANDALONE","name":"metadata","registered":1,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"measure","registered":2,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"stream","registered":3,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"warn","module":"STANDALONE","name":"max-fan-out-size","registered":3,"time":"2024-07-30T21:41:31+08:00","message":"ignoring duplicate flag"}
{"level":"debug","module":"STANDALONE","name":"grpc","registered":4,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"liaison-http","registered":5,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"pprof-service","registered":6,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"metric-service","registered":7,"total":7,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"metadata","registered":1,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"server-queue","registered":2,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"measure","registered":3,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"stream","registered":4,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"warn","module":"DATA","name":"max-fan-out-size","registered":4,"time":"2024-07-30T21:41:31+08:00","message":"ignoring duplicate flag"}
{"level":"debug","module":"DATA","name":"pprof-service","registered":5,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"metric-service","registered":6,"total":6,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"metadata","registered":1,"total":5,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"grpc","registered":2,"total":5,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"liaison-http","registered":3,"total":5,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"pprof-service","registered":4,"total":5,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"metric-service","registered":5,"total":5,"time":"2024-07-30T21:41:31+08:00","message":"register flags"}
version v0.6.1-37-g3da0259-main

**Comment by kekekekekeshi** [comment]
> Hi, `/usr/bin/banyand-server data` is for the cluster mode. If you want to run banyandb as a single node, `/usr/bin/banyand-server standalone` works. Refer to [standalone installation](https://github.com/apache/skywalking-banyandb/blob/main/docs/installation/standalone.md). For setting up a cluster, use [cluster installation](https://github.com/apache/skywalking-banyandb/blob/main/docs/installation/cluster.md).

**I didn't understand the following content**

Node Discovery
The node discovery is based on the etcd cluster. The etcd cluster is required for the metadata module to provide the metadata service and nodes discovery service for the whole cluster.

The host is registered to the etcd cluster by the banyand-server-static automatically based on node-host-provider :

node-host-provider=hostname : Default. The OS's hostname is registered as the host part in the address.
node-host-provider=ip : The OS's the first non-loopback active IP address(IPv4) is registered as the host part in the address.
node-host-provider=flag : node-host is registered as the host part in the address.

**When I start data and then go to start liaison, there will be an issue where the node already exists**

/usr/bin/banyand-server data --etcd-endpoints=[https://10.211.55.21:2379,https://10.211.55.22:2379,https://10.211.55.23:2379](https://10.211.55.21:2379,https//10.211.55.22:2379,https://10.211.55.23:2379) --etcd-tls-ca-file=/etc/etcd/tls/ca.pem --etcd-tls-cert-file=/etc/etcd/tls/etcd.pem --etcd-tls-key-file=/etc/etcd/tls/etcd-key.pem --etcd-username=root --etcd-password=root --grpc-host=10.211.55.21 --grpc-port=17912 --logging-level=debug

/usr/bin/banyand-server liaison --etcd-endpoints=https://10.211.55.21:2379,https://10.211.55.22:2379,https://10.211.55.23:2379 --etcd-tls-ca-file=/etc/etcd/tls/ca.pem --etcd-tls-cert-file=/etc/etcd/tls/etcd.pem --etcd-tls-key-file=/etc/etcd/tls/etcd-key.pem --etcd-username=root --etcd-password=root --grpc-host=10.211.55.21 --grpc-port=17912 --logging-level=debug
{"level":"debug","module":"STANDALONE","name":"metadata","registered":1,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"measure","registered":2,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"stream","registered":3,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"warn","module":"STANDALONE","name":"max-fan-out-size","registered":3,"time":"2024-07-30T22:16:11+08:00","message":"ignoring duplicate flag"}
{"level":"debug","module":"STANDALONE","name":"grpc","registered":4,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"liaison-http","registered":5,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"pprof-service","registered":6,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"STANDALONE","name":"metric-service","registered":7,"total":7,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"metadata","registered":1,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"server-queue","registered":2,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"measure","registered":3,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"stream","registered":4,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"warn","module":"DATA","name":"max-fan-out-size","registered":4,"time":"2024-07-30T22:16:11+08:00","message":"ignoring duplicate flag"}
{"level":"debug","module":"DATA","name":"pprof-service","registered":5,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"DATA","name":"metric-service","registered":6,"total":6,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"metadata","registered":1,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"grpc","registered":2,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"liaison-http","registered":3,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"pprof-service","registered":4,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}
{"level":"debug","module":"LIAISON","name":"metric-service","registered":5,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"register flags"}

██████╗  █████╗ ███╗   ██╗██╗   ██╗ █████╗ ███╗   ██╗██████╗ ██████╗ 
██╔══██╗██╔══██╗████╗  ██║╚██╗ ██╔╝██╔══██╗████╗  ██║██╔══██╗██╔══██╗
██████╔╝███████║██╔██╗ ██║ ╚████╔╝ ███████║██╔██╗ ██║██║  ██║██████╔╝
██╔══██╗██╔══██║██║╚██╗██║  ╚██╔╝  ██╔══██║██║╚██╗██║██║  ██║██╔══██╗
██████╔╝██║  ██║██║ ╚████║   ██║   ██║  ██║██║ ╚████║██████╔╝██████╔╝
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═════╝ 
{"level":"info","time":"2024-07-30T22:16:11+08:00","message":"starting as a liaison server"}
{"level":"debug","module":"LIAISON","name":"metadata","ran":1,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"validate config"}
{"level":"debug","module":"LIAISON","name":"grpc","ran":2,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"validate config"}
{"level":"debug","module":"LIAISON","name":"liaison-http","ran":3,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"validate config"}
{"level":"debug","module":"LIAISON","name":"pprof-service","ran":4,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"validate config"}
{"level":"debug","module":"LIAISON","name":"metric-service","ran":5,"total":5,"time":"2024-07-30T22:16:11+08:00","message":"validate config"}
{"level":"info","module":"LIAISON","time":"2024-07-30T22:16:11+08:00","message":"started"}
{"level":"info","module":"LIAISON","roles":[1,3],"time":"2024-07-30T22:16:11+08:00","message":"the node will run as"}
{"level":"info","module":"LIAISON","elapsed":0.633086,"name":"signal","time":"2024-07-30T22:16:11+08:00","message":"pre-run completed"}
{"level":"debug","ts":1722348971.9433084,"caller":"v3@v3.5.13/retry_interceptor.go:53","msg":"retrying of unary invoker","target":"etcd-endpoints://0xc0001381e0/10.211.55.21:2379","attempt":0}
{"level":"debug","ts":1722348972.0302632,"caller":"v3@v3.5.13/retry_interceptor.go:53","msg":"retrying of unary invoker","target":"etcd-endpoints://0xc0001381e0/10.211.55.21:2379","attempt":0}
{"level":"debug","ts":1722348972.0322359,"caller":"v3@v3.5.13/retry_interceptor.go:53","msg":"retrying of unary invoker","target":"etcd-endpoints://0xc0001381e0/10.211.55.21:2379","attempt":0}
{"level":"fatal","module":"LIAISON","error":"pre-run module[metadata]: node[etcd-1:17912] already exists in etcd: key /banyandb/nodes/etcd-1:17912, response: header:<cluster_id:14419496597857270165 member_id:13627017585491445394 revision:300 raft_term:932 > responses:<response_range:<header:<revision:300 > kvs:<key:\"/banyandb/nodes/etcd-1:17912\" create_revision:300 mod_revision:300 version:1 value:\"\\n\\016\\022\\014etcd-1:17912\\022\\002\\001\\002\\032\\014etcd-1:17912*\\013\\010\\206\\351\\243\\265\\006\\020\\237\\327\\272O\" lease:4811411082752780589 > count:1 > > : rpc error: code = AlreadyExists desc = banyandb: resource already exists","time":"2024-07-30T22:16:12+08:00","message":"unexpected exit"}
