### ISSUE TITLE
Unable to monitor SQL ，and my oracle driver ：ojdbc7-12.1.0

### ISSUE THREAD

**Issue by Anarchists** [apache/skywalking#1303]
skywalking-5.0.0-alpha

agent error log :

```
ERROR 2018-06-04 11:09:08 InstMethodsInter :  class[class oracle.jdbc.driver.T4CPreparedStatement] before method[executeQuery] intercept failure 
java.lang.NullPointerException
	at org.apache.skywalking.apm.plugin.jdbc.oracle.PreparedStatementExecuteMethodsInterceptor.beforeMethod(PreparedStatementExecuteMethodsInterceptor.java:42)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2721)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2718)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:145)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.*****.database.jdbc.impl.Execute.getResultSet(bd:6)
	at com.*****.database.jdbc.impl.Query.M(a:250)
	at com.*****.database.jdbc.impl.Query.doQuery(a:230)
	at com.*****.database.jdbc.impl.DBImpl.query(gd:128)
	at com.*****.database.peisistence.crud.impl.PrimarySqlImpl.getPageData(kb:63)
	at com.*****.database.peisistence.crud.CRUDService.getPageData(rb:330)
	at com.*****.database.peisistence.crud.CRUDService.getResultListPaginatorNative(rb:359)
	at com.*****.database.peisistence.crud.impl.query.NativeQuery.getResultList(fb:28)
	at com.*****.database.peisistence.crud.impl.query.NativeQuery.getResultList(fb:193)
	at com.*****.core.dao.CommonDao.findList(so:291)
	at com.*****.core.dao.CommonDao.findList(so:587)
	at com.*****.basic.bizlogic.orga.user.impl.UserServiceDbImpl.getAllFrameUserRelation(dg:914)
	at com.*****.basic.bizlogic.orga.ou.init.OuInit.initCacheOu(wf:152)
	at com.*****.basic.cache.impl.EHCacheInit.F(fn:620)
	at com.*****.basic.cache.impl.EHCacheInit.init(fn:169)
	at com.*****.basic.cache.CacheInit.init(el:147)
	at com.*****.basic.cache.SubscriberInit.initMemory(zi:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:717)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:288)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:234)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethod(ReflectUtil.java:191)
	at com.*****.basic.timetask.*****StartInit.startInit(gc:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:717)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:288)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethodWithObjHasParame(ReflectUtil.java:234)
	at com.*****.core.utils.reflect.ReflectUtil.invokeMethod(ReflectUtil.java:191)
	at com.*****.core.dto.*****DispatcherServlet.initFrameworkServlet(b:178)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:491)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5231)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5518)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wu-sheng** [comment]
@Anarchists  Oracle has many license restrict, I asked @ascrutae to help, but I am not sure whether could he have the suitable env.

I think debug a NPE should be easy. Could you try to solve this by your own?

**Comment by Anarchists** [comment]
![image](https://user-images.githubusercontent.com/33044665/40957548-4011ecb0-68c8-11e8-982a-12dc93a3b427.png)

**Comment by Anarchists** [comment]
![qq 20180605114159](https://user-images.githubusercontent.com/33044665/40957736-0682e9b2-68c9-11e8-96a0-7fd0d24270d8.png)

**Comment by wu-sheng** [comment]
@Anarchists What is your connection URL?

@ascrutae I think you may miss a constructor or way to initialize.

**Comment by Anarchists** [comment]
jdbc:oracle:thin:@192.168.212.234:1521:orcl

**Comment by wu-sheng** [comment]
Oracle is not going to be supported in an ASF project.
