### ISSUE TITLE
Mongo 1.9.x driver support

### ISSUE THREAD

**Issue by asivanadi** [apache/skywalking#1308]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [!] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- What happen?
ERROR 2018-06-04 23:17:27 InstMethodsInter :  class[class com.mongodb.MongoClient] before method[execute] intercept failure
java.lang.NullPointerException

ERROR 2018-06-04 23:17:27 InstMethodsInter :  class[class com.mongodb.MongoClient] after method[execute] intercept failure
java.lang.IllegalStateException: No active span.
	at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:390)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:155)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:159)
	at org.apache.skywalking.apm.plugin.mongodb.v3.MongoDBMethodInterceptor.afterMethod(MongoDBMethodInterceptor.java:189)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at com.mongodb.Mongo.execute(Mongo.java)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:333)
	at com.mongodb.DBCollection.updateImpl(DBCollection.java:495)
	at com.mongodb.DBCollection.update(DBCollection.java:455)
	at com.mongodb.DBCollection.update(DBCollection.java:432)

The same worked in 3.x version of incubator-skywalking

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@ascrutae Please recheck codes with 3.x release.

@asivanadi Actually, you could check by yourself too.

**Comment by ascrutae** [comment]
Could you post me that the driver version you use?

**Comment by asivanadi** [comment]
1.9.2

**Comment by ascrutae** [comment]
I think this issue maybe occur that mongo plugin miss the witness class.  I will recheck this

**Comment by wu-sheng** [comment]
@ascrutae Again, witness check is a fail safe mechanism. You can't say error caused by that. Any unsupported version has possibility to cause unexpected exception.

**Comment by asivanadi** [comment]
@wu-sheng how did we support this in 3.x version ?

**Comment by wu-sheng** [comment]
@asivanadi Open the URL I gave you already. It is the supported list.

**Comment by wu-sheng** [comment]
> how did we support this in 3.x version ?

@asivanadi We haven't ever. At least, we don't intend to. Maybe something accidently works out.

**Comment by wu-sheng** [comment]
No feedback and old lib.
