### ISSUE TITLE
receive zipkin spans error

### ISSUE THREAD

**Issue by MLeft** [apache/skywalking#1754]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want use skywalking to collect zipkin span, but get NEP in `skywalking-collector-server.log`, skywalking-webapp(http://localhost:8080/#/trace) can not see these trace either.
What can i do for this?
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 5.0.0-RC2
Zipkin-brave 5.4.0
Elasticsearche 5.5.3
OS WIN10
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
skywalking-collector-server.log:
```
2018-10-11 15:34:25,102 - org.apache.skywalking.apm.collector.receiver.zipkin.provider.cache.caffeine.CaffeineSpanCache -829174 [ForkJoinPool.commonPool-worker-2] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.transform.SegmentBuilder.buildRef(SegmentBuilder.java:238) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.transform.SegmentBuilder.initSpan(SegmentBuilder.java:166) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.transform.SegmentBuilder.scanSpansFromRoot(SegmentBuilder.java:126) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.transform.SegmentBuilder.build(SegmentBuilder.java:89) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.transform.Zipkin2SkyWalkingTransfer.transfer(Zipkin2SkyWalkingTransfer.java:59) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.cache.caffeine.CaffeineSpanCache.onRemoval(CaffeineSpanCache.java:75) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at org.apache.skywalking.apm.collector.receiver.zipkin.provider.cache.caffeine.CaffeineSpanCache.onRemoval(CaffeineSpanCache.java:45) ~[receiver-zipkin-provider-5.0.0-RC2.jar:5.0.0-RC2]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$notifyRemoval$1(BoundedLocalCache.java:286) ~[caffeine-2.6.2.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_101]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_101]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_101]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_101]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_101]
2018-10-11 15:34:25,102 - org.apache.skywalking.apm.collector.receiver.zipkin.provider.cache.caffeine.CaffeineSpanCache -829174 [ForkJoinPool.commonPool-worker-2] WARN  [] - Zipkin trace:ZipkinTrace{spans=[{"traceId":"2d10f39070f84afe","parentId":"fd7bfc2684f81b9c","id":"950c3df562b85a25","kind":"SERVER","name":"heyservice/sayok","timestamp":1539243242879015,"duration":184,"localEndpoint":{"serviceName":"service-f","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":51403},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"b490d6fce6c33284","id":"fd7bfc2684f81b9c","kind":"CLIENT","name":"helloservice/sayok","timestamp":1539243242876016,"duration":4203,"localEndpoint":{"serviceName":"service-c","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":40014}}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"SERVER","name":"get /trace/c","timestamp":1539243242876049,"duration":5862,"localEndpoint":{"serviceName":"service-c","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51421},"tags":{"http.method":"GET","http.path":"/trace/c","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"CLIENT","name":"get","timestamp":1539243242872407,"duration":2446,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"tags":{"http.method":"GET","http.path":"/trace/b"}}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"CLIENT","name":"get","timestamp":1539243242875338,"duration":6503,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":50013},"tags":{"http.method":"GET","http.path":"/trace/c"}}, {"traceId":"2d10f39070f84afe","id":"2d10f39070f84afe","kind":"SERVER","name":"get /trace/a","timestamp":1539243242871098,"duration":12003,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51417},"tags":{"http.method":"GET","http.path":"/trace/a","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"}}, {"traceId":"2d10f39070f84afe","parentId":"fd7bfc2684f81b9c","id":"950c3df562b85a25","kind":"CLIENT","name":"heyservice/sayok","timestamp":1539243242878034,"duration":1933,"localEndpoint":{"serviceName":"service-d","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":40016}}, {"traceId":"2d10f39070f84afe","parentId":"b490d6fce6c33284","id":"fd7bfc2684f81b9c","kind":"SERVER","name":"helloservice/sayok","timestamp":1539243242877045,"duration":2551,"localEndpoint":{"serviceName":"service-d","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":51365},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"SERVER","name":"get /trace/b","timestamp":1539243242873067,"duration":1427,"localEndpoint":{"serviceName":"service-b","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51419},"tags":{"http.method":"GET","http.path":"/trace/b","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"},"shared":true}]}
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by MLeft** [comment]
> SkyWalking Zipkin is incubating for this reason, we didn't test for the different scenario. Could you post your trace data in zipkin format here? Or run debug to find out why NPE in `buildRef(SegmentBuilder.java:238)`

do you mean these trace date :
```
Zipkin trace:ZipkinTrace{spans=[{"traceId":"2d10f39070f84afe","parentId":"fd7bfc2684f81b9c","id":"950c3df562b85a25","kind":"SERVER","name":"heyservice/sayok","timestamp":1539243242879015,"duration":184,"localEndpoint":{"serviceName":"service-f","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":51403},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"b490d6fce6c33284","id":"fd7bfc2684f81b9c","kind":"CLIENT","name":"helloservice/sayok","timestamp":1539243242876016,"duration":4203,"localEndpoint":{"serviceName":"service-c","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":40014}}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"SERVER","name":"get /trace/c","timestamp":1539243242876049,"duration":5862,"localEndpoint":{"serviceName":"service-c","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51421},"tags":{"http.method":"GET","http.path":"/trace/c","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"CLIENT","name":"get","timestamp":1539243242872407,"duration":2446,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"tags":{"http.method":"GET","http.path":"/trace/b"}}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"CLIENT","name":"get","timestamp":1539243242875338,"duration":6503,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":50013},"tags":{"http.method":"GET","http.path":"/trace/c"}}, {"traceId":"2d10f39070f84afe","id":"2d10f39070f84afe","kind":"SERVER","name":"get /trace/a","timestamp":1539243242871098,"duration":12003,"localEndpoint":{"serviceName":"service-a","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51417},"tags":{"http.method":"GET","http.path":"/trace/a","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"}}, {"traceId":"2d10f39070f84afe","parentId":"fd7bfc2684f81b9c","id":"950c3df562b85a25","kind":"CLIENT","name":"heyservice/sayok","timestamp":1539243242878034,"duration":1933,"localEndpoint":{"serviceName":"service-d","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":40016}}, {"traceId":"2d10f39070f84afe","parentId":"b490d6fce6c33284","id":"fd7bfc2684f81b9c","kind":"SERVER","name":"helloservice/sayok","timestamp":1539243242877045,"duration":2551,"localEndpoint":{"serviceName":"service-d","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"172.17.16.178","port":51365},"shared":true}, {"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"SERVER","name":"get /trace/b","timestamp":1539243242873067,"duration":1427,"localEndpoint":{"serviceName":"service-b","ipv4":"172.17.16.178"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":51419},"tags":{"http.method":"GET","http.path":"/trace/b","mvc.controller.class":"TraceController","mvc.controller.method":"receiveAndSend"},"shared":true}]}
```
I have serviceA/B/C/D

Here is some test:

Service | Status
------------ | -------------
A-->B(http) | OK
A-->B(http)<br />A-->C(http) | OK
A-->B(http)<br />A-->C(http)<br />A-->D(http) | NEP
A-->B(dubbo) | NEP

**Comment by BuQingYan** [comment]
I have the same problem，have you solved this problem?

**Comment by wu-sheng** [comment]
I am very busy these days, could you @BuQingYan @MLeft try to debug and find the issue by yourself and send a PR to us? NPE should not hard to fix.

**Comment by wuyoushan** [comment]
I debugged the program. In line 107 parentId ="2d10f39070f84afe" List<Span> spanList 

0={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"SERVER"}
1={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"CLIENT"}
2={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"CLIENT"}
3={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"SERVER"}

List has order, if the span order is changed to kind=CLIENT in front
0={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"CLIENT"}
1={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"CLIENT"}
2={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"b490d6fce6c33284","kind":"SERVER"}
3={"traceId":"2d10f39070f84afe","parentId":"2d10f39070f84afe","id":"7ad683dff428ad15","kind":"SERVER"}

clientPartSpan will add the corresponding object on line 162, so 238 lines will not produce NPE

I want to create a merge request to modify it, but I don't know how to modify it.
