### ISSUE TITLE
Duplicate entry '201902190402_4_8_33' for key 'PRIMARY'

### ISSUE THREAD

**Issue by a198720** [apache/skywalking#2255]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to fixed it
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0-SNAPSHOT,Centos7.x, jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
2019-02-19 04:02:49,987 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 58 [pool-16-thread-1] ERROR [] - Duplicate entry '201902190402_4_8_33' for key 'PRIMARY'
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '201902190402_4_8_33' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:634) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:414) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:52) ~[storage-jdbc-hikaricp-plugin-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.batchPersistence(H2BatchDAO.java:55) ~[storage-jdbc-hikaricp-plugin-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:113) ~[server-core-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$22(PersistenceTimer.java:65) ~[server-core-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
use zookeeper as cluster manager, mysql 8 as storage.

**Comment by a198720** [comment]
Is it possible to solve this problem by adding a distributed transaction control?

**Comment by wu-sheng** [comment]
I know this, but don't know why exactly. Maybe, because Database batch writing wouldn't flush immediately by another transaction. DTS wouldn't help. Maybe the solutiom is adding a recheck lock, after the batch writing.

**Comment by a198720** [comment]
Does this error affect the data?

**Comment by wu-sheng** [comment]
Yes. It will cause the metric data loose.

**Comment by a198720** [comment]
thank you.  I will also consider how to solve this problem.

**Comment by wu-sheng** [comment]
Thank you. Look forward to your feedback and solution. I think the database would guarantee this, we need a code level mechanism to wait for the data flush.

**Comment by wu-sheng** [comment]
Closing for now. No update and further progress.
