### ISSUE TITLE
Exception:: Class Cast Exception with DBCDriverInterceptor 

### ISSUE THREAD

**Issue by ychandu** [apache/skywalking#2277]
`ERROR 2019-02-21 15:55:10:705 InstMethodsInter :  class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure 
java.lang.ClassCastException: com.sun.proxy.$Proxy95 cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
	at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:430)
	at com.mysql.jdbc.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:170)
	at com.mysql.jdbc.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:85)
	at com.mysql.jdbc.NonRegisteringDriver.connectReplicationConnection(NonRegisteringDriver.java:457)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY(NonRegisteringDriver.java:314)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY$accessor$RVqvkyyH(NonRegisteringDriver.java)
	at com.mysql.jdbc.NonRegisteringDriver$auxiliary$gIvLYnV8.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.Driver.connect$accessor$uuunn4IT(Driver.java)
	at com.mysql.jdbc.Driver$auxiliary$N0h0vKEF.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.Driver.connect(Driver.java)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

ERROR 2019-02-21 15:55:10:706 InstMethodsInter :  class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure 
java.lang.ClassCastException: com.sun.proxy.$Proxy95 cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
	at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:430)
	at com.mysql.jdbc.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:170)
	at com.mysql.jdbc.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:85)
	at com.mysql.jdbc.NonRegisteringDriver.connectReplicationConnection(NonRegisteringDriver.java:457)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY(NonRegisteringDriver.java:314)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY$accessor$RVqvkyyH(NonRegisteringDriver.java)
	at com.mysql.jdbc.NonRegisteringDriver$auxiliary$gIvLYnV8.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.Driver.connect$accessor$uuunn4IT(Driver.java)
	at com.mysql.jdbc.Driver$auxiliary$N0h0vKEF.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.Driver.connect(Driver.java)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

ERROR 2019-02-21 15:55:10:707 InstMethodsInter :  class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure 
java.lang.ClassCastException: com.sun.proxy.$Proxy95 cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
	at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:430)
	at com.mysql.jdbc.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:170)
	at com.mysql.jdbc.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:85)
	at com.mysql.jdbc.NonRegisteringDriver.connectReplicationConnection(NonRegisteringDriver.java:457)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY(NonRegisteringDriver.java:314)
	at com.mysql.jdbc.NonRegisteringDriver.connect$original$yH3OOEwY$accessor$RVqvkyyH(NonRegisteringDriver.java)
	at com.mysql.jdbc.NonRegisteringDriver$auxiliary$gIvLYnV8.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at com.mysql.jdbc.Driver.connect$accessor$uuunn4IT(Driver.java)
	at com.mysql.jdbc.Driver$auxiliary$N0h0vKEF.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.mysql.jdbc.Driver.connect(Driver.java)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)`

Agent Version: 6.0 GA

**Comment by wu-sheng** [comment]
MySQL version 6 or 8?

**Comment by ychandu** [comment]
MySQL 5.7 , MySQL java connector - 5.1.4? is this information fine.

**Comment by wu-sheng** [comment]
Look like MySQL 5.1.4 connector test passed, https://github.com/SkyAPMTest/agent-integration-test-report#mysql. 

Have you tried the latest version?
There are many ways to use MySQL, I think you may be using a way we haven't checked and supported.
