### ISSUE TITLE
HTTP/1.1 409 Conflict

### ISSUE THREAD

**Issue by Stephen-sen** [apache/skywalking#2496]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when I use es cluster,and backend config is zk cluster.when I start one backend service all is ok,but when I start two or more backend,the log always show HTTP/1.1 409 Conflict.
___
### Bug
- Which version of SkyWalking, OS and JRE?
ES version 6.7.0
Skywaking version 6.0-GA
ZK vesion 3.4.14
- Which company or project?

- What happen?
the flowing is log
`{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[type][ghs-order-diss_0_0]: version conflict, required seqNo [5119828], primary term [4]. current document has seqNo [5119829] and primary term [4]","index_uuid":"WSysIDFAReG7htva23-kZw","shard":"2","index":"service_inventory"}],"type":"version_conflict_engine_exception","reason":"[type][ghs-order-diss_0_0]: version conflict, required seqNo [5119828], primary term [4]. current document has seqNo [5119829] and primary term [4]","index_uuid":"WSysIDFAReG7htva23-kZw","shard":"2","index":"service_inventory"},"status":409}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:366) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.forceUpdate(ElasticSearchClient.java:172) ~[library-client-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.forceUpdate(RegisterEsDAO.java:60) ~[storage-elasticsearch-plugin-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:77) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
		at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_201]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:72) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:36) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
	Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://10.123.129.15:9200], URI [/service_inventory/type/ghs-order-diss_0_0/_update?refresh=true&timeout=1m], status line [HTTP/1.1 409 Conflict]`

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment]
@Stephen-sen Don't worry about it, this is a distributed consistency problem. we use the document version to avoid different OAP server get the same document id. So, you get this conflict log.

**Comment by Stephen-sen** [comment]
ok,I see,thank you

**Comment by wanbenchao** [comment]
I encountered the same error and the UI page had no data
