### ISSUE TITLE
facing issue while connecting collector to elastic

### ISSUE THREAD

**Issue by hemant-learningforever** [apache/skywalking#2522]
- Why do you submit this issue?
-  Question or discussion
-  Bug

While staring skywalking collector getting below issue.
Exception in thread "main" ElasticsearchStatusException[Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:

In the logs this is what i got
2019-04-24 19:02:01,428 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 97 [main] INFO [] - elasticsearch cluster nodes: localhost:9200
2019-04-24 19:02:02,777 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller - 78 [main] INFO [] - table: all_heatmap_hour does not exist
2019-04-24 19:02:02,838 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 89 [main] INFO [] - index elasticsearch_all_heatmap_hour's mapping builder str: {"_all":{"enabled":false},"properties":{"step":{"type":"integer"},"num_of_steps":{"type":"integer"},"detail_group":{"type":"keyword"},"time_bucket":{"type":"long"}}}

Is there any script to create all required indexes first?

Thanks,
Hemant.

**Comment by wu-sheng** [comment]
SkyWalking should create index automatically. If not, please check startup log.

**Comment by hemant-learningforever** [comment]
There is no file called as startup log

All i could see is skywalking-oap-server.log which talks gives the string and error message as below.

2019-04-25 15:29:30,621 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 89 [main] INFO  [] - index all_p50_day's mapping builder str: {"_all":{"enabled":false},"properties":{"value":{"type":"integer"},"precision":{"type":"integer"},"detail_group":{"type":"keyword"},"time_bucket":{"type":"long"}}}


Exception in thread "main" ElasticsearchStatusException[Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {_all={enabled=false}, properties={precision={type=integer}, time_bucket={type=long}, value={type=integer}, detail_group={type=keyword}}}]]]; nested: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [type : {_all={enabled=false}, properties={precision={type=integer}, time_bucket={type=long}, value={type=integer}, detail_group={type=keyword}}}]]];
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653)
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508)
        at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99)
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:114)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:96)
        at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:79)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:91)
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57)
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65)
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43)

Can someone help? Is there a doc to explain what settings are required at elastic side?

**Comment by wu-sheng** [comment]
We don't know any special setting for index creation.

> 2019-04-25 15:29:30,621 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 89 [main] INFO [] - index all_p50_day's mapping builder str: {"_all":{"enabled":false},"properties":{"value":{"type":"integer"},"precision":{"type":"integer"},"detail_group":{"type":"keyword"},"time_bucket":{"type":"long"}}}

This looks like the index creation command.

**Comment by galaxyyao** [comment]
I met similar skywalking error log when building skywalking 6.1.0 + elasticsearch 7.0.1.
After I downgraded elasticsearch version to 6.7.2, the error log no longer occurs.
So I guess the problem may be somewhat related to calling certain api that no longer supported by elasticsearch 7.

BTW, the detailed error log with es 7 is as below. I hope it may be helpful in troubleshooting:

> 2019-05-14 17:48:36,033 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 78 [main] INFO  [] - index all_heatmap_hour's columnTypeEsMapping builder str: {"type":{"properties":{"step":{"type":"integer"},"num_of_steps":{"type":"integer"},"detail_group":{"type":"keyword"},"time_bucket":{"type":"long"}}}}
2019-05-14 17:48:36,802 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:106) ~[library-client-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:82) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:79) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:132) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
        Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://10.16.34.125:9200], URI [/all_heatmap_hour?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]"}},"status":400}
                at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
                at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:106) ~[library-client-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:82) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:79) ~[server-core-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:132) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
                at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
        Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://10.16.34.125:9200], URI [/all_heatmap_hour?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]"}},"status":400}
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [type : {type={properties={num_of_steps={type=integer}, time_bucket={type=long}, step={type=integer}, detail_group={type=keyword}}}}]]
        at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:510) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:421) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:451) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:617) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[elasticsearch-6.3.2.jar:6.3.2]
        ... 12 more
