### ISSUE TITLE
zipkin client invoke /api/v2/spans error

### ISSUE THREAD

**Issue by manheiba** [apache/skywalking#2525]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
#### Bug description.
 zipkin(version 2.7.1) client invoke to /api/v2/spans 
```
stack
org.springframework.web.client.HttpServerErrorException: 500 Server Error
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:89)
at org.springframework.web.client.RestTemplate.handleResponse$original$HK9wpf9R(RestTemplate.java:708)
at org.springframework.web.client.RestTemplate.handleResponse$original$HK9wpf9R$accessor$APv18Qze(RestTemplate.java)
at org.springframework.web.client.RestTemplate$auxiliary$lVIjkQ7h.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java)
at org.springframework.web.client.RestTemplate.doExecute$original$HK9wpf9R(RestTemplate.java:661)
at org.springframework.web.client.RestTemplate.doExecute$original$HK9wpf9R$accessor$APv18Qze(RestTemplate.java)
at org.springframework.web.client.RestTemplate$auxiliary$ygHPnboY.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java)
at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateWrapper.doExecute(ZipkinRestTemplateSenderConfiguration.java:116)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:636)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:598)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender.post(RestTemplateSender.java:93)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:104)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:96)
at zipkin2.Call$Base.execute(Call.java:379)
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:272)
at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:179)
```

then , I see the errors log of skywalking-oap-server.log 
SpanV2JettyHandler - 65 [qtp522082506-271] ERROR [] - Malformed reading List<Span> from json
```
2019-04-25 20:57:37,143 - org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanV2JettyHandler - 65 [qtp522082506-269] ERROR [] - Malformed reading List<Span> from json
java.lang.IllegalArgumentException: Malformed reading List<Span> from json
        at zipkin2.internal.JsonCodec.exceptionReading(JsonCodec.java:240) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.JsonCodec.readList(JsonCodec.java:155) ~[zipkin-2.9.1.jar:?]
        at zipkin2.codec.SpanBytesDecoder$3.decodeList(SpanBytesDecoder.java:107) ~[zipkin-2.9.1.jar:?]
        at zipkin2.codec.SpanBytesDecoder.decodeList(SpanBytesDecoder.java:151) ~[zipkin-2.9.1.jar:?]
        at zipkin2.codec.SpanBytesDecoder$3.decodeList(SpanBytesDecoder.java:118) ~[zipkin-2.9.1.jar:?]
        at org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanProcessor.convert(SpanProcessor.java:45) ~[zipkin-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanV2JettyHandler.doPost(SpanV2JettyHandler.java:59) [zipkin-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: zipkin2.internal.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at zipkin2.internal.gson.stream.JsonReader.syntaxError(JsonReader.java:1568) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.gson.stream.JsonReader.checkLenient(JsonReader.java:1409) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.gson.stream.JsonReader.doPeek(JsonReader.java:593) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.gson.stream.JsonReader.beginArray(JsonReader.java:343) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.JsonCodec$JsonReader.beginArray(JsonCodec.java:57) ~[zipkin-2.9.1.jar:?]
        at zipkin2.internal.JsonCodec.readList(JsonCodec.java:149) ~[zipkin-2.9.1.jar:?]
        ... 30 more
```

**Comment by wu-sheng** [comment]
@adriancole Any idea?

**Comment by wu-sheng** [comment]
I guess this is some kinds of protocol incompatible, but since we are using Zipkin lib, either we read HTTP request body in the wrong way, or there is update in Zipkin.

@adriancole You may have a better idea?

**Comment by manheiba** [comment]
It is suggested to use Kafka to collect Zipkin data

**Comment by adriancole** [comment]
mm so this looks like the client is spring cloud sleuth as the main zipkin-reporter project has no RestTemplateSender. can you give version details on this?

note: you can use latest brave by using a bom to align versions, just in case there's something fixed more recently than the code you are using https://github.com/openzipkin/brave#version-alignments

My "guess" is that this is an empty body somehow sent. That should never happen. I'm not sure if the root problem is in the sender or the async reporter. However, our codec can try to work around it.

**Comment by adriancole** [comment]
related https://github.com/apache/incubator-zipkin-reporter-java/issues/138

**Comment by wu-sheng** [comment]
@manheiba Please follow the suggestion.

**Comment by manheiba** [comment]
### tks 
#### starter-zipkin & starter-sleuth version are 1.3.5.RELEASE
#### I used springboot 1.5.15.RELEASE with dependency below : 

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
```

#### application.properties
```
spring.sleuth.sampler.percentage=1.0
spring.zipkin.compression.enabled=true
spring.zipkin.service.name=skywalkingsleuthdemo
spring.zipkin.message-timeout=1
spring.zipkin.base-url=http://xx.xx.xx.xx:9412
```

**Comment by adriancole** [comment]
ok in this case, please update to latest zipkin reporter to make sure
there's no bug already fixed. sleuth 1.3 does not use brave, but it uses
the same reporting library

https://github.com/apache/incubator-zipkin-reporter-java#version-alignments
