### ISSUE TITLE
Field named rt in service_name index not found.

### ISSUE THREAD

**Issue by jyy1990** [apache/skywalking#2602]
linux：sky版本5.0.0GA，es版本5.6.8，collectorService启动后日志里报这个错误
![image](https://user-images.githubusercontent.com/35125132/57209952-3e159b80-700d-11e9-9748-79daa5c2452a.png)

2019-05-06 14:31:16,529 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -6238 [main] ERROR [] - Field named rt in service_name index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
	... 3 more

**Comment by wu-sheng** [comment]
Please use SkyWalking 6. For 5, this means you are updating from the old version. You need to delete all indexes in es and reboot all agents.
