### ISSUE TITLE
skywalking是否兼容springCloud gateway 

### ISSUE THREAD

**Issue by gaofeng36599** [apache/skywalking#2611]
我想用skywalking监控网关，出现了问题。
我的网关用的是springboot+springCloud gateway，添加上探针agent后，skywalking报错如下图。
因为我所有的调用都是通过网关做的转发，所以系统整个链路能有网关的信息，烦请各位老师解答下。

DEBUG 2019-05-07 09:01:59:935 TraceSegmentServiceClient :  6 trace segments have been sent to collector.
ERROR 2019-05-07 09:01:59:961 InstMethodsInter :  class[class reactor.netty.http.server.HttpServerOperations] before method[status] intercept failure
java.lang.ClassCastException: java.lang.Integer cannot be cast to io.netty.handler.codec.http.HttpResponseStatus
        at org.apache.skywalking.apm.plugin.spring.webflux.v5.StatusInterceptor.beforeMethod(StatusInterceptor.java:48)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at reactor.netty.http.server.HttpServerOperations.status(HttpServerOperations.java)
        at org.springframework.http.server.reactive.ReactorServerHttpResponse.applyStatusCode(ReactorServerHttpResponse.java:80)

**Comment by SataQiu** [comment]
Ref: https://github.com/apache/skywalking/pull/2517

**Comment by wu-sheng** [comment]
English only. And thank @SataQiu to point the right one.
