### ISSUE TITLE
There are numbers of "TIMED WAITING" & "BLOCKED" threads in jstack log

### ISSUE THREAD

**Issue by chenmutime** [apache/skywalking#2658]
[environment]
1 single virtual machine, 4C/8GB, with es & skywalking server deployed.
standalone one-node elasticsearch, assigned Xmx4g for jvm.
skywalking server deployed on the same vm, assigned Xmx2g for jvm.
2 spring boot applications (deployed on another vm) connected to skywalking server.

[symptom]
1. After restarting es & skywalking server, skywalking server receives continued traces from application.
2. It lasts 15-30 minutes. after then, no traces come into skywalking server any more.

[effort taken]
1. I've checked elasticsearch.log. There are no obvious error messages in elasticsearch.log.
2. I've checked gc.log. There are no gc overhead messages in gc.log.
3. I've printed stacktrace using jstack, log shows as below:

```
"DataCarrier.IndicatorPersistentWorker.all_p50_day.Consumser.0.Thread" #20 daemon prio=5 os_prio=0 tid=0x00007f3e9507f000 nid=0x2e99 waiting on condition [0x00007f3e58acd000]
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:72)
```
```
"DataCarrier.IndicatorPersistentWorker.endpoint_avg.Consumser.0.Thread" #43 daemon prio=5 os_prio=0 tid=0x00007f3e950e2800 nid=0x2eb0 waiting for monitor entry [0x00007f3dfb2f1000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:286)
- waiting to lock <0x00000000813c8440> (a org.elasticsearch.action.bulk.BulkProcessor)
at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:271)
at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:267)
at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:253)
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.lambda$batchPersistence$0(BatchProcessEsDAO.java:64)
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO$$Lambda$278/81782502.accept(Unknown Source)
at java.lang.Iterable.forEach(Iterable.java:75)
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.batchPersistence(BatchProcessEsDAO.java:62)
at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.onWork(PersistenceWorker.java:51)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorPersistentWorker.onWork(IndicatorPersistentWorker.java:63)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorPersistentWorker$PersistentConsumer.consume(IndicatorPersistentWorker.java:153)
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101)
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68)
```

```
"DataCarrier.IndicatorAggregateWorker.instance_jvm_cpu.Consumser.0.Thread" #152 daemon prio=5 os_prio=0 tid=0x00007f3e951c1000 nid=0x2f1d sleeping[0x00007f3df4584000]
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.apache.skywalking.apm.commons.datacarrier.buffer.Buffer.save(Buffer.java:64)
at org.apache.skywalking.apm.commons.datacarrier.buffer.Channels.save(Channels.java:52)
at org.apache.skywalking.apm.commons.datacarrier.DataCarrier.produce(DataCarrier.java:88)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorPersistentWorker.in(IndicatorPersistentWorker.java:68)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorTransWorker.in(IndicatorTransWorker.java:89)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorTransWorker.in(IndicatorTransWorker.java:32)
at org.apache.skywalking.oap.server.core.remote.client.SelfRemoteClient.push(SelfRemoteClient.java:55)
at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:51)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:93)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$$Lambda$203/1364775767.accept(Unknown Source)
at java.util.HashMap$Values.forEach(HashMap.java:981)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:88)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:73)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:38)
at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:131)
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101)
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68)
```

4. I've checked es cluster stat and node stat.
heap percent is in normal range, and cluster keeps yellow.

[target]
I wonder if you could give some hint on:
- if there is recommended hardware for skywalking deployment. Like recommend 1C/2GB for single application tracing.
- if there is any log or troubleshooting methods I could take for more deeply looking into the problem.

**Comment by wu-sheng** [comment]
Have you checked the ElasticSearch log? Is there GC log there?

15 mins are very short, even can't be affected by TTL. 

@peng-yongsheng suggestion?

**Comment by chenmutime** [comment]
```
2019-05-14T11:51:35.050+0800: 61631.320: Total time for which application threads were stopped: 0.0357366 seconds, Stopping threads took: 0.0001109 seconds
2019-05-14T11:51:35.056+0800: 61631.326: Total time for which application threads were stopped: 0.0005567 seconds, Stopping threads took: 0.0000694 seconds
2019-05-14T11:51:35.058+0800: 61631.328: Total time for which application threads were stopped: 0.0003282 seconds, Stopping threads took: 0.0000618 seconds
2019-05-14T11:52:13.062+0800: 61669.332: [GC (Allocation Failure) 2019-05-14T11:52:13.062+0800: 61669.332: [ParNew
Desired survivor size 17432576 bytes, new threshold 6 (max 6)
- age   1:     637648 bytes,     637648 total
- age   2:      49376 bytes,     687024 total
- age   3:        664 bytes,     687688 total
- age   4:      92232 bytes,     779920 total
- age   5:         96 bytes,     780016 total
- age   6:      39008 bytes,     819024 total
: 273784K->1174K(306688K), 0.0515317 secs] 851262K->578652K(4160256K), 0.0518978 secs] [Times: user=0.13 sys=0.00, real=0.05 secs] 
2019-05-14T11:52:13.114+0800: 61669.384: Total time for which application threads were stopped: 0.0527399 seconds, Stopping threads took: 0.0000840 seconds
2019-05-14T11:52:13.115+0800: 61669.385: Total time for which application threads were stopped: 0.0004761 seconds, Stopping threads took: 0.0000548 seconds
2019-05-14T11:52:13.116+0800: 61669.386: Total time for which application threads were stopped: 0.0003557 seconds, Stopping threads took: 0.0000546 seconds
2019-05-14T11:52:13.116+0800: 61669.386: Total time for which application threads were stopped: 0.0002822 seconds, Stopping threads took: 0.0000583 seconds
2019-05-14T11:52:13.117+0800: 61669.387: Total time for which application threads were stopped: 0.0002746 seconds, Stopping threads took: 0.0000556 seconds
2019-05-14T11:52:50.811+0800: 61707.081: [GC (Allocation Failure) 2019-05-14T11:52:50.811+0800: 61707.081: [ParNew
Desired survivor size 17432576 bytes, new threshold 6 (max 6)
- age   1:     632360 bytes,     632360 total
- age   2:       2792 bytes,     635152 total
- age   3:      47128 bytes,     682280 total
- age   4:        472 bytes,     682752 total
- age   5:      92104 bytes,     774856 total
- age   6:         64 bytes,     774920 total
: 273814K->1246K(306688K), 0.0606944 secs] 851292K->578763K(4160256K), 0.0609771 secs] [Times: user=0.12 sys=0.00, real=0.06 secs]
```

**Comment by chenmutime** [comment]
This is GC log:
```
2019-05-14T11:51:35.050+0800: 61631.320: Total time for which application threads were stopped: 0.0357366 seconds, Stopping threads took: 0.0001109 seconds
2019-05-14T11:51:35.056+0800: 61631.326: Total time for which application threads were stopped: 0.0005567 seconds, Stopping threads took: 0.0000694 seconds
2019-05-14T11:51:35.058+0800: 61631.328: Total time for which application threads were stopped: 0.0003282 seconds, Stopping threads took: 0.0000618 seconds
2019-05-14T11:52:13.062+0800: 61669.332: [GC (Allocation Failure) 2019-05-14T11:52:13.062+0800: 61669.332: [ParNew
Desired survivor size 17432576 bytes, new threshold 6 (max 6)
- age   1:     637648 bytes,     637648 total
- age   2:      49376 bytes,     687024 total
- age   3:        664 bytes,     687688 total
- age   4:      92232 bytes,     779920 total
- age   5:         96 bytes,     780016 total
- age   6:      39008 bytes,     819024 total
: 273784K->1174K(306688K), 0.0515317 secs] 851262K->578652K(4160256K), 0.0518978 secs] [Times: user=0.13 sys=0.00, real=0.05 secs] 
2019-05-14T11:52:13.114+0800: 61669.384: Total time for which application threads were stopped: 0.0527399 seconds, Stopping threads took: 0.0000840 seconds
2019-05-14T11:52:13.115+0800: 61669.385: Total time for which application threads were stopped: 0.0004761 seconds, Stopping threads took: 0.0000548 seconds
2019-05-14T11:52:13.116+0800: 61669.386: Total time for which application threads were stopped: 0.0003557 seconds, Stopping threads took: 0.0000546 seconds
2019-05-14T11:52:13.116+0800: 61669.386: Total time for which application threads were stopped: 0.0002822 seconds, Stopping threads took: 0.0000583 seconds
2019-05-14T11:52:13.117+0800: 61669.387: Total time for which application threads were stopped: 0.0002746 seconds, Stopping threads took: 0.0000556 seconds
2019-05-14T11:52:50.811+0800: 61707.081: [GC (Allocation Failure) 2019-05-14T11:52:50.811+0800: 61707.081: [ParNew
Desired survivor size 17432576 bytes, new threshold 6 (max 6)
- age   1:     632360 bytes,     632360 total
- age   2:       2792 bytes,     635152 total
- age   3:      47128 bytes,     682280 total
- age   4:        472 bytes,     682752 total
- age   5:      92104 bytes,     774856 total
- age   6:         64 bytes,     774920 total
: 273814K->1246K(306688K), 0.0606944 secs] 851292K->578763K(4160256K), 0.0609771 secs] [Times: user=0.12 sys=0.00, real=0.06 secs]
```

**Comment by chenmutime** [comment]
I used the command line "top -HP PID" to print some of the information associated with Elasticsearch:
```
top - 17:18:45 up 116 days,  3:10,  2 users,  load average: 1.97, 2.10, 1.88
Threads:  77 total,   0 running,  77 sleeping,   0 stopped,   0 zombie
%Cpu(s): 19.7 us,  3.0 sy,  0.0 ni, 77.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8010576 total,   195028 free,  6484028 used,  1331520 buff/cache
KiB Swap:  8257532 total,  7053024 free,  1204508 used.  1127316 avail Mem 
```

**Comment by wu-sheng** [comment]
@chenmutime Please try the 6.3.0, which including
1. ElasticSearch storage implementation totally changed, much less ES cluster payload
1. Unexpected TTL payload issue has been fixed.
1. FAQ doc about how to set up several key configurations in ES cluster.
