### ISSUE TITLE
Class ContextStorageOverride can not be found.

### ISSUE THREAD

**Issue by Carles1983** [apache/skywalking#2663]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ *] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  Skywlking 6.1
  Windows7 + Eclispe + JDK1.8
  SpringBoot 2.1.0.RELEASE
  SpringCloud Greenwich.RELEASE

- Which company or project?

- What happen?
  Integrated skywalking with spring-cloud-gateway(version 2.1.0) .
  During start, an exception (ClassNotFoundException) was thrown.
  I cannot find the class file among the souce codes.

  java.lang.ClassNotFoundException: org.apache.skywalking.apm.dependencies.io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_191]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_191]
	at org.apache.skywalking.apm.dependencies.io.grpc.Context.createStorage(Context.java:137) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.Context.storage(Context.java:129) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.Context.current(Context.java:181) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.Context$Key.get(Context.java:891) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:384) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor.interceptCall(CensusStatsModule.java:675) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:784) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:118) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:115) [skywalking-agent.jar:6.1.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [skywalking-agent.jar:6.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Hi, I think you changed our source codes, we don't have that.

**Comment by Carles1983** [comment]
I didn't do anything. The code is in skywakling-agent.jar from agent directoty, apache-skywalking-apm-6.1.0.tar.gz 
<img width="1268" alt="manifest" src="https://user-images.githubusercontent.com/26129625/57680038-4a2dd880-765f-11e9-8f7e-a81966cfc13f.png">
<img width="1268" alt="class" src="https://user-images.githubusercontent.com/26129625/57680067-59148b00-765f-11e9-9e39-e9d200c72965.png">

**Comment by wu-sheng** [comment]
But we don't use this. We use the agent every day.

**Comment by wu-sheng** [comment]
From the codes you post, there is only a `class.forname` attempted. Will switch to no-op. Also, this is `FINE` level log.
