### ISSUE TITLE
oap service can't connect to elasticsearch in v6.1.0

### ISSUE THREAD

**Issue by vision-ken** [apache/skywalking#2666]
### Build from GitHub:
1. Prepare git, JDK8 and maven3
2. `git clone https://github.com/apache/skywalking.git`
3. `cd skywalking/`
4. `git checkout v6.1.0`
5. `git submodule init`
6. `git submodule update`
7. Run `./mvnw clean package -DskipTests`

### Run in docker:
1. ` cd docker`
2. ` make build`
3. `docker-compose up -d`

Got exception in oap service:
```java
2019-05-14 13:03:34,358 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -3121 [main] INFO  [] - start the provider elasticsearch in storage module.
2019-05-14 13:03:34,358 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -3121 [main] INFO  [] - elasticsearch cluster nodes: localhost:9200
2019-05-14 13:03:34,907 - org.apache.skywalking.oap.server.starter.OAPServerStartUp -3670 [main] ERROR [] - Connection refused
org.apache.skywalking.oap.server.library.module.ModuleStartException: Connection refused
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:137) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
Caused by: java.io.IOException: Connection refused
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:275) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:81) ~[library-client-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:129) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	... 3 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_181]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
```

This happen in v6.1.0, but work fine in v6.0.0-GA.

**Comment by wu-sheng** [comment]
Connection issue should be solved by yourself. There is no special thing there.

**Comment by windhost** [comment]
+1
