### ISSUE TITLE
skywalking-oap-server error

### ISSUE THREAD

**Issue by ns500** [apache/skywalking#2694]
Skywalking -oap-server has a large number of error diaries：
2019-05-16 21:54:05,170 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-2] WARN  [] - Can't found service by service instance id from cache, service instance id is: 277
2019-05-16 21:54:05,222 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-2] WARN  [] - Can't found service by service instance id from cache, service instance id is: 299
2019-05-16 21:54:05,277 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-2] WARN  [] - Can't found service by service instance id from cache, service instance id is: 266
2019-05-16 21:54:05,304 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-2] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:119) ~[skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:149) ~[skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:92) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:270) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-05-16 21:54:05,307 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-2] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:119) ~[skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:149) ~[skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:92) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:270) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.1.0.jar:6.1.0]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-05-16 21:54:05,327 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-2] WARN  [] - Can't found service by service instance id from cache, service instance id is: 273

**Comment by wu-sheng** [comment]
Please search issue before you submit a new one. This means, you deleted the ElasticSearch, but haven't restarted the agents.

**Comment by ns500** [comment]
I have restarted the agent, and the error still exists. I don't need your reply any more.
