### ISSUE TITLE
[Agent]  gRPC incompatible in j9vm

### ISSUE THREAD

**Issue by PrettyJerry** [apache/skywalking#2702]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ --- ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

  **Linux
  skywalking 6.1
  j9vm  1.7.0_20190408**

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

when i deploy agent  on  **websphere8.0 and j9vm**, agent cant connect to oapserver , it seems like **grpc** and **netty** error.

```
DEBUG 2019-05-17 15:50:36:553 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  Selected collector grpc service running, reconnect:true. 
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:264)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.JettyTlsUtil.getJettyAlpnUnavailabilityCause(JettyTlsUtil.java:75)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:257)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
DEBUG 2019-05-17 15:50:36:766 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  Selected collector grpc service is not available. Wait 30 seconds to retry 
INFO 2019-05-17 15:50:43:519 main AgentClassLoader :  /was/skywalking-agent/plugins/apm-grpc-1.x-plugin-6.1.0.jar loaded. 
INFO 2019-05-17 15:50:51:565 server.startup : 2 AgentClassLoader :  /was/skywalking-agent/plugins/apm-grpc-1.x-plugin-6.1.0.jar loaded. 
DEBUG 2019-05-17 15:51:06:544 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  **Selected collector grpc service running, reconnect:true.** 
DEBUG 2019-05-17 15:51:36:544 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  **Selected collector grpc service running, reconnect:false.** 
DEBUG 2019-05-17 15:52:06:544 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  **Selected collector grpc service running, reconnect:false.** 
DEBUG 2019-05-17 15:52:36:544 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  **Selected collector grpc service running, reconnect:false.** 
```

**Comment by PrettyJerry** [comment]
my test env:   agent addr: 10.70.50.13  server addr:10.70.50.35   in the same subnet , so the network is no problem. and telnet 10.70.50.35 11800 is ok

**Comment by wu-sheng** [comment]
@PrettyJerry Could you try to run gRPC directly in your env? Look like this is out SkyWalking scope.

**Comment by wu-sheng** [comment]
Also, I noticed, why ssl is activated? Also I noticed `Selected collector grpc service running, reconnect:false.`, this should mean the gRPC connected.
