### ISSUE TITLE
Exception while fetching data (/cpm) : IDs can't be null

### ISSUE THREAD

**Issue by zhangwenliang012** [apache/skywalking#2706]
2019-05-17 17:19:13,448 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-05-17 17:19:13,456 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-05-17 17:19:13,542 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@4315c28c{/,null,AVAILABLE}
2019-05-17 17:19:13,573 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@617449dd{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-05-17 17:19:13,574 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @15947ms
2019-05-17 17:19:13,984 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 49 [main] INFO  [] - persistence timer start
2019-05-17 17:19:14,007 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 42 [main] INFO  [] - Cache update timer start
2019-05-17 17:19:24,088 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 264 [I/O dispatcher 4] INFO  [] - Bulk [1] completed in 636 milliseconds
2019-05-17 17:19:26,241 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 264 [I/O dispatcher 4] INFO  [] - Bulk [2] completed in 984 milliseconds
2019-05-17 17:19:41,994 - graphql.execution.SimpleDataFetcherExceptionHandler - 23 [qtp998283025-87] WARN  [] - Exception while fetching data (/cpm) : IDs can't be null
java.lang.RuntimeException: IDs can't be null
	at org.apache.skywalking.oap.server.core.query.MetricQueryService.getValues(MetricQueryService.java:61) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getValues(MetricQuery.java:53) ~[query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.1.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:87) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:81) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105) [library-server-6.1.0.jar:6.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2019-05-17 17:19:44,959 - graphql.execution.SimpleDataFetcherExceptionHandler - 23 [qtp998283025-87] WARN  [] - Exception while fetching data (/cpm) : IDs can't be null
java.lang.RuntimeException: IDs can't be null
	at org.apache.skywalking.oap.server.core.query.MetricQueryService.getValues(MetricQueryService.java:61) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getValues(MetricQuery.java:53) ~[query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.1.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:87) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:81) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105) [library-server-6.1.0.jar:6.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by zhangwenliang012** [comment]
F12 
{data: {}, errors: [{message: "Exception while fetching data (/sla) : IDs can't be null"},…]}
data
:
{}
errors
:
[{message: "Exception while fetching data (/sla) : IDs can't be null"},…]
0
:
{message: "Exception while fetching data (/sla) : IDs can't be null"}
1
:
{message: "Exception while fetching data (/nodeCpm) : IDs can't be null"}
2
:
{message: "Exception while fetching data (/nodeLatency) : IDs can't be null"}
3
:
{message: "Exception while fetching data (/cpmS) : IDs can't be null"}
4
:
{message: "Exception while fetching data (/latencyS) : IDs can't be null"}
5
:
{message: "Exception while fetching data (/cpmC) : IDs can't be null"}
6
:
{message: "Exception while fetching data (/latencyC) : IDs can't be null"}

**Comment by wu-sheng** [comment]
Ref #2704
