### ISSUE TITLE
spring-cloud-alibaba feign里面使用，这个是什么原因？是什么地方没有配置对吗 

### ISSUE THREAD

**Issue by tigerleeli** [apache/skywalking#2712]
DEBUG 2019-05-19 15:27:33:063 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-05-19 15:27:33:082 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:115)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/13581384/57979104-62c93480-7a4b-11e9-8375-40cf5895994a.png)

**Comment by wu-sheng** [comment]
English only. From log, grpc connection can't be established.

**Comment by tigerleeli** [comment]
> English only. From log, grpc connection can't be established.

我知道 grpc 没有建立连接，但是我想问为什么没有建立？可能的原因是什么

**Comment by wu-sheng** [comment]
No feedback if you keep using Chinese. Sorry. This is Apache requirement.

**Comment by tigerleeli** [comment]
Ok,I want to know why grpc connection can't be established? Can you explain why I failed?Thanks!

**Comment by wu-sheng** [comment]
Can't see from the log your post. Usually, it is because, oap server binds wrong ip and OSfirewall.

**Comment by tigerleeli** [comment]
> Can't see from the log your post. Usually, it is because, oap server binds wrong ip and OSfirewall.

ok

**Comment by sunqian2** [comment]
same problem happened to me，i run sky server in docker， but run agent in my windows。can i use it by this way？

**Comment by wu-sheng** [comment]
> same problem happened to me，i run sky server in docker， but run agent in my windows。can i use it by this way？

Any way you like, just make sure the network is connectable.
