### ISSUE TITLE
start up skywalking error

### ISSUE THREAD

**Issue by GreyZeng** [apache/skywalking#2760]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0
- Which company or project?
Java Project 
- What happen?
elk 7.0 or elk 6.x  
run skywalking startup.bat

collector error:

2019-05-27 14:39:26,221 - org.apache.skywalking.oap.server.core.remote.annotation.StreamAnnotationListener - 45 [main] INFO  [] - The owner class of stream data annotation, class name: org.apache.skywalking.oap.server.core.register.ServiceInventory
2019-05-27 14:39:26,221 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - storage module exist 2 providers
org.apache.skywalking.oap.server.library.module.DuplicateProviderException: storage module exist 2 providers
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:142) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:30) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorProcess.create(IndicatorProcess.java:55) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.analysis.indicator.annotation.IndicatorTypeListener.notify(IndicatorTypeListener.java:42) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan$AnnotationListenerCache.lambda$complete$0(AnnotationScan.java:83) ~[server-core-6.1.0.jar:6.1.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_202]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan$AnnotationListenerCache.complete(AnnotationScan.java:83) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan$AnnotationListenerCache.access$300(AnnotationScan.java:64) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.lambda$scan$0(AnnotationScan.java:56) ~[server-core-6.1.0.jar:6.1.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_202]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.scan(AnnotationScan.java:55) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.start(CoreModuleProvider.java:173) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]

If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read the document carefully. You changed the `application.yml` incorrectly.

**Comment by GreyZeng** [comment]
i just config the yml storage nodes

`storage:
  elasticsearch:
#    nameSpace: ${SW_NAMESPACE:""}
    clusterName: CollectorDBCluster
#    clusterNodes: localhost:9200
#    user: ${SW_ES_USER:""}
#    password: ${SW_ES_PASSWORD:""}
#    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:2}
#    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:0}
#    # Batch process setting, refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.5/java-docs-bulk-processor.html
#    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:2000} # Execute the bulk every 2000 requests
#    bulkSize: ${SW_STORAGE_ES_BULK_SIZE:20} # flush the bulk every 20mb
#    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
#    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
#    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
#    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
#  h2:
#    driver: ${SW_STORAGE_H2_DRIVER:org.h2.jdbcx.JdbcDataSource}
#    url: ${SW_STORAGE_H2_URL:jdbc:h2:mem:skywalking-oap-db}
#    user: ${SW_STORAGE_H2_USER:sa}
#    metadataQueryMaxSize: ${SW_STORAGE_H2_QUERY_MAX_SIZE:5000}
#  mysql:
#    metadataQueryMaxSize: ${SW_STORAGE_H2_QUERY_MAX_SIZE:5000}`

**Comment by GreyZeng** [comment]
> Read the document carefully. You changed the `application.yml` incorrectly.

i just config the yml storage nodes

storage:
elasticsearch:
clusterName: CollectorDBCluster

elk.yml config is
cluster.name: CollectorDBCluster

run skywalking startup.bat

error is :

2019-05-27 14:57:14,074 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - null
java.lang.NullPointerException: null
at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.parseClusterNodes(ElasticSearchClient.java:91) ~[library-client-6.1.0.jar:6.1.0]
at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:70) ~[library-client-6.1.0.jar:6.1.0]
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:129) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]

**Comment by wu-sheng** [comment]
Please read the document, we have indicated how to set up ElasticSearch as storage. Also, the document has guided you about how to do a quick start.

**Comment by weipengd** [comment]
> > 仔细阅读文档。你改错了`application.yml`。
> 
> 我只是配置yml存储节点
> 
> storage：
> elasticsearch：
> clusterName：CollectorDBCluster
> 
> elk.yml config是
> cluster.name：CollectorDBCluster
> 
> 运行skywalking startup.bat
> 
> 错误是：
> 
> 2019-05-27 14：57：14,074 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - null 
> java.lang.NullPointerException：null 
> org.apache.skywalking.oap。
> org.apache.skywalking.oap.server.library.client.elasticsearch上的server.library.client.elasticsearch.ElasticSearchClient.parseClusterNodes（ElasticSearchClient.java:91）〜[library-client-6.1.0.jar：6.1.0] .ElasticSearchClient.connect（ElasticSearchClient.java:70）〜[library-client-6.1.0.jar：6.1.0] 
> at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start（StorageModuleElasticsearchProvider。 java：129）〜[storage-elasticsearch-plugin-6.1.0.jar：6.1.0]
> 在org.apache.skywalking.oap.server.library.module.BootstrapFlow.start（BootstrapFlow.java:57）〜[library-module-6.1.0.jar：6.1.0] 
> org.apache.skywalking.oap。 server.library.module.ModuleManager.init（ModuleManager.java:65）〜[library-module-6.1.0.jar：6.1.0] 
> at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main（OAPServerStartUp） .java：43）[server-starter-6.1.0.jar：6.1.0]

Cluster module exist 2 providers, is this problem handled?

**Comment by wu-sheng** [comment]
This is also another example of not reading document.
