### ISSUE TITLE
Infrequent exception: SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by zengqinglei** [apache/skywalking#2761]
- **Infrequent exception: SocketTimeoutException: Read timed out**
- [ ] The production environment refreshes the UI page, and the timeout exception is abnormal.
- [ ] Run based on docker
- [ ] Operating system: centos7
- [ ] Skywalking is version 6.1.0

___
### The exception information is as follows:
``` bash
2019-05-27T07:06:15.598281179Z Caused by: com.netflix.client.ClientException: null
2019-05-27T07:06:15.598286088Z 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:118)
2019-05-27T07:06:15.598291408Z 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:152)
2019-05-27T07:06:15.598296896Z 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:49)
2019-05-27T07:06:15.598302369Z 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
2019-05-27T07:06:15.598307472Z 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
2019-05-27T07:06:15.598312488Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
2019-05-27T07:06:15.598317562Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2019-05-27T07:06:15.598322996Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598328086Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598333161Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598338256Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598343884Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598349121Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598354214Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598359207Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
2019-05-27T07:06:15.598364324Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2019-05-27T07:06:15.598369674Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598384334Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598390199Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598395345Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598400974Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598406171Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598411943Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598417185Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598422287Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598427465Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598432595Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598437859Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598443077Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598448217Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598453654Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598459800Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598465016Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598470013Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598475104Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598480656Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598485885Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598490978Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598496013Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
2019-05-27T07:06:15.598501141Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2019-05-27T07:06:15.598506661Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598511704Z 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
2019-05-27T07:06:15.598516837Z 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
2019-05-27T07:06:15.598521896Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598528737Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598538851Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598544002Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598549597Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598554847Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598560402Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2019-05-27T07:06:15.598565657Z 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2019-05-27T07:06:15.598570778Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598576120Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
2019-05-27T07:06:15.598581195Z 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2019-05-27T07:06:15.598585713Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598590435Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598595033Z 	at rx.Observable.subscribe(Observable.java:10247)
2019-05-27T07:06:15.598600042Z 	at rx.Observable.subscribe(Observable.java:10214)
2019-05-27T07:06:15.598604678Z 	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
2019-05-27T07:06:15.598609610Z 	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:411)
2019-05-27T07:06:15.598614601Z 	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
2019-05-27T07:06:15.598620062Z 	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
2019-05-27T07:06:15.598625177Z 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:158)
2019-05-27T07:06:15.598630499Z 	... 67 common frames omitted
2019-05-27T07:06:15.598635525Z Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
2019-05-27T07:06:15.598640867Z 	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
2019-05-27T07:06:15.598645855Z 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
2019-05-27T07:06:15.598651123Z 	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
2019-05-27T07:06:15.598656281Z 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
2019-05-27T07:06:15.598661627Z 	... 129 common frames omitted
2019-05-27T07:06:15.598667264Z Caused by: java.net.SocketTimeoutException: Read timed out
2019-05-27T07:06:15.598672337Z 	at java.net.SocketInputStream.socketRead0(Native Method)
2019-05-27T07:06:15.598677367Z 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
2019-05-27T07:06:15.598688778Z 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
2019-05-27T07:06:15.598694363Z 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
2019-05-27T07:06:15.598699459Z 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
2019-05-27T07:06:15.598704573Z 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
2019-05-27T07:06:15.598710177Z 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
2019-05-27T07:06:15.598715655Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
2019-05-27T07:06:15.598720960Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
2019-05-27T07:06:15.598726212Z 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
2019-05-27T07:06:15.598731373Z 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
2019-05-27T07:06:15.598736726Z 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
2019-05-27T07:06:15.598742040Z 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
2019-05-27T07:06:15.598747239Z 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
2019-05-27T07:06:15.598764467Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
2019-05-27T07:06:15.598771361Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
2019-05-27T07:06:15.598776578Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2019-05-27T07:06:15.598781766Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
2019-05-27T07:06:15.598786765Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2019-05-27T07:06:15.598792004Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2019-05-27T07:06:15.598804156Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
2019-05-27T07:06:15.598810448Z 	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:82)
2019-05-27T07:06:15.598815784Z 	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:42)
2019-05-27T07:06:15.598821276Z 	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
2019-05-27T07:06:15.598826578Z 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
2019-05-27T07:06:15.598831904Z 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
2019-05-27T07:06:15.598846532Z 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
2019-05-27T07:06:15.598853342Z 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
2019-05-27T07:06:15.598858783Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598863820Z 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
2019-05-27T07:06:15.598869210Z 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
2019-05-27T07:06:15.598874543Z 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
2019-05-27T07:06:15.598879742Z 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
2019-05-27T07:06:15.598885016Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598890028Z 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
2019-05-27T07:06:15.598895249Z 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
2019-05-27T07:06:15.598900404Z 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
2019-05-27T07:06:15.598905479Z 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
2019-05-27T07:06:15.598910929Z 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
2019-05-27T07:06:15.598916324Z 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
2019-05-27T07:06:15.598921583Z 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
2019-05-27T07:06:15.598926815Z 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
2019-05-27T07:06:15.598931999Z 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
2019-05-27T07:06:15.598937337Z 	at rx.Subscriber.setProducer(Subscriber.java:209)
2019-05-27T07:06:15.598947441Z 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
2019-05-27T07:06:15.598952933Z 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
2019-05-27T07:06:15.598958114Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598963262Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598968586Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598973863Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598979577Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2019-05-27T07:06:15.598991338Z 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2019-05-27T07:06:15.598996892Z 	at rx.Observable.subscribe(Observable.java:10247)
2019-05-27T07:06:15.599002146Z 	at rx.Observable.subscribe(Observable.java:10214)
2019-05-27T07:06:15.599007223Z 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
2019-05-27T07:06:15.599012339Z 	... 131 common frames omitted
```

**I hope to hear from you soon, thank you!**

**Comment by wu-sheng** [comment]
This is just caused by your OAP doesn't start up right.

**Comment by zengqinglei** [comment]
> This is just caused by your OAP doesn't start up right.

Hi!
I checked the oap container through docker logs -f -t --tail 100 skywalking-oap, the operation has been normal, no exception!
My development environment is deployed in the same way, there is no such problem!
The docker-compose content is as follows:

``` dockerfile
  skywalking-oap:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/skywalking-oap:6.1.0
    container_name: skywalking-oap
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - SW_CLUSTER_ZK_HOST_PORT=${Host}:2181
      - SW_CLUSTER_CONSUL_HOST_PORT=${Host}:8500
      - SW_STORAGE_ES_CLUSTER_NODES=${Host}:9200
      - SW_ES_USER=elastic
      - SW_ES_PASSWORD=Za888888
    volumes:
      - ${Workdir}/skywalking/config:/skywalking/config:ro

  skywalking-ui:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/skywalking-ui:6.1.0
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 18080:8080
    environment:
      collector.ribbon.listOfServers: skywalking-oap:12800
```

Similarly, it is normal to view the information via the command line: `docker exec skywalking-ui ping skywalking-oap`.

**Comment by wu-sheng** [comment]
I can't tell what happens in your env. But I noticed two things
1. Your set both ZK and Consul, I don't know why.
1. Your Zuul log says timeout, then means your UI can't connect to OAP server.

From my perspective, you haven't understood how OAP works. Please read the document, try quick start and advanced features, rather than simply use a docker image to start.
We are running OAP in k8s for long time, I am sure whether some configs are being misunderstood or something else.

**Comment by zengqinglei** [comment]
> I can't tell what happens in your env. But I noticed two things
> 
> 1. Your set both ZK and Consul, I don't know why.
> 2. Your Zuul log says timeout, then means your UI can't connect to OAP server.
> 
> From my perspective, you haven't understood how OAP works. Please read the document, try quick start and advanced features, rather than simply use a docker image to start.
> We are running OAP in k8s for long time, I am sure whether some configs are being misunderstood or something else.

Sorry, although the configuration is consul, `application.yml` is not enabled!
Only zookeeper clusters are available.
Therefore, due to the same deployment method of the development environment, it is normal to run for a long time, and the problem just mentioned is accidental. I hope that you can help, give some reasons for guessing, thank you!

**At the same time, I will go to the official deployment documentation.**

**Comment by hanahmily** [comment]
According to document of  [skywalking-ui](https://hub.docker.com/r/apache/skywalking-ui <https://hub.docker.com/r/apache/skywalking-ui>), the environment variable of oap address is `SW_OAP_ADDRESS` instead of `collector.ribbon.listOfServers`

Hongtao Gao

Apache SkyWalking && Apache ShardingSphere
Twitter, @hanahmily
