### ISSUE TITLE
Unable to parse response body for Response

### ISSUE THREAD

**Issue by xiongshiyan** [apache/skywalking#2778]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
how to resolve this problem?
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0
- Which company or project?
zytx
- What happen?

```
2019-05-29 13:20:09,820 - org.elasticsearch.client.RestClient - 59 [I/O dispatcher 1] DEBUG [] - request [PUT http://xxxx:9200/all_heatmap_day?master_timeout=30s&timeout=30s] returned [HTTP/1.1 200 OK]
2019-05-29 13:20:09,821 - org.apache.http.impl.nio.client.InternalIODispatch - 85 [I/O dispatcher 1] DEBUG [] - http-outgoing-0 [ACTIVE] [content length: 48; pos: 48; completed: true]
2019-05-29 13:20:09,850 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] **ERROR [] - Unable to parse response body for Response{requestLine=PUT /all_heatmap_day?master_timeout=30s&timeout=30s HTTP/1.1, host=http://xxxxxxx:9200, response=HTTP/1.1 200 OK}**
org.apache.skywalking.oap.server.library.module.ModuleStartException: Unable to parse response body for Response{requestLine=PUT /all_heatmap_day?master_timeout=30s&timeout=30s HTTP/1.1, host=http://xxxxxxxx:9200, response=HTTP/1.1 200 OK}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:137) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: Unable to parse response body for Response{requestLine=PUT /all_heatmap_day?master_timeout=30s&timeout=30s HTTP/1.1, host=http://xxxxxxxxxx:9200, response=HTTP/1.1 200 OK}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:84) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:79) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:132) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	... 3 more

```

**Comment by xiongshiyan** [comment]
version of es is 5.2.2

**Comment by wu-sheng** [comment]
Please read the document, we have indicated es supported version for storage.
