### ISSUE TITLE
Exception while fetching data (/getTopNServiceThroughput) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]

### ISSUE THREAD

**Issue by LiuZeng520** [apache/skywalking#2782]
2019-05-30 09:54:25,183 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,187 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,191 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,192 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse - 105 [grpc-default-executor-39] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.setPublicAttrs(MultiScopesSpanListener.java:178) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.parseEntry(MultiScopesSpanListener.java:120) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.lambda$notifyEntryListener$1(SegmentParse.java:212) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_191]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.notifyEntryListener(SegmentParse.java:210) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.preBuild(SegmentParse.java:174) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.parse(SegmentParse.java:83) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse$Producer.send(SegmentParse.java:263) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:49) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:43) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-05-30 09:54:25,198 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,201 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-66] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,201 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,205 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,212 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,252 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,253 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse - 105 [grpc-default-executor-66] ERROR [] - null
java.lang.NullPointerException: null
2019-05-30 09:54:25,258 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-40] ERROR [] - null
java.lang.NullPointerException: null

**Comment by wu-sheng** [comment]
Please search existing issue. This means the storage has been deleted, but agent doesn't restart.
