### ISSUE TITLE
apm-kafka-v1-plugin-6.1.0 ：java.lang.IllegalArgumentException: ContextSnapshot can't be null.

### ISSUE THREAD

**Issue by Liu-XinYuan** [apache/skywalking#2783]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
   skywalking agent 6.1.0

- What happen?
```
ERROR 2019-05-30 10:27:18:832 kafka-producer-network-thread | producer-1 InstMethodsInter :  class[class org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback] before method[onCompletion] intercept failure 
java.lang.IllegalArgumentException: ContextSnapshot can't be null.
        at org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:145)
        at org.apache.skywalking.apm.plugin.kafka.v1.CallbackInterceptor.beforeMethod(CallbackInterceptor.java:37)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:201)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:187)
        at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:599)
        at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:575)
        at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:485)
        at org.apache.kafka.clients.producer.internals.Sender.access$100(Sender.java:74)
        at org.apache.kafka.clients.producer.internals.Sender$1.onComplete(Sender.java:700)
        at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
        at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:532)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:524)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
```
___
### Requirement or improvement
Seems to be no setSkyWalkingDynamicField for org.apache.skywalking.apm.plugin.kafka.v1.CallbackInterceptor
```
 public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {
        AbstractSpan abstractSpan = ContextManager.createLocalSpan("Producer/Callback");
        //Get the SnapshotContext
        ContextSnapshot contextSnapshot = (ContextSnapshot)objInst.getSkyWalkingDynamicField();
        ContextManager.continued(contextSnapshot);
    }
```

**Comment by wu-sheng** [comment]
Kafka version?

**Comment by Liu-XinYuan** [comment]
> Kafka version?
2.0.1

**Comment by wu-sheng** [comment]
Read #2720
