### ISSUE TITLE
[lettuce] before method[writeToChannelAndFlush] intercept failure   java.lang.NullPointerException

### ISSUE THREAD

**Issue by evanxuhe** [apache/skywalking#2790]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking6.1.0
SpringBoot 2.1.5RELEASE
spring-boot-starter-data-redis:2.1.5RELEASE
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

redis works well
but no data about redis received
and reports the error about lettuce intercept failure
```shell
ERROR 2019-05-30 19:31:32:153 lettuce-nioEventLoop-4-3 InstMethodsInterWithOverrideArgs :  class[class io.lettuce.core.protocol.AsyncCommand] before method[onComplete] intercept failure 
java.lang.ClassCastException: io.lettuce.core.protocol.CommandExpiryWriter$$Lambda$833/818080089 cannot be cast to java.util.function.Consumer
        at org.apache.skywalking.apm.plugin.lettuce.v5.AsyncCommandMethodInterceptor.beforeMethod(AsyncCommandMethodInterceptor.java:45)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:81)
        at io.lettuce.core.protocol.AsyncCommand.onComplete(AsyncCommand.java)
        at io.lettuce.core.protocol.CommandExpiryWriter.potentiallyExpire(CommandExpiryWriter.java:174)
        at io.lettuce.core.protocol.CommandExpiryWriter.write(CommandExpiryWriter.java:111)
        at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
        at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:467)
        at io.lettuce.core.AbstractRedisAsyncCommands.authAsync(AbstractRedisAsyncCommands.java:86)
        at io.lettuce.core.StatefulRedisConnectionImpl.activated(StatefulRedisConnectionImpl.java:130)
        at io.lettuce.core.protocol.DefaultEndpoint.lambda$notifyChannelActive$0(DefaultEndpoint.java:379)
        at io.lettuce.core.protocol.SharedLock.lambda$doExclusive$0(SharedLock.java:82)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:103)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:81)
        at io.lettuce.core.protocol.DefaultEndpoint.notifyChannelActive(DefaultEndpoint.java:363)
        at io.lettuce.core.protocol.CommandHandler.channelActive(CommandHandler.java:268)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.ChannelGroupListener.channelActive(ChannelGroupListener.java:40)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.PlainChannelInitializer$1.channelActive(PlainChannelInitializer.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1396)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

ERROR 2019-05-30 19:31:32:155 lettuce-nioEventLoop-4-3 InstMethodsInter :  class[class io.lettuce.core.protocol.DefaultEndpoint] before method[writeToChannelAndFlush] intercept failure 
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.apache.skywalking.apm.agent.core.dictionary.NetworkAddressDictionary.find(NetworkAddressDictionary.java:45)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createExitSpan(TracingContext.java:322)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:122)
        at org.apache.skywalking.apm.plugin.lettuce.v5.RedisChannelWriterInterceptor.beforeMethod(RedisChannelWriterInterceptor.java:62)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java)
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:142)
        at io.lettuce.core.protocol.CommandExpiryWriter.write(CommandExpiryWriter.java:112)
        at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
        at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:467)
        at io.lettuce.core.AbstractRedisAsyncCommands.authAsync(AbstractRedisAsyncCommands.java:86)
        at io.lettuce.core.StatefulRedisConnectionImpl.activated(StatefulRedisConnectionImpl.java:130)
        at io.lettuce.core.protocol.DefaultEndpoint.lambda$notifyChannelActive$0(DefaultEndpoint.java:379)
        at io.lettuce.core.protocol.SharedLock.lambda$doExclusive$0(SharedLock.java:82)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:103)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:81)
        at io.lettuce.core.protocol.DefaultEndpoint.notifyChannelActive(DefaultEndpoint.java:363)
        at io.lettuce.core.protocol.CommandHandler.channelActive(CommandHandler.java:268)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.ChannelGroupListener.channelActive(ChannelGroupListener.java:40)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.PlainChannelInitializer$1.channelActive(PlainChannelInitializer.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1396)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

ERROR 2019-05-30 19:31:32:158 lettuce-nioEventLoop-4-3 InstMethodsInter :  class[class io.lettuce.core.protocol.DefaultEndpoint] after method[writeToChannelAndFlush] intercept failure 
java.lang.IllegalStateException: No active span.
        at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:382)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:161)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:165)
        at org.apache.skywalking.apm.plugin.lettuce.v5.RedisChannelWriterInterceptor.afterMethod(RedisChannelWriterInterceptor.java:72)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
        at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java)
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:142)
        at io.lettuce.core.protocol.CommandExpiryWriter.write(CommandExpiryWriter.java:112)
        at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
        at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:467)
        at io.lettuce.core.AbstractRedisAsyncCommands.authAsync(AbstractRedisAsyncCommands.java:86)
        at io.lettuce.core.StatefulRedisConnectionImpl.activated(StatefulRedisConnectionImpl.java:130)
        at io.lettuce.core.protocol.DefaultEndpoint.lambda$notifyChannelActive$0(DefaultEndpoint.java:379)
        at io.lettuce.core.protocol.SharedLock.lambda$doExclusive$0(SharedLock.java:82)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:103)
        at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:81)
        at io.lettuce.core.protocol.DefaultEndpoint.notifyChannelActive(DefaultEndpoint.java:363)
        at io.lettuce.core.protocol.CommandHandler.channelActive(CommandHandler.java:268)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.ChannelGroupListener.channelActive(ChannelGroupListener.java:40)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.lettuce.core.PlainChannelInitializer$1.channelActive(PlainChannelInitializer.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1396)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by evanxuhe** [comment]
io.lettuce:lettuce-core.jar version=5.1.6
which coincides with the official requirements

**Comment by zhaoyuguang** [comment]
Can you write a demo to reproduce this scenario？

**Comment by evanxuhe** [comment]
> Can you write a demo to reproduce this scenario？

OK wait a minute

**Comment by evanxuhe** [comment]
> Can you write a demo to reproduce this scenario？

https://gitee.com/evanxuhe/apm-demo/tree/master
You can reproduce it easily
Or you can launch A only by commenting the restTemplate part
I user skywalking 6.1.0

**Comment by wu-sheng** [comment]
Fixed.
