### ISSUE TITLE
get http 500 error when sending a span without "kind" attribute to zipkin receiver

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [apache/skywalking#2836]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  - Our framework had implemented zipkin v1 reporter, i try skywalking as the backend。 but i got some problem to sending span data to SW. The zipkin plugin throw an Exception because it receive span without "kind" data.
  - my question is: it's a correct action that to throw an Exception when the "kind" attr is a null value? 

___
### Bug
- Which version of SkyWalking, OS and JRE?
  - the problem exists in tag v6.1.0 and master branch

- Which company or project?
  - Kingdee

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

in project zipkin-reveiver-plugin. class [org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward](https://github.com/apache/skywalking/blob/master/oap-server/server-receiver-plugin/zipkin-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/zipkin/trace/SpanForward.java)

``` java

    public void send(List<Span> spanList) {

            // omit code......

            String spanName = span.name();
            Span.Kind kind = span.kind();
            switch (kind) { // exception will throw here if "kind" is null;
                case SERVER:
                case CONSUMER:
                    if (!StringUtil.isEmpty(spanName) && serviceId != Const.NONE) {
                        int endpointId = endpointInventoryCache.getEndpointId(serviceId, spanName,
                            DetectPoint.SERVER.ordinal());
                        if (endpointId != Const.NONE) {
                            zipkinSpan.setEndpointId(endpointId);
                        } else if (config.isRegisterZipkinEndpoint()) {
                            CoreRegisterLinker.getEndpointInventoryRegister().getOrCreate(serviceId, spanName, DetectPoint.SERVER);
                        }
                    }
            }
            if (!StringUtil.isEmpty(spanName)) {
                zipkinSpan.setEndpointName(spanName);
            }

            // omit code......
    }
```

``` 
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward.lambda$send$0(SpanForward.java:76) ~[classes/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_111]
	at org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward.send(SpanForward.java:55) ~[classes/:?]
	at org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanProcessor.convert(SpanProcessor.java:65) ~[classes/:?]
	at org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanV1JettyHandler.doPost(SpanV1JettyHandler.java:67) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
  - Should it be more acceptable if SW gave a default value to the attr "kind" or just skip the step?

**Comment by wu-sheng** [comment]
Zipkin receiver is experimental. We requires that tag.

**Comment by Duncan-tree-zhou** [comment]
Is that means the zipkin format is not yet supported?

**Comment by wu-sheng** [comment]
We support, but first not production ready, we said very clearly in our document, then, we need those tags today. If you want to support this feature, I could assist you, but SkyWalking PMC are interesting in SkyWalking native agents more, and our users are too.

**Comment by Duncan-tree-zhou** [comment]
> We support, but first not production ready, we said very clearly in our document, then, we need those tags today. If you want to support this feature, I could assist you, but SkyWalking PMC are interesting in SkyWalking native agents more, and our users are too.

Acutally i had tried the java auto again first. But there some problem to assist the skywalking tracing with our rpc component which is in the [supported list](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md) (dubbox 2.8.4). It looks like they had some custom enhancement on the rpc component. So the next step, I will try to use the java againt and find out the compatibility problem. Thanks for your advise.

**Comment by Duncan-tree-zhou** [comment]
ref : [SpanForward.java](https://github.com/apache/skywalking/blob/master/oap-server/server-receiver-plugin/zipkin-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/zipkin/trace/SpanForward.java)

the problem still exists in latest code. 

check [zipkin-api](https://zipkin.io/zipkin-api/#/). the attribute "kind" can be null. While in Skywalking zipkin receiver, it's forced to be not null.

**Comment by wu-sheng** [comment]
@Duncan-tree-zhou No one changed that, it is still the same.

**Comment by wu-sheng** [comment]
When you read the codes, you will know why we need that.

**Comment by Duncan-tree-zhou** [comment]
@wu-sheng So you mean that if one of the span.kind in the batch is null, all the span should not be processed in send() method? actually i am trying to understand the code logic and get confused about it. i am not able to see the trace when i am using the zipkin receiver.

**Comment by wu-sheng** [comment]
There is no certain thing here. Like I said, just experimental.
