### ISSUE TITLE
Exception while fetching data (/getAlarm) : Statement parameter 3 not set.

### ISSUE THREAD

**Issue by wslongchen** [apache/skywalking#2848]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ √] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking version : 6.1.0 (Downloaded from Latest release)
OS : CentOS release 6.5 (Final)
Java version "1.8.0_131"

- Which company or project?

Prepare to use the demo of the SkyWalking.

- What happen?

Display blanks when clicking 'all' button.But actually clicking on the 'service' button has data.
Screenshot :
![image](https://user-images.githubusercontent.com/6868861/59238410-98b79e00-8c30-11e9-96d1-eabf28fb333c.png)
![image](https://user-images.githubusercontent.com/6868861/59238524-14194f80-8c31-11e9-9ed0-1d7a0d2aa18f.png)

Well , I checked the log and found the following misprints ,I guess it should be that the controller receives the parameters empty, and then goes to the formatted query statement to cause the parameters not set and cause the error.

Finally, due to my environmental reasons, I can not debug to find the problem for the time being, but it does not affect our use of SkyWalkingfor normal work, but still very much hope for help.

```shell
2019-06-11 10:06:21,133 - graphql.execution.SimpleDataFetcherExceptionHandler - 23 [qtp68195659-1939] WARN  [] - Exception while fetching data (/getAlarm) : Statement parameter 3 not set.
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Statement parameter 3 not set.
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLAlarmQueryDAO.getAlarm(MySQLAlarmQueryDAO.java:67) ~[storage-jdbc-hikaricp-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.query.AlarmQueryService.getAlarm(AlarmQueryService.java:53) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.AlarmQuery.getAlarm(AlarmQuery.java:62) ~[query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.resolver.AlarmQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.1.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:87) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:81) [query-graphql-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101) [library-server-6.1.0.jar:6.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105) [library-server-6.1.0.jar:6.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.sql.SQLException: Statement parameter 3 not set.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1172) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:794) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2002) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:142) ~[library-client-6.1.0.jar:6.1.0]
	... 44 more
```

___
### Requirement or improvement
- May everything be better and better

**Comment by wu-sheng** [comment]
This should have been fixed in master.
