### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/dependencies/io/grpc/internal/DelayedStream$7

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#2849]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Agent logs had errors like this:
ERROR 2019-06-11 09:39:24:748 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient :  Transform and send UpstreamSegment to collector fail. 
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/dependencies/io/grpc/internal/DelayedStream$7
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.DelayedStream.flush(DelayedStream.java:240)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:435)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:321)
	at org.apache.skywalking.apm.agent.core.remote.TraceSegmentServiceClient.consume(TraceSegmentServiceClient.java:111)
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101)
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68)

**Comment by wu-sheng** [comment]
We have this class in agent jar, you could check. I am not sure why you have this issue.
