### ISSUE TITLE
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN

### ISSUE THREAD

**Issue by Skqing** [apache/skywalking#2862]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [1 ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
apache-skywalking-apm-6.1.0.tar JRE1.8

- What happen?
```
DEBUG 2019-06-12 17:35:59:324 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-06-12 17:35:59:330 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:115)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

DEBUG 2019-06-12 17:36:02:324 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-06-12 17:36:02:330 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:115)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Grpc error. You need to make sure network available and OAP server started.

**Comment by SevenBlue2018** [comment]
I checked the oap server that I did not find any error.
![image](https://user-images.githubusercontent.com/11767168/62991420-22c6f180-be82-11e9-9ed2-3e7855d122c9.png)
![image](https://user-images.githubusercontent.com/11767168/62991429-26f30f00-be82-11e9-9a44-714876f80d91.png)
I do not know the reason.

**Comment by wu-sheng** [comment]
Check your ip and port binding.

**Comment by SevenBlue2018** [comment]
Check where?

**Comment by SevenBlue2018** [comment]
Agent connnect the oap server, ip and port is right.

**Comment by SevenBlue2018** [comment]
Originally everything is normal.When I have a problem the disk space is full, I emptied the es data and restarted it.Now The agent has the above problem.

**Comment by wu-sheng** [comment]
If you erased all es data, you need to reboot agents.

**Comment by SevenBlue2018** [comment]
Oh my god!!!

**Comment by SevenBlue2018** [comment]
I did the same thing in another environment, but the agent can send data normally without restarting.I do not know this is why?

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/62993004-3f662800-be88-11e9-8a85-bc4114e8f7ea.png)
Agent did not restart.

**Comment by wu-sheng** [comment]
Hard to tell from my side. If you erased the metadata, reboot is required, unless in 6.3.0+ agent.

**Comment by SevenBlue2018** [comment]
ok, thank you!!!
