### ISSUE TITLE
Wrong Line Number in error stack after using skywalking

### ISSUE THREAD

**Issue by evanxuhe** [apache/skywalking#2914]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
**The line number in error stack displys wrong**, different from real line number in java source, after using skywalking
like the NullPointerException shows **202** in ChargingPileServiceImpl.java 
but actually **168** !
___
![screenshot](https://user-images.githubusercontent.com/24379174/59814834-3d309300-9349-11e9-9e50-27f5840a7853.png)

### Bug
- What do you want to know?
The reason and how to fix

I have uploaded the debugging classes like **com.chehejia.aisp.charging.api.controller.MobileChargingController$auxiliary$xpBfyibB** shown in the error stack, which is zipped in [debugging.zip](https://github.com/apache/skywalking/files/3308552/debugging.zip)

```
java.lang.NullPointerException: null
	at com.chehejia.aisp.charging.api.service.impl.ChargingPileServiceImpl.setVehicleInfo(ChargingPileServiceImpl.java:202) ~[classes!/:?]
	at com.chehejia.aisp.charging.api.service.impl.ChargingPileServiceImpl.getPileBasic(ChargingPileServiceImpl.java:168) ~[classes!/:?]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic$original$ur0oD1AC(MobileChargingController.java:143) ~[classes!/:?]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic$original$ur0oD1AC$accessor$AIw0pivL(MobileChargingController.java) ~[classes!/:?]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController$auxiliary$xpBfyibB.call(Unknown Source) ~[classes!/:?]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) ~[skywalking-agent.jar:6.1.0]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic(MobileChargingController.java) ~[classes!/:?]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController$$FastClassBySpringCGLIB$$42df9a7d.invoke(<generated>) ~[classes!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:150) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at com.chehejia.iam.client.auth.IamClientAuthAspect.aroundIAMPermissions(IamClientAuthAspect.java:57) ~[aisp-iam-starter-2.0.0-SNAPSHOT.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController$$EnhancerBySpringCGLIB$$6b555d02.getChargingPilesBasic(<generated>) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$F71Tq1gA(InvocableHandlerMethod.java:133) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$F71Tq1gA$accessor$VI5bANvB(InvocableHandlerMethod.java) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod$auxiliary$a8kW4v0c.call(Unknown Source) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) ~[skywalking-agent.jar:6.1.0]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.1.10.jar!/:1.1.10]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111) [spring-boot-actuator-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.Connectors.executeRootHandler$original$PDmsmr3u(Connectors.java:360) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.Connectors.executeRootHandler$original$PDmsmr3u$accessor$XLgE1k8M(Connectors.java) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.Connectors$auxiliary$nEdrUcVf.call(Unknown Source) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:86) [skywalking-agent.jar:6.1.0]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.13.Final.jar!/:2.0.13.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by wu-sheng** [comment]
I am looking at this stack, and confusing.
> at com.chehejia.aisp.charging.api.service.impl.ChargingPileServiceImpl.setVehicleInfo(ChargingPileServiceImpl.java:202) ~[classes!/:?]

Is this class enhanced by SkyWalking? If so, open the `agent.is_open_debugging_class`, and check the class of this in `/debugging` folder of the agent.

**Comment by wu-sheng** [comment]
There is no SkyWalking class in this method stack, such as an interceptor. Such as this

> at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) ~[skywalking-agent.jar:6.1.0]
	at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic(MobileChargingController.java) ~[classes!/:?]

`MobileChargingController#getChargingPilesBasic` should be manipulated by SkyWalking, but not the class you said. So please confirm first.

**Comment by evanxuhe** [comment]
> There is no SkyWalking class in this method stack, such as an interceptor. This is the evidence of another class enhanced.
> 
> > at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) ~[skywalking-agent.jar:6.1.0]
> > at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic(MobileChargingController.java) ~[classes!/:?]
> 
> `MobileChargingController#getChargingPilesBasic` should be manipulated by SkyWalking, but not the class you said. So please confirm first.

I know that And I am also confused. Controller is manipulated while ServiceImpl is not. But it does happen, and many applications show the problem. I wanna know if the introduce of controller enhance finally caused the problem some way although not enhancing service class directly

**Comment by evanxuhe** [comment]
> There is no SkyWalking class in this method stack, such as an interceptor. This is the evidence of another class enhanced.
> 
> > at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) ~[skywalking-agent.jar:6.1.0]
> > at com.chehejia.aisp.charging.api.controller.MobileChargingController.getChargingPilesBasic(MobileChargingController.java) ~[classes!/:?]
> 
> `MobileChargingController#getChargingPilesBasic` should be manipulated by SkyWalking, but not the class you said. So please confirm first.

What confues me more is that the line number **143** controller is right. But the line number 202 is wrong, which is rather unbelievable. Do you have any idea about any reason can cause it ?

**Comment by wu-sheng** [comment]
> What confues me more is that the line number 143 controller is right. But the line number 202 is wrong, which is rather unbelievable. Do you have any idea about any reason can cause it ?

Still recommend to check the debug folder, whether somehow the class with wrong line number is there? If not, as I expected, I am confusing too. We put all enhanced classes with the enhanced results there.

**Comment by evanxuhe** [comment]
> > What confues me more is that the line number 143 controller is right. But the line number 202 is wrong, which is rather unbelievable. Do you have any idea about any reason can cause it ?
> 
> Still recommend to check the debug folder, whether somehow the class with wrong line number is there? If not, as I expected, I am confusing too. We put all enhanced classes with the enhanced results there.

OK . I will try to find out the reasonAnd I attach the controller java src.

**Comment by evanxuhe** [comment]
> > What confues me more is that the line number 143 controller is right. But the line number 202 is wrong, which is rather unbelievable. Do you have any idea about any reason can cause it ?
> 
> Still recommend to check the debug folder, whether somehow the class with wrong line number is there? If not, as I expected, I am confusing too. We put all enhanced classes with the enhanced results there.

What's more I upload controller java src as reference
![screenshot_1](https://user-images.githubusercontent.com/24379174/59824099-c1434480-9362-11e9-9708-0361a8cf95c6.png)

**Comment by wu-sheng** [comment]
If I remember right, we don't enhance class of `@ResponseBody`.

**Comment by evanxuhe** [comment]
> If I remember right, we don't enhance class of `@ResponseBody`.

Yes. Thank u for your patience. 
Finally we found that the stack appears that same after removing agent,which **proves that agent works well and make no any bad effects.** 
What's more, **the error stack is right and I understand wrongly before**. setVehicle(143) is the method that throws Exp while the line number points to where Exp really happens, which is inside setVehicle(line number 202). Therefore the stack shows in the right way.
The guess from other developers ,at the first time, misled me to think it is caused by agent. Sorry for that. I will keep more cautious next time to prompt a issue

**Comment by wu-sheng** [comment]
Thanks for update. Make sense. Good luck in SkyWalking.
