### ISSUE TITLE
Bug java.lang.ArithmeticExceptio

### ISSUE THREAD

**Issue by evanxuhe** [apache/skywalking#2922]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking6.1.0 in K8s
- Which company or project?
   chehejia 
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
  
**2Skywalking oap instances as a cluster in K8s**
  After restarting ES, two oaps has been propmting error. And no data shows in UI.
  It seems like that there are no grpclient. What cause it? The connection between instances seems OK 
```
2019-06-21 15:08:59,143 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -9461 [DataCarrier.INDICATOR_L1_AGGREGATION.BulkConsumePool.15.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:114) ~[server-core-6.1.0.jar:6.1.0]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_212]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:109) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:84) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:36) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:152) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49) [apm-datacarrier-6.1.0.jar:6.1.0]
2019-06-21 15:08:59,147 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -9465 [DataCarrier.INDICATOR_L1_AGGREGATION.BulkConsumePool.8.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:114) ~[server-core-6.1.0.jar:6.1.0]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_212]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:109) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:84) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:36) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:152) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49) [apm-datacarrier-6.1.0.jar:6.1.0]
2019-06-21 15:08:59,149 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -9467 [DataCarrier.INDICATOR_L1_AGGREGATION.BulkConsumePool.10.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:50) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:32) ~[server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:114) ~[server-core-6.1.0.jar:6.1.0]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_212]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:109) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:84) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:36) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:152) [server-core-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-6.1.0.jar:6.1.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49) [apm-datacarrier-6.1.0.jar:6.1.0]
```

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This means your cluster coordinator doesn't work. If you are using k8s coordinator, please make sure it has granted to access API Server.

**Comment by evanxuhe** [comment]
> This means your cluster coordinator doesn't work. If you are using k8s coordinator, please make sure it has granted to access API Server.

I just simply delete all k8s (including RABC) and it worked. 
Thank you
