### ISSUE TITLE
One trace segment has been abandoned, cause by buffer is full.

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#3005]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
-  Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
the new release version of 6.2.0. 
i found the bug in win10 and centos 7
my JRE is openjdk8 and jdk8

- What happen?
i lost my agent trace segment data,  but my server is ok, it can recieve jvm metrics, when i debug it i found it didn't call the method of "batchPersistence" which is bulk update or save the data.
i have no idea about how to fix it, can you give me some advice, thank you.

the client log is:
DEBUG 2019-07-04 20:42:55:761 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:762 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:762 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:763 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:763 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:763 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:768 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:771 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:771 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:772 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:773 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:773 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:773 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:774 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:774 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:775 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:778 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:780 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:780 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:780 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:55:781 pool-7-thread-9 TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-07-04 20:42:56:782 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-07-04 20:42:59:782 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.

the server log is :
2019-07-04 20:46:15,674 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager - 88 [pool-5-thread-1] DEBUG [] - Refresh remote nodes collection.
2019-07-04 20:46:15,674 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager - 98 [pool-5-thread-1] DEBUG [] - Cluster instance: 0.0.0.0_11800
2019-07-04 20:46:15,674 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager - 121 [pool-5-thread-1] DEBUG [] - Remote client list: 0.0.0.0_11800,
2019-07-04 20:46:16,293 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMMetricReportServiceHandler - 43 [grpc-default-executor-7] DEBUG [] - receive the jvm metrics from service instance, id: 13
2019-07-04 20:46:17,293 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMMetricReportServiceHandler - 43 [grpc-default-executor-7] DEBUG [] - receive the jvm metrics from service instance, id: 13
2019-07-04 20:46:18,293 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMMetricReportServiceHandler - 43 [grpc-default-executor-7] DEBUG [] - receive the jvm metrics from service instance, id: 13
2019-07-04 20:46:19,294 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMMetricReportServiceHandler - 43 [grpc-default-executor-7] DEBUG [] - receive the jvm metrics from service instance, id: 13
2019-07-04 20:46:20,293 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMMetricReportServiceHandler - 43 [grpc-default-executor-7] DEBUG [] - receive the jvm metrics from service instance, id: 13

**Comment by wu-sheng** [comment]
This log just shows you, your backend can't support the payload  generated by agents. So agent choose to abandon rather than crash your application memory.
We have explained this many many times. Please search issue before submit a duplicate one.

**Comment by coki230** [comment]
my error may be not same as the others, because when the agent abandoned the data, the server cann't save any trace segment any more, if the reason is payload, the server my lost some data, but in my situation it lost all the data, i debug it found the server recive it, but cann't save it any more, i do not know why yet.

**Comment by coki230** [comment]
and in the class of "ConsumerThread" and "MultipleChannelsConsumer",  the variable of “hasData” always is false. so it cann't call the method of "createBulkProcessor" in the class of "ElasticSearchClient"

**Comment by wu-sheng** [comment]
That class is a basic class for skywalking queue. It is empty means nothing in the queue.

**Comment by liuzhaozhao** [comment]
I also encountered the same problem. After testing, I found that some oap servers find elasticSearch when they write data and there is an exception, which can cause stop writing elasticSearch. If the agent selects this oap server to report data, it will cause the above problem，The problem can be resolved temporarily by restarting the oap server, but the following issues need to be resolved in the end
1. Agent is highly available. When reporting data to the bottleneck, select other nodes or multiple nodes to report, rather than fixing one oap server node;
2. Oap server needs to add write exception retry;

**Comment by coki230** [comment]
I find out the reason, the bug is caused by auto Flush and the method of "batchPersistence", because the ES  need lock the same lock when flush and internalAdd(which called by batchPersistence). so i delete the auto flush the result is  so far are normal. the underneath is my thread dump brief:

"DataCarrier.RECORD_PERSISTENT.BulkConsumePool.0.Thread" #24 daemon prio=5 os_prio=0 tid=0x000000002585a800 nid=0xc1c waiting for monitor entry [0x000000002715f000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:286)
        - waiting to lock <0x00000006c2c52eb0> (a org.elasticsearch.action.bulk.BulkProcessor)
        at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:271)
        at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:267)
        at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:253)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.lambda$batchPersistence$0(BatchProcessEsDAO.java:64)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO$$Lambda$285/523676665.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.batchPersistence(BatchProcessEsDAO.java:62)
        at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.onWork(PersistenceWorker.java:51)
        at org.apache.skywalking.oap.server.core.analysis.worker.RecordPersistentWorker$PersistentConsumer.consume(RecordPersistentWorker.java:103)
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80)
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49)

"elasticsearch[scheduler][T#1]" #72 daemon prio=5 os_prio=0 tid=0x00000000202c7000 nid=0x850 waiting for monitor entry [0x000000002a85e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.elasticsearch.action.bulk.BulkProcessor$Flush.run(BulkProcessor.java:367)
        - waiting to lock <0x00000006c2c52eb0> (a org.elasticsearch.action.bulk.BulkProcessor)
        at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:182)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"pool-14-thread-1" #68 prio=5 os_prio=0 tid=0x00000000202c4000 nid=0xfa8 waiting on condition [0x0000000029b4e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c2c53160> (a java.util.concurrent.Semaphore$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
        at org.elasticsearch.action.bulk.BulkRequestHandler.execute(BulkRequestHandler.java:60)
        at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:339)
        at org.elasticsearch.action.bulk.BulkProcessor.flush(BulkProcessor.java:358)
        - locked <0x00000006c2c52eb0> (a org.elasticsearch.action.bulk.BulkProcessor)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.batchPersistence(BatchProcessEsDAO.java:72)
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:113)
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:65)
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer$$Lambda$201/296552796.run(Unknown Source)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by 1346735074** [comment]
How to solve this problem

**Comment by wujun8** [comment]
https://github.com/apache/skywalking/issues/2066#issuecomment-535312082
Hope this helps.
