### ISSUE TITLE
Added zookeeper configuration in application.yml, but reported an error？

### ISSUE THREAD

**Issue by weipengd** [apache/skywalking#3024]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

019-07-08 16:27:31,505 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-07-08 16:27:31,510 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-07-08 16:27:31,558 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@6b0f266e{/,null,AVAILABLE}
2019-07-08 16:27:31,573 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@33e4b9c4{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-07-08 16:27:31,573 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @246101ms
2019-07-08 16:27:31,574 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - cluster module exist 2 providers
org.apache.skywalking.oap.server.library.module.DuplicateProviderException: cluster module exist 2 providers
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:142) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:30) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:191) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:63) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:66) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]

**Comment by zhaoyuguang** [comment]
` cluster module exist 2 providers`  The problem is here.
You maybe not delete `standalone` at `application.yml`

**Comment by weipengd** [comment]
Configure cluster mode, is it wrong to configure zookeeper in application.yml? How to configure the cluster mode, there is no detailed documentation, can you say a little more, thank you
  


dongweipeng_927@126.com
 
发件人： 于玉桔
发送时间： 2019-07-08 16:43
收件人： apache/skywalking
抄送： code_rsk; Author
主题： Re: [apache/skywalking] Added zookeeper configuration in application.yml, but reported an error？ (#3024)
cluster module exist 2 providers The problem is here.
You maybe not delete standalone at application.yml

**Comment by wu-sheng** [comment]
It is hard to believe, you are saying there is no document. You even don't understand the first introduction in application.yml.

Please don't leave this kind of messages, which only shows you never read the document.

**Comment by wu-sheng** [comment]
We give a very clear document link in readme. There are many things introduced. Clearly, you never read.

**Comment by weipengd** [comment]
The document was not written in detail, just to say a rough idea, I did not find a clear explanation. If you have to read the document if you have any problems, then is it necessary for the students to read the textbooks and do not need the teacher to guide them?



dongweipeng_927@126.com
 
发件人： 吴晟 Wu Sheng
发送时间： 2019-07-08 17:01
收件人： apache/skywalking
抄送： code_rsk; Author
主题： Re: [apache/skywalking] Added zookeeper configuration in application.yml, but reported an error？ (#3024)
We give a very clear document link in readme. There are many things introduced. Clearly, you never read.

**Comment by wu-sheng** [comment]
This is an open source project, not at school. You totally ask a wrong question. Everyone works voluntarily, that is all.

Why do you say document just includes rough idea? For your question, it is very clear there. We even have volunteer to provide Chinese version document.

**Comment by wu-sheng** [comment]
You need to spend time on open source project, not asking a committer to spend their personal time to answer the same question repeatly.

**Comment by weipengd** [comment]
this document no cluster details.



dongweipeng_927@126.com
 
发件人： 吴晟 Wu Sheng
发送时间： 2019-07-09 14:13
收件人： apache/skywalking
抄送： code_rsk; Author
主题： Re: [apache/skywalking] Added zookeeper configuration in application.yml, but reported an error？ (#3024)
You need to spend time on open source project, not asking a committer to spend their personal time to answer the same question repeatly.

**Comment by phospherus** [comment]
cluster:
  # standalone:            ####此处是重点

经过我的测试，需要第一次启动的时候，使用集群方式，并初始化数据到存储中
