### ISSUE TITLE
spring cloud gateway 2.0.x exception

### ISSUE THREAD

**Issue by zengxiaowengit** [apache/skywalking#3037]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to fix this bug? is this version skywalking cannot supported?
OR now which spring cloud version is supported so I can switch to.
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking version: 6.2.0
OS:  ubuntu 16.04
jre: oracle jre-8u161-linux-x64
spring-cloud-dependencies: Greenwich.RELEASE
spring-cloud-starter-gateway: 2.1.0.RELEASE ( depend on spring-boot-starter-webflux ) 

- Which company or project?
Guo Tai Jun An Futures.

- What happen?
when I start project,  many warn Exception occured like this:
> java.lang.IllegalStateException: Cannot resolve type description for javax.servlet.http.HttpServlet

the first trace print this Exception:
> ERROR 2019-07-10 02:50:52:881 reactor-http-epoll-6 InstMethodsInter :  class[class reactor.netty.http.client.HttpClientOperations] before method[send] intercept failure 
java.lang.IllegalArgumentException: ContextSnapshot can't be null.
        at org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:145)
        at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v2.HttpClientOperationsSendInterceptor.beforeMethod(HttpClientOperationsSendInterceptor.java:59)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at reactor.netty.http.client.HttpClientOperations.send(HttpClientOperations.java)
        at org.springframework.http.client.reactive.ReactorClientHttpRequest.lambda$writeWith$0(ReactorClientHttpRequest.java:87)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.springframework.http.client.reactive.AbstractClientHttpRequest.doCommit(AbstractClientHttpRequest.java:133)
        at org.springframework.http.client.reactive.ReactorClientHttpRequest.writeWith(ReactorClientHttpRequest.java:83)
        at org.springframework.http.codec.FormHttpMessageWriter.lambda$write$0(FormHttpMessageWriter.java:139)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:141)
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:169)
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:441)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:470)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:515)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:544)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:338)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:745)

And only the first request trace item can be sent to oap server,  then oap server can not receive trace any more. 

the detail log please see the attatchment.
[skywalking-api.log](https://github.com/apache/skywalking/files/3375583/skywalking-api.log)

___
### Requirement or improvement
- could you provide the supported version of webflux or gateway version?
Thanks a lot.

**Comment by wu-sheng** [comment]
We don't support 2.0.x. Supported list is there

**Comment by zengxiaowengit** [comment]
@zhaoyuguang I have switched spring-cloud-gateway version to 2.1.x, and it doesn't work well too. through serveral test cases, 

- I found it's because gateway 2.1.x can't work with spring-boot version 2.1.6. 
Then I use spring boot 2.1.4, It's work. may be we should support in next skywalking version, right? 

Thanks a lot.
