### ISSUE TITLE
facing issue while connecting collector to elastic 7.1

### ISSUE THREAD

**Issue by lmzhizhe** [apache/skywalking#3047]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Question or discussion ] Question or discussion
- [ Bug] Bug

___
### Question
- What do you want to know?
start error with es7.1,how to resolved it?
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2 linux centos  jdk 1.8
- Which company or project?
vivo
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

````
route allocated: 1 of 10; total allocated: 3 of 30]
2019-07-11 16:18:48,357 - org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager - 299 [I/O dispatcher 1] DEBUG [] - Connection [id: http-outgoing-0][route: {}->http://172.20.226.147:9200] can be kept alive indefinitely
2019-07-11 16:18:48,357 - org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl - 154 [I/O dispatcher 1] DEBUG [] - http-outgoing-0 172.20.226.153:12847<->172.20.226.147:9200[ACTIVE][r:r]: Set timeout 0
2019-07-11 16:18:48,357 - org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager - 305 [I/O dispatcher 1] DEBUG [] - Connection released: [id: http-outgoing-0][route: {}->http://172.20.226.147:9200][total kept alive: 3; route allocated: 1 of 10; total allocated: 3 of 30]
2019-07-11 16:18:48,357 - org.elasticsearch.client.RestClient - 59 [I/O dispatcher 1] DEBUG [] - request [PUT http://172.20.226.147:9200/_template/alarm_record] returned [HTTP/1.1 400 Bad Request]
2019-07-11 16:18:48,361 - org.apache.http.impl.nio.client.InternalIODispatch - 85 [I/O dispatcher 1] DEBUG [] - http-outgoing-0 [ACTIVE] [content length: 1191; pos: 1191; completed: true]
2019-07-11 16:18:48,361 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - method [PUT], host [http://172.20.226.147:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
org.apache.skywalking.oap.server.library.module.ModuleStartException: method [PUT], host [http://172.20.226.147:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:104) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.2.0.jar:6.2.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: method [PUT], host [http://172.20.226.147:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:93) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:99) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
	... 3 more

````

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Simply, we don't support. Read document.

**Comment by walkersing** [comment]
skywalking 6.5.0
es 7.5.0
the same as error

> `2019-12-04 12:56:21,948 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 69 [main] INFO  [] - index alarm_record's columnTypeEsMapping builder str: {"type":{"properties":{"scope":{"type":"integer"},"name":{"type":"keyword"},"id0":{"type":"integer"},"id1":{"type":"integer"},"start_time":{"type":"long"},"alarm_message":{"type":"keyword","copy_to":"alarm_message_match"},"alarm_message_match":{"type":"text","analyzer":"oap_analyzer"},"time_bucket":{"type":"long"}}}}
2019-12-04 12:56:23,295 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - method [PUT], host [http://192.168.1.16:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
org.apache.skywalking.oap.server.library.module.ModuleStartException: method [PUT], host [http://192.168.1.16:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:141) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.5.0.jar:6.5.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: method [PUT], host [http://192.168.1.16:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:96) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:136) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
	... 3 more`
