### ISSUE TITLE
Running for a while sky, can't collect data, start to report error

### ISSUE THREAD

**Issue by weipengd** [apache/skywalking#3050]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- - What happen?
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2019-07-11 17:53:53,380 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.EndpointInventoryCacheEsDAO - 56 [grpc-default-executor-10] ERROR [] - Request cannot be executed; I/O reactor status: STOPPED
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:351) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.get(RestHighLevelClient.java:293) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.get(ElasticSearchClient.java:187) ~[library-client-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.EndpointInventoryCacheEsDAO.getEndpointId(EndpointInventoryCacheEsDAO.java:49) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.cache.EndpointInventoryCache.getEndpointId(EndpointInventoryCache.java:69) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.register.service.EndpointInventoryRegister.getOrCreate(EndpointInventoryRegister.java:54) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler.lambda$doEndpointRegister$2(RegisterServiceHandler.java:141) ~[skywalking-register-receiver-plugin-6.1.0.jar:6.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_101]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) [?:1.8.0_101]
	at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler.doEndpointRegister(RegisterServiceHandler.java:137) [skywalking-register-receiver-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$MethodHandlers.invoke(RegisterGrpc.java:513) [apm-network-6.1.0.jar:6.1.0]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2019-07-11 17:53:49,049 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler - 65 [grpc-default-executor-106] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]

**Comment by wu-sheng** [comment]
Maybe your OAP or Elasticsearch crashed somehow.
