### ISSUE TITLE
Linux environment error, windows normal, default configuration used

### ISSUE THREAD

**Issue by jvmtar** [apache/skywalking#3079]
2019-07-15 12:33:20,879 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-07-15 12:33:20,885 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-07-15 12:33:21,014 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@10c07b8d{/,null,AVAILABLE}
2019-07-15 12:33:21,056 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@dc79225{HTTP/1.1,[http/1.1]}{account.jetbrains.com:12800}
2019-07-15 12:33:21,057 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @6838ms
2019-07-15 12:33:21,061 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 49 [main] INFO  [] - persistence timer start
2019-07-15 12:33:21,078 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 42 [main] INFO  [] - Cache update timer start
2019-07-15 12:33:22,089 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO - 84 [pool-13-thread-1] ERROR [] - Table "SERVICE_INVENTORY" not found; SQL statement:
select * from service_inventory where is_address=?  and mapping_last_update_time>? [42102-196]
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table "SERVICE_INVENTORY" not found; SQL statement:
select * from service_inventory where is_address=?  and mapping_last_update_time>? [42102-196]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO.loadLastMappingUpdate(H2ServiceInventoryCacheDAO.java:70) ~[storage-jdbc-hikaricp-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.update(CacheUpdateTimer.java:58) ~[server-core-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.lambda$start$0(CacheUpdateTimer.java:48) ~[server-core-6.2.0.jar:6.2.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.2.0.jar:6.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: org.h2.jdbc.JdbcSQLException: Table "SERVICE_INVENTORY" not found; SQL statement:
select * from service_inventory where is_address=?  and mapping_last_update_time>? [42102-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.readTableOrView(Parser.java:5552) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.readTableFilter(Parser.java:1266) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2095) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1940) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1755) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parseSelect(Parser.java:1743) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parsePrepared(Parser.java:449) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parse(Parser.java:321) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.parse(Parser.java:293) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Parser.prepareCommand(Parser.java:258) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Session.prepareLocal(Session.java:578) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Session.prepareCommand(Session.java:519) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[h2-1.4.196.jar:1.4.196]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:125) ~[library-client-6.2.0.jar:6.2.0]
	... 11 more
2019-07-15 12:33:25,081 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO - 84 [pool-13-thread-1] ERROR [] - Table "SERVICE_INVENTORY" not found; SQL statement:
select * from service_inventory where is_address=?  and mapping_last_update_time>? [42102-196]

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check your init logs, why tables are not created automatically.

**Comment by mxwdxypage** [comment]
me too
