### ISSUE TITLE
redis-cluster too many nodes cause  too long index id in elasticsearch

### ISSUE THREAD

**Issue by carlvine500** [apache/skywalking#3096]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2.0 linux java8
- Which company or project?
oap
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
create a redis-cluster with lots of instance,such as :
172.31.88.62:8300;172.31.88.50:8300;172.31.88.62:8301;172.31.88.50:8301;172.31.88.62:8302;172.31.88.50:8302;172.31.88.62:8303;172.31.88.50:8303;172.31.88.62:8304;172.31.88.50:8304;172.31.88.62:8305;172.31.88.50:8305;172.31.88.62:8306;172.31.88.50:8306;172.31.88.62:8307;172.31.88.62:8308;172.31.88.50:8308;172.31.88.62:8309;172.31.88.62:8315;172.31.88.73:8316;172.31.88.73:8317;172.31.88.73:8318;172.31.88.73:8319;172.31.88.73:8300;172.31.88.73:8301;172.31.88.73:8302;172.31.88.73:8303;172.31.88.73:8304;172.31.88.73:8305;172.31.88.73:8306;172.31.88.73:8307;172.31.88.73:8308;172.31.88.73:8309;172.31.88.73:8315;172.31.88.50:8315;172.31.

and cause exception :  
```
2019-07-16 16:48:48,227 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 106 [DataCarrier.REGISTER_L2.BulkConsumePool.0.Thread] ERROR [] - Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 774;
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 774;
        at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.action.index.IndexRequest.validate(IndexRequest.java:183) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:515) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:348) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.forceInsert(ElasticSearchClient.java:251) ~[library-client-6.2.0.jar:6.2.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.forceInsert(RegisterEsDAO.java:51) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:103) ~[server-core-6.2.0.jar:6.2.0]
        at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_141]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:85) [server-core-6.2.0.jar:6.2.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:36) [server-core-6.2.0.jar:6.2.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:142) [server-core-6.2.0.jar:6.2.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-6.2.0.jar:6.2.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49) [apm-datacarrier-6.2.0.jar:6.2.0]
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
redis plugin cut down  redis-nodes , such as ：
172.31.88.62:8300;172.31.88.50:8300;172.31.88.62:8301;...

**Comment by wu-sheng** [comment]
This is unexpected. Maybe add max length for redis plugin about peer?

**Comment by carlvine500** [comment]
nice !
