### ISSUE TITLE
Java agent cannot trace gRPC stream service

### ISSUE THREAD

**Issue by aiyanbo** [apache/skywalking#3142]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWaling: 6.2.0
OS: Mac OS X 10.14.4
JRE: 1.8.0_181
gRPC: 1.22.1

- What happen?
When application invoke gRPC stream service failed, trace cannot work and log will output this:

- beforeMethod
```
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.grpc.v1.StreamCallClientInterceptor cannot be cast to org.apache.skywalking.apm.plugin.grpc.v1.BlockingCallClientInterceptor
	at org.apache.skywalking.apm.plugin.grpc.v1.AsyncUnaryRequestCallCallInterceptor.beforeMethod(AsyncUnaryRequestCallCallInterceptor.java:39)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInterWithOverrideArgs.intercept(StaticMethodsInterWithOverrideArgs.java:75)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:267)
	at io.grpc.stub.ClientCalls.asyncServerStreamingCall(ClientCalls.java:75)
``` 

- afterMethod

```
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:161)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:165)
	at org.apache.skywalking.apm.plugin.grpc.v1.AsyncUnaryRequestCallCallInterceptor.afterMethod(AsyncUnaryRequestCallCallInterceptor.java:50)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInterWithOverrideArgs.intercept(StaticMethodsInterWithOverrideArgs.java:96)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:267)
	at io.grpc.stub.ClientCalls.asyncServerStreamingCall(ClientCalls.java:75)
```

**Comment by wu-sheng** [comment]
I will ask @ascrutae to take a look, but as we have plenty of plugins, I suggest you try to learn how plugin works and debug by yourself first.

**Comment by aiyanbo** [comment]
@wu-sheng Fixed by https://github.com/apache/skywalking/pull/3145

**Comment by ascrutae** [comment]
@aiyanbo The `AsyncUnaryRequestCallCallInterceptor` used to intercept the `UNARY` GRPC service,  the  `UNARY` service is blocking service and I'm curious that the blocking service calls by streaming service, so could you send me the demo to reproduce this issue?

**Comment by aiyanbo** [comment]
**proto**

```
import "google/protobuf/empty.proto";

service ProjectService {
  rpc GetProjects(google.protobuf.Empty) returns (stream Project) {
  }
}

message Project {
  int64 id = 1;
  string name = 2;
}
```
**client**

```
ManagedChannel channel = ...
ProjectServiceGrpc.ProjectServiceStub stub = ProjectServiceGrpc.newStub(channel)
Empty request = Empty.newBuilder().build();
StreamObserver[Project] observer = ...
stub.getProject(request, observer);
```
