### ISSUE TITLE
Starting elasticsearch Error about log4j2: status logger logged an error before logging was configured when add agent setting

### ISSUE THREAD

**Issue by by-xu** [apache/skywalking#3160]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I added agentpath in jvm.options of elasticsearch when I start elasticsearch,then I got error like this
___
### Bug
- Which version of SkyWalking, OS and JRE?

system suse12sp3
skywalking 6.2.0
elasticsearch6.7.1
JRE openjdk version "1.8.0_131"

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

/TIVOLI/elastic/elasticsearch-6.5.1$DEBUG 2019-07-22 17:01:25:666 main AgentPackagePath :  The beacon class location is jar:file:/data/skywalking-agent/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class. 
INFO 2019-07-22 17:01:25:671 main SnifferConfigInitializer :  Config file found in /data/skywalking-agent/config/agent.config. 
2019-07-22 17:01:28,567 SkywalkingAgent-1-GRPCChannelManager-0 ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2 
Exception in thread "main" java.lang.IllegalStateException: status logger logged an error before logging was configured 
        at org.elasticsearch.common.logging.LogConfigurator.checkErrorListener(LogConfigurator.java:149) 
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122) 
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:302) 
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) 
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) 
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) 
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) 
        at org.elasticsearch.cli.Command.main(Command.java:90) 
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) 
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) 
Refer to the log for complete error details. 
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

I find an old problem suggest to deal this problem by add
-Djava.ext.path=
then I get problem like this

2019-07-23 15:25:14,016 SkywalkingAgent-1-GRPCChannelManager-0 ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2 
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA512 SecretKeyFactory not available 
Likely root cause: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA512 SecretKeyFactory not available 
        at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122) 
        at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160) 
        at org.elasticsearch.common.settings.KeyStoreWrapper.createCipher(KeyStoreWrapper.java:296) 
        at org.elasticsearch.common.settings.KeyStoreWrapper.decrypt(KeyStoreWrapper.java:345) 
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:241) 
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:295) 
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) 
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) 
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) 
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) 
        at org.elasticsearch.cli.Command.main(Command.java:90) 
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) 
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) 
Refer to the log for complete error details. 

my collector and webui is working without problem and I can also see other services on it

**Comment by wu-sheng** [comment]
I don't think you should add SkyWalking agent to ElasticSearch server side. SkyWalking is APM system, designed for business applications, web service, rpc service provider/consumer.

There is a lot of dark magic, including code manipulation tech.

This error from the text, shows, the elastic search doesn't allow gRPC startup because of log conflictions :) My suggestion is, just don't do this.
