### ISSUE TITLE
elk7.2  sky start error

### ISSUE THREAD

**Issue by qianglu1989** [apache/skywalking#3187]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion

___
### Question
 {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]"}},"status":400}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:140) ~[library-client-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:86) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:99) ~[storage-elasticsearch-plugin-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.2.0.jar:6.2.0]
		at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.2.0.jar:6.2.0]
	Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://10.0.254.33:9200], URI [/skywalking620_endpoint_inventory?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]"}},"status":400}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [type : {type={properties={sequence={type=integer}, heartbeat_time={type=long}, service_id={type=integer}, name={copy_to=name_match, type=keyword}, detect_point={type=integer}, name_match={analyzer=oap_analyzer, type=text}, register_time={type=long}}}}]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:510) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:421) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:451) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:617) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[elasticsearch-6.3.2.jar:6.3.2]
	... 12 more

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___

**Comment by kezhenxu94** [comment]
Read the docs for supported elasticsearch versions, we don't support elasticsearch 7.2 yet

**Comment by 1346735074** [comment]
Yes, this only supports 6.3.2-6.8.2, not 7.0
