### ISSUE TITLE
ScopeDefine name = All not found

### ISSUE THREAD

**Issue by Stephen-sen** [apache/skywalking#3258]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
when i upgrade skywalking to 6.3 ,when I start oapserver I have this error

2019-08-13 20:24:33,086 - org.apache.curator.framework.state.ConnectionStateManager - 71 [main-EventThread] INFO  [] - State change: CONNECTED
2019-08-13 20:24:33,129 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 71 [main] INFO  [] - Prepare the default provider in core module.
2019-08-13 20:24:33,371 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 71 [main] ERROR [] - ScopeDefine name = All not found.
org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine name = All not found.
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:95) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]
Caused by: org.apache.skywalking.oap.server.core.UnexpectedException: ScopeDefine name = All not found.
	at org.apache.skywalking.oap.server.core.source.DefaultScopeDefine.valueOf(DefaultScopeDefine.java:127) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.parser.OALListener.enterSource(OALListener.java:52) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.grammar.OALParser$SourceContext.enterRule(OALParser.java:605) ~[oal-grammar-6.3.0.jar:6.3.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:61) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:159) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:93) ~[server-core-6.3.0.jar:6.3.0]
	... 3 more

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Not sure what is happening. The class w/ annotation is there.

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/62945488-646b8400-be11-11e9-9067-3567573ad3a0.png)

**Comment by wu-sheng** [comment]
Feedback, this is caused by JDK 11. We don't support that.

**Comment by 18965824402** [comment]
> 反馈，这是由JDK 11引起的。我们不支持这一点。

我也遇到同样的问题  那6.3版本需要什么版本的jdk

**Comment by ty1207** [comment]
> > 反馈，这是由JDK 11引起的。我们不支持这一点。
> 
> 我也遇到同样的问题 那6.3版本需要什么版本的jdk

很奇怪，我在idc环境的jdk11下可以运行，但是阿里云环境的jdk下无法运行，同样报错

**Comment by liangxp** [comment]
JDK8 也是一样的问题，不知道具体原因，求解

**Comment by hello-zhengzq** [comment]
not only caused by JDK11, but also caused by JDK8, i try version 6.3 and 6.4, same error happened.

**Comment by kezhenxu94** [comment]
> not only caused by JDK11, but also caused by JDK8, i try version 6.3 and 6.4, same error happened.

JDK8 is the recommended version for our OAP backend, and we run the e2e test in every PR and the tests results show that it works well in JDK8, did you really got the exactly same exception? Can you provide more details?

**Comment by hello-zhengzq** [comment]
> > not only caused by JDK11, but also caused by JDK8, i try version 6.3 and 6.4, same error happened.
> 
> @hello-zhengzq JDK8 is the recommended version for our OAP backend, and we run the e2e test in every PR and the tests results show that it works well in JDK8, did you really got the exactly same exception? Can you provide more details?

hello, my environment：
macOS 10.12.6
java version "1.8.0_221"

i used refer to some urls like [https://blog.csdn.net/zhangningkid/article/details/100517587](url)

1. i installed elasticsearch6.5 in docker and visit http://localhost:9200/ to confirm it run well.
2. i configed the elasticsearch part in application.yml as follow:
```
storage:
  elasticsearch:
    nameSpace: ${SW_NAMESPACE:"docker-cluster"}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
```

3. then i ran startup.sh and got webapp startup well, but oapserver started failed, the error log as follow:
```
2019-10-07 11:25:13,626 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
2019-10-07 11:25:13,720 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the standalone provider in cluster module.
2019-10-07 11:25:13,721 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the default provider in core module.
2019-10-07 11:25:14,335 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - ScopeDefine name = All not found.
org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine name = All not found.
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:95) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]
Caused by: org.apache.skywalking.oap.server.core.UnexpectedException: ScopeDefine name = All not found.
	at org.apache.skywalking.oap.server.core.source.DefaultScopeDefine.valueOf(DefaultScopeDefine.java:127) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.parser.OALListener.enterSource(OALListener.java:52) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.grammar.OALParser$SourceContext.enterRule(OALParser.java:605) ~[oal-grammar-6.3.0.jar:6.3.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:61) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:159) ~[oal-rt-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:93) ~[server-core-6.3.0.jar:6.3.0]
	... 3 more
```

**Comment by kezhenxu94** [comment]
> > > not only caused by JDK11, but also caused by JDK8, i try version 6.3 and 6.4, same error happened.
> > 
> > 
> > @hello-zhengzq JDK8 is the recommended version for our OAP backend, and we run the e2e test in every PR and the tests results show that it works well in JDK8, did you really got the exactly same exception? Can you provide more details?
> 
> hello, my environment：
> macOS 10.12.6
> java version "1.8.0_221"
> 
> i used skywalking refering to some urls like [https://blog.csdn.net/zhangningkid/article/details/100517587](url)
> 
> 1. i installed elasticsearch6.5 in docker and visit http://localhost:9200/ to confirm it run well.
> 2. i configed the elasticsearch part in application.yml as follow:
> 
> ```
> storage:
>   elasticsearch:
>     nameSpace: ${SW_NAMESPACE:"docker-cluster"}
>     clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
> ```
> 
> 1. then i ran startup.sh and got webapp startup well, but oapserver started failed, the error log as follow:
> 
> ```
> 2019-10-07 11:25:13,626 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
> 2019-10-07 11:25:13,720 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the standalone provider in cluster module.
> 2019-10-07 11:25:13,721 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the default provider in core module.
> 2019-10-07 11:25:14,335 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - ScopeDefine name = All not found.
> org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine name = All not found.
> 	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:95) ~[server-core-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]
> Caused by: org.apache.skywalking.oap.server.core.UnexpectedException: ScopeDefine name = All not found.
> 	at org.apache.skywalking.oap.server.core.source.DefaultScopeDefine.valueOf(DefaultScopeDefine.java:127) ~[server-core-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oal.rt.parser.OALListener.enterSource(OALListener.java:52) ~[oal-rt-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oal.rt.grammar.OALParser$SourceContext.enterRule(OALParser.java:605) ~[oal-grammar-6.3.0.jar:6.3.0]
> 	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> 	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:61) ~[oal-rt-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:159) ~[oal-rt-6.3.0.jar:6.3.0]
> 	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:93) ~[server-core-6.3.0.jar:6.3.0]
> 	... 3 more
> ```
> 
> i first used version6.4.0 and got the same error, then i tried version6.3.0, it also not worked, so the above log is about the version6.3.0.

Can you try to upgrade the Guava version and try again? The current guava version should be under 23, you can download the 23-jre version (.jar) from mvnrepository.org and replace the existed guava.jar in oap-libs, I doubt that it's some bug in old guava version, please let me know whether it works or not, thanks

**Comment by wu-sheng** [comment]
I think we never release skywalking under latest guava. @hello-zhengzq, you need to package the master branch by yourself.

**Comment by kezhenxu94** [comment]
Hi @Stephen-sen  @18965824402 @liangxp @hello-zhengzq , I think I found the reason, there're two reasons why it won't work:

- JDK8: There're special characters in the full path of the OAP folder, may be Chinese character (I reproduce this)
- JDK11: The compatibilities of Guava version, we have upgraded to 23-jre to solve this problem

@wu-sheng I think we should mention this (special characters in OAP is not allowed) in the doc

**Comment by wu-sheng** [comment]
@kezhenxu94 Feel free to update this in the document.

**Comment by hello-zhengzq** [comment]
> > > > not only caused by JDK11, but also caused by JDK8, i try version 6.3 and 6.4, same error happened.
> > > 
> > > 
> > > @hello-zhengzq JDK8 is the recommended version for our OAP backend, and we run the e2e test in every PR and the tests results show that it works well in JDK8, did you really got the exactly same exception? Can you provide more details?
> > 
> > 
> > hello, my environment：
> > macOS 10.12.6
> > java version "1.8.0_221"
> > i used skywalking refering to some urls like [https://blog.csdn.net/zhangningkid/article/details/100517587](url)
> > 
> > 1. i installed elasticsearch6.5 in docker and visit http://localhost:9200/ to confirm it run well.
> > 2. i configed the elasticsearch part in application.yml as follow:
> > 
> > ```
> > storage:
> >   elasticsearch:
> >     nameSpace: ${SW_NAMESPACE:"docker-cluster"}
> >     clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
> > ```
> > 
> > 
> > 
> > 1. then i ran startup.sh and got webapp startup well, but oapserver started failed, the error log as follow:
> > 
> > ```
> > 2019-10-07 11:25:13,626 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
> > 2019-10-07 11:25:13,720 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the standalone provider in cluster module.
> > 2019-10-07 11:25:13,721 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the default provider in core module.
> > 2019-10-07 11:25:14,335 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - ScopeDefine name = All not found.
> > org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine name = All not found.
> > 	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:95) ~[server-core-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]
> > Caused by: org.apache.skywalking.oap.server.core.UnexpectedException: ScopeDefine name = All not found.
> > 	at org.apache.skywalking.oap.server.core.source.DefaultScopeDefine.valueOf(DefaultScopeDefine.java:127) ~[server-core-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oal.rt.parser.OALListener.enterSource(OALListener.java:52) ~[oal-rt-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oal.rt.grammar.OALParser$SourceContext.enterRule(OALParser.java:605) ~[oal-grammar-6.3.0.jar:6.3.0]
> > 	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> > 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> > 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> > 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> > 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
> > 	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:61) ~[oal-rt-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:159) ~[oal-rt-6.3.0.jar:6.3.0]
> > 	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:93) ~[server-core-6.3.0.jar:6.3.0]
> > 	... 3 more
> > ```
> > 
> > 
> > i first used version6.4.0 and got the same error, then i tried version6.3.0, it also not worked, so the above log is about the version6.3.0.
> 
> Can you try to upgrade the Guava version and try again? The current guava version should be under 23, you can download the 23-jre version (.jar) from mvnrepository.org and replace the existed guava.jar in oap-libs, I doubt that it's some bug in old guava version, please let me know whether it works or not, thanks

i replace version6.3's guava-20.0.jar to guava-23.0.jar, i works, great!!

**Comment by hello-zhengzq** [comment]
> Hi @Stephen-sen @18965824402 @liangxp @hello-zhengzq , I think I found the reason, there're two reasons why it won't work:
> 
>     * JDK8: There're special characters in the full path of the OAP folder, may be Chinese character (I reproduce this)
> 
>     * JDK11: The compatibilities of Guava version, we have upgraded to 23-jre to solve this problem #3541
> 
> 
> @wu-sheng I think we should mention this (special characters in OAP is not allowed) in the doc

it is indeed i place it in the full path which contains chinese character, i modify the path to a full english path and return to guava20, it works as well.

**Comment by wu-sheng** [comment]
> it is indeed i place it in the full path which contains chinese character, i modify the path to a full english path and return to guava20, it works as well.

Guava 23 is for JDK 11+
