### ISSUE TITLE
6.3.0

### ISSUE THREAD

**Issue by Dauber01** [apache/skywalking#3264]
i use the 6.1.0 before, at this morning，i update it to 6.3.0. and it with the exception of 
2019-08-14 12:15:40,060 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -14320 [DataCarrier.REGISTER_L1.BulkConsumePool.2.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
2019-08-14 12:15:45,066 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -19326 [DataCarrier.REGISTER_L1.BulkConsumePool.2.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
2019-08-14 12:15:50,068 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -24328 [DataCarrier.REGISTER_L1.BulkConsumePool.2.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
so what is happend ,and what should i do to resove it

**Comment by wu-sheng** [comment]
I don't know what you did. Do you upgrade from old version or something?

**Comment by Dauber01** [comment]
yes,i use the image in docker hub ,and run is ,and in version 6.1.0 ,there is no exception in it ,when i used the 6.3.0. it faild and the run commod is like this.
sudo docker run -e TZ="Asia/Shanghai"  --name apche-oap-node1 --restart always -d -p 12800:12800 -p 11800:11800 -e SW_STORAGE=elasticsearch -e SW_STORAGE_ES_CLUSTER_NODES=ip:port,ip:port,ip:port -e SW_NAMESPACE=skywalking -e SW_STORAGE_ES_BULK_ACTIONS=2000 -e SW_STORAGE_ES_BULK_SIZE=20 -e SW_STORAGE_ES_FLUSH_INTERVAL=10 -e SW_STORAGE_ES_CONCURRENT_REQUESTS=2 -e SW_STORAGE_ES_QUERY_MAX_SIZE=5000 -e SW_STORAGE_ES_QUERY_SEGMENT_SIZE=200 -e SW_CLUSTER=nacos -e SW_SERVICE_NAME=SkyWalking_OAP_Cluster -e SW_CLUSTER_NACOS_HOST_PORT=ip:port,ip:port,ip:port apache/skywalking-oap-server

**Comment by wu-sheng** [comment]
In this kind of upgrade, unless you have followed our changes(known our storage changes), you need to
1. Stop all agents.
1. Stop OAPs, and erase ES all indexes.
1. Clear the OAP buffers
1. Reboot everything back online.

**Comment by Dauber01** [comment]
i just try the 6.2.0 version ,it doesn't has the exception .did you have change the storage format at 6.3.0?

**Comment by wu-sheng** [comment]
In 6.2.0, it changed too. Read the changes log in the root folder. No exception doesn't mean it works as expected.

**Comment by Dauber01** [comment]
thank you for your answer
