### ISSUE TITLE
The topology map cannot be displayed after starting for a while

### ISSUE THREAD

**Issue by shook2012** [apache/skywalking#3277]
- Why do you submit this issue?
- [ ] Bug

### Bug
version:6.3.0
Jdk: 1.8.131
os:centos 6.8

- What happen?
The topology map cannot be displayed after starting for a while

2019-08-16 14:32:42,787 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 292 [pool-16-thread-1] INFO  [] - Synchronous bulk took time: 3429 millis, size: 648
2019-08-16 14:32:44,115 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 311 [I/O dispatcher 3] INFO  [] - Bulk execution id [7782] completed in 52 milliseconds, size: 40
2019-08-16 14:32:45,552 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 112 [DataCarrier.REGISTER_L2.BulkConsumePool.0.Thread] ERROR [] - Elasticsearch exception [type=es_rejected_execution_exception, reason=rejected execution of processing of [19302869][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[skywalkingapm_service_inventory][1]] containing [index {[skywalkingapm_service_inventory][type][appcloud-app_0_0], source[{"sequence":12,"last_update_time":1565585596332,"heartbeat_time":1565937176591,"node_type":0,"name":"appcloud-app","address_id":0,"is_address":0,"mapping_service_id":0,"register_time":1565585596332,"properties":"{}"}]}] and a refresh, target allocation id: PbT1YNTuQFOiva22tUafjw, primary term: 3 on EsThreadPoolExecutor[name = es_3/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@3076e97[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 5720877]]]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=es_rejected_execution_exception, reason=rejected execution of processing of [19302869][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[skywalkingapm_service_inventory][1]] containing [index {[skywalkingapm_service_inventory][type][appcloud-app_0_0], source[{"sequence":12,"last_update_time":1565585596332,"heartbeat_time":1565937176591,"node_type":0,"name":"appcloud-app","address_id":0,"is_address":0,"mapping_service_id":0,"register_time":1565585596332,"properties":"{}"}]}] and a refresh, target allocation id: PbT1YNTuQFOiva22tUafjw, primary term: 3 on EsThreadPoolExecutor[name = es_3/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@3076e97[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 5720877]]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:366) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.forceUpdate(ElasticSearchClient.java:254) ~[library-client-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.forceUpdate(RegisterEsDAO.java:56) ~[storage-elasticsearch-plugin-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:89) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_131]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:84) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:35) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:141) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.20.161:9200], URI [/skywalkingapm_service_inventory/type/appcloud-app_0_0/_update?refresh=true&timeout=1m], status line [HTTP/1.1 429 Too Many Requests]
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[es_3][192.168.20.163:9300][indices:data/write/update[s]]"}],"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [19302869][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[skywalkingapm_service_inventory][1]] containing [index {[skywalkingapm_service_inventory][type][appcloud-app_0_0], source[{\"sequence\":12,\"last_update_time\":1565585596332,\"heartbeat_time\":1565937176591,\"node_type\":0,\"name\":\"appcloud-app\",\"address_id\":0,\"is_address\":0,\"mapping_service_id\":0,\"register_time\":1565585596332,\"properties\":\"{}\"}]}] and a refresh, target allocation id: PbT1YNTuQFOiva22tUafjw, primary term: 3 on EsThreadPoolExecutor[name = es_3/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@3076e97[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 5720877]]"},"status":429}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:366) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.forceUpdate(ElasticSearchClient.java:254) ~[library-client-6.3.0.jar:6.3.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.forceUpdate(RegisterEsDAO.java:56) ~[storage-elasticsearch-plugin-6.3.0.jar:6.3.0]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:89) ~[server-core-6.3.0.jar:6.3.0]
		at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_131]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:84) [server-core-6.3.0.jar:6.3.0]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:35) [server-core-6.3.0.jar:6.3.0]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:141) [server-core-6.3.0.jar:6.3.0]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
	Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.20.161:9200], URI [/skywalkingapm_service_inventory/type/appcloud-app_0_0/_update?refresh=true&timeout=1m], status line [HTTP/1.1 429 Too Many Requests]
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[es_3][192.168.20.163:9300][indices:data/write/update[s]]"}],"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [19302869][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[skywalkingapm_service_inventory][1]] containing [index {[skywalkingapm_service_inventory][type][appcloud-app_0_0], source[{\"sequence\":12,\"last_update_time\":1565585596332,\"heartbeat_time\":1565937176591,\"node_type\":0,\"name\":\"appcloud-app\",\"address_id\":0,\"is_address\":0,\"mapping_service_id\":0,\"register_time\":1565585596332,\"properties\":\"{}\"}]}] and a refresh, target allocation id: PbT1YNTuQFOiva22tUafjw, primary term: 3 on EsThreadPoolExecutor[name = es_3/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@3076e97[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 5720877]]"},"status":429}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]

**Comment by wu-sheng** [comment]
Check Elasticsearch storage document, there are some ElasticSearch settings suggestions. And please make sure your ES cluster is powerful enough.
