### ISSUE TITLE
backend can not update from 6.2.0 to 6.3.0

### ISSUE THREAD

**Issue by lmzhizhe** [apache/skywalking#3325]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion
___
### Question
- What do you want to know?
can not upgrade
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2.0  centos7.4 java8
- Which company or project?
vivo
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
get  this error when I update backend from 6.2.0 to 6.3.0 

``2019-08-26 11:12:07,574 - org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler - 107 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:96) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:86) [server-core-6.3.0.jar:6.3.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-08-26 11:12:07,574 - org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler - 107 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:96) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:86) [server-core-6.3.0.jar:6.3.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-08-26 11:12:07,575 - org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler - 107 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:96) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:86) [server-core-6.3.0.jar:6.3.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-08-26 11:12:07,575 - org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler - 107 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:96) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.remote.RemoteServiceHandler$1.onNext(RemoteServiceHandler.java:86) [server-core-6.3.0.jar:6.3.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
``
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Internal communication protocol has been changed, you need to change backend to 6.3 at one time.
