### ISSUE TITLE
oap Null startup error

### ISSUE THREAD

**Issue by 1346735074** [apache/skywalking#3355]
```
2019-08-28 10:07:56,364 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.lock.RegisterLockInstaller -25511 [main] INFO  [] - table: register_lock does not exist
2019-08-28 10:07:56,513 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -25660 [main] INFO  [] - start the provider default in istio-telemetry module.
2019-08-28 10:07:56,518 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -25665 [main] INFO  [] - start the provider default in receiver-jvm module.
2019-08-28 10:07:56,525 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -25672 [main] INFO  [] - start the provider default in receiver-register module.
2019-08-28 10:07:56,773 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer -25920 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-08-28 10:07:56,776 - org.eclipse.jetty.server.Server -25923 [main] INFO  [] - jetty-9.4.2.v20170220
2019-08-28 10:07:56,816 - org.eclipse.jetty.server.handler.ContextHandler -25963 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@566f1852{/,null,AVAILABLE}
2019-08-28 10:07:56,826 - org.eclipse.jetty.server.AbstractConnector -25973 [main] INFO  [] - Started ServerConnector@9b23822{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-08-28 10:07:56,826 - org.eclipse.jetty.server.Server -25973 [main] INFO  [] - Started @26037ms
2019-08-28 10:07:57,132 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer -26279 [main] INFO  [] - persistence timer start
2019-08-28 10:07:57,135 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer -26282 [main] INFO  [] - Cache update timer start
2019-08-28 10:07:58,975 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager -28122 [pool-4-thread-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.client.Address.equals(Address.java:52) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.HashMap.putVal(HashMap.java:635) ~[?:1.8.0_181]
	at java.util.HashMap.put(HashMap.java:612) ~[?:1.8.0_181]
	at java.util.HashSet.add(HashSet.java:220) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.lambda$distinct$2(RemoteClientManager.java:138) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.distinct(RemoteClientManager.java:137) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:92) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2019-08-28 10:08:03,975 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager -33122 [pool-4-thread-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.client.Address.equals(Address.java:52) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.HashMap.putVal(HashMap.java:635) ~[?:1.8.0_181]
	at java.util.HashMap.put(HashMap.java:612) ~[?:1.8.0_181]
	at java.util.HashSet.add(HashSet.java:220) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.lambda$distinct$2(RemoteClientManager.java:138) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.distinct(RemoteClientManager.java:137) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:92) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by 1346735074** [comment]
@wu-sheng Can you help me look over this problem

**Comment by wu-sheng** [comment]
Please try the latest release. This NPE is not known by me. It looks like someone set a null to hostname.
