### ISSUE TITLE
storage mysql no create table

### ISSUE THREAD

**Issue by mytimes** [apache/skywalking#3373]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  oapServiceInit.sh has beed execute，but only register_lock table be created
   what‘s  wrong？

__
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking 6.3
  openjdk version "1.8.0_191"
  OS  centos 6.8
  mysql 5.6

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
2019-08-28 23:50:04,142 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO - 84 [pool-13-thread-1] ERROR [] - Table 'sky.service_inventory' doesn't exist
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table 'sky.service_inventory' doesn't exist
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO.loadLastUpdate(H2ServiceInventoryCacheDAO.java:70) ~[storage-jdbc-hikaricp-plugin-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.updateServiceInventory(CacheUpdateTimer.java:63) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.update(CacheUpdateTimer.java:56) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.lambda$start$0(CacheUpdateTimer.java:48) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.3.0.jar:6.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.sql.SQLSyntaxErrorException: Table 'sky.service_inventory' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:142) ~[library-client-6.3.0.jar:6.3.0]
	... 12 more
2019-08-28 23:50:04,143 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2NetworkAddressInventoryCacheDAO - 77 [pool-13-thread-1] ERROR [] - Table 'sky.network_address_inventory' doesn't exist
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table 'sky.network_address_inventory' doesn't exist
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2NetworkAddressInventoryCacheDAO.loadLastUpdate(H2NetworkAddressInventoryCacheDAO.java:63) ~[storage-jdbc-hikaricp-plugin-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.updateNetAddressInventory(CacheUpdateTimer.java:83) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.update(CacheUpdateTimer.java:57) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.lambda$start$0(CacheUpdateTimer.java:48) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.3.0.jar:6.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.sql.SQLSyntaxErrorException: Table 'sky.network_address_inventory' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:142) ~[library-client-6.3.0.jar:6.3.0]
	... 12 more
2019-08-28 23:50:14,142 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO - 84 [pool-13-thread-1] ERROR [] - Table 'sky.service_inventory' doesn't exist
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table 'sky.service_inventory' doesn't exist
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ServiceInventoryCacheDAO.loadLastUpdate(H2ServiceInventoryCacheDAO.java:70) ~[storage-jdbc-hikaricp-plugin-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.updateServiceInventory(CacheUpdateTimer.java:63) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.update(CacheUpdateTimer.java:56) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.lambda$start$0(CacheUpdateTimer.java:48) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.3.0.jar:6.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.sql.SQLSyntaxErrorException: Table 'sky.service_inventory' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:142) ~[library-client-6.3.0.jar:6.3.0]
	... 12 more
2019-08-28 23:50:14,144 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2NetworkAddressInventoryCacheDAO - 77 [pool-13-thread-1] ERROR [] - Table 'sky.network_address_inventory' doesn't exist
org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Table 'sky.network_address_inventory' doesn't exist
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:151) ~[library-client-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2NetworkAddressInventoryCacheDAO.loadLastUpdate(H2NetworkAddressInventoryCacheDAO.java:63) ~[storage-jdbc-hikaricp-plugin-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.updateNetAddressInventory(CacheUpdateTimer.java:83) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.update(CacheUpdateTimer.java:57) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer.lambda$start$0(CacheUpdateTimer.java:48) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.3.0.jar:6.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.sql.SQLSyntaxErrorException: Table 'sky.network_address_inventory' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:142) ~[library-client-6.3.0.jar:6.3.0]
	... 12 more
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please check your startup logs, the table should be checked and auto-creating.

**Comment by mytimes** [comment]
only table register_lock be created ，this is log。

2019-08-16 14:01:03,189 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2RegisterLockInstaller - 56 [main] DEBUG [] - creating table:
CREATE TABLE IF NOT EXISTS register_lock (
id int PRIMARY KEY,
sequence int,
name VARCHAR(100)
)

2019-08-16 14:01:03,190 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 75 [main] DEBUG [] **- execute aql: CREATE TABLE IF NOT EXISTS register_lock (
id int PRIMARY KEY,
sequence int,
name VARCHAR(100)
)**

2019-08-16 14:01:03,196 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 121 [main] DEBUG [] - execute query with result: select 1 from register_lock where id = 14
2019-08-16 14:01:03,227 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 121 [main] DEBUG [] - execute query with result: select 1 from register_lock where id = 15
2019-08-16 14:01:03,228 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 121 [main] DEBUG [] - execute query with result: select 1 from register_lock where id = 16
2019-08-16 14:01:03,228 - org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient - 121 [main] DEBUG [] - execute query with result: select 1 from register_lock where id = 7
2019-08-16 14:01:03,229 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-sharing-server module.
2019-08-16 14:01:03,229 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in service-mesh module.
2019-08-16 14:01:03,238 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 71 [main] INFO  [] - Try to lock buffer directory, directory is: /usr/glm/skywalking/apache-skywalking-apm-bin/bin/../mesh-buffer
2019-08-16 14:01:03,239 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 84 [main] INFO  [] - Lock buffer directory successfully, directory is: /usr/glm/skywalking/apache-skywalking-apm-bin/bin/../mesh-buffer
2019-08-16 14:01:03,251 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 115 [main] INFO  [] - Bind handler MeshGRPCHandler into gRPC server 0.0.0.0:11800
2019-08-16 14:01:03,254 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-register module.
2019-08-16 14:01:03,254 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 115 [main] INFO  [] - Bind handler ApplicationRegisterHandler into gRPC server 0.0.0.0:11800
2019-08-16 14:01:03,259 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 115 [main] INFO  [] - Bind handler InstanceDiscoveryServiceHandler into gRPC server 0.0.0.0:1180

2019-08-16 14:01:03,423 - io.netty.util.internal.CleanerJava6 - 71 [main] DEBUG [] - java.nio.ByteBuffer.cleaner(): available
2019-08-16 14:01:03,429 - io.netty.util.internal.PlatformDependent - 71 [main] DEBUG [] - org.jctools-core.MpscChunkedArrayQueue: available
2019-08-16 14:01:03,453 - io.netty.channel.DefaultChannelId - 76 [main] DEBUG [] - -Dio.netty.processId: 23248 (auto-detected)
2019-08-16 14:01:03,455 - io.netty.util.NetUtil - 76 [main] DEBUG [] - -Djava.net.preferIPv4Stack: false
2019-08-16 14:01:03,456 - io.netty.util.NetUtil - 76 [main] DEBUG [] - -Djava.net.preferIPv6Addresses: false
2019-08-16 14:01:03,457 - io.netty.util.NetUtil - 86 [main] DEBUG [] - Loopback interface: lo (lo, 127.0.0.1)
2019-08-16 14:01:03,458 - io.netty.util.NetUtil - 81 [main] DEBUG [] - /proc/sys/net/core/somaxconn: 128
2019-08-16 14:01:03,459 - io.netty.channel.DefaultChannelId - 76 [main] DEBUG [] - -Dio.netty.machineId: 00:16:3e:ff:fe:0c:bc:55 (auto-detected)
2019-08-16 14:01:03,466 - io.netty.util.internal.InternalThreadLocalMap - 76 [main] DEBUG [] - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
2019-08-16 14:01:03,466 - io.netty.util.internal.InternalThreadLocalMap - 76 [main] DEBUG [] - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
2019-08-16 14:01:03,477 - io.netty.util.ResourceLeakDetector - 81 [main] DEBUG [] - -Dio.netty.leakDetection.level: simple
2019-08-16 14:01:03,477 - io.netty.util.ResourceLeakDetector - 81 [main] DEBUG [] - -Dio.netty.leakDetection.targetRecords: 4
2019-08-16 14:01:03,511 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.numHeapArenas: 4
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.numDirectArenas: 4
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.pageSize: 8192
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.maxOrder: 11
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.chunkSize: 16777216
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.tinyCacheSize: 512
2019-08-16 14:01:03,512 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.smallCacheSize: 256
2019-08-16 14:01:03,513 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.normalCacheSize: 64
2019-08-16 14:01:03,513 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2019-08-16 14:01:03,513 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.cacheTrimInterval: 8192
2019-08-16 14:01:03,513 - io.netty.buffer.PooledByteBufAllocator - 76 [main] DEBUG [] - -Dio.netty.allocator.useCacheForAllThreads: true
2019-08-16 14:01:03,523 - io.netty.buffer.ByteBufUtil - 76 [main] DEBUG [] - -Dio.netty.allocator.type: pooled
2019-08-16 14:01:03,523 - io.netty.buffer.ByteBufUtil - 76 [main] DEBUG [] - -Dio.netty.threadLocalDirectBufferSize: 0
2019-08-16 14:01:03,523 - io.netty.buffer.ByteBufUtil - 76 [main] DEBUG [] - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/graphql] register by org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler-61a2aeb7
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/application/register] register by org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.ApplicationRegisterServletHandler-7f642bf
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/instance/register] register by org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.InstanceDiscoveryServletHandler-43e3a390
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/instance/heartbeat] register by org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.InstanceHeartBeatServletHandler-44aa91e2
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/networkAddress/register] register by org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.NetworkAddressRegisterServletHandler-50dc49e1
2019-08-16 14:01:03,540 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/servicename/discovery] register by org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.ServiceNameDiscoveryServiceHandler-650a1aff
2019-08-16 14:01:03,541 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 98 [main] DEBUG [] - jetty servlet mappings: [/segments] register by org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.rest.TraceSegmentServletHandler-3e151e1f
2019-08-16 14:01:03,544 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-08-16 14:01:03,583 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@7e5e6573{/,null,AVAILABLE}
2019-08-16 14:01:03,597 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@44eb2452{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-08-16 14:01:03,597 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @9042ms
2019-08-16 14:01:03,600 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 54 [main] INFO  [] - persistence timer start
2019-08-16 14:01:03,603 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 42 [main] INFO  [] - Cache updateServiceInventory timer start
**2019-08-16 14:01:03,605 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 51 [main] INFO  [] - OAP starts up in init mode successfully, exit now..**

**Comment by mytimes** [comment]
@wu-sheng  only table register_lock  be created. why?
