### ISSUE TITLE
envoy grpc stream problem 

### ISSUE THREAD

**Issue by artemsre** [apache/skywalking#3380]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
skywalking server can't collect envoy grpc stream 

- SkyWalking 6.3 and 6.2 ,CentOS and 
$ java -version 
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

I use simple config https://github.com/apache/skywalking/blob/master/docs/en/setup/envoy/config.yaml

Change port to 11800 and socket address 

Skywalking  oam logs

`Aug 30, 2019 10:33:07 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@495691be
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
        at org.apache.skywalking.oap.server.receiver.envoy.MetricServiceGRPCHandler$1.onError(MetricServiceGRPCHandler.java:168)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

`

skywalking-oap-server.log
`
2019-08-30 10:33:07,006 - org.apache.skywalking.oap.server.receiver.envoy.MetricServiceGRPCHandler - 167 [grpc-default-executor-3] ERROR [] - Error in rec
eiving metrics from envoy
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

`

Envoy side:
`[2019-08-30 14:38:45.854][10807026][debug][router] [external/envoy/source/common/router/router.cc:514] [C0][S2601321041541453695] router decoding headers:
':method', 'POST'
':path', '/envoy.service.metrics.v2.MetricsService/StreamMetrics'
':authority', 'service_skywalking'
':scheme', 'http'
'te', 'trailers'
'content-type', 'application/grpc'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.128.36.180'
[2019-08-30 14:38:45.854][10807026][debug][client] [external/envoy/source/common/http/codec_client.cc:26] [C4] connecting
[2019-08-30 14:38:45.854][10807026][debug][connection] [external/envoy/source/common/network/connection_impl.cc:702] [C4] connecting to 10.144.194.52:11800
[2019-08-30 14:38:45.854][10807026][debug][connection] [external/envoy/source/common/network/connection_impl.cc:711] [C4] connection in progress
[2019-08-30 14:38:45.854][10807026][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:726] [C4] setting stream-level initial window size to 268435456
[2019-08-30 14:38:45.854][10807026][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:748] [C4] updating connection-level initial window size to 268435456
[2019-08-30 14:38:45.854][10807026][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
[2019-08-30 14:38:45.887][10807026][debug][connection] [external/envoy/source/common/network/connection_impl.cc:559] [C4] delayed connection error: 61
[2019-08-30 14:38:45.887][10807026][debug][connection] [external/envoy/source/common/network/connection_impl.cc:188] [C4] closing socket: 0
[2019-08-30 14:38:45.887][10807026][debug][client] [external/envoy/source/common/http/codec_client.cc:82] [C4] disconnect. resetting 0 pending requests
[2019-08-30 14:38:45.887][10807026][debug][pool] [external/envoy/source/common/http/http2/conn_pool.cc:149] [C4] client disconnected
[2019-08-30 14:38:45.887][10807026][debug][router] [external/envoy/source/common/router/router.cc:868] [C0][S2601321041541453695] upstream reset: reset reason connection failure
[2019-08-30 14:38:45.887][10807026][debug][http] [external/envoy/source/common/http/async_client_impl.cc:91] async http request response headers (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'`

Where is my mistake? May be wrong java version?

**Comment by wu-sheng** [comment]
Do you just send metrics service to SkyWalking?

**Comment by artemsre** [comment]
I used config from https://github.com/apache/skywalking/blob/master/docs/en/setup/envoy/config.yaml 

No any other metric components configured. Just envoy stat_sink cluster.

**Comment by wu-sheng** [comment]
@dio Do you know what is this error?

**Comment by wu-sheng** [comment]
@artemsre I am pinging to Envoy maintainer to give some suggestions. Could you verify whether the metrics send? I tested this, it worked.

**Comment by wu-sheng** [comment]
@artemsre Document is improved, I will merge the PR after CI passed.
