### ISSUE TITLE
Elasticsearch exception [type=index_not_found_exception, reason=no such index]

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3395]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
 Hello, report a BUG, but I'm not sure if there's a problem with the runtime environment. We've been using elasticsearch for storage and skywalking.We found that after a long run, skywalking oap reported an index_not_found exception, and skywalking UI was no longer able to display anything.After restarting oap, you can return to normal, and then, after a while, the same failure occurs again.Who can help analyze some of the most likely causes?

<img width="922" alt="Snipaste_2019-09-02_11-53-11" src="https://user-images.githubusercontent.com/52440226/64140043-a6e31800-ce35-11e9-85e7-cf686e2376b0.png">

elasticsearch 的配置如下：
![image](https://user-images.githubusercontent.com/52440226/64140124-ec9fe080-ce35-11e9-8692-2a6c849a01ad.png)

**Comment by wu-sheng** [comment]
As far as I known, no one is facing this in committer team. I think you have to do some research on es about why. This is an es error.

**Comment by webb2019** [comment]
> As far as I known, no one is facing this in committer team. I think you have to do some research on es about why. This is an es error.

After several days of observation, this ES "index_not_found exception" occurs approximately every morning (1:00 am).
 I found the issue #3214 mention this problem that I encountered.
mybe this is not a bug. just config wrong.
In the skywalking document says that:
![image](https://user-images.githubusercontent.com/52440226/64306582-dde83380-cfc5-11e9-88f1-c67222eeb268.png)
I guess, skywalking did not create a new index the next day as the documentation mentioned.
I would like to ask skywalking whether it requires elasticsearch as storage to explicitly support automatic index creation that action.auto_create_index: true 
I neet help ,thanks

**Comment by wu-sheng** [comment]
Skywalking creates index template, new index created driven by data. So, if template is there, it should create automatically.

**Comment by webb2019** [comment]
> Skywalking creates index template, new index created driven by data. So, if template is there, it should create automatically.

I checked that the index templates was still there, and the next day, the new index  was actually created that index id is , but I wasn't sure if all the indexes were created successfully,  And keep error output log
![image](https://user-images.githubusercontent.com/52440226/64421030-30fbdc80-d0d3-11e9-88e6-292e1a26ee59.png)

![image](https://user-images.githubusercontent.com/52440226/64421102-63a5d500-d0d3-11e9-9fcf-a90bd20f59fb.png)

Can you help analyze where the problem is most likely to be

**Comment by wu-sheng** [comment]
I don't know what happens at your sides, all users are using this, not clear only you showing the error. Sorry. But also, we don't use a local(powerless) es to generate several days data.

**Comment by webb2019** [comment]
您好，这个问题太痛了，每次重启skywalking oap就可以了，然后运行一天都没事，过了晚上12点，就不行了，然后又重启oap ，可能不是本地部暑ES不够强大，扛不住。会不会是oap cache与es出现了事务一致性的问题，重启之后就相当于重新load了。



Webb


------------------ Original ------------------

**Comment by yab119074412** [comment]
I have met the same problem too, and it has troubled me several days.

**Comment by jdzgd** [comment]
I have met the same problem too

**Comment by wu-sheng** [comment]
@jdzgd This issue has closed. Nothing to update.

**Comment by lianghuiyuan** [comment]
我遇到了同样的问题，每天晚上12点之后 oap 就不再收到数据：

OAP logs:
```
$ kubectl logs -f skywalking-skywalking-oap-db86c5bf6-tctfk -n monitoring
2020-04-24 08:48:52,277 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker -8453500 [pool-6-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
        at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:118) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:72) ~[server-alarm-plugin-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:195) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_181]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:195) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:184) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:143) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:108) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:99) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:93) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:71) ~[server-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by wu-sheng** [comment]
@lianghuiyuan English only. Your question has nothing related to this topic.

**Comment by lianghuiyuan** [comment]
OK, Thanks! I mean I meet the same case as @webb2019 : 
> `每次重启skywalking oap就可以了，然后运行一天都没事，过了晚上12点，就不行了，然后又重启oap `

the oap error logs is above. Every day after 24:00 the skywalking-ui show no data, if restart skywalking, skywalking-ui goes back to show data OK.

**Comment by wu-sheng** [comment]
Enhance your ES cluster, every 2400, we begin to delete expired indexes

**Comment by gengmengong** [comment]
I have met the same problem too.

OAP logs:
`2020-08-26 23:09:09,522 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker -43856557 [pool-6-thread-1] ERROR [] - Elasticsearch exception [type=index_not_found_exception, reason=no such index [service_instance_relation_client_side]]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [service_instance_relation_client_side]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.ids(ElasticSearch7Client.java:201) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.dao.MetricsEs7DAO.multiGet(MetricsEs7DAO.java:40) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.loadFromStorage(MetricsPersistentWorker.java:206) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:146) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:132) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.0.1.jar:8.0.1]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.0.1.jar:8.0.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch-master:9200], URI [/service_instance_relation_client_side/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [service_instance_relation_client_side]","resource.type":"index_or_alias","resource.id":"service_instance_relation_client_side","index_uuid":"_na_","index":"service_instance_relation_client_side"}],"type":"index_not_found_exception","reason":"no such index [service_instance_relation_client_side]","resource.type":"index_or_alias","resource.id":"service_instance_relation_client_side","index_uuid":"_na_","index":"service_instance_relation_client_side"},"status":404}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.ids(ElasticSearch7Client.java:201) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.dao.MetricsEs7DAO.multiGet(MetricsEs7DAO.java:40) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.loadFromStorage(MetricsPersistentWorker.java:206) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:146) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:132) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.0.1.jar:8.0.1]
		at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.0.1.jar:8.0.1]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by gengmengong** [comment]
I have met the same problem too.
OAP logs:
```
2020-08-26 23:09:09,522 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker -43856557 [pool-6-thread-1] ERROR [] - Elasticsearch exception [type=index_not_found_exception, reason=no such index [service_instance_relation_client_side]]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [service_instance_relation_client_side]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.ids(ElasticSearch7Client.java:201) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.dao.MetricsEs7DAO.multiGet(MetricsEs7DAO.java:40) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.loadFromStorage(MetricsPersistentWorker.java:206) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:146) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:132) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.0.1.jar:8.0.1]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.0.1.jar:8.0.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch-master:9200], URI [/service_instance_relation_client_side/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [service_instance_relation_client_side]","resource.type":"index_or_alias","resource.id":"service_instance_relation_client_side","index_uuid":"_na_","index":"service_instance_relation_client_side"}],"type":"index_not_found_exception","reason":"no such index [service_instance_relation_client_side]","resource.type":"index_or_alias","resource.id":"service_instance_relation_client_side","index_uuid":"_na_","index":"service_instance_relation_client_side"},"status":404}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.ids(ElasticSearch7Client.java:201) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.dao.MetricsEs7DAO.multiGet(MetricsEs7DAO.java:40) ~[storage-elasticsearch7-plugin-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.loadFromStorage(MetricsPersistentWorker.java:206) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:146) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:132) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.0.1.jar:8.0.1]
		at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.0.1.jar:8.0.1]
		at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.0.1.jar:8.0.1]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by lnikolaou** [comment]
how can i contact you @webb2019 ?

**Comment by drightchao** [comment]
@webb2019  I got the same problem, how did you resolve it? Could you share some thoughts? thx a lot!

**Comment by drightchao** [comment]
It appears the solution is the config of action.auto_create_index of elasticsearch cluster settings. Set action.auto_create_index to "true" or skywalking's index namespace or pattern like "+skywalking*", no more index_not_found_exception happens.

**Comment by Jedore** [comment]
Got the same error.

**Comment by benchem** [comment]
Got the same error @ version 8.9.0

**Comment by think153** [comment]
Got the same error. @version 9.4.0

**Comment by EricLye** [comment]
the same error, annoying

**Comment by ruinmi** [comment]
> @lianghuiyuan English only. Your question has nothing related to this topic.

撇脚英语还要English only吗
