### ISSUE TITLE
More reasonable error output

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#3402]
Hi community
I knew we are familiar with the following errors. But they bother us and our users to find what's going on in oap internal.

Can we have a more proper method to improve it? Want to hear your voice, thanks.

```
ap-deployment-dcd587fb8-bqrlp oap java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
oap-deployment-dcd587fb8-bqrlp oap      at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
oap-deployment-dcd587fb8-bqrlp oap      at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.remote.selector.ForeverFirstSelector.select(ForeverFirstSelector.java:37) ~[server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:58) ~[server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:47) ~[server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:32) ~[server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:77) [server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:34) [server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:104) [server-core-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-6.1.0.7.jar:6.1.0.7]
oap-deployment-dcd587fb8-bqrlp oap      at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:49) [apm-datacarrier-6.1.0.7.jar:6.1.0.7]
```

**Comment by wu-sheng** [comment]
I am not sure why this happens, coordinator bug?

**Comment by hanahmily** [comment]
found a potential reason.
https://github.com/apache/skywalking/blob/06c357da6cf4b919afa7534fa6d9f5404d1d3dbe/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/RemoteSenderService.java#L56
`clientList` may be cleared by 
https://github.com/apache/skywalking/blob/06c357da6cf4b919afa7534fa6d9f5404d1d3dbe/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java#L223 

When `RemoteSenderService` gets `clientList` which may refer to `clientA`. Before clientList is accessed, clientA may be replaced by clientB and cleared by `RemoteClientManager`.

Dose this make any sense? @wu-sheng @peng-yongsheng

**Comment by wu-sheng** [comment]
In theory, it is possible. The error local could happen occasionally. This seems a tricky issue. Set up an optimize lock? Or?

**Comment by wu-sheng** [comment]
@hanahmily This has been fixed.
