### ISSUE TITLE
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by SummerOfServenteen** [apache/skywalking#3409]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
version of SkyWalking : from master,The last submission date is 2019.08.27.
besides i write an plugin about ons-client.When i update skyWalking agent and server from 6.1-release to this snapshot , The following exception occurred.
OS：Linux
JRE：1.8
env:online
- Which company or project?
I can't locate the problem right now.Could you please help me to check this problem?
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
ERROR 2019-09-04 11:11:30:780 grpc-default-executor-3 TraceSegmentServiceClient : Send UpstreamSegment to collector fail with a grpc internal exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:526)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

ERROR 2019-09-04 11:11:41:033 grpc-default-executor-3 TraceSegmentServiceClient : Send UpstreamSegment to collector fail with a grpc internal exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:526)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
___

**Comment by wu-sheng** [comment]
`DEADLINE_EXCEEDED` is a standard fail-safe mechanism, a.k.a. timeout, meaning your OAP server doesn't reply in time.

**Comment by liyongfa0311** [comment]
Why is there no link tracking on the UI after this error occurs in my service, only interacting with Eureka?

**Comment by liyongfa0311** [comment]
I also have no link display after restarting the service.

**Comment by SummerOfServenteen** [comment]
the OAP server  Exception.What may causes this error...
2019-09-04 23:29:18,490 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler - 64 [grpcServerPool-1-thread-28] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2019-09-04 23:29:18,490 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler - 64 [grpcServerPool-1-thread-27] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by wu-sheng** [comment]
@SummerOfServenteen Your above log just shows the agent disconnected.

**Comment by SummerOfServenteen** [comment]
@wu-sheng , i find that when I start up the agent, this happens with great probability.Then I checked  the thread status on the OAP server and found that "grpcServerPool-1-thread" was all BLOCKED.I guess there are deadlocks between threads.
OAP server1:
![image](https://user-images.githubusercontent.com/31895647/64683175-56af2a00-d4b5-11e9-9084-7aa0c6df3e4d.png)
OAP server2:
![image](https://user-images.githubusercontent.com/31895647/64683268-8a8a4f80-d4b5-11e9-9837-a58195084801.png)
[summer1.txt](https://github.com/apache/skywalking/files/3599900/summer1.txt)
[summer2.txt](https://github.com/apache/skywalking/files/3599903/summer2.txt)
May I trouble you to have a look?

**Comment by wu-sheng** [comment]
Bulk mechanism should have upgraded in 6.3.0, very different to 6.1 and 6.2

**Comment by SummerOfServenteen** [comment]
But I‘m useing the 6.5 snapshot both agent and server right now...

**Comment by wu-sheng** [comment]
We are not facing it after upgrade, please flush happens in es server side only.

**Comment by FredHuan** [comment]
@SummerOfServenteen how do you fix this issue? i met this too in 6.4.0, run with docker in k8s.

**Comment by SevenBlue2018** [comment]
@SummerOfServenteen  hello how to write an plugin about ons-client?

**Comment by SummerOfServenteen** [comment]
@FredHuan ,not yet,i have no time recently

**Comment by SummerOfServenteen** [comment]
@SevenBlue2018 ,There are official documents. You can have a look at them.

**Comment by feiyuyitiao** [comment]
> 

facing save issue on version skywalking:8.9.0
