### ISSUE TITLE
NPE BUG

### ISSUE THREAD

**Issue by WildWolfBang** [apache/skywalking#3413]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking v6.3.0
OS centos6
JRE openjdk version "1.8.0_181"  OpenJDK Runtime Environment (IcedTea 3.9.0) (Alpine 8.181.13-r0)  OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- Which company or project?

- What happen?
use apache/skywalking-oap-server:6.3.0 with nacos,then NPE. The Class
org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker line 69 is under suspicion.
`2019-09-04 10:55:38,059 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -1240886 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
2019-09-04 10:55:43,061 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -1245888 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
2019-09-04 10:55:48,063 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -1250890 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null`

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The root core should be here from your logs
> org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0] at 

But at L81 https://github.com/apache/skywalking/blob/v6.3.0/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/register/ServiceInstanceInventory.java#L81
we require UUID, but seem it is not there. I don't know why. Have seen this before or around.

**Comment by WildWolfBang** [comment]
Yesterday,I depoly docker image apache/skywalking-oap-server:6.3.0,modify docker-entrypoint.sh for seting pod ip to env like this.then nacos can display the SkyWalking_OAP_Cluster with right ip instead of 0.0.0.0.
![nacos](https://user-images.githubusercontent.com/17874410/64320487-3aad1380-cff1-11e9-8b92-53b38d4e1074.png)

> export SW_CORE_GRPC_HOST=${SYS_POD_IP}
exec java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap \
     ${JAVA_OPTS} -classpath ${CLASSPATH} org.apache.skywalking.oap.server.starter.OAPServerStartUp "$@"

@wu-sheng 
But now,every 5min log print the NPE info,not at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory  L81, so mybe it's a smoke bomb.

> 2019-09-05 02:02:53,209 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44291192 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:02:58,211 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44296194 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:03,213 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44301196 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:08,215 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44306198 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:13,216 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44311199 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:18,218 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44316201 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:23,220 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44321203 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:28,222 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44326205 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:33,224 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44331207 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:38,226 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44336209 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:43,228 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44341211 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:48,230 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44346213 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:53,231 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44351214 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:03:58,233 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44356216 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:03,235 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44361218 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:08,237 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44366220 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:13,239 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44371222 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:18,241 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44376224 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:23,243 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44381226 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:28,245 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44386228 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:33,247 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44391230 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
2019-09-05 02:04:38,249 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker -44396232 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null

**Comment by wu-sheng** [comment]
This issue needs to be fixed.
