### ISSUE TITLE
Clients of Skywalking cannot be register by themselves.

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/skywalking#3448]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 6.3.0
OS: 7.6.1810
JRE: 1.8

- What happen?

My skywalking has the error - "java.lang.OutOfMemoryError: Java heap space" occurred. After I adjusted the JVM options and reboot the server(not agent), but I found some of my clients could't be register by themselves. the logs as the following:

The angent logs:
---------------------------
DEBUG 2019-09-10 18:10:15:408 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT.

2019-09-10 19:06:23,556 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-36] WARN  [] - Service instance 177 heartbeat, but not found in storage. 2019-09-10 19:06:23,557 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 68 [grpc-default-executor-36] WARN  [] - Can't find service by service instance id from cache, service instance id is: 177, will send a reset command to agent side

I think rebooting the agant will be recovered. I rememberd this version will register by themselves automatically, I don't need to restart angent any more. but why will it happen?

Please help me out to to diagnose the issues. 

Thanks~

**Comment by kezhenxu94** [comment]
> Can't find service by service instance id from cache, service instance id is: 177, will send a reset command to agent side

The agent should re-register to the backend after sometime (cool down, defaults to 10 minutes)

**Comment by zhaoxunyong** [comment]
But half a day is gone by, I still couldn‘t see some of agent re-registerd by themselves, according to you, it will re-registered in 10 minuties. It's so weird,  and just this logs showing up:

------
2019-09-11 08:20:59,044 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-529] WARN  [] - Service instance 174 heartbeat, but not found in storage.
2019-09-11 08:20:59,045 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 68 [grpc-default-executor-529] WARN  [] - Can't find service by service instance id from cache, service instance id is: 174, will send a reset command to agent side
2019-09-11 08:20:59,514 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-530] WARN  [] - Can't find service by service instance id from cache, service instance id is: 177
2019-09-11 08:20:59,556 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-530] WARN  [] - Service instance 177 heartbeat, but not found in storage.
2019-09-11 08:20:59,557 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 68 [grpc-default-executor-530] WARN  [] - Can't find service by service instance id from cache, service instance id is: 177, will send a reset command to agent side
2019-09-11 08:21:00,004 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 98 [grpc-default-executor-530] WARN  [] - Cannot recognize service instance id [174] from cache, segment will be ignored

Please help me again, because I don't wanna reboot my production agent, thanks.

**Comment by kezhenxu94** [comment]
Please attach the logs of agents that don't work

**Comment by zhaoxunyong** [comment]
Here are some logs of one of my agents, please help me out check：

Yesterday's log:
----
ERROR 2019-09-10 10:34:00:544 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$ServiceInstancePingBlockingStub.doPing(ServiceInstancePingGrpc.java:158)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:166)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:418)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more


Today's log:
---
DEBUG 2019-09-10 10:44:54:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-10 10:44:57:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-10 10:45:00:925 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  Selected collector grpc service running, reconnect:true. 
DEBUG 2019-09-10 10:45:00:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-10 10:45:03:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-10 10:45:06:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-10 10:45:08:422 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient :  11 trace segments have been abandoned, cause by no available channel. 
DEBUG 2019-09-10 10:45:09:952 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT.

---
I couldn't see any "cooling down" in this log as well.

**Comment by wu-sheng** [comment]
Are you using the 6.3.0+ agent? The reboot doesn't exist before that.

**Comment by zhaoxunyong** [comment]
I am sure my version is 6.3.0. agents won't re-register after "OutOfMemoryError" occurred in server, and I couldn't see the "cool down" in the logs. It still doent's re-register so far.   I am going to give it a try for the 6.4.0 version observing whether or not it still have the same problem.

**Comment by wu-sheng** [comment]
What do you expect after `OutOfMemoryError`? This is hard to say. Re-register is not for this case.

**Comment by zhaoxunyong** [comment]
The situation is when "OutOfMemoryError" occurred, I rebooted the server. I expect agents can re-gistering by themselves without rebooting them, but it didn't work. maybe in "OutOfMemoryError" situation, re-register is not support. Am i meaning right?

**Comment by wu-sheng** [comment]
That is no `re-register`, that should be called as `reconnect`, because you are talking about gRPC level connection. This has an issue in 6.3.0, YES. We have fixed it in 6.4.0 release.

**Comment by zhaoxunyong** [comment]
I see, thank you so much. I'll give it a shot right way.
