### ISSUE TITLE
grpc will be disconnected as long as connected

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#3451]
**OS：AIX 6.1
JDK：IBM j9 1.6.0
Agent：6.3.0
Server：6.3.0**

**When I start the app，I could see agent registered serviceId and instanceId. But, grpc will throw new exception and be disconnected after a while.**  This is the exception stack:
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$ServiceInstancePingBlockingStub.doPing(ServiceInstancePingGrpc.java:158)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:162)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:328)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:161)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:109)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:192)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:216)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
	at java.lang.Thread.run(Thread.java:736)

**What is more? I have merged the code of focing forcing reconecting of 6.4.0, and the grpc will be connected , but it will be disconnected as long as connected.**

T**he server has that error logs**:
Sep 11, 2019 10:25:41 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@22bd491a
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:289)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:105)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:609)
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingPkg.<init>(ServiceInstancePingPkg.java:37)
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingPkg.<init>(ServiceInstancePingPkg.java:9)
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingPkg$1.parsePartialFrom(ServiceInstancePingPkg.java:604)
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingPkg$1.parsePartialFrom(ServiceInstancePingPkg.java:599)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
        ... 9 more

**Comment by wu-sheng** [comment]
If the backend is not in high payload, check your firewall. gRPC connection is keeping alive as long as possible.
