### ISSUE TITLE
OAPSERVERStartUp启动报错

### ISSUE THREAD

**Issue by lichengliang1** [apache/skywalking#3452]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- 

- [ ] [ ] Question or discussion

- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- skywalking6.3  jdk1.8 es6.5

- Which company or project?

- What happen?
55 [main] ERROR [] - Duplicate worker name:all_p99_rec
org.apache.skywalking.oap.server.core.UnexpectedException: Duplicate worker name:all_p99_rec
        at org.apache.skywalking.oap.server.core.worker.WorkerInstancesService.put(WorkerInstancesService.java:49) ~[server-core-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsStreamProcessor.create(MetricsStreamProcessor.java:96) ~[server-core-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.core.analysis.StreamAnnotationListener.notify(StreamAnnotationListener.java:53) ~[server-core-6.3.0.jar:6.3.0]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_211]
        at org.apache.skywalking.oal.rt.OALRuntime.notifyAllListeners(OALRuntime.java:168) ~[oal-rt-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.start(CoreModuleProvider.java:178) ~[server-core-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]

启动报这个错误，我该怎么去处理它
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
