### ISSUE TITLE
Service instance 14 heartbeat, but not found in storage.

### ISSUE THREAD

**Issue by lichengliang1** [apache/skywalking#3453]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.3 jdk1.8 es6.5

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-0] WARN  [] - Service instance 14 heartbeat, but not found in storage.
2019-09-11 12:42:35,012 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.ServiceInstanceInventoryCacheDAO - 60 [grpc-default-executor-0] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory$Builder.map2Data(ServiceInstanceInventory.java:173) ~[server-core-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.ServiceInstanceInventoryCacheDAO.get(ServiceInstanceInventoryCacheDAO.java:55) [storage-elasticsearch-plugin-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.core.cache.ServiceInstanceInventoryCache.get(ServiceInstanceInventoryCache.java:75) [server-core-6.3.0.jar:6.3.0]
        at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler.doPing(ServiceInstancePingServiceHandler.java:63) [skywalking-register-receiver-plugin-6.3.0.jar:6.3.0]
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$MethodHandlers.invoke(ServiceInstancePingGrpc.java:210) [apm-network-6.3.0.jar:6.3.0]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2019-09-11 12:42:35,013 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 68 [grpc-default-executor-0] WARN  [] - Can't find service by service instance id from cache, service instance id is: 14, will send a reset command to agent side

是我ES版本的问题吗？

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Your removed all indexes but agent didn't reboot. So either you wait 10 mins to wait agent hot-reboot, or reboot the agent with service directly.
