### ISSUE TITLE
The application that 'docker-entrypoint.sh' generated make skywalking 6.3 NPE

### ISSUE THREAD

**Issue by itfinally** [apache/skywalking#3460]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking 6.3 ( docker version 

I use   docker.io/apache/skywalking-oap-server:latest   version.

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

The config template that [docker-entrypoint](https://github.com/apache/skywalking-docker/blob/master/6/6.3/oap/docker-entrypoint.sh) has an error config.

It make OAP server raise an error （ NullPointException

```yml
docker-entrypoint:
  default:
```

And the error stack info :

```text
2019-09-11 18:17:43,823 - org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister - 64 [main] INFO  [] - Current configurations after the bootstrap sync.
Following dynamic config items are available.
---------------------------------------------
key:receiver-trace.default.slowDBAccessThreshold    module:receiver-trace    provider:default    value(current):

2019-09-11 18:17:44,108 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-09-11 18:17:44,113 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-09-11 18:17:44,190 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@33d230ce{/,null,AVAILABLE}
2019-09-11 18:17:44,213 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@4e8598d9{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-09-11 18:17:44,215 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @18433ms
2019-09-11 18:17:44,247 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 54 [main] INFO  [] - persistence timer start
2019-09-11 18:17:44,254 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 42 [main] INFO  [] - Cache updateServiceInventory timer start
2019-09-11 18:17:44,507 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker - 108 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_152]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_152]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
```

I don't know the cause of the exception, but  the OAP server up after I contrast the file( docker version and non-docker version ) and remove that config.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am highly doubting this is a docker issue. UUID is not existing somehow.

**Comment by hanahmily** [comment]
It's because nacos-plugin didn't set telemetry instance id.
```
TelemetryRelatedContext.INSTANCE.setId(selfAddress.toString());
```
I'm gonna send PR to fix it.
