### ISSUE TITLE
org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - ScopeDefine fieldName = All not found.

### ISSUE THREAD

**Issue by liangxp** [apache/skywalking#3477]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug

___
### Question：start exception
 `
2019-09-17 16:23:10,069 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - ScopeDefine fieldName = All not found.
org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine fieldName = All not found.
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:95) ~[server-core-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.4.0.jar:6.4.0]
Caused by: org.apache.skywalking.oap.server.core.UnexpectedException: ScopeDefine fieldName = All not found.
	at org.apache.skywalking.oap.server.core.source.DefaultScopeDefine.valueOf(DefaultScopeDefine.java:152) ~[server-core-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oal.rt.parser.OALListener.enterSource(OALListener.java:52) ~[oal-rt-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oal.rt.grammar.OALParser$SourceContext.enterRule(OALParser.java:605) ~[oal-grammar-6.4.0.jar:6.4.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:61) ~[oal-rt-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:147) ~[oal-rt-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:93) ~[server-core-6.4.0.jar:6.4.0]
	... 3 more
`

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 6.4
OS:MAC OS 11
JRE:1.8

**Comment by wu-sheng** [comment]
This class is in the distribution. I am not sure why the error log shows up.

**Comment by wu-sheng** [comment]
I think you need to debug and find out why the classpath scan is not working. It should be.
