### ISSUE TITLE
Send UpstreamSegment to collector fail with a grpc internal exception

### ISSUE THREAD

**Issue by Daych** [apache/skywalking#3490]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know? 

Im using Docker version of skywalking oap and ui, need to check the docker container, when im using Skywalking 6.1 version, the service is showing on the UI, but when I upgraded to use 6.4 version, the Services are not shown on the UI (for the Endpoint/DB,Cache and MQ had display without problem, then I checked the agent logs are showing below

========================================

ERROR 2019-09-20 01:41:22:155 grpc-default-executor-368 TraceSegmentServiceClient : Send UpstreamSegment to collector fail with a grpc internal exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
        at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:526)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
        at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
        at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
===================================

any suggestion and action that I can take ?
___
### Bug
- Which version of SkyWalking, OS and JRE? 

version 6.4 docker version
Centos 7.5.1804
openjdk version "1.8.0_191"

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
the services data is not shown
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
`DEADLINE_EXCEEDED` only means timeout, the segment can't send to upstream in time(10s in default), so error shows up. If this keeps showing up, you may have a backend performance issue or network issue.

**Comment by wu-sheng** [comment]
@Daych Read #3491

**Comment by Daych** [comment]
@wu-sheng Thanks for your helping, another issue I can found is the UI is missing the Logout function, can you add it back also ?

**Comment by wu-sheng** [comment]
> Thanks for your helping, another issue I can found is the UI is missing the Logout function, can you add it back also ?

Old login/login has been confirmed as a security vulnerability. There is no adding it back. Only option is someone contributing a new good one.
