### ISSUE TITLE
trace detail error with collecting envoy trace by skywalking zipkin receiver

### ISSUE THREAD

**Issue by andrewshaoyu** [apache/skywalking#3545]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

can skywalking work with envoy directly?

### Which version of SkyWalking, OS and JRE?
6.4.0

in k8s

use official docker image

### my setup step
1. enable the zipkin receiver in skywalking-oap env
1. set the envoy zipkinAddress to skywalking-oap:9411
1. change the skywalking-ui timezone

### problem
get the trace list in skywalking ui with trace id ,start time and duration.

but cannot get the trace detail,i find the error in skywalking-oap log

```
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.storage.plugin.zipkin.elasticsearch.ZipkinTraceQueryEsDAO.doFlexibleTraceQuery(ZipkinTraceQueryEsDAO.java:183) ~[storage-zipkin-plugin-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.server.core.query.TraceQueryService.queryTrace(TraceQueryService.java:108) ~[server-core-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.queryTrace(TraceQuery.java:80) ~[query-graphql-plugin-6.4.0.jar:6.4.0]
	at org.apache.skywalking.oap.query.graphql.resolver.TraceQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.4.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:87) [query-graphql-plugin-6.4.0.jar:6.4.0]
```

i think the trace have stored,and query success. but I don't know where is the problem.

**Comment by wu-sheng** [comment]
Read #2653
