### ISSUE TITLE
IndexOutOfBoundsException in start the oap

### ISSUE THREAD

**Issue by Zack-Ku** [apache/skywalking#3602]
I use https://github.com/apache/skywalking-kubernetes 
to deploy 6.4.0 version. 
But when start to oap ,it occur IndexOutOfBoundsException.
Both 11800 and 12800 port are inactivated。

Stack：
2019-10-11 11:00:01,748 - org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker -346586 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
at org.apache.skywalking.oap.server.core.remote.selector.ForeverFirstSelector.select(ForeverFirstSelector.java:37) ~[server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:58) ~[server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:47) ~[server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:32) ~[server-core-6.4.0.jar:6.4.0]
at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:76) [server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) [server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.4.0.jar:6.4.0]
at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.4.0.jar:6.4.0]
at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.4.0.jar:6.4.0]

**Comment by wu-sheng** [comment]
This error may happen as a bug, fixed in master. But it would affect the bootstrap. So, if ports are not listening, there is another issue.
