### ISSUE TITLE
Redisson agent report error

### ISSUE THREAD

**Issue by terranhu** [apache/skywalking#3688]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ 1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
redisson agent report many error logs
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4 , aliyun ecs,jdk8
- Which company or project?

- What happen?
below is one error log.

`ERROR 2019-10-23 04:22:54:738 Thread-7 InstMethodsInter : class[class org.redisson.client.RedisConnection] after method[send] intercept failure
java.lang.IllegalStateException: No active span.
        at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:392)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:182)
        at org.apache.skywalking.apm.plugin.redisson.v3.RedisConnectionMethodInterceptor.afterMethod(RedisConnectionMethodInterceptor.java:93)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
        at org.redisson.client.RedisConnection.send(RedisConnection.java)
        at org.redisson.command.CommandAsyncService.sendCommand(CommandAsyncService.java:1238)
        at org.redisson.command.CommandAsyncService.lambda$async$5(CommandAsyncService.java:786)
        at org.redisson.command.CommandAsyncService$$Lambda$577/1574674469.accept(Unknown Source)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
        at org.redisson.misc.RedissonPromise$$Lambda$560/875053581.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
        at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:769)
        at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:641)
        at org.redisson.RedissonLock.isExistsAsync(RedissonLock.java:510)
        at org.redisson.RedissonObject.isExists(RedissonObject.java:232)
        at org.redisson.RedissonLock.isLocked(RedissonLock.java:500)
        at com.yjh.mushroom.framework.lock.impl.RedisLockExecutorImpl.unlock(RedisLockExecutorImpl.java:95)
        at com.yjh.mushroom.framework.lock.impl.RedisLockExecutorImpl.unlock(RedisLockExecutorImpl.java:33)
        at com.yjh.mushroom.framework.lock.impl.RedisLockDelegateImpl.invoke(RedisLockDelegateImpl.java:48)
        at com.yjh.mushroom.framework.lock.aop.LockInterceptor.invoke(LockInterceptor.java:126)
        at com.yjh.mushroom.framework.lock.aop.LockInterceptor.invoke(LockInterceptor.java:46)`

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Humhunter** [comment]
I have the same problem

**Comment by wu-sheng** [comment]
@zhaoyuguang maybe a version incompatible ? Could you recheck?

**Comment by gzq6527** [comment]
I have the same problem
Skywalking6.4 is compatible with redisson3.11.0
Change your redisson to redisson3.11.0

**Comment by gzq6527** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [ ]  Question or discussion
> * [ 1] Bug
> * [ ]  Requirement
> * [ ]  Feature or performance improvement
> 
> ### Question
> * What do you want to know?
>   redisson agent report many error logs
> 
> ### Bug
> * Which version of SkyWalking, OS and JRE?
>   6.4 , aliyun ecs,jdk8
> * Which company or project?
> * What happen?
>   below is one error log.
> 
> `ERROR 2019-10-23 04:22:54:738 Thread-7 InstMethodsInter : class[class org.redisson.client.RedisConnection] after method[send] intercept failure java.lang.IllegalStateException: No active span. at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:392) at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:182) at org.apache.skywalking.apm.plugin.redisson.v3.RedisConnectionMethodInterceptor.afterMethod(RedisConnectionMethodInterceptor.java:93) at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105) at org.redisson.client.RedisConnection.send(RedisConnection.java) at org.redisson.command.CommandAsyncService.sendCommand(CommandAsyncService.java:1238) at org.redisson.command.CommandAsyncService.lambda$async$5(CommandAsyncService.java:786) at org.redisson.command.CommandAsyncService$$Lambda$577/1574674469.accept(Unknown Source) at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) at org.redisson.misc.RedissonPromise$$Lambda$560/875053581.operationComplete(Unknown Source) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162) at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181) at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:769) at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:641) at org.redisson.RedissonLock.isExistsAsync(RedissonLock.java:510) at org.redisson.RedissonObject.isExists(RedissonObject.java:232) at org.redisson.RedissonLock.isLocked(RedissonLock.java:500) at com.yjh.mushroom.framework.lock.impl.RedisLockExecutorImpl.unlock(RedisLockExecutorImpl.java:95) at com.yjh.mushroom.framework.lock.impl.RedisLockExecutorImpl.unlock(RedisLockExecutorImpl.java:33) at com.yjh.mushroom.framework.lock.impl.RedisLockDelegateImpl.invoke(RedisLockDelegateImpl.java:48) at com.yjh.mushroom.framework.lock.aop.LockInterceptor.invoke(LockInterceptor.java:126) at com.yjh.mushroom.framework.lock.aop.LockInterceptor.invoke(LockInterceptor.java:46)`
> 
> ### Requirement or improvement
> * Please describe about your requirements or improvement suggestions.

I have the same problem
This problem will cause the link to be broken.
Skywalking6.4 is compatible with redisson3.11.0
Change your redisson to redisson3.11.0

**Comment by wu-sheng** [comment]
If the version is not on the supported list, then it is not a bug.

**Comment by zhaojingyang** [comment]
i have the same problem using redission 3.13.1.  i need to update skywalking version? 6.4.0 later?
