### ISSUE TITLE
Test plugin Occasionally ConcurrentModificationException

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#3693]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
[2019-10-23T06:59:24.104Z] 2019-10-23 06:58:57.605:INFO:oejs.Server:main: Started @1898ms

[2019-10-23T06:59:24.104Z] http://localhost:12800/receiveData: HTTP/1.1 200 OK

[2019-10-23T06:59:24.104Z] Oct 23, 2019 6:59:12 AM org.apache.coyote.AbstractProtocol init

[2019-10-23T06:59:24.104Z] INFO: Initializing ProtocolHandler ["http-nio-8080"]

[2019-10-23T06:59:24.104Z] Oct 23, 2019 6:59:12 AM org.apache.catalina.core.StandardService startInternal

[2019-10-23T06:59:24.104Z] INFO: Starting service [Tomcat]

[2019-10-23T06:59:24.104Z] Oct 23, 2019 6:59:12 AM org.apache.catalina.core.StandardEngine startInternal

[2019-10-23T06:59:24.104Z] INFO: Starting Servlet engine: [Apache Tomcat/9.0.17]

[2019-10-23T06:59:24.104Z] Oct 23, 2019 6:59:12 AM org.apache.catalina.core.ApplicationContext log

[2019-10-23T06:59:24.104Z] INFO: Initializing Spring embedded WebApplicationContext

[2019-10-23T06:59:24.104Z] Oct 23, 2019 6:59:14 AM org.apache.coyote.AbstractProtocol start

[2019-10-23T06:59:24.104Z] INFO: Starting ProtocolHandler ["http-nio-8080"]

[2019-10-23T06:59:24.105Z] Oct 23, 2019 6:59:14 AM org.apache.catalina.core.ApplicationContext log

[2019-10-23T06:59:24.105Z] INFO: Initializing Spring DispatcherServlet 'dispatcherServlet'

[2019-10-23T06:59:24.105Z] http://localhost:8080/postgresql-scenario/case/healthcheck: HTTP/1.1 200 

[2019-10-23T06:59:24.105Z] To visit entry service

[2019-10-23T06:59:24.105Z] SuccessTo receive actual data

[2019-10-23T06:59:24.105Z] 2019-10-23 06:59:20.756:WARN:oejs.HttpChannel:qtp1237762639-17: /receiveData

[2019-10-23T06:59:24.105Z] java.util.ConcurrentModificationException

[2019-10-23T06:59:24.105Z] 	at java.util.ArrayList.forEach(ArrayList.java:1260)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.lambda$serialize$1(SegmentItemsSerializer.java:37)

[2019-10-23T06:59:24.105Z] 	at java.util.HashMap.forEach(HashMap.java:1289)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.serialize(SegmentItemsSerializer.java:32)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.serialize(SegmentItemsSerializer.java:27)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:669)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJsonTree(Gson.java:562)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJsonTree(Gson.java:541)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.ValidateDataSerializer.serialize(ValidateDataSerializer.java:38)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.ValidateDataSerializer.serialize(ValidateDataSerializer.java:30)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:669)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:648)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:603)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:583)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.service.ReceiveDataService.doGet(ReceiveDataService.java:43)

[2019-10-23T06:59:24.105Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

[2019-10-23T06:59:24.105Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.Server.handle(Server.java:564)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)

[2019-10-23T06:59:24.105Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)

[2019-10-23T06:59:24.105Z] 	at java.lang.Thread.run(Thread.java:748)

[2019-10-23T06:59:24.105Z] To validate

[2019-10-23T06:59:24.105Z] [2019-10-23 06:59:21:728] [ERROR] - org.apache.skywalking.plugin.test.agent.tool.Main.verify(Main.java:52) - 

[2019-10-23T06:59:24.105Z] assert failed.

[2019-10-23T06:59:24.105Z] IllegalDataFileException actualData.yaml 

[2019-10-23T06:59:24.105Z] 

[2019-10-23T06:59:24.105Z] <html>

[2019-10-23T06:59:24.105Z] <head>

[2019-10-23T06:59:24.105Z] <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

[2019-10-23T06:59:24.105Z] <title>Error 500 Server Error</title>

[2019-10-23T06:59:24.105Z] </head>

[2019-10-23T06:59:24.105Z] <body><h2>HTTP ERROR 500</h2>

[2019-10-23T06:59:24.105Z] <p>Problem accessing /receiveData. Reason:

[2019-10-23T06:59:24.105Z] <pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.util.ConcurrentModificationException

[2019-10-23T06:59:24.105Z] 	at java.util.ArrayList.forEach(ArrayList.java:1260)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.lambda$serialize$1(SegmentItemsSerializer.java:37)

[2019-10-23T06:59:24.105Z] 	at java.util.HashMap.forEach(HashMap.java:1289)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.serialize(SegmentItemsSerializer.java:32)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.SegmentItemsSerializer.serialize(SegmentItemsSerializer.java:27)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:669)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJsonTree(Gson.java:562)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJsonTree(Gson.java:541)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.ValidateDataSerializer.serialize(ValidateDataSerializer.java:38)

[2019-10-23T06:59:24.105Z] 	at org.apache.skywalking.plugin.test.mockcollector.entity.ValidateDataSerializer.serialize(ValidateDataSerializer.java:30)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)

[2019-10-23T06:59:24.105Z] 	at com.google.gson.Gson.toJson(Gson.java:669)

[2019-10-23T06:59:24.106Z] 	at com.google.gson.Gson.toJson(Gson.java:648)

[2019-10-23T06:59:24.106Z] 	at com.google.gson.Gson.toJson(Gson.java:603)

[2019-10-23T06:59:24.106Z] 	at com.google.gson.Gson.toJson(Gson.java:583)

[2019-10-23T06:59:24.106Z] 	at org.apache.skywalking.plugin.test.mockcollector.service.ReceiveDataService.doGet(ReceiveDataService.java:43)

[2019-10-23T06:59:24.106Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

[2019-10-23T06:59:24.106Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.Server.handle(Server.java:564)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)

[2019-10-23T06:59:24.106Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)

[2019-10-23T06:59:24.106Z] 	at java.lang.Thread.run(Thread.java:748)

[2019-10-23T06:59:24.106Z] </pre>

[2019-10-23T06:59:24.106Z] <hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.2.v20170220</a><hr/>

[2019-10-23T06:59:24.106Z] 

[2019-10-23T06:59:24.106Z] </body>

[2019-10-23T06:59:24.106Z] </html>

[2019-10-23T06:59:24.106Z] [ERROR] Scenario[postgresql-scenario-9.2-1004-jdbc4] failed!

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
This is a failure due to other uncertain reasons. Even if fixed, the test-case still fails(maybe expectedData.yml validates failure, or other). So I think we don't fix it.

**Comment by wu-sheng** [comment]
As this has no update in 20+ days. I am closing it. If we have some clues, we could continue on this.
