### ISSUE TITLE
[plugin] NettySocketIOPluginConnectionInstrumentation ClassNotFoundException

### ISSUE THREAD

**Issue by arugal** [apache/skywalking#3705]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

https://github.com/apache/skywalking/blob/69a28d45919a04e6b1f77a99d4d5b7d8e01d11b3/apm-sniffer/apm-sdk-plugin/netty-socketio-plugin/src/main/resources/skywalking-plugin.def#L19

```
java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.plugin.netty.socketio.define.NettySocketIOPluginConnectionInstrumentation
	at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:152)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.skywalking.apm.agent.core.plugin.PluginBootstrap.loadPlugins(PluginBootstrap.java:70)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

**Comment by wu-sheng** [comment]
How does this happen? I think this PR just get merged with tests passed.

**Comment by wu-sheng** [comment]
FYI @mrproliu

**Comment by arugal** [comment]
> How does this happen? I think this PR just get merged with tests passed.

My guess is that ```skywalking-plugin. def``` forgot to update.

**Comment by wu-sheng** [comment]
Fix sent. Thanks for reminding.
