### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by terrywpf** [apache/skywalking#3710]
http://192.168.2.150:8080/graphql
HTTP ERROR 500
Problem accessing /graphql. Reason:

    Server Error
Caused by:
java.lang.UnsupportedOperationException: GraphQL only supports POST method
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doGet(GraphQLQueryHandler.java:68)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doGet(JettyJsonHandler.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
Powered by Jetty:// 9.4.2.v20170220

**Comment by terrywpf** [comment]
query:
  graphql:
    path: ${SW_QUERY_GRAPHQL_PATH:/graphql}
alarm:
  default:
telemetry:
  none:
configuration:
  none:
How to configure under centos

**Comment by terrywpf** [comment]
2019-10-25 10:32:00.021  WARN 21492 --- [http-nio-8080-exec-7] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/trace] in DispatcherServlet with name 'dispatcherServlet'
2019-10-25 10:32:09.444  WARN 21492 --- [http-nio-8080-exec-10] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/trace] in DispatcherServlet with name 'dispatcherServlet'
2019-10-25 10:33:23.857  WARN 21492 --- [http-nio-8080-exec-10] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/topology] in DispatcherServlet with name 'dispatcherServlet'
2019-10-25 10:33:24.261  WARN 21492 --- [http-nio-8080-exec-6] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/topology] in DispatcherServlet with name 'dispatcherServlet'
2019-10-25 10:46:13.827  WARN 21492 --- [http-nio-8080-exec-3] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/trace] in DispatcherServlet with name 'dispatcherServlet'

**Comment by kezhenxu94** [comment]
Don't know what you're asking, `http://192.168.2.150:8080/graphql` is for UI to call with POST method, not for directly access in browser(GET), keep asking simple questions without reading the documentations first is not welcome in open-sourced project
