### ISSUE TITLE
SkyWalking 6.4.0 is incompatible with redisson 3.11.1

### ISSUE THREAD

**Issue by czq080** [apache/skywalking#3762]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking6.4.0,linux,jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
**ERROR 2019-10-30 18:30:19:614 redisson-netty-4-3 ConstructorInter : ConstructorInter failure.
java.lang.NoSuchMethodError: org.redisson.client.RedisClientConfig.getAddress()Ljava/net/URI;
        at org.apache.skywalking.apm.plugin.redisson.v3.RedisConnectionMethodInterceptor.onConstruct(RedisConnectionMethodInterceptor.java:109)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter.intercept(ConstructorInter.java:69)
        at org.redisson.client.RedisConnection.<init>(RedisConnection.java)
        at org.redisson.client.handler.RedisConnectionHandler.createConnection(RedisConnectionHandler.java:36)
        at org.redisson.client.handler.BaseConnectionHandler.channelRegistered(BaseConnectionHandler.java:55)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:140)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:824)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)**
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@zhaoyuguang Is this version supposed?

@czq080 Have you checked the supported list document?

**Comment by wu-sheng** [comment]
@czq080 Document said, `Redisson Easy Java Redis client 3.5.2+`. Do you use the easy Java Redis client?

**Comment by czq080** [comment]
@wu-sheng yes.

**Comment by zhaoyuguang** [comment]
hi @czq080  Please provide the demo, let us reproduce this case.
And use `dependency:tree` find the real redisson version

**Comment by gzq6527** [comment]
Redisson agent report error #3688

**Comment by gzq6527** [comment]
I have the same problem
Skywalking6.4 is compatible with redisson3.11.0
Change your redisson to redisson3.11.0

**Comment by czq080** [comment]
hi @zhaoyuguang  This is the demo.[https://github.com/czq080/skywalking-redisson-demo.git](url)
dependency tree is as follow.

> [INFO] com.example:skywalking-redisson-demo:jar:0.0.1-SNAPSHOT
[INFO] \- org.redisson:redisson:jar:3.11.1:compile
[INFO]    +- io.netty:netty-common:jar:4.1.36.Final:compile
[INFO]    +- io.netty:netty-codec:jar:4.1.36.Final:compile
[INFO]    +- io.netty:netty-buffer:jar:4.1.36.Final:compile
[INFO]    +- io.netty:netty-transport:jar:4.1.36.Final:compile
[INFO]    |  \- io.netty:netty-resolver:jar:4.1.36.Final:compile
[INFO]    +- io.netty:netty-resolver-dns:jar:4.1.36.Final:compile
[INFO]    |  \- io.netty:netty-codec-dns:jar:4.1.36.Final:compile
[INFO]    +- io.netty:netty-handler:jar:4.1.36.Final:compile
[INFO]    +- javax.cache:cache-api:jar:1.0.0:compile
[INFO]    +- io.projectreactor:reactor-core:jar:3.2.6.RELEASE:compile
[INFO]    |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO]    +- io.reactivex.rxjava2:rxjava:jar:2.2.7:compile
[INFO]    +- de.ruedigermoeller:fst:jar:2.57:compile
[INFO]    |  +- org.javassist:javassist:jar:3.21.0-GA:compile
[INFO]    |  \- org.objenesis:objenesis:jar:2.5.1:compile
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO]    +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.9:compile
[INFO]    |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    +- net.bytebuddy:byte-buddy:jar:1.9.10:compile
[INFO]    \- org.jodd:jodd-bean:jar:5.0.10:compile
[INFO]       \- org.jodd:jodd-core:jar:5.0.10:compile

**Comment by czq080** [comment]
> hi @zhaoyuguang This is the demo.[https://github.com/czq080/skywalking-redisson-demo.git](url)
> dependency tree is as follow.
> 
> > [INFO] com.example:skywalking-redisson-demo:jar:0.0.1-SNAPSHOT
> > [INFO] - org.redisson:redisson:jar:3.11.1:compile
> > [INFO]    +- io.netty:netty-common:jar:4.1.36.Final:compile
> > [INFO]    +- io.netty:netty-codec:jar:4.1.36.Final:compile
> > [INFO]    +- io.netty:netty-buffer:jar:4.1.36.Final:compile
> > [INFO]    +- io.netty:netty-transport:jar:4.1.36.Final:compile
> > [INFO]    |  - io.netty:netty-resolver:jar:4.1.36.Final:compile
> > [INFO]    +- io.netty:netty-resolver-dns:jar:4.1.36.Final:compile
> > [INFO]    |  - io.netty:netty-codec-dns:jar:4.1.36.Final:compile
> > [INFO]    +- io.netty:netty-handler:jar:4.1.36.Final:compile
> > [INFO]    +- javax.cache:cache-api:jar:1.0.0:compile
> > [INFO]    +- io.projectreactor:reactor-core:jar:3.2.6.RELEASE:compile
> > [INFO]    |  - org.reactivestreams:reactive-streams:jar:1.0.2:compile
> > [INFO]    +- io.reactivex.rxjava2:rxjava:jar:2.2.7:compile
> > [INFO]    +- de.ruedigermoeller:fst:jar:2.57:compile
> > [INFO]    |  +- org.javassist:javassist:jar:3.21.0-GA:compile
> > [INFO]    |  - org.objenesis:objenesis:jar:2.5.1:compile
> > [INFO]    +- org.slf4j:slf4j-api:jar:1.7.25:compile
> > [INFO]    +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.9:compile
> > [INFO]    |  - org.yaml:snakeyaml:jar:1.23:compile
> > [INFO]    +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
> > [INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
> > [INFO]    |  - com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
> > [INFO]    +- net.bytebuddy:byte-buddy:jar:1.9.10:compile
> > [INFO]    - org.jodd:jodd-bean:jar:5.0.10:compile
> > [INFO]       - org.jodd:jodd-core:jar:5.0.10:compile

The log is as follow:

> ERROR 2019-11-01 15:36:39:251 redisson-netty-2-15 ConstructorInter : ConstructorInter failure. 
java.lang.NoSuchMethodError: org.redisson.client.RedisClientConfig.getAddress()Ljava/net/URI;
        at org.apache.skywalking.apm.plugin.redisson.v3.RedisConnectionMethodInterceptor.onConstruct(RedisConnectionMethodInterceptor.java:109)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter.intercept(ConstructorInter.java:69)
        at org.redisson.client.RedisConnection.<init>(RedisConnection.java)
        at org.redisson.client.handler.RedisConnectionHandler.createConnection(RedisConnectionHandler.java:36)
        at org.redisson.client.handler.BaseConnectionHandler.channelRegistered(BaseConnectionHandler.java:55)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:140)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:824)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)

**Comment by zhaoyuguang** [comment]
Thanks lot

**Comment by czq080** [comment]
> I have the same problem
> Skywalking6.4 is compatible with redisson3.11.0
> Change your redisson to redisson3.11.0

Got it.
