### ISSUE TITLE
NPE about GraphQL

### ISSUE THREAD

**Issue by Videl** [apache/skywalking#3924]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.5.0, Debian 9, OpenJDK 1.8.0_212

- Which company or project? 
Personal

- What happens?
I'm currently test driving Skywalking to get a feel of its capabilities and of OpenTracing.
I'm running Skywalking on my server, with a couple of applications.
As such, Skywalking has a minimal configuration (the same as the default, except the webapp.yml which has a user specified). It's still on H2.

I have a NPE related to GraphQL when one of the applications using the agent is sending metrics to the collector The NPE happens

```
2019-11-23 20:26:04,877 - org.eclipse.jetty.server.HttpChannel - 507 [qtp1350377659-43] WARN  [] - /graphql
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:81) ~[query-graphql-plugin-6.5.0.jar:6.5.0]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54) ~[library-server-6.5.0.jar:6.5.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101) ~[library-server-6.5.0.jar:6.5.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105) ~[library-server-6.5.0.jar:6.5.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) ~[jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) ~[jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) ~[jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]

        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
2019-11-23 20:28:59,286 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 69 [pool-11-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
```

Kindest regards!
Any pointers? Do I need to run a GraphQL server? Or do I have to disable some settings?

**Comment by wu-sheng** [comment]
GraphQL is for query, not for collecting data. So, I am a little confused about your context.

**Comment by Videl** [comment]
I'm just trying out Skywalking, so it's just the default settings (H2 db) + an account in webapp.yml for secure login.

**Comment by wu-sheng** [comment]
Two things.
1. I assume you set the wrong port. gRPC port should be used in the agent config.
1. The login has been removed.

**Comment by Videl** [comment]
Thanks! I'll check those things. I upgraded from 6.1.0, I took my old webapp.yml file

**Comment by wu-sheng** [comment]
> Thanks! I'll check those things. I upgraded from 6.1.0, I took my old webapp.yml file

First, if you run the upgrade, the agent YAML should keep unchanged. That is the thing needs to be rechecked. As you were using 6.1.0, you should reboot the agent after you upgrade. Last thing, H2 default if in memory mode, if you reboot the backend, agent is required to reboot too due to data lost. Auto agent hot reboot(don't need to reboot agent) is supported from 6.4.0, you could check the change log.

A simple question, are you using SkyWalking for test or production? If test considering you are using H2, why there is an upgrade scenario.

**Comment by wu-sheng** [comment]
> I took my old webapp.yml file

Adding auth should be fine, it is just not working but not blocking the app.

**Comment by Videl** [comment]
Alright, I checked my applications agent config and indeed, I forgot to change them.. so I did.
I also noticed a 1hour difference in times between the host time and containers time, so I also fixed the timezone of my containers.

My containers connects fine to Skywalking as per their logs, and then send their traces correctly:

```
DEBUG 2019-11-24 18:12:52:590 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-11-24 18:12:54:229 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient : 3 trace segments have been sent to collector.
DEBUG 2019-11-24 18:12:55:590 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
```
When I had only one container up, it worked fine on the UI side, but as soon as I turned a second one, the graphql replies from the website are this:
```
{
  "errors": [
    {
      "message": "Variable 'serviceId' has coerced Null value for NonNull type 'ID!'"
    }
  ]
}
```
It seems everything is updated correctly.. did I miss something?
I made sure to launch Skywalking before the agents.
I'm using Skywalking for test.

Thank you very much for the pointers you gave already.

**Comment by wu-sheng** [comment]
How many services could you find on your UI side? 

> I made sure to launch Skywalking before the agents.

This is not required. It is OK to be after.

**Comment by Videl** [comment]
Alright, after checking everything once again to see if I missed anything obvious, I stumbled about other issues about error "IDs can't be null" and seeing the answers that said to check all timezones, I noticed the UI settings on the bottom of the page. 

I believe I didn't see anything because it was just misconfigured to an old date. I started everything, made some requests and it's all working.
Thanks for your help, I'll try to check all the guides here and see if I can contribute..
I noticed you linked the 6.6.0 milestone to this issue about the webapp auth. Would you like to keep this issue open?

**Comment by wu-sheng** [comment]
ID can't be null should be ignored by backend. I am sure why you are seeing this. But it is harmness, just a UI tiny bug.

Notice for time, click reload on the page, or open refresh, otherwise, the time stays in the old time.

For auth, there is no short term plan for it, as it is not required, and easily build by user without change codes. I set up milestone for tracking the progress, nothing more.

As you have resolved the issue, I am closing this.

**Comment by Videl** [comment]
Alright thanks.
