### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_222] 	

### ISSUE THREAD

**Issue by Nupur13** [apache/skywalking#3940]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I am not able to use mysql as a storage for skywalking

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.3
JRE 1.8

- Which company or project?
DewSolutions

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Added Mysql as a storage on config/application.yml
mysql:
          #      properties:
      jdbcUrl: ${SW_JDBC_URL:"jdbc:mysql:/*.*.*.*:****/swtest"}
      dataSource.user: ${SW_DATA_SOURCE_USER: ****}
      dataSource.password: ${SW_DATA_SOURCE_PASSWORD:****}
      dataSource.cachePrepStmts: ${SW_DATA_SOURCE_CACHE_PREP_STMTS:true}
      dataSource.prepStmtCacheSize: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE:250}
      dataSource.prepStmtCacheSqlLimit: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
      dataSource.useServerPrepStmts: ${SW_DATA_SOURCE_USE_SERVER_PREP_STMTS:true}
      metadataQueryMaxSize: ${SW_STORAGE_MYSQL_QUERY_MAX_SIZE:5000}
and commented H2 driver.
Now when I restart services, found error in logs/skywalking-oap-server.log
ERROR:
2019-11-26 11:45:13,557 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_222]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_222]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_222]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_222]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_222]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_222]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_222]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:306) ~[guava-20.0.jar:?]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.scan(AnnotationScan.java:57) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:88) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:94) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.3.0.jar:6.3.0]
Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Nupur13** [comment]
@wu-sheng Please help

**Comment by wu-sheng** [comment]
You are posting agent side error. What do you mean? Confused. Please read storage doc before you switch to MySQL storage.

**Comment by Nupur13** [comment]
@wu-sheng actually prior to mysql storage, on h2 it was working fine. 
Thanks for the prompt response. Will check first on agent level.
Thanks

**Comment by wu-sheng** [comment]
I am pretty sure, you miss an important part of the storage doc, you don't add MySQL driver lib.

**Comment by Nupur13** [comment]
Have added into oap-lib
