### ISSUE TITLE
springcloud gateway bug

### ISSUE THREAD

**Issue by kingtiger2** [apache/skywalking#3968]
SkyWalking 6.5.0,jdk 1.8.0,sc gateway 2.1.0.RELEASE

ERROR 2019-11-29 09:32:01:629 lettuce-epollEventLoop-4-1 InstMethodsInter : class[class org.springframework.cloud.gateway.filter.NettyRoutingFilter] before method[filter] intercept failure 
java.lang.ClassCastException: org.springframework.web.server.adapter.DefaultServerWebExchange cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
	at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.NettyRoutingFilterInterceptor.getEnhancedInstance(NettyRoutingFilterInterceptor.java:80)
	at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.NettyRoutingFilterInterceptor.getEnhancedInstance(NettyRoutingFilterInterceptor.java:78)
	at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.NettyRoutingFilterInterceptor.getInstance(NettyRoutingFilterInterceptor.java:67)
	at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.NettyRoutingFilterInterceptor.beforeMethod(NettyRoutingFilterInterceptor.java:42)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java)
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:135)
	at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44)
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)

**Comment by wu-sheng** [comment]
Duplicated, we are trying to locate and improve the plugin.
