### ISSUE TITLE
Use h2 to report the following error every few days

### ISSUE THREAD

**Issue by chad0329** [apache/skywalking#4028]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- skyworking 6.5

- Which company or project?

- What happen?
2019-12-06 03:19:51,906 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-10-thread-1] ERROR [] - Value too long for column "DETAIL_GROUP VARCHAR(20000) SELECTIVITY 100": "'0,4
36292|4096,1|1,530167|2,141820|4098,1|3,71155|4,32341|5,32153|6,21623|7,29949|8,71384|9,58988|12297,1|10,31440|11,17089|12,2... (20005)"; SQL statement:
UPDATE all_p75_month SET 
value= ?,precision= ?,detail_group= ?,time_bucket= ? WHERE id = ? [22001-196]
org.h2.jdbc.JdbcSQLException: Value too long for column "DETAIL_GROUP VARCHAR(20000) SELECTIVITY 100": "'0,436292|4096,1|1,530167|2,141820|4098,1|3,71155|4,32341|5,32153|6,21623|7,29949|8,71384|9,58988|12297,1|
10,31440|11,17089|12,2... (20005)"; SQL statement:
UPDATE all_p75_month SET 
value= ?,precision= ?,detail_group= ?,time_bucket= ? WHERE id = ? [22001-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:797) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.dml.Update.update(Update.java:125) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.CommandContainer.update(CommandContainer.java:101) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Command.executeUpdate(Command.java:260) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:207) ~[h2-1.4.196.jar:1.4.196]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:51) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.synchronous(H2BatchDAO.java:72) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:111) ~[server-core-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:67) ~[server-core-6.5.0.jar:6.5.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.5.0.jar:6.5.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

___
### Requirement or improvement
- Value too long for column
- Then no data on front page

**Comment by wu-sheng** [comment]
Please read the document.

![image](https://user-images.githubusercontent.com/5441976/70400901-20f3f000-1a68-11ea-98bd-072ce4afa600.png)

H2 storage is in memory mode default, it is not designed for this.
