### ISSUE TITLE
no suitable driver found

### ISSUE THREAD

**Issue by alishangtian** [apache/skywalking#4058]
2019-12-13 17:10:35,926 - com.zaxxer.hikari.HikariDataSource - 80 [main] INFO  [] - HikariPool-1 - Starting...
2019-12-13 17:10:35,971 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/skywalking
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://10.38.164.79:3306/skywalking
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:334) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.connect(JDBCHikariCPClient.java:44) ~[library-client-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider.start(MySQLStorageProvider.java:123) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.5.0.jar:6.5.0]
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315) ~[?:1.8.0_222]
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:103) ~[HikariCP-3.1.0.jar:?]
	... 9 more

**Comment by alishangtian** [comment]
my skywalking version is 6.5

**Comment by wu-sheng** [comment]
Yes, you can't find. Because you need to add manually. MySQL driver is GPL licensed, it is not allowed to include in Apache release.

**Comment by geektcp** [comment]
Solution: 
cd apache-skywalking-apm-bin-es7/oap-libs/ 
wget http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.48/mysql-connector-java-5.1.48.jar

**Comment by angelosun** [comment]
where

> Solution:
> 
> ```
> cd apache-skywalking-apm-bin-es7/oap-libs/ 
> wget http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.48/mysql-connector-java-5.1.48.jar
> ```
> 
> Then restart skywalking and this problem fixed !

I ran the OAPServerStartUp on the apm source code,  I got the same problem,  however I don't find the  the oap-libs in the whole project directory, where should I put the driver jar file in ? Pls help!

**Comment by angelosun** [comment]
> where
> 
> > Solution:
> > ```
> > cd apache-skywalking-apm-bin-es7/oap-libs/ 
> > wget http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.48/mysql-connector-java-5.1.48.jar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then restart skywalking and this problem fixed !
> 
> I ran the OAPServerStartUp on the apm source code, I got the same problem, however I don't find the folder oap-libs in the whole project directory, where should I put the driver jar file in ? Pls help!

BTW the version is 9.0

**Comment by angelosun** [comment]
> We are talking about binary, https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-storage/#mysql.
> 
> If you are playing with source codes, then you have all control to pom. Do what you like to do.

I got it, thanks a lot!
