### ISSUE TITLE
No metrics data  to report to collector when client server is running for some time.

### ISSUE THREAD

**Issue by adventurer2008** [apache/skywalking#4077]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question

   Skywalking is 6.6 and JDK is 1.8 and database is H2.

- My client server is tomcat. when tomcat server with skywalking startup, everything is ok. Dashboard of skywalking can collect data and display normally. but after some time , there are some errors from skywalking client logs, which is as below.

DEBUG 2019-12-17 16:22:45:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-12-17 16:22:48:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-12-17 16:22:51:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-12-17 16:22:54:721 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:false. 
DEBUG 2019-12-17 16:22:54:724 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-12-17 16:23:22:757 SkywalkingAgent-4-JVMService-consume-0 JVMService : send JVM metrics to Collector fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29999852980ns
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at org.apache.skywalking.apm.network.language.agent.v2.JVMMetricReportServiceGrpc$JVMMetricReportServiceBlockingStub.collect(JVMMetricReportServiceGrpc.java:158)
        at org.apache.skywalking.apm.agent.core.jvm.JVMService$Sender.run(JVMService.java:145)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

DEBUG 2019-12-17 16:23:24:721 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:false. 
ERROR 2019-12-17 16:23:24:728 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29999863629ns
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$ServiceInstancePingBlockingStub.doPing(ServiceInstancePingGrpc.java:158)
        at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:179)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

From dashboard of skywalking UI page, we can see that no data is collected from the client.
I have searched all the issues from github and no answers. So I hope to get useful help .
Thanks a lot.
![image](https://user-images.githubusercontent.com/15321530/70984256-1cc57380-20f5-11ea-80b7-3810ec8fe498.png)

**Comment by adventurer2008** [comment]
It seems that if there is no access to the tomcat server, the agent of skywalking think it's timeout more than 30s and it occurs exceptions.

**Comment by wu-sheng** [comment]
Please read the documentation, H2 is for demo only.

**Comment by adventurer2008** [comment]
Thanks a lot.  Let me try ES.
