### ISSUE TITLE
No metrics data to report to collector when client server is running for half an hour. 

### ISSUE THREAD

**Issue by adventurer2008** [apache/skywalking#4089]
Question
Skywalking is 6.6 and JDK is 1.8 and database is ES 6.8.

My client server is tomcat. when tomcat server with skywalking startup, everything is ok. Dashboard of skywalking can collect data and display normally. but after around half an hour , there are some errors from skywalking client logs, which is as below.

DEBUG 2019-12-17 16:22:45:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, **status:CONNECTED**.
DEBUG 2019-12-17 16:22:48:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-12-17 16:22:51:725 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-12-17 16:22:54:721 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:false.
DEBUG 2019-12-17 16:22:54:724 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED.
ERROR 2019-12-17 16:23:22:757 SkywalkingAgent-4-JVMService-consume-0 JVMService : **send JVM metrics to Collector fail.**
**org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29999852980ns**
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
at org.apache.skywalking.apm.network.language.agent.v2.JVMMetricReportServiceGrpc$JVMMetricReportServiceBlockingStub.collect(JVMMetricReportServiceGrpc.java:158)
at org.apache.skywalking.apm.agent.core.jvm.JVMService$Sender.run(JVMService.java:145)
at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

DEBUG 2019-12-17 16:23:24:721 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:false.
ERROR 2019-12-17 16:23:24:728 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29999863629ns
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$ServiceInstancePingBlockingStub.doPing(ServiceInstancePingGrpc.java:158)
at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:179)
at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

From dashboard of skywalking UI page, we can see that no data is collected and not data is reported to server from the client.
I have searched all the issues from github and no answers. So I hope to get useful help .
Thanks a lot.
![image](https://user-images.githubusercontent.com/15321530/71226703-bcfae280-2317-11ea-8412-2da10ffa33f9.png)

**Comment by wu-sheng** [comment]
DEADLINE_EXCEEDED means your OAP server is not responsing. Check your server side and storage(ES). They may be not healthy.

**Comment by adventurer2008** [comment]
It should be the problem of server side, because if I restart OAP server, then it's ok.
My ES storage  is green and health. The log of  OAP server is normal. I also can curl the port of OAP server  sucessfully.  I don't know why.

2019-12-20 15:58:34,185 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 355 [pool-11-thread-1] INFO  [] - Synchronous bulk took time: 1000 millis, size: 36
2019-12-20 15:58:38,192 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 355 [pool-11-thread-1] INFO  [] - Synchronous bulk took time: 1002 millis, size: 36
2019-12-20 15:58:42,195 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 355 [pool-11-thread-1] INFO  [] - Synchronous bulk took time: 967 millis, size: 36
2019-12-20 15:58:46,200 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 355 [pool-11-thread-1] INFO  [] - Synchronous bulk took time: 999 millis, size: 36
2019-12-20 15:58:50,205 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 355 [pool-11-thread-1] INFO  [] - Synchronous bulk took time: 1001 millis, size: 36

**Comment by wu-sheng** [comment]
The server side usually blocked by storage from my understanding. But, this is only my guess.

**Comment by adventurer2008** [comment]
I deployed  skywalking  to another server ,then it's ok.

**Comment by mcn259** [comment]
I also have same problem，How to resolve?

**Comment by skundu1234** [comment]
Hi Team,
Did you get resolution
