### ISSUE TITLE
Skywalking 6.5 version apm-spring-cloud-gateway-2.x-plugin cause error

### ISSUE THREAD

**Issue by Owenxh** [apache/skywalking#4110]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.5 
- Which company or project?
Spring Cloud Gateway 2.1.10.RELEASE
- What happen?
When I use apm-spring-cloud-gateway-2.x-plugin cause an error:
```java
org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.context.SWTransmitter cannot be cast to org.apache.skywalking.apm.agent.core.context.trace.AbstractSpan
```

 Here is the part of the log:

```java
ERROR 2019-12-23 20:57:29:967 reactor-http-nio-3 InstMethodsInter : class[class org.springframework.web.reactive.function.server.DefaultServerResponseBuilder$BodyInserterResponse] before method[writeToInternal] intercept failure
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.context.SWTransmitter cannot be cast to org.apache.skywalking.apm.agent.core.context.trace.AbstractSpan
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.AbstractServerResponseMethodInterceptor.beforeMethod(AbstractServerResponseMethodInterceptor.java:48)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at org.springframework.web.reactive.function.server.DefaultServerResponseBuilder$BodyInserterResponse.writeToInternal(DefaultServerResponseBuilder.java)
	at org.springframework.web.reactive.function.server.DefaultServerResponseBuilder$AbstractServerResponse.writeTo(DefaultServerResponseBuilder.java:351)
	at org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler.write(AbstractErrorWebExceptionHandler.java:298)
	at org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler.lambda$handle$2(AbstractErrorWebExceptionHandler.java:261)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
```

**Comment by wu-sheng** [comment]
Please try the master branch or use next 6.6.0 release(will be soon). There are several fixes happened there.
