### ISSUE TITLE
I can shorten elasticsearch index name

### ISSUE THREAD

**Issue by huangkaiyan10** [apache/skywalking#4136]
I wanted to use elassandra's elasticsearch feature on this project and integrate skywalking link tracking to discover this problem.I used the skywalking version is apache-skywalking-apm-6.5.0.

[cassandra] Both keyspace and table name should be comprised of only alphanumeric characters, cannot be empty and are limited in size to 48 characters (that limit exists mostly to avoid filenames (which may include the keyspace and table name) to go over the limits of certain file systems). By default, keyspace and table names are case insensitive (myTable is equivalent to mytable) but case sensitivity can be forced by using double-quotes ("myTable" is different from mytable).

Below is the error log

2019-12-26 16:38:15,547 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - Elasticsearch exception [type=invalid_request_exception, reason=Keyspace names shouldn't be more than 48 characters long (got "instance_clr_available_completion_port_threads_hour_20191226")]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=invalid_request_exception, reason=Keyspace names shouldn't be more than 48 characters long (got "instance_clr_available_completion_port_threads_hour_20191226")]
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:168) ~[library-client-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:82) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:136) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.5.0.jar:6.5.0]
at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.5.0.jar:6.5.0]

**Comment by wu-sheng** [comment]
Could you share which storage are you using?

**Comment by kezhenxu94** [comment]
@huangkaiyan10 so Cassandra ElasticSearch is a variation of ElasticSearch? If you must use Cassandra ElasticSearch, I think you may need to find out how to cancel the limitations on key space length on Cassandra side, at least, I don’t think we’ll provide another storage type specifically for this variation, will we @wu-sheng ? If the only difference is indices name length, maybe a config item to shorten the names, but it really needs investigation on the differences.

**Comment by huangkaiyan10** [comment]
> Could you share which storage are you using?

Cassandra as a store for elasticsearch. Cassandra has a limitation, Keyspace and table name are limited in size to 48 characters (that limit exists mostly to avoid filenames (which may include the keyspace and table name) to go over the limits of certain file systems)

**Comment by huangkaiyan10** [comment]
@kezhenxu94  Cassandra as a store for elasticsearch. Cassandra has a limitation, Keyspace and table names are limited in size to 48 characters (that limit exists mostly to avoid filenames (which may include the keyspace and table name) to go over the limits of certain files Systems). Settings are not currently provided to resolve this issue

**Comment by wu-sheng** [comment]
We don't have that, as we even don't know this use case. But how do you expect to make the name shorter? Most names are defined in OAL and widely used UI, CLI and many 3rd party systems, even commercial production. 

Could you indicate what you want to do?

**Comment by huangkaiyan10** [comment]
@wu-sheng use Cassandra as a store for elasticsearch.

**Comment by wu-sheng** [comment]
I know that part, I mean what do you want to change in your mind? Simply changing the name is very hard to be accepted by the community. And you will break a lot of things.

**Comment by huangkaiyan10** [comment]
if I want use  Cassandra as a store ，the name is limited in size to 48 characters 。cassandra's Keyspace and table names are limited in size to 48 characters .

**Comment by huangkaiyan10** [comment]
@wu-sheng if I want use Cassandra as a store ，the name is limited in size to 48 characters 。cassandra's Keyspace and table names are limited in size to 48 characters .

**Comment by wu-sheng** [comment]
I have already known that. But my question is, what do you want from us? Clearly, we are impossible to change all names to follow your requirements, they are bounded in the codes everywhere.

**Comment by wu-sheng** [comment]
Any further discussion?
