### ISSUE TITLE
The binding 11800 port address is occupied

### ISSUE THREAD

**Issue by chndu** [apache/skywalking#4168]
Please answer these questions before submitting your issue.

2019-12-31 04:03:16,227 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in receiver-register module.
2019-12-31 04:03:16,227 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in service-mesh module.
2019-12-31 04:03:16,228 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in receiver-jvm module.
2019-12-31 04:03:16,229 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in istio-telemetry module.
2019-12-31 04:03:16,230 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in receiver-clr module.
2019-12-31 04:03:16,231 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the elasticsearch7 provider in storage module.
2019-12-31 04:03:16,684 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the standalone provider in cluster module.
2019-12-31 04:03:16,685 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in core module.
2019-12-31 04:03:32,044 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 111 [main] INFO  [] - Server started, host 0.0.0.0 listening on 11800
2019-12-31 04:03:32,255 - org.eclipse.jetty.util.log - 192 [main] INFO  [] - Logging initialized @21205ms to org.eclipse.jetty.util.log.Slf4jLog
2019-12-31 04:03:32,856 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 68 [main] INFO  [] - http server root context path: /
2019-12-31 04:03:33,199 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the graphql provider in query module.
2019-12-31 04:03:34,625 - com.coxautodev.graphql.tools.SchemaClassScanner - 155 [main] WARN  [] - Schema type was defined but can never be accessed, and can be safely deleted: NodeType
2019-12-31 04:03:37,087 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in alarm module.
2019-12-31 04:03:37,715 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in envoy-metric module.
2019-12-31 04:03:37,716 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the none provider in configuration module.
2019-12-31 04:03:37,719 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider standalone in cluster module.
2019-12-31 04:03:37,719 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider none in configuration module.
2019-12-31 04:03:37,719 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider graphql in query module.
2019-12-31 04:03:37,762 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler GraphQLQueryHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:37,836 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider none in telemetry module.
2019-12-31 04:03:37,837 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in core module.
2019-12-31 04:03:37,843 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler RemoteServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:38,005 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler HealthCheckServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:39,099 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.database.DatabaseStatementDispatcher is added into DefaultScopeDefine 18.
2019-12-31 04:03:39,099 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.relation.instance.ServiceInstanceCallRelationDispatcher is added into DefaultScopeDefine 5.
2019-12-31 04:03:39,100 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.segment.SegmentDispatcher is added into DefaultScopeDefine 12.
2019-12-31 04:03:39,100 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.endpointrelation.EndpointCallRelationDispatcher is added into DefaultScopeDefine 6.
2019-12-31 04:03:39,101 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.log.HTTPAccessLogDispatcher is added into DefaultScopeDefine 25.
2019-12-31 04:03:39,101 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.analysis.manual.relation.service.ServiceCallRelationDispatcher is added into DefaultScopeDefine 4.
2019-12-31 04:03:41,576 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.AllDispatcher is added into DefaultScopeDefine 0.
2019-12-31 04:03:41,576 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceJVMMemoryDispatcher is added into DefaultScopeDefine 9.
2019-12-31 04:03:41,577 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceCLRGCDispatcher is added into DefaultScopeDefine 20.
2019-12-31 04:03:41,577 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceCLRThreadDispatcher is added into DefaultScopeDefine 21.
2019-12-31 04:03:41,577 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceDispatcher is added into DefaultScopeDefine 1.
2019-12-31 04:03:41,578 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceDispatcher is added into DefaultScopeDefine 2.
2019-12-31 04:03:41,578 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceJVMCPUDispatcher is added into DefaultScopeDefine 8.
2019-12-31 04:03:41,578 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceRelationDispatcher is added into DefaultScopeDefine 5.
2019-12-31 04:03:41,579 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceRelationDispatcher is added into DefaultScopeDefine 4.
2019-12-31 04:03:41,579 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.EndpointRelationDispatcher is added into DefaultScopeDefine 6.
2019-12-31 04:03:41,580 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.EndpointDispatcher is added into DefaultScopeDefine 3.
2019-12-31 04:03:41,580 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceCLRCPUDispatcher is added into DefaultScopeDefine 19.
2019-12-31 04:03:41,634 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.DatabaseAccessDispatcher is added into DefaultScopeDefine 17.
2019-12-31 04:03:41,634 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.ServiceInstanceJVMGCDispatcher is added into DefaultScopeDefine 11.
2019-12-31 04:03:41,634 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager - 120 [main] INFO  [] - Dispatcher org.apache.skywalking.oal.rt.dispatcher.EnvoyInstanceMetricDispatcher is added into DefaultScopeDefine 22.
2019-12-31 04:03:41,635 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in alarm module.
2019-12-31 04:03:41,635 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider elasticsearch7 in storage module.
2019-12-31 04:03:41,636 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 157 [main] INFO  [] - elasticsearch cluster nodes: 192.168.253.100:9200
2019-12-31 04:03:52,527 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-sharing-server module.
2019-12-31 04:03:52,530 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in service-mesh module.
2019-12-31 04:03:52,695 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 71 [main] INFO  [] - Try to lock buffer directory, directory is: /home/skywalking/apache-skywalking/bin/../mesh-buffer
2019-12-31 04:03:52,725 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 84 [main] INFO  [] - Lock buffer directory successfully, directory is: /home/skywalking/apache-skywalking/bin/../mesh-buffer
2019-12-31 04:03:52,947 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler MeshGRPCHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:52,954 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-register module.
2019-12-31 04:03:52,955 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler ApplicationRegisterHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:52,988 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler InstanceDiscoveryServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,028 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler ServiceNameDiscoveryHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,032 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler NetworkAddressRegisterServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,104 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler RegisterServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,154 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler ServiceInstancePingServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,198 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler ApplicationRegisterServletHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,200 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler InstanceDiscoveryServletHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,202 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler InstanceHeartBeatServletHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,234 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler NetworkAddressRegisterServletHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,236 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler ServiceNameDiscoveryServiceHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,236 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-clr module.
2019-12-31 04:03:53,243 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler CLRMetricReportServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,278 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-trace module.
2019-12-31 04:03:53,280 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler TraceSegmentServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,371 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler TraceSegmentReportServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,376 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 74 [main] INFO  [] - Bind handler TraceSegmentServletHandler into jetty server 0.0.0.0:12800
2019-12-31 04:03:53,388 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 71 [main] INFO  [] - Try to lock buffer directory, directory is: /home/skywalking/apache-skywalking/bin/../trace-buffer/v5
2019-12-31 04:03:53,389 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 84 [main] INFO  [] - Lock buffer directory successfully, directory is: /home/skywalking/apache-skywalking/bin/../trace-buffer/v5
2019-12-31 04:03:53,495 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 71 [main] INFO  [] - Try to lock buffer directory, directory is: /home/skywalking/apache-skywalking/bin/../trace-buffer
2019-12-31 04:03:53,495 - org.apache.skywalking.oap.server.library.buffer.BufferStream - 84 [main] INFO  [] - Lock buffer directory successfully, directory is: /home/skywalking/apache-skywalking/bin/../trace-buffer
2019-12-31 04:03:53,566 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in envoy-metric module.
2019-12-31 04:03:53,567 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler MetricServiceGRPCHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,591 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler AccessLogServiceGRPCHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,654 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in istio-telemetry module.
2019-12-31 04:03:53,657 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler IstioTelemetryGRPCHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,706 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in receiver-jvm module.
2019-12-31 04:03:53,711 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler JVMMetricsServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:53,758 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 138 [main] INFO  [] - Bind handler JVMMetricReportServiceHandler into gRPC server 0.0.0.0:11800
2019-12-31 04:03:55,132 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 59 [main] ERROR [] - Failed to bind
org.apache.skywalking.oap.server.library.module.ModuleStartException: Failed to bind
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:211) ~[server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:67) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:68) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-es7-6.6.0.jar:6.6.0]
Caused by: org.apache.skywalking.oap.server.library.server.grpc.GRPCServerException: Failed to bind
	at org.apache.skywalking.oap.server.library.server.grpc.GRPCServer.start(GRPCServer.java:133) ~[library-server-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:208) ~[server-core-6.6.0.jar:6.6.0]
	... 4 more
Caused by: java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:252) ~[grpc-netty-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:163) ~[grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:78) ~[grpc-core-1.15.1.jar:1.15.1]
	at org.apache.skywalking.oap.server.library.server.grpc.GRPCServer.start(GRPCServer.java:131) ~[library-server-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:208) ~[server-core-6.6.0.jar:6.6.0]
	... 4 more
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_191]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_191]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_191]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]

**Comment by wu-sheng** [comment]
Your `ip:port` is being used. Nothing special.
