### ISSUE TITLE
30,000 milliseconds timeout on connection http-outgoing-1018 [ACTIVE]

### ISSUE THREAD

**Issue by JCchenxiang** [apache/skywalking#4232]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I upgrade Skywalking to 6.6 with elasticsearch7.2, oap logs keep reporting the following  error，What does it mean and how can i fix it?
----
2020-01-14 10:43:18,455 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 262 [pool-11-thread-1] ERROR [] - 30,000 milliseconds timeout on connection http-outgoing-1018 [ACTIVE]
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1018 [ACTIVE]
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:789) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.synchronousBulk(ElasticSearch7Client.java:259) ~[storage-elasticsearch7-plugin-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.synchronous(BatchProcessEsDAO.java:70) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:111) ~[server-core-6.6.0.jar:6.6.0]

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is just your ES server unreachable.

**Comment by JCchenxiang** [comment]
no,my ES server is reachable.Skywalking UI  is normal，but The above error log will be printed at intervals。And I found in the trace dashboard there are only 10,000 traces, in fact more than it
![image](https://user-images.githubusercontent.com/37063302/72323385-909e7000-36e3-11ea-8239-7a0c52a4319f.png)

**Comment by wu-sheng** [comment]
My point is, that this is not in the SkyWalking control.  Maybe ES is not powerful enough, you need to scale out.

**Comment by WJC101** [comment]
> no,my ES server is reachable.Skywalking UI is normal，but The above error log will be printed at intervals。And I found in the trace dashboard there are only 10,000 traces, in fact more than it
> ![image](https://user-images.githubusercontent.com/37063302/72323385-909e7000-36e3-11ea-8239-7a0c52a4319f.png)

I have this problem too,when i uesd elasticsearch7.2,it whill be happend,but my ES server  is reachable too.
Do you solve it?

![image](https://user-images.githubusercontent.com/51395991/78049949-4063af80-73ae-11ea-8ce5-f4ed03b95796.png)

**Comment by WJC101** [comment]
I found a similar problem,but I don't know where to configure it in application.yml

https://segmentfault.com/a/1190000021669853

**Comment by wlyu** [comment]
The error frequency is     SW_STORAGE_ES_FLUSH_INTERVAL
It always exists error!
8.0.1+es7.6.1
how  to resolve ?
