### ISSUE TITLE
Getting Exception while jboss fuse JVM start Up with java agent

### ISSUE THREAD

**Issue by VishalShahare** [apache/skywalking#4323]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ yes] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to get skywailking java agent working for jboss fuse application.
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.6.0, linux, java 1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
getting below error while starting the {jboss fuse} JVM with skywalking java agent.

Error during instantiation of the implementation object
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withSerializationInclusion(Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/SerializationConfig;
        at io.fabric8.insight.log.service.LogQuery.<init>(LogQuery.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.8.0_74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[:1.8.0_74]
        at java.lang.Class.newInstance(Class.java:442)[:1.8.0_74]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:253)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:127)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:871)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:838)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:850)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:419)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:376)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialize(BundleComponentActivator.java:172)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.BundleComponentActivator.<init>(BundleComponentActivator.java:120)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:258)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.Activator.access$000(Activator.java:45)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:185)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)[152:org.apache.felix.scr:1.8.4]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:479)[152:org.apache.felix.scr:1.8.4]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:414)[152:org.apache.felix.scr:1.8.4]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)[152:org.apache.felix.scr:1.8.4]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443)[152:org.apache.felix.scr:1.8.4]
        at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:869)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:790)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:515)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2100)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)[org.apache.felix.framework-4.4.1.jar:]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)[org.apache.felix.framework-4.4.1.jar:]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am not sure who has experienced working on JBoss fuse. And I noticed that you are using apache `felix`, which is OSGI framework. I don't use SkyWalking agent on that too.

**Comment by VishalShahare** [comment]
Issue got resolved.
Added below JVM argument in addition to the skywalking java agent argument.   
 -Xbootclasspath/p:{Path To}/jackson-annotations-2.5.0.jar:{Path To}/jackson-core-2.5.4.jar:{Path To}/jackson-databind-2.5.4.jar

**Comment by wu-sheng** [comment]
Could you submit a FAQ for this? Add a markdown linked from here. https://github.com/apache/skywalking/blob/master/docs/en/FAQ/README.md#runtime
