### ISSUE TITLE
About Upgrade 6.2.0 to 6.6.0 questions

### ISSUE THREAD

**Issue by dengliming** [apache/skywalking#4352]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

When I upgrade skywalking 6.2.0 to 6.6.0, The following exception occurs.

2020-02-12 11:28:01,989 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.NetworkAddressInventoryCacheEsDAO - 78 [grpcServerPool-1-thread-2] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.NetworkAddressInventory$Builder.map2Data(NetworkAddressInventory.java:151) ~[server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.NetworkAddressInventoryCacheEsDAO.get(NetworkAddressInventoryCacheEsDAO.java:73) [storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.cache.NetworkAddressInventoryCache.get(NetworkAddressInventoryCache.java:80) [server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.register.service.NetworkAddressInventoryRegister.update(NetworkAddressInventoryRegister.java:113) [server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanExchanger.exchange(SpanExchanger.java:118) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:161) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:104) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:282) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:57) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:49) [skywalking-trace-receiver-plugin-6.6.0.jar:6.6.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dengliming** [comment]
Is there any way to solve this？And there is no official update documentation. @wu-sheng

**Comment by wu-sheng** [comment]
Read FAQ, doc is there.
