### ISSUE TITLE
GRPCChannelManager : Create channel to  fail

### ISSUE THREAD

**Issue by Felicite93** [apache/skywalking#4450]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [v] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the cause? help me, thanks.
___
### Bug
- Which version of SkyWalking, OS and JRE?
   version: 6.6.0
   OS: centos 4.14.123-111.109.amzn2.x86_64
  JDK version: 1.8.0_121
- Which company or project?

- What happen?
 I remove the apm-vertx-core-3.x-plugin-6.6.0.jar from the plugins
___
### log
DEBUG 2020-03-06 12:13:18:636 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2020-03-06 12:13:21:583 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:true. 
ERROR 2020-03-06 12:13:21:584 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Create channel to  fail. 
java.lang.NullPointerException
        at org.apache.skywalking.apm.agent.core.remote.GRPCChannelManager.run(GRPCChannelManager.java:122)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

DEBUG 2020-03-06 12:13:21:585 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service is not available. Wait 30 seconds to retry 
DEBUG 2020-03-06 12:13:21:638 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT.
>

**Comment by wu-sheng** [comment]
I am not sure what is happening.  I could just say the `managedChannel` is NULL somehow.

https://github.com/apache/skywalking/blob/v6.6.0/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/GRPCChannelManager.java#L122

**Comment by wu-sheng** [comment]
Need you local debug to see what happens.
