### ISSUE TITLE
how can i use receiver_zipkin for es7 

### ISSUE THREAD

**Issue by HuiHang-Yu** [apache/skywalking#4479]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
how can i use receiver_zipkin for es7 storage

**Comment by HuiHang-Yu** [comment]
In my case , i find the below exception when i use receiver_zipkin and zipkin-elasticsearch storage .

  org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:121) ~[library-client-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:133) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-es7-6.6.0.jar:6.6.0]

**Comment by wu-sheng** [comment]
I don't think the elasticsearch7 is not available for this. @kezhenxu94 Correct me if I am wrong.
