### ISSUE TITLE
2020-03-10 12:21:46,199 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 362 [pool-11-thread-1] ERROR [] - listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#4480]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lsy1990** [comment]
2020-03-10 12:21:46,199 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 362 [pool-11-thread-1] ERROR [] - listener timeout after waiting for [30000] ms
java.io.IOException: listener timeout after waiting for [30000] ms
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:684) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:259) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.synchronousBulk(ElasticSearchClient.java:359) ~[library-client-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO.synchronous(BatchProcessEsDAO.java:70) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:111) ~[server-core-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:67) ~[server-core-6.6.0.jar:6.6.0]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.6.0.jar:6.6.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

**Comment by lsy1990** [comment]
@wu-sheng 大神好，我这里在试用skywalking，因为是试用，所以在k8s上简单部署了下es6.8.4， 挂载的是分布式存储。我已经将索引刷新时间改为60s，但是oap_server （也在k8s上），调用ES存储接口（http协议），非常频繁的报上面的错误。请问有什么部署建议，可以改进这个问题？

**Comment by wu-sheng** [comment]
English only.
