### ISSUE TITLE
i use es7  When start collector server,There an error : "storage module no provider exists"

### ISSUE THREAD

**Issue by MrZhouFor** [apache/skywalking#4581]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug

___
### Question
- What do you want to know?
i use es7  when start collector server, there an error : "storage module no provider exists".(Both versions 6.6 and 7.0 have this error.)
Hao can i start right collector? Thanks
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking version : 6.6 or 7.0  
elasticsearch version: 7.6.1    
OS version :  Linux version 3.10.0-1062.12.1.el7.x86_64  (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) 

- What happen?

**error log:**
```
2020-03-26 22:52:58,186 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in receiver-clr module.
2020-03-26 22:52:58,187 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 59 [main] ERROR [] - storage module no provider exists.
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: storage module no provider exists.
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:86) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:52) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-6.6.0.jar:6.6.0]
```

** V6.6 storage config:**
![image](https://user-images.githubusercontent.com/14541486/77727107-862e1a00-7034-11ea-91d7-6fc95b06e2cc.png)

**Comment by wu-sheng** [comment]
Read the documentation, there is one es7 package there.

**Comment by KiritoStudio** [comment]
I met the same issue. The resolution is download **Binary Distribution for ElasticSearch 7** instead of **Binary Distribution** from the [official download page](http://skywalking.apache.org/downloads/).

**Comment by mach8686devops** [comment]
> **Binary Distribution for ElasticSearch 7** instead of **Binary Distribution** from the [official download page](http://skywalking.apache.org/downloads/)

what is this mean? I do not get what is the difference
