### ISSUE TITLE
Data truncation: Data too long for column 'id' at row 1

### ISSUE THREAD

**Issue by thekernelthe** [apache/skywalking#4585]
In version 6.5, below errors will come up after running normally afer some days: 

2020-03-28 16:02:18,487 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 116 [DataCarrier.REGISTER_L2.BulkConsumePool.0.Thread] ERROR [] - Data truncation: Data too long for column 'id' at row 1
java.io.IOException: Data truncation: Data too long for column 'id' at row 1
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2RegisterDAO.forceInsert(H2RegisterDAO.java:52) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:113) ~[server-core-6.5.0.jar:6.5.0]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:95) [server-core-6.5.0.jar:6.5.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:40) [server-core-6.5.0.jar:6.5.0]
        at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:153) [server-core-6.5.0.jar:6.5.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.5.0.jar:6.5.0]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.5.0.jar:6.5.0]
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'id' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.19.jar:8.0.19]
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637) ~[mysql-connector-java-8.0.19.jar:8.0.19]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-connector-java-8.0.19.jar:8.0.19]
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[mysql-connector-java-8.0.19.jar:8.0.19]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:51) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2RegisterDAO.forceInsert(H2RegisterDAO.java:50) ~[storage-jdbc-hikaricp-plugin-6.5.0.jar:6.5.0]

Anyone knows how to fix it? Thanks.

**Comment by wu-sheng** [comment]
Duplicated.
