### ISSUE TITLE
[ERROR]  Elasticsearch exception index already exists

### ISSUE THREAD

**Issue by Hinsteny** [apache/skywalking#4596]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 Could multiple environments skywalking-oap-server use one same es cluster?
___
#### Details
- use skywalking-oap-server docker-hub image
`docker pull apache/skywalking-oap-server:6.6.0-es7`
- deploy in k8s config
```
        - name: SW_NAMESPACE
          value: skywalking
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: 10.10.102.34:9200
        - name: SW_ES_USER
          value: elastic
        - name: SW_ES_PASSWORD
          value: qexr_2020
        - name: SW_CLUSTER
          value: zookeeper
        - name: SW_CLUSTER_ZK_HOST_PORT
          value: 10.10.100.29:2181
```
- start docker container then get exception

```
2020-03-31 11:39:02,852 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -21877 [main] ERROR [] - Elasticsearch exception [type=resource_already_exists_exception, reason=index [skywalking_service_instance_relation_client_p50_hour-20200331/sTucbrZvTM6OmsybWB06kQ] already exists]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=resource_already_exists_exception, reason=index [skywalking_service_instance_relation_client_p50_hour-20200331/sTucbrZvTM6OmsybWB06kQ] already exists]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1385) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:125) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.createIndex(ElasticSearch7Client.java:95) ~[storage-elasticsearch7-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:86) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:138) ~[storage-elasticsearch7-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-es7-6.6.0.jar:6.6.0]
	Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://10.10.102.34:9200], URI [/skywalking_service_instance_relation_client_p50_hour-20200331?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [skywalking_service_instance_relation_client_p50_hour-20200331/sTucbrZvTM6OmsybWB06kQ] already exists","index_uuid":"sTucbrZvTM6OmsybWB06kQ","index":"skywalking_service_instance_relation_client_p50_hour-20200331"}],"type":"resource_already_exists_exception","reason":"index [skywalking_service_instance_relation_client_p50_hour-20200331/sTucbrZvTM6OmsybWB06kQ] already exists","index_uuid":"sTucbrZvTM6OmsybWB06kQ","index":"skywalking_service_instance_relation_client_p50_hour-20200331"},"status":400}
```

**Comment by wu-sheng** [comment]
@hanahmily @innerpeacez Any clue? This is new to me.

**Comment by dominicqi** [comment]
@wu-sheng v6.6.0  https://github.com/apache/skywalking/blob/cf6d53c79b9ddb6dfc1cff0d95a2e4dabea9d246/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/StorageEsInstaller.java#L84-L89    
The `isExistsIndex ` condition is the indexName without timeSeries。This is fixed in master . But this is  still not atomic ,should we ignore the exists exception?

**Comment by wu-sheng** [comment]
This is for template Check. There is no exist exception. It is normal whether existing or not.
The error is elasticsearch can't access.

**Comment by libinglong** [comment]
In my environment, it is the bad performance of es or bad network causing this exception.
The es client tries to create the index but timeout, and try agin.But the first creating success though timeout, then the second attempt fails with "resource_already_exists_exception".



![image](https://user-images.githubusercontent.com/38123153/108800615-99dc5a80-75ce-11eb-9058-220720d90584.png)
