### ISSUE TITLE
etcd 3.x DDC

### ISSUE THREAD

**Issue by smartisanyyh** [apache/skywalking#4606]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to fix it 
___
### Bug
- Which version of SkyWalking, OS and JRE?
- Which company or project?

- What happen?
I want to use the DDC feature with  etc  3.4.7 but  i got an error  while  starting oapserver   

2020-04-03 17:26:17,976 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - wait for etcd value change fail
org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigException: wait for etcd value change fail
        at org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigWatcherRegister.registerKeyListeners(EtcdConfigWatcherRegister.java:107) ~[configuration-etcd-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigWatcherRegister.readConfig(EtcdConfigWatcherRegister.java:70) ~[configuration-etcd-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.configSync(ConfigWatcherRegister.java:79) ~[configuration-api-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.start(ConfigWatcherRegister.java:67) ~[configuration-api-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.configuration.api.AbstractConfigurationProvider.notifyAfterCompleted(AbstractConfigurationProvider.java:53) ~[configuration-api-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:64) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:70) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-7.0.0.jar:7.0.0]
Caused by: org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigException: wait for value changed fail
        at org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigWatcherRegister.onDataValueChanged(EtcdConfigWatcherRegister.java:141) ~[configuration-etcd-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.configuration.etcd.EtcdConfigWatcherRegister.registerKeyListeners(EtcdConfigWatcherRegister.java:105) ~[configuration-etcd-7.0.0.jar:7.0.0]
        ... 8 more

look like  can't find the key 

i tried put the follow two  keys into etcd    with alarm config content   but it does't work
- /skywalking/alarm.default.alarm-settings
- alarm.default.alarm-settings

i don't know  what 'group' and 'clusterName' config is   maybe i config wrong
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read the dynamic config center, etcd pkugin, source codes. And March with the etcd doc.

**Comment by smartisanyyh** [comment]
i found that  org.mousio.etcd4j only  support etc2.x  that' why   i can't  startup

**Comment by wu-sheng** [comment]
Thanks for feedback.

**Comment by taidixiong** [comment]
can support etcd3.x?
