### ISSUE TITLE
vert.x plugin can not boot 

### ISSUE THREAD

**Issue by zohar-soul** [apache/skywalking#4609]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.6, OS debian 9 , jre openjdk version "11.0.6" 
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
with vert.x 3.8.5, vertx httpclient and HttpServerResponse can't start normally.

`ERROR 2020-04-05 15:15:09:096 main ConstructorInter : ConstructorInter failure. 
java.lang.ClassCastException: class io.vertx.core.net.impl.SocketAddressImpl cannot be cast to class java.lang.String (io.vertx.core.net.impl.SocketAddressImpl is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at org.apache.skywalking.apm.plugin.vertx3.HttpClientRequestImplEndInterceptor.onConstruct(HttpClientRequestImplEndInterceptor.java:46)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter.intercept(ConstructorInter.java:65)
        at io.vertx.core.http.impl.HttpClientRequestImpl.<init>(HttpClientRequestImpl.java)
        at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1108)
        at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1074)
        at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:606)
        at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:324)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:283)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
        at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:166)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:331)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:301)
        at org.lightink.reader.service.YueduSchedule.fetchShuyuan(YueduSchedule.kt:33)
        at org.lightink.reader.service.YueduSchedule.getBookSource(YueduSchedule.kt:25)
        at org.gosky.candlekeep.AppApplicationKt.main(AppApplication.kt:64)

ERROR 2020-04-05 15:15:09:192 main InstMethodsInter : class[class io.vertx.core.http.impl.HttpClientRequestImpl] before method[end] intercept failure 
java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
        at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:164)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:143)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:121)
        at org.apache.skywalking.apm.plugin.vertx3.HttpClientRequestImplEndInterceptor.beforeMethod(HttpClientRequestImplEndInterceptor.java:58)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java)
        at io.vertx.ext.web.client.impl.HttpContext.handleSendRequest(HttpContext.java:489)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:286)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
        at io.vertx.ext.web.client.impl.HttpContext.sendRequest(HttpContext.java:179)
        at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:356)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:283)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
        at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:166)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:331)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:301)
        at org.lightink.reader.service.YueduSchedule.fetchShuyuan(YueduSchedule.kt:33)
        at org.lightink.reader.service.YueduSchedule.getBookSource(YueduSchedule.kt:25)
        at org.gosky.candlekeep.AppApplicationKt.main(AppApplication.kt:64)`

vertx插件 与 vertx 3.8.5(当前最新正式版) 似乎不兼容的了.

目前skywalking的vertx 插件针对的vertx版本是多少呢?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by BFergerson** [comment]
Vert.x was only tested up to [3.7.x](https://github.com/SkyAPMTest/agent-auto-integration-testcases/blob/master/vertx-web-3.x-scenario/testcase.yml#L23).

I was going to look into this but I can't find the Vert.x scenarios which used to be run here: https://github.com/SkyAPMTest/agent-auto-integration-testcases

@wu-sheng, do you know why those tests were removed?

**Comment by wu-sheng** [comment]
@BFergerson Because all tests have been moved inside the main repo, and keep being tested in every PR. Could you read the plugin test doc again? We have updated there.

**Comment by BFergerson** [comment]
@wu-sheng, I understand plugin tests were moved to the main repo, I'm asking why the Vert.x tests weren't simply moved along with all the others. Was there someone wrong with them? I'm just curious why all the other scenarios made it over but not those. Either way, I'll get them updated for this repo.

**Comment by wu-sheng** [comment]
Because the transform needs some manual works. So, some have been done, some are not. 😁 The progress is tracked in #3583

**Comment by zohar-soul** [comment]
@BFergerson
i found in vertx 3.8.5 ,host = allArguments[4] and port = allArguments[5].
Also I found that io.vertx.ext.web.Router.accept () is deprecated, but the vert.x plugin seems to depend on this to take effect?

我发现router的accept方法被标记为废弃了,但是vertx 插件似乎依赖于这个方法来完成注入?

**Comment by zohar-soul** [comment]
@wu-sheng 
For each plugin of skywalking, is it possible to add a user guide or get started quickly?
Just like the vertx plugin depends on `vertx.createHttpServer (). RequestHandler (router :: accept) .listen (8080)`. This way of writing,
And usually everyone writes `vertx.createHttpServer (). RequestHandler (router) .listen (8080)`, because the accept method has been marked as abandoned as early as at least 3.6.x. It is difficult to find it without turning the source code Only use this to have endpoint data.

-------

对于skywalking的每个插件,是不是可以增加一个使用指南或者快速上手之类的呢?
就像vertx 插件依赖于 `vertx.createHttpServer().requestHandler(router::accept).listen(8080)`.这种写法,
而通常大家的写法是 `vertx.createHttpServer().requestHandler(router).listen(8080)`,因为accept方法早在至少3.6.x就已经被标记为废弃的了.不翻源码很难找到是必须使用这个才有endpoint的数据.

**Comment by wu-sheng** [comment]
@zohar-soul I think as an open source project with 200+ contributors, it is nearly impossible to write a documentation about this. Such as vert.x plugin was contributed by @BFergerson.

I have no production experiences about this library. So, I only review basing on codes and plugin test result. I still enough people to read source codes, and do collaboration. This is the only way to make the project better.

@BFergerson Please consider the 2 kinds of APIs.

**Comment by zohar-soul** [comment]
@wu-sheng 
Well, I mean, I hope that plugin may have a simple readme provided by the author to describe the relevant introductions. :P
--------

嗯,我的意思是期望每个插件也许可以有作者提供一个简单的readme来描述下相关介绍之类的.

**Comment by BFergerson** [comment]
I will work on moving the Vert.x scenarios and adding support for Vert.x 3.8.x this week.

@zohar-soul, I don't think any of the plugins have documentation. What @wu-sheng said above is the best case for figuring out how the plugin works. The documentation for Apache SkyWalking is pretty good and for me to explain how the plugin works I would literally have to re-iterate what's already documented in this project given that it relies heavily on the project itself to work. The code for getting Vert.x to work with Apache SkyWalking is < 1000 LOC so the plugin support itself is not the complicated part. See: [Plugin Development Guide](https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md)

As for the deprecated methods, you should understand that the Vert.x plugin strives to work with the largest range of versions possible so there may be mentions of deprecated (and even removed) functionality without the plugin itself. With that being said, the code you posted is not actually present in the plugin but rather present in the plugin's test code. Changing that test code wouldn't fix your issue but actually might break the ability to test versions prior to 3.6.x. I'll try to remove it but I imagine I'll end up needing to write an additional test instead.

**Comment by zohar-soul** [comment]
@BFergerson 
en,I understand, thank for you help :)

**Comment by wu-sheng** [comment]
@BFergerson Does PR #4624 help this issue?

**Comment by BFergerson** [comment]
@wu-sheng, nope. Working on this next

**Comment by wu-sheng** [comment]
@zohar-soul You could try PR #4736

**Comment by zohar-soul** [comment]
@wu-sheng 
ok, it works.
👍

**Comment by wu-sheng** [comment]
@zohar-soul You have tested it already? So quickly you are.
