### ISSUE TITLE
kafka plugin ERROR

### ISSUE THREAD

**Issue by heytong** [apache/skywalking#4652]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking 7.0

ERROR 2020-04-15 10:26:09:123 Thread-16 ConstructorInter : ConstructorInter failure. 
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at org.apache.skywalking.apm.plugin.kafka.ProducerConstructorMapInterceptor.onConstruct(ProducerConstructorMapInterceptor.java:34)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter.intercept(ConstructorInter.java:65)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.createKafkaProducer(DefaultKafkaProducerFactory.java:405)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.createProducer(DefaultKafkaProducerFactory.java:391)
	at org.springframework.kafka.core.KafkaTemplate.getTheProducer(KafkaTemplate.java:463)
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:401)
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:216)
	
___
### Bug
- Which version of SkyWalking, OS and JRE?
el7, openjdk version "1.8.0_242"
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please check whether your Kafka client/server versions in our supported list.

**Comment by heytong** [comment]
> Please check whether your Kafka client/server versions in our supported list.

where is the url for supported list of  kafka version, please.
thanks.

**Comment by wu-sheng** [comment]
It is in the agent set up document. Please read the document.

**Comment by heytong** [comment]
<dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka</artifactId>
                <version>2.3.4.RELEASE</version>
            </dependency>

**Comment by heytong** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md

can not find spring-kafka

**Comment by wu-sheng** [comment]
Then there isn't. We haven't tested it and don't provide it officially. If you need that, try to read plugin development doc and plugin test doc, we could accept a new plugin for this.

**Comment by heytong** [comment]
> Then there isn't. We haven't tested it and don't provide it officially. If you need that, try to read plugin development doc and plugin test doc, we could accept a new plugin for this.

But, this error log loop forever.   
30G error logs per hour.
I can not use skywalking trace in this project.

**Comment by wu-sheng** [comment]
You could remove the kafka plugin, then everything should be fine, just trace and topology breaks at this point.
