### ISSUE TITLE
skywalking7.0-es  tomcat8 ,agent log error

### ISSUE THREAD

**Issue by Huangzsnone** [apache/skywalking#4659]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
packages:apache-skywalking-apm-bin-es7
agent  :tomcat 8 
agent log error
ERROR 2020-04-16 15:32:04:512 http-nio-8080-exec-9 InstMethodsInter : class[class com.mysql.jdbc.JDBC42CallableStatement] after method[execute] intercept failure 
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/plugin/jdbc/define/StatementEnhanceInfos
	at org.apache.skywalking.apm.plugin.jdbc.mysql.PreparedStatementExecuteMethodsInterceptor.afterMethod(PreparedStatementExecuteMethodsInterceptor.java:79)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
	at com.mysql.jdbc.CallableStatement.execute(CallableStatement.java)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at com.simuwang.dataservice.sql.SqlDao$5.doInCallableStatement(SqlDao.java:158)
	at com.simuwang.dataservice.sql.SqlDao$5.doInCallableStatement(SqlDao.java:151)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1083)
	at com.simuwang.dataservice.sql.SqlDao.query(SqlDao.java:143)
	at com.simuwang.dataservice.sql.SqlDao.query(SqlDao.java:133)
	at com.simuwang.dataservice.service.IndicatorServiceImpl.getNames(IndicatorServiceImpl.java:135)
	at com.simuwang.dataservice.service.IndicatorServiceImpl.getIndicatorRanges(IndicatorServiceImpl.java:376)
	at com.simuwang.dataservice.service.guojun.AllProAnalysisServiceImpl.getHistoryReturn(AllProAnalysisServiceImpl.java:64)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController.getHistoryReturn$original$kCqLDMzX(AllProAnalysisController.java:80)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController.getHistoryReturn$original$kCqLDMzX$accessor$K8jwwu7x(AllProAnalysisController.java)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController$auxiliary$JGnIPdqV.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController.getHistoryReturn(AllProAnalysisController.java)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController$$FastClassBySpringCGLIB$$456def8c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
	at com.simuwang.dataservice.aop.DataServiceAOP.spentTime(DataServiceAOP.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.simuwang.dataservice.controller.v1.guojun.AllProAnalysisController$$EnhancerBySpringCGLIB$$c2a1bc93.getHistoryReturn(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$9lqDpcWo(InvocableHandlerMethod.java:133)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$9lqDpcWo$accessor$ac5bx76o(InvocableHandlerMethod.java)
	at org.springframework.web.method.support.InvocableHandlerMethod$auxiliary$fygOCWHk.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke$original$kmJIGcCC(StandardHostValve.java:140)
	at org.apache.catalina.core.StandardHostValve.invoke$original$kmJIGcCC$accessor$KTzOCiZv(StandardHostValve.java)
	at org.apache.catalina.core.StandardHostValve$auxiliary$fSaPrwhf.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment]
Seems like a MySQL plugin issue. Please make sure the version is in the supported list.

**Comment by Huangzsnone** [comment]
the mysql version,our mysql version is 5.7.27

**Comment by wu-sheng** [comment]
According to https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/mysql-scenario, I think we didn't test 5.7.27.

Here are the tested version list, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/mysql-scenario/support-version.list.

If 5.7 has some incompatible changes, the plugin is required to follow those change. If you are interesting, consider to debug why and send a pull request to fix this.

**Comment by Huangzsnone** [comment]
I think if the JDBC.Driver plugin is not supported ,the log have same WARN:
WARN 2020-04-16 16:09:48:618 http-nio-8080-exec-1 AbstractClassEnhancePluginDefine : enhance class com.mysql.jdbc.Driver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.DriverInstrumentation is not working. Because witness class **com.mysql.cj.api.MysqlConnection is not existed**. 
WARN 2020-04-16 16:09:48:638 http-nio-8080-exec-1 AbstractClassEnhancePluginDefine : enhance class com.mysql.jdbc.NonRegisteringDriver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.DriverInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed.

**Comment by wu-sheng** [comment]
That is v6 detection mechanism. You are facing incompatible in the 5.x

**Comment by Huangzsnone** [comment]
OK,Tks，I try it again.
