### ISSUE TITLE
[Question]skywalking 使用envoy接入istio报错

### ISSUE THREAD

**Issue by HashTableHu** [apache/skywalking#4687]
使用版本：
skywalking 7；es：6.5.4
问题描述：skywalking接收数据失败，连不上istio
配置：
envoy-metric:
  selector: ${SW_ENVOY_METRIC:default}
  default:
    alsHTTPAnalysis: ${SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS:"k8s-mesh"}
出错日志如下：
2020-04-22 10:45:08,870 - org.apache.skywalking.oap.server.receiver.envoy.als.K8sALSServiceMeshHTTPAnalysis - 122 [load-pod-0] ERROR [] - run load pod error
io.kubernetes.client.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801) ~[client-java-api-4.0.0.jar:?]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18795) ~[client-java-api-4.0.0.jar:?]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18773) ~[client-java-api-4.0.0.jar:?]
	at org.apache.skywalking.oap.server.receiver.envoy.als.K8sALSServiceMeshHTTPAnalysis.loadPodInfo(K8sALSServiceMeshHTTPAnalysis.java:101) ~[envoy-metrics-receiver-plugin-7.0.0.jar:7.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponse(Call.java:286) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.execute(Call.java:80) ~[okhttp-2.7.5.jar:?]
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:797) ~[client-java-api-4.0.0.jar:?]
	... 10 more
2020-04-22 10:45:09,201 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 94 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2020-04-22 10:45:09,211 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2020-04-22 10:45:09,332 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@6df791a4{/,null,AVAILABLE}
2020-04-22 10:45:09,386 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@30ec211a{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2020-04-22 10:45:09,390 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @16512ms
2020-04-22 10:45:09,394 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 59 [main] INFO  [] - persistence timer start
2020-04-22 10:45:09,414 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 50 [main] INFO  [] - Cache updateServiceInventory timer start
2020-04-22 10:45:23,578 - org.apache.skywalking.oap.server.receiver.envoy.als.K8sALSServiceMeshHTTPAnalysis - 122 [load-pod-0] ERROR [] - run load pod error
io.kubernetes.client.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801) ~[client-java-api-4.0.0.jar:?]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18795) ~[client-java-api-4.0.0.jar:?]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18773) ~[client-java-api-4.0.0.jar:?]
	at org.apache.skywalking.oap.server.receiver.envoy.als.K8sALSServiceMeshHTTPAnalysis.loadPodInfo(K8sALSServiceMeshHTTPAnalysis.java:101) ~[envoy-metrics-receiver-plugin-7.0.0.jar:7.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponse(Call.java:286) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.execute(Call.java:80) ~[okhttp-2.7.5.jar:?]
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:797) ~[client-java-api-4.0.0.jar:?]
	... 10 more

**Comment by wu-sheng** [comment]
English only, if you are using als, you need to allow skywalking to access api server.

**Comment by HashTableHu** [comment]
sorry!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Does skyking 7 support istio1.4 or better ,The official document says very little about how to use envoy to access istio and the required configuration is not very detailed. Can you give me a complete configuration?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 中午11:03
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question]skywalking 使用envoy接入istio报错 (#4687)





 
English only, if you are using als, you need to allow skywalking to access api server.

**Comment by wu-sheng** [comment]
In the ALS level, it is not related to istio version. We don't access isitio in the ALS solution, it is an abstract solution, we have an CNCF session about this, https://www.youtube.com/watch?v=tERm39ju9ew.

**Comment by HashTableHu** [comment]
In other words, skywalking was only tested with istio mixer and not with envoy,&nbsp;Use envoy to receive data&nbsp;just an ideal route。Can I understand that?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 中午11:47
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question]skywalking 使用envoy接入istio报错 (#4687)





 
In the ALS level, it is not related to istio version. We don't access isitio in the ALS solution, it is an abstract solution, we have an CNCF session about this, https://www.youtube.com/watch?v=tERm39ju9ew.

**Comment by wu-sheng** [comment]
You are not right. Please watch the video I posted, it is about what is ALS solution. If you want mixer solution, we have only supported 1.3.3. Mixer usually keeps changing, but basically, if you understand the mixder bypass adaptor config, you still could make it work at there.

**Comment by HashTableHu** [comment]
I have successfully accessed skywalking with istio mixer adaptor, but there are some problems with envoy.I'm going to watch the video and figure it out.Thank you very much!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 中午11:59
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question]skywalking 使用envoy接入istio报错 (#4687)





 
You are not right. Please watch the video I posted, it is about what is ALS solution. If you want mixer solution, we have only supported 1.3.3. Mixer usually keeps changing, but basically, if you understand the mixder bypass adaptor config, you still could make it work at there.
