### ISSUE TITLE
[Question] skywalking receiver reports an error of "Unexpected HTTP/1.x " 

### ISSUE THREAD

**Issue by HashTableHu** [apache/skywalking#4704]
Version information:
1.skywalking v6.5
2.elasticsearch v6.5
3.linux（ARM64）

description:
When the Java agent sends data to the skywalking collector port 11800, the skywalking receiver reports an error as follows:

四月 24, 2020 1:37:25 下午 io.grpc.netty.NettyServerTransport notifyTerminated
信息: Transport failed
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /Register/doServiceRegister 
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

please!

**Comment by wu-sheng** [comment]
You are sending HTTP 1 data to the gRPC port. I don't understand how do you make this. Our agents don't use HTTP protocol, except for Nginx Lua.

**Comment by HashTableHu** [comment]
Oh, that's how I use the command. Is that right?

java -javaagent:/skywalking/skywalking-agent.jar -Dskywalking.agent.service_name=cloud-user -Dskywalking.collector.backend_service=192.168.40.205:11800 -Duser.timezone=GMT+08 -jar officeplatform-0.0.1-SNAPSHOT.jar

**Comment by HashTableHu** [comment]
> You are sending HTTP 1 data to the gRPC port. I don't understand how do you make this. Our agents don't use HTTP protocol, except for Nginx Lua.

**Comment by HashTableHu** [comment]
Oh, that's how I use the command. Is that right?

java -javaagent:/skywalking/skywalking-agent.jar -Dskywalking.agent.service_name=cloud-user -Dskywalking.collector.backend_service=192.168.40.205:11800 -Duser.timezone=GMT+08 -jar officeplatform-0.0.1-SNAPSHOT.jar






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 下午5:50
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question] skywalking receiver reports an error of "Unexpected HTTP/1.x "  (#4704)





 
You are sending HTTP 1 data to the gRPC port. I don't understand how do you make this. Our agents don't use HTTP protocol, except for Nginx Lua.

**Comment by wu-sheng** [comment]
Your command doesn't match the logs.

**Comment by HashTableHu** [comment]
Ok, I'll check it again.&nbsp;Thank you very much!
By the way,&nbsp;Is this command correct for the normal way of using Java agent??





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 晚上8:18
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question] skywalking receiver reports an error of "Unexpected HTTP/1.x "  (#4704)





 
Your command doesn't match the logs.

**Comment by wu-sheng** [comment]
The command should be right. The agent log will be there if the command is right.

**Comment by HashTableHu** [comment]
Ok, thank you very much！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴晟 Wu Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 上午9:46
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"胡国涛"<1144355028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] [Question] skywalking receiver reports an error of "Unexpected HTTP/1.x "  (#4704)





 
The command should be right. The agent log will be there if the command is right.

**Comment by 1450793561** [comment]
I also found this problem here, and I don't know how to solve it. Although it does not affect the sending of grpc, the oap side log keeps printing this

**Comment by XXMY** [comment]
> I also found this problem here, and I don't know how to solve it. Although it does not affect the sending of grpc, the oap side log keeps printing this

I accidentally mixed up the gRPC and HTTP ports. You might want to double-check yours.
