### ISSUE TITLE
OAP server failed when use es as storage

### ISSUE THREAD

**Issue by NilChow** [apache/skywalking#4723]
First time, I started my skywalking without change of storage config, it succeed.
But when I use the elasticsearch as storage, I got an error like this:

org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 59 [main] ERROR [] - org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:121) ~[library-client-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:133) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-es7-6.6.0.jar:6.6.0]

My skywalking version is : 6.6.0
elasticsearch version is : 6.5.4
And elasticsearch running successful, but skywalking oap-server failed, whar reason cause this error?

**Comment by wu-sheng** [comment]
My guess, you open `elasticsearch` as storage, but use `*-es7` binary tar.

**Comment by NilChow** [comment]
> My guess, you open `elasticsearch` as storage, but use `*-es7` binary tar.

I did a test : curl http:127.0.0.1:9200
and response info shows like this:
![image](https://user-images.githubusercontent.com/57666663/80346781-def40b00-889d-11ea-9dd9-dc7a2a2d0543.png)

**Comment by wu-sheng** [comment]
I mean SkyWalking tar, not ElasticSearch. We have 2 binary tars, one for es6, the other for es7. Please check our document and download page.

**Comment by NilChow** [comment]
yes, I use es7 binary tar. I thought it can compatible with es6. Thank you，>_<.
