### ISSUE TITLE
Agent 7 leads to OOM

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4730]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
sw7，es6，jdk8，agent7

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
After the agent is turned on, the server applies oom in less than 30 minutes
Here is the error log：
ERROR 2020-04-27 16:35:33:294 http-nio-8090-exec-12 InstMethodsInter : class[class org.apache.catalina.core.StandardHostValve] before method[throwable] intercept failure
java.lang.NullPointerException
        at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:171)
        at org.apache.skywalking.apm.plugin.tomcat78x.TomcatExceptionInterceptor.beforeMethod(TomcatExceptionInterceptor.java:31)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java)
        at org.apache.catalina.core.StandardHostValve.invoke$original$mlDaxxLY(StandardHostValve.java:173)
        at org.apache.catalina.core.StandardHostValve.invoke$original$mlDaxxLY$accessor$vdWW1lPn(StandardHostValve.java)
        at org.apache.catalina.core.StandardHostValve$auxiliary$an6yrGPU.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This seems an incompatible plugin issue. You need to find which plugin is causing this error.

**Comment by huohuanhuan** [comment]
Is it the plug-in in my application or your agent C

**Comment by wu-sheng** [comment]
SkyWalking agent plugin, this error means, the tomcat plugin can't find the span, which should be there. Most likely other plugin closed this unexpectedly.
