### ISSUE TITLE
use elasticsearch7.4.0 skywalking  doesn't work

### ISSUE THREAD

**Issue by sxiaoyuer** [apache/skywalking#4779]
Which version of SkyWalking, OS and JRE?
skywalking-7.0.0-es7, centos7.6, java8

Which company or project?
app which use elasticsearch7.4.0 

What happen?
2020-05-12 19:58:08,219 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - ../es_keystore.jks
org.apache.skywalking.oap.server.library.module.ModuleStartException: ../es_keystore.jks
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:224) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: java.nio.file.NoSuchFileException: ../es_keystore.jks
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_231]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_231]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_231]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_231]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_231]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_231]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_231]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_231]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createClient(ElasticSearchClient.java:151) ~[library-client-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:95) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:216) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]

**Comment by wu-sheng** [comment]
`../es_keystore.jks` has been provided if you open the username/password as the official image. If you don't want this, repackage the image by yourself, the docker files are here, https://github.com/apache/skywalking-docker

In the next 8.0.0 release, we will provide the username/password without jks requirement in the default image.

**Comment by chj9** [comment]
I also have the same error ,in version 7.0.0 my solution was
1. generate certificate
```
keytool -genkeypair -alias es_keystore -keypass es_keystore -keyalg RSA -keysize 1024 -validity 9999 -keystore es_keystore.jks -storepass es_keystore

keytool -importkeystore -srckeystore es_keystore.jks -destkeystore es_keystore.jks -deststoretype pkcs12
```
2. Dockerfile
```
FROM apache/skywalking-oap-server:7.0.0-es7
COPY ./es_keystore.jks /skywalking/config/es_keystore.jks
```
3. oap config
```
SW_SW_STORAGE_ES_SSL_JKS_PATH=/skywalking/config/es_keystore.jks
SW_SW_STORAGE_ES_SSL_JKS_PASS=es_keystore
```
successful problem solving
