### ISSUE TITLE
Exception while fetching data (/databaseTopNRecords)

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#4786]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
   SkyWalking  version 7.0.0
   influxdb        version 1.8
   use docker
 
- What happen?

     **Exception while fetching data (/databaseTopNRecords)**

 `java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.apache.skywalking.oap.server.storage.plugin.influxdb.query.TopNRecordsQuery.lambda$getTopNRecords$1(TopNRecordsQuery.java:85) ~[storage-influxdb-plugin-7.0.0.jar:7.0.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.storage.plugin.influxdb.query.TopNRecordsQuery.getTopNRecords(TopNRecordsQuery.java:83) ~[storage-influxdb-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.core.query.TopNRecordsQueryService.getTopNRecords(TopNRecordsQueryService.java:49) ~[server-core-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQuery.getTopNRecords(TopNRecordsQuery.java:62) ~[query-graphql-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:7.0.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:93) [query-graphql-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:83) [query-graphql-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:59) [library-server-7.0.0.jar:7.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:107) [library-server-7.0.0.jar:7.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:112) [library-server-7.0.0.jar:7.0.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by wu-sheng** [comment]
@dmsolr This seems an influxdb storage error, have this been fixed in the new implementation?

**Comment by dmsolr** [comment]
@bnubobby , Thanks. I will create a PR to fix them soon.
