### ISSUE TITLE
java.lang.NullPointerException-at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler.lambda$doServiceInstanceRegister$1{RegisterServiceHandler.java:177}

### ISSUE THREAD

**Issue by welcome6688** [apache/skywalking#4801]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✔ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
OAP server error：nullPoint
___
bug info ：
2020-05-19 11:45:02 java.lang.NullPointerException
2020-05-19 11:45:02 	at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler.lambda$doServiceInstanceRegister$1(RegisterServiceHandler.java:177)
2020-05-19 11:45:02 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-05-19 11:45:02 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
2020-05-19 11:45:02 	at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler.doServiceInstanceRegister(RegisterServiceHandler.java:137)
2020-05-19 11:45:02 	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$MethodHandlers.invoke(RegisterGrpc.java:509)
2020-05-19 11:45:02 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
2020-05-19 11:45:02 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
2020-05-19 11:45:02 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
2020-05-19 11:45:02 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2020-05-19 11:45:02 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2020-05-19 11:45:02 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-05-19 11:45:02 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-05-19 11:45:02 	at java.lang.Thread.run(Thread.java:748)
2020-05-19 11:45:02 
2020-05-19 11:45:02 May 19, 2020 3:45:02 AM io.grpc.internal.SerializingExecutor run
2020-05-19 11:45:02 SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7bed071f

**Comment by welcome6688** [comment]
Using ES as storage

**Comment by wu-sheng** [comment]
duplicated. es data reased, but the agent keeps runnig. search the issues before submitted.
