### ISSUE TITLE
tomcat start stop problem

### ISSUE THREAD

**Issue by niah161951** [apache/skywalking#4836]
perform stop tomcat  the command   an error is as follows :
./shutdown.sh 
Using CATALINA_BASE:   /var/www/apps/apache-tomcat-8.5.39
Using CATALINA_HOME:   /var/www/apps/apache-tomcat-8.5.39
Using CATALINA_TMPDIR: /var/www/apps/apache-tomcat-8.5.39/temp
Using JRE_HOME:        /opt/jdk1.8.0_181/jre
Using CLASSPATH:       /var/www/apps/apache-tomcat-8.5.39/bin/bootstrap.jar:/var/www/apps/apache-tomcat-8.5.39/bin/tomcat-juli.jar
DEBUG 2020-05-28 17:19:19:089 main AgentPackagePath : The beacon class location is jar:file:/var/www/apps/apache-tomcat-8.5.39/agent/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class. 
INFO 2020-05-28 17:19:19:095 main SnifferConfigInitializer : Config file found in /var/www/apps/apache-tomcat-8.5.39/agent/config/agent.config. 
Error: the agent throws an exception error: java.rmi.server.ExportException: Port already in use: 9000; nested exception is: 
	java.net.BindException: The address is already in use (Bind failed)
sun.management.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 9000; nested exception is: 
	java.net.BindException: The address is already in use (Bind failed)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
	at sun.management.Agent.startAgent(Agent.java:262)
	at sun.management.Agent.startAgent(Agent.java:452)
Caused by: java.rmi.server.ExportException: Port already in use: 9000; nested exception is: 
	java.net.BindException: The address is already in use (Bind failed)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:236)
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:173)
	at sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
	at sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:816)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:468)
	... 2 more

**Comment by wu-sheng** [comment]
This is port in use, not skywalking's issue.

**Comment by niah161951** [comment]
Sorry, the company bought the framework and integrated tomcat.This kind of problem @wu-sheng

**Comment by wu-sheng** [comment]
Sorry, we can't support private version.
