### ISSUE TITLE
Have trustStorePath and trustStorePass been set to empty, or do you refuse to connect?

### ISSUE THREAD

**Issue by andyhewenhui** [apache/skywalking#4837]
trustStorePath: ${SW_SW_STORAGE_ES_SSL_JKS_PATH:""}
 trustStorePass: ${SW_SW_STORAGE_ES_SSL_JKS_PASS:""}
 user: ${SW_ES_USER:"xxxx"}
 password: ${SW_ES_PASSWORD:"xxxxxx"} 

2020-05-28 20:15:06,993 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Connection refused
org.apache.skywalking.oap.server.library.module.ModuleStartException: Connection refused
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:224) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: java.net.ConnectException: Connection refused
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:804) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:677) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:96) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:216) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        ... 4 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_252]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[?:1.8.0_252]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]

**Comment by wu-sheng** [comment]
That depends on your ES cluster.

**Comment by andyhewenhui** [comment]
The problem is found. It is the localhost = > private network ip of ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}.

**Comment by tirelibirefe** [comment]
Hello @andyhewenhui andy
How did you set up following lines?
`    trustStorePath: ${SW_SW_STORAGE_ES_SSL_JKS_PATH:"../es_keystore.jks"}`
