### ISSUE TITLE
skywalking print error in biz log

### ISSUE THREAD

**Issue by darcydai** [apache/skywalking#4848]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Version 6.6.0  in jdk 1.8 and centos 7.0

- Which company or project?
koolearn

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I found some no class found some error in my application biz log(not in skywalking agent log), then I download the agent jar in product machine and decompile the jar found the class exists. 

```
Jun 01, 2020 4:51:36 PM org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls cancelThrow
SEVERE: RuntimeException encountered while closing call
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/dependencies/io/grpc/internal/DelayedStream$8
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.DelayedStream.cancel(DelayedStream.java:267)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.DelayedClientTransport$PendingStream.cancel(DelayedClientTransport.java:367)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.cancel(ClientCallImpl.java:395)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCall.cancel(PartialForwardingClientCall.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall.cancel(ForwardingClientCall.java:22)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall$SimpleForwardingClientCall.cancel(ForwardingClientCall.java:44)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCall.cancel(PartialForwardingClientCall.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall.cancel(ForwardingClientCall.java:22)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall$SimpleForwardingClientCall.cancel(ForwardingClientCall.java:44)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCall.cancel(PartialForwardingClientCall.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall.cancel(ForwardingClientCall.java:22)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCall$SimpleForwardingClientCall.cancel(ForwardingClientCall.java:44)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.cancelThrow(ClientCalls.java:237)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:134)
	at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$ServiceInstancePingBlockingStub.doPing(ServiceInstancePingGrpc.java:158)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:179)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Sorry, this class exists, for sure. Don't know what happens at your local env.
