### ISSUE TITLE
kafka consumer start error

### ISSUE THREAD

**Issue by amwyyyy** [apache/skywalking#4865]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
version:
SkyWalking7.0.0
spring-kafka:2.2.8.RELEASE
kafka-clients:2.0.1

When kafka consumer uses topicPattern, the agent will report an error.
```
@KafkaListener(topicPattern = KAFKA_TOPIC_NAME)
public void onDemoMessage(ConsumerRecord<String, String> record) {
// ...
}
```
skywalking-api.log
```
ERROR 2020-06-05 17:57:30:137 restartedMain InstMethodsInter : class[class org.apache.kafka.clients.consumer.KafkaConsumer] before method[subscribe] intercept failure 
java.lang.ClassCastException: java.util.regex.Pattern cannot be cast to java.util.Collection
	at org.apache.skywalking.apm.plugin.kafka.SubscribeMethodInterceptor.beforeMethod(SubscribeMethodInterceptor.java:33)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(KafkaConsumer.java)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.subscribeOrAssignTopics(KafkaMessageListenerContainer.java:584)

```

**Comment by wu-sheng** [comment]
This seems a plugin incompatible case. Most plugins are contributed by the users, so, please try to learn the plugin development( we provided doc), and add supports to this case. We are welcome your contribution.
