### ISSUE TITLE
zipkin-receiver not work in "apache-skywalking-apm-bin-es7" and docker image(skywalking-oap-server:7.0.0-es7)

### ISSUE THREAD

**Issue by czs1993** [apache/skywalking#4883]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 skywalking-apm-es7-7.0.0,windows,jdk 1.8  and docker image version (skywalking-oap-server:7.0.0-es7) ,Centos7
- Which company or project?
skywalking-oap-server + Elasticsearch7 +zipkin Agent
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
when startup the service or run docker, follows errors hanppened:

```
 org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [receiver_zipkin] missing.
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:64) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
```
I checked that the oap-libs folder was missing  "zipkin-2.9.1.jar "and "zipkin-receiver-plugin-7.0.0.jar" compared to Binary Distribution  apache-skywalking-apm-7.0.0. 
Then I  copy "zipkin-2.9.1.jar "and "zipkin-receiver-plugin-7.0.0.jar" to oap-libs, follows new errors hanppened:

```
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/RemovalListener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_211]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_211]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
	at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[guava-28.1-jre.jar:?]
	at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.scan(AnnotationScan.java:56) ~[server-core-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:151) ~[server-core-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:95) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:54) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.RemovalListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
	... 19 more

```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
 skywalking-apm-es7-7.0.0 and docker image(skywalking-oap-server:7.0.0-es7) support zipkin-receiver-plugin .

**Comment by wu-sheng** [comment]
It exists in es6 storage only. The documentation indicated this.

**Comment by czs1993** [comment]
@wu-sheng  thanks, Is this will supported in  skywalking version 8.0.0 ?

**Comment by thanq** [comment]
same question ,  Is this will supported in skywalking version 8?

**Comment by wu-sheng** [comment]
No, it is an experimental feature only(as doc said too). Unless, there are contributors who will focus on these features, and enhance them for product ready,  no committer is working on this. More and more people move on SkyWalking native agents already and has no plan to do so, as far as I known. Sorry.
