### ISSUE TITLE
skywalking-python not working for requests lib

### ISSUE THREAD

**Issue by chestarss** [apache/skywalking#4925]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking server 8.0
skywalking-python make install by master branch with HEAD/3892cab9d5d2c03

- Which company or project?

- What happen?
```python
from skywalking import agent, config
import requests

config.init(collector='trace.domain.name:11800', service='test')

agent.start()
url = 'http://127.0.0.1:8000/taskdetail/?task_id=328'
resp = requests.get(url)

```

```python
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    resp = requests.get(url)
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/admin/git/skywalking-python/skywalking/plugins/sw_requests/__init__.py", line 46, in _sw_request
    with context.new_exit_span(op=url_param.path or "/", peer=url_param.netloc, carrier=carrier) as span:
  File "/home/admin/git/skywalking-python/skywalking/trace/context/__init__.py", line 75, in new_exit_span
    span.inject(carrier=carrier)
  File "/home/admin/git/skywalking-python/skywalking/trace/span/__init__.py", line 209, in inject
    carrier.endpoint = self.context.spans[0].op
IndexError: list index out of range

```

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
Should be fixed by https://github.com/apache/skywalking-python/pull/14
