### ISSUE TITLE
java.lang.NullPointerException  at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan

### ISSUE THREAD

**Issue by LinXiaoJian** [apache/skywalking#5011]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I sent the request, I saw the NullPointerException in the skywalking-api.log file. Does Skywalking 8.0.1 support vertx 3.8.5 ? How should I solve this problem？

- Which version of SkyWalking, OS and JRE?
SkyWalking 8.0.1
vertx 3.8.5
k3s v1.18.4 + k3s1

ERROR 2020-07-02 11:12:22:875 vert.x-eventloop-thread-0 InstMethodsInter : class[class io.vertx.ext.web.impl.RouteState] after method[handleContext] intercept failure 
java.lang.NullPointerException
        at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:172)
        at org.apache.skywalking.apm.plugin.vertx3.RouteStateInterceptor.afterMethod(RouteStateInterceptor.java:82)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$$Lambda$417/00000000B4815850.handle(Unknown Source)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:516)
        at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
        at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:163)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage$original$5bFp59Ed(Http1xServerConnection.java:140)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage$original$5bFp59Ed$accessor$6WLZB3ND(Http1xServerConnection.java)
        at io.vertx.core.http.impl.Http1xServerConnection$auxiliary$Xo68aMgs.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java)
        at io.vertx.core.net.impl.VertxHandler$$Lambda$404/00000000D000C7C0.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by wu-sheng** [comment]
Vert.x supported versions and libs are here, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md
Also, tests codes are https://github.com/apache/skywalking/tree/master/test/plugin/scenarios

Please recheck with our tests first.

**Comment by LinXiaoJian** [comment]
I can see support for vertx 3.8.1 in the Supported-list.md,  But I just couldn't get started，I added the apm-mysql-*.jar and it didn't work

2 vert.x-eventloop-thread-0 AbstractClassEnhancePluginDefine : enhance class com.mysql.cj.jdbc.Driver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.DriverInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed. 
WARN 2020-07-02 15:55:47:738 vert.x-eventloop-thread-0 AbstractClassEnhancePluginDefine : enhance class com.mysql.cj.jdbc.NonRegisteringDriver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.CacheIpsInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed. 
WARN 2020-07-02 15:55:47:988 vert.x-eventloop-thread-0 AbstractClassEnhancePluginDefine : enhance class com.mysql.cj.jdbc.ConnectionImpl by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.ConnectionInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed. 
WARN 2020-07-02 15:55:47:988 vert.x-eventloop-thread-0 AbstractClassEnhancePluginDefine : enhance class com.mysql.cj.jdbc.ConnectionImpl by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.ConnectionImplCreateInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed. 
WARN 2020-07-02 15:55:48:358 vert.x-eventloop-thread-0 AbstractClassEnhancePluginDefine : enhance class com.mysql.cj.jdbc.StatementImpl by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.StatementInstrumentation is not working. Because witness class com.mysql.cj.api.MysqlConnection is not existed.

**Comment by wu-sheng** [comment]
These warnings have nothing related to the vert.x. And these are not errors.

**Comment by BFergerson** [comment]
@LinXiaoJian, I can help you with the Vert.x issue if you provide some sample code or more information about the issue but I'm not sure what mysql-connector-java has to do with Vert.x. They are unrelated and should not affect each other.

**Comment by LinXiaoJian** [comment]
@BFergerson  @wu-sheng  I followed the error to find the following code, I'm using Kotlin development, I don't know if this is relevant


![object CloudoptServer {](https://user-images.githubusercontent.com/11407854/86350525-67739b00-bc95-11ea-8f5a-b8e1f118b594.jpg)
![Scan resources](https://user-images.githubusercontent.com/11407854/86350537-6b9fb880-bc95-11ea-9321-11b40f755031.jpg)

**Comment by BFergerson** [comment]
@LinXiaoJian, unfortunately, those images aren't enough for me to help. Most of that code seems to be more custom than Vert.x idiomatic. Are you able to produce this issue in a project you can send me the source code for (via GitHub)? Preferrable the minimally reproducible one.

I don't think Kotlin should cause the issue you're seeing.

**Comment by LinXiaoJian** [comment]
@BFergerson  I am currently using the framework of is my friend, open source web framework based on vertx, if you are interested in, you can view the following address: https://github.com/cloudoptlab/cloudopt-next

**Comment by BFergerson** [comment]
@LinXiaoJian, I'll give it a go. Please provide step-by-step instructions necessary to produce the issue.

**Comment by LinXiaoJian** [comment]
@BFergerson 
1. I installed Skywalking through the Rancher store
2.I copy /agent directory to the project source directory

**Comment by wu-sheng** [comment]
@LinXiaoJian I think it is better you provide the demo codes in a repo, which is 100% causing the exceptions.

**Comment by T-baby** [comment]
I had the same problem, I looked at the test cases for skywalking and there are no tests for vert.x 3.8+, is it not supported for 3.8+?

**Comment by BFergerson** [comment]
@T-baby, how did you determine that there are no tests for Vert.x 3.8+? There are basic tests for 3.0.x - 3.9.x.

What additionally should be tested and can you produce this issue in a demo repo?
