### ISSUE TITLE
Is there some bugs that for below exception?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5022]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
ERROR 2020-07-03 15:09:19:937 Sharding-Sphere-1 InstMethodsInter : class[class io.shardingsphere.core.executor.prepared.PreparedStatementExecutor$3] before method[execute0] intercept failure 
java.lang.NoClassDefFoundError: io/shardingsphere/core/executor/ShardingExecuteDataMap
        at org.apache.skywalking.apm.plugin.shardingsphere.ExecuteInterceptor.beforeMethod(ExecuteInterceptor.java:42)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:59)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:46)
        at io.shardingsphere.core.executor.ShardingExecuteEngine$1.call(ShardingExecuteEngine.java:98)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

ERROR 2020-07-03 15:09:19:938 Sharding-Sphere-2 InstMethodsInter : class[class io.shardingsphere.core.executor.prepared.PreparedStatementExecutor$3] before method[execute0] intercept failure 
java.lang.NoClassDefFoundError: io/shardingsphere/core/executor/ShardingExecuteDataMap
        at org.apache.skywalking.apm.plugin.shardingsphere.ExecuteInterceptor.beforeMethod(ExecuteInterceptor.java:42)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:59)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:46)
        at io.shardingsphere.core.executor.ShardingExecuteEngine$1.call(ShardingExecuteEngine.java:98)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment]
Please report to ShardingSphere community. They contributed the plugins

**Comment by lsy1990** [comment]
Thanks
