### ISSUE TITLE
oracle-10.x-plugin NullPointerException 

### ISSUE THREAD

**Issue by amenema** [apache/skywalking#5071]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
the skywalking version is 7.0.0, use Centos7, java8.

- Which company or project?
the project is a weChat callback service.
- What happen?
I introduced oracle-10.x-plugin into the service agent. Recently, I found some NullPointerException error in the skywalking agent log. By looking up the source code of oracle-10.x-plugin, I think it may be caused by the  cacheobject in line 70 of [PreparedStatementExecuteMethodsInterceptor.java](https://github.com/SkyAPM/java-plugin-extensions/blob/master/oracle-10.x-plugin/src/main/java/io/skywalking/apm/plugin/jdbc/oracle/PreparedStatementExecuteMethodsInterceptor.java) does not make a non null judgment.

This is error log.

`ERROR 2020-07-10 10:13:25:134 default4 InstMethodsInter : class[class oracle.jdbc.driver.T4CPreparedStatement] handle method[execute] exception failure
java.lang.NullPointerException
	at io.skywalking.apm.plugin.jdbc.oracle.PreparedStatementExecuteMethodsInterceptor.handleMethodException(PreparedStatementExecuteMethodsInterceptor.java:70)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:90)
	at oracle.jdbc.driver.T4CPreparedStatement.execute(T4CPreparedStatement.java)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute$original$CHejiyoT(OraclePreparedStatementWrapper.java:1376)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute$original$CHejiyoT$accessor$yUVoLJwW(OraclePreparedStatementWrapper.java)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper$auxiliary$SmOgRWQO.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3051)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy112.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:84)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)`

**Comment by wu-sheng** [comment]
Oracle plugin is not a part of Apache SkyWalking, it is an ecosystem extension. Please submit the issue or pull request to their repo.
