### ISSUE TITLE
Error in connection with ES7 in version 8.0.1

### ISSUE THREAD

**Issue by zhuangyea** [apache/skywalking#5072]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug

___
### Question
Download 8.0.1 local make docker. After docker compose is started, OAP service reports an error
- oap service error：
 2020-07-10 10:31:19,670 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -4403 [main] INFO [] - elasticsearch cluster nodes: elasticsearch:9200
2020-07-10 10:31:20,014 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -4747 [main] ERROR [] - org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:134) ~[library-client-8.0.1.jar:8.0.1]
at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:185) ~[storage-elasticsearch-plugin-8.0.1.jar:8.0.1]
at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.0.1.jar:8.0.1]
at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.0.1.jar:8.0.1]
at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.0.1.jar:8.0.1]
at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.0.1.jar:8.0.1]
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 8.0.1
ElasticSearch 7.8.0

**Comment by wu-sheng** [comment]
We have two release binaries for es6 and es7, make sure you choose the right one with correct configuration.

**Comment by wu-sheng** [comment]
Read the document.
