### ISSUE TITLE
add agent error

### ISSUE THREAD

**Issue by iportman** [apache/skywalking#5077]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of SkyWalking, OS and JRE?
apache-skywalking-apm-es7-8.0.1

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

After adding the jvm -agent parameter, the system runs the main function and reports an error

```sh
-javaagent:D:\some\apache-skywalking-apm-bin-es7\agent\skywalking-agent.jar
```

```java
Exception in thread "main" java.lang.ClassFormatError: Duplicate interface name "org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/EnhancedInstance" in class file org/eclipse/jetty/server/HttpChannel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.jetty.server.AbstractConnector.<init>(AbstractConnector.java:158)
	at org.eclipse.jetty.server.AbstractNetworkConnector.<init>(AbstractNetworkConnector.java:44)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:212)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:95)
	at kd.bos.service.bootstrap.embedjetty.EmbedJettyServer.start(EmbedJettyServer.java:62)
	at kd.bos.service.bootstrap.Booter.main(Booter.java:41)
	at kd.bos.service.webserver.JettyServer.main(JettyServer.java:15)
	at kd.bos.devenv.bos.OneInit.start(OneInit.java:30)
	at kd.bos.debugserver.One_Log.main(One_Log.java:128)
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Your description is not enough. Our agents are working well in Jetty, it is tested. Maybe your private framework is manipulating byte codes somehow. You need to check by yourself.
