### ISSUE TITLE
Encounters an error “java.lang.RuntimeException: Prepare for async repeatedly. Span is already in async mode.”

### ISSUE THREAD

**Issue by janecms** [apache/skywalking#5150]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [✔️ ] Bug

___
### Bug
SkyWalking:8.0.1
OS: MAC/Linux
JRE: OpenJDK 1.8.0_242/1.8.0_252

- Which company or project?
 spring cloud gateway 2.1.5

- What happen?
This problem was not found in the test environment, so I think it may have something to do with concurrency。
View the Agent local log file。The log content contains ：
`
**java.lang.RuntimeException: Prepare for async repeatedly. Span is already in async mode.**
        at org.apache.skywalking.apm.agent.core.context.trace.AbstractTracingSpan.prepareForAsync(AbstractTracingSpan.java:301)
        at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.HttpClientFinalizerSendInterceptor.beforeMethod(HttpClientFinalizerSendInterceptor.java:45)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:75)
        at reactor.netty.http.client.HttpClientFinalizer.send(HttpClientFinalizer.java)
        at reactor.netty.http.client.HttpClientFinalizer.send(HttpClientFinalizer.java:44)
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter$original$zQOMXuoX(NettyRoutingFilter.java:128)
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter$original$zQOMXuoX$accessor$17xErV0d(NettyRoutingFilter.java)
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter$auxiliary$JpE5vsrn.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:85)
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java)
        at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138)
        at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44)
        at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
`
other log in our test env.
`
WARN 2020-07-20 17:29:07:495 reactor-http-epoll-3 TracingContext : More than 300 spans required to create
java.lang.RuntimeException: Shadow tracing context. Thread dump
        at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:562)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createExitSpan(TracingContext.java:323)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:119)
        at org.apache.skywalking.apm.plugin.jedis.v2.JedisMethodInterceptor.beforeMethod(JedisMethodInterceptor.java:38)
`

___
### Requirement or improvement
- I found the issue (5144) (https://github.com/apache/skywalking/issues/5144),The two mistakes are similar. I don't know if they are one。How to solve this problem

**Comment by wu-sheng** [comment]
Duplicate.

**Comment by janecms** [comment]
@wu-sheng ,can i tell me  how to solve this problem now,Version 8.1.0 is now a snapshot version。

Please let me know.

Thanks

**Comment by Glenrun** [comment]
I also encountered this issue. Is there any time line to fix? @wu-sheng

**Comment by wu-sheng** [comment]
Read #5177

**Comment by janecms** [comment]
Thanks @wu-sheng 。  I followed the content mentioned in issue  #5177。 perform the following actions。Found that the problem has not been resolved, but exception has changed。
my actions:
1. only changes org.apache.skywalking.apm.plugin.spring.webflux.v5.DispatcherHandlerHandleMethodInterceptor.java，Keep the content consistent with the master。
2. Other, the content has not changed。so I change 'apm-spring-webflux-5.x-plugin-8.0.1.jar'.

At Last,After jmeter pressure test  ，An exception occurs:
`WARN 2020-07-28 13:40:21:096 reactor-http-nio-8 TracingContext : More than 300 spans required to create 
java.lang.RuntimeException: Shadow tracing context. Thread dump
	at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:562)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.createEntrySpan(TracingContext.java:262)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.createEntrySpan(ContextManager.java:94)
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.DispatcherHandlerHandleMethodInterceptor.beforeMethod(DispatcherHandlerHandleMethodInterceptor.java:63)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java)
	at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:122)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)`

What I want to know is, is the update incomplete? Still BUG is not completely fixed。Can you help me analyze it?

**Comment by wu-sheng** [comment]
This error is totally different case. which plugin causes this need your local work. Check why span can't be closed as expected.

**Comment by janecms** [comment]
> This error is totally different case. which plugin causes this need your local work. Check why span can't be closed as expected.

Thank you !   I will try later 。

**Comment by Glenrun** [comment]
I'm facing the same suituation, after I update my source code locally as #5177, the same stack trace shown:
.......
java.lang.RuntimeException: Prepare for async repeatedly. Span is already in async mode.** at org.apache.skywalking.apm.agent.core.context.trace.AbstractTracingSpan.prepareForAsync(AbstractTracingSpan.java:301) at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v21x.HttpClientFinalizerSendInterceptor.beforeMethod(HttpClientFinalizerSendInterceptor.java:45) at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:75) at reactor.netty.http.client.HttpClientFinalizer.send(HttpClientFinalizer.java) at reactor.netty.http.client.HttpClientFinalizer.send(HttpClientFinalizer.java:44) at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter$original$zQOMXuoX(NettyRoutingFilter.java:128) at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter$original$zQOMXuoX$accessor$17xErV0d(NettyRoutingFilter.java) at org.springframework.cloud.gateway.filter.NettyRoutingFilter$auxiliary$JpE5vsrn.call(Unknown Source) at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:85) at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java) at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138) at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
.....

**Comment by ascrutae** [comment]
@Glenrun that error logs that you display maybe cause by gateway plugin,  Cloud you give me the demo to reproduce this issue?

**Comment by Glenrun** [comment]
Yes, it is caused by gateway plugin, since if i remove gateway plugin, it works. I'm sorry i'm not able to provide a demo for reproduce at hand, since our source code in a finacinal secure environment, I can't take it out.

**Comment by wu-sheng** [comment]
If you are not really using the spring gateway, don't activate that plugin.

**Comment by happyhakka6** [comment]
skywalking-agent 8.11.0   还是报同样的问题
jdk: OpenJDK 1.8.0_242
spring-cloud-gateway-webflux:2.2.3.RELEASE
