### ISSUE TITLE
skywalking upgrade 7 to 8

### ISSUE THREAD

**Issue by heytong** [apache/skywalking#5163]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
___
### Question
agent version: 7.0
collector version: 8.0.1
es index:  del all
collector log: 
```
org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker - 178 [pool-5-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:75) ~[server-alarm-plugin-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:185) ~[server-core-8.0.1.jar:8.0.1]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_131]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:185) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:164) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:132) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.0.1.jar:8.0.1]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.0.1.jar:8.0.1]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_131]
```

**Comment by wu-sheng** [comment]
Don't support this.

**Comment by heytong** [comment]
那这个升级就没法搞了, 这么多服务器不可能停机啊

**Comment by sky-dail** [comment]
agent  version 7.0
oap 8.1.0   ui  8.1.0
es 7.9.1 
也遇到了上述问题，请问可以解决吗？或者说能够提供一个相对比较新的配套的版本，我部署下

**Comment by wu-sheng** [comment]
Please keep discussion in English. 

> agent version 7.0
oap 8.1.0 ui 8.1.0

This is not supported. Read release note, https://github.com/apache/skywalking/releases/tag/v8.0.0

**Comment by JiGW24** [comment]
I have upgrade problem like this. For SK8, what suitable ES version  can I use? or give some other advice.

> agent version 7.0
> oap 8.1.0 ui 8.1.0
> es 7.9.1
> 也遇到了上述问题，请问可以解决吗？或者说能够提供一个相对比较新的配套的版本，我部署下

I have upgrade problem like this. For SK8, what suitable ES version  can I use? or give some other advice.

**Comment by JiGW24** [comment]
> agent version 7.0
> oap 8.1.0 ui 8.1.0
> es 7.9.1
> 也遇到了上述问题，请问可以解决吗？或者说能够提供一个相对比较新的配套的版本，我部署下

I have upgrade problem like this. For SK8, what suitable ES version  can I use? or give some other advice.

**Comment by RedisOptimal** [comment]
> Don't support this.

#8864 https://github.com/apache/skywalking/issues/8864
The Can't split service ID into 2 parts is easy to fix. @ScopeDefaultColumn.VirtualColumnDefinition(fieldName = "entityId", columnName = "entity_id", isID = true, type = String.class) should be added into event.


I read all issues about this problem, but none of it that talk about what should I do to fix it. 
And I dont want to submit any code of it.
