### ISSUE TITLE
when skywalking oap start,happen error

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywaling 7.0 ,os linux, jre jdk8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by killGC** [comment]
2020-08-03 10:41:53,311 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - method [HEAD], host [http://192.168.201.53:9200], URI [/_template/elasticsearch_service_sla?master_timeout=30s], status line [HTTP/1.1 429 Too Many Requests]
org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [http://192.168.201.53:9200], URI [/_template/elasticsearch_service_sla?master_timeout=30s], status line [HTTP/1.1 429 Too Many Requests]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1680) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.IndicesClient.existsTemplate(IndicesClient.java:1209) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.isExistsTemplate(ElasticSearch7Client.java:152) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.isExists(StorageEsInstaller.java:56) ~[storage-elasticsearch-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:50) ~[server-core-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:219) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://192.168.201.53:9200], URI [/_template/elasticsearch_service_sla?master_timeout=30s], status line [HTTP/1.1 429 Too Many Requests]
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        ... 10 more

**Comment by wu-sheng** [comment]
HTTP 429 is an ElasticSearch server issue. It rejected the request, maybe because of the performance or health status. Please check your ElasticSearch
