### ISSUE TITLE
[bug] ERROR [] - Data truncation: Data too long for column 'statement' at row 1

### ISSUE THREAD

**Issue by CodingOX** [apache/skywalking#5236]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 8.1.0
OS:CentOS 7
JRE:OpenJDK 11

- Which company or project?

- What happen?
I user `mysql 5.7` as storage,the charset is `utf8mb4` and engines is `InnoDB`

`skywalking-oap-server.log` show the errors，it show `h2`! but i use `mysql` as storage
```yaml
storage:
  selector: ${SW_STORAGE:mysql}
```

error logs..
```
[pool-4-thread-1] ERROR [] - Data truncation: Data too long for column 'statement' at row 1
2020-08-05 11:12:53,058 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 71 [pool-4-thread-1] ERROR [] - Data truncation: Data too long for column 'statement' at row 1
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'statement' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1288) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:53) ~[storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.synchronous(H2BatchDAO.java:72) [storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:122) [server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) [server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.1.0.jar:8.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

___
### Requirement or improvement
How to fix the error?

**Comment by wu-sheng** [comment]
Similar to #5135. But that pull request is not perfect.
