### ISSUE TITLE
docker start fail, Exist cycle module dependencies in

### ISSUE THREAD

**Issue by dislazy** [apache/skywalking#5246]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [1 ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
docker pull apache/skywalking-oap-server:latest 
then start the docker
logs:
2020-08-06 01:48:04,708 - org.apache.skywalking.oap.server.library.module.ModuleDefine -9014 [main] INFO  [] - Prepare the default provider in prometheus-fetcher module.
2020-08-06 01:48:04,709 - org.apache.skywalking.oap.server.library.module.ModuleDefine -9015 [main] INFO  [] - Prepare the default provider in envoy-metric module.
2020-08-06 01:48:04,710 - org.apache.skywalking.oap.server.library.module.ModuleDefine -9016 [main] INFO  [] - Prepare the none provider in configuration module.
2020-08-06 01:48:04,721 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -9027 [main] ERROR [] - Exist cycle module dependencies in 
receiver-trace[provider=org.apache.skywalking.oap.server.receiver.trace.provider.TraceModuleProvider]
org.apache.skywalking.oap.server.library.module.CycleDependencyException: Exist cycle module dependencies in 
receiver-trace[provider=org.apache.skywalking.oap.server.receiver.trace.provider.TraceModuleProvider]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.makeSequence(BootstrapFlow.java:112) ~[library-module-8.1.0.jar:8.1.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.<init>(BootstrapFlow.java:39) ~[library-module-8.1.0.jar:8.1.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-8.1.0.jar:8.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.1.0.jar:8.1.0]

___
### Bug
- Which version of SkyWalking, OS and JRE?
latest
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Latest could change with time. We just released 8.1, the default yaml changed. You need to sync the change.

**Comment by dislazy** [comment]
ok thanks
