### ISSUE TITLE
java.lang.NoClassDefFoundError: io/shardingsphere/core/executor/ShardingExecuteDataMap

### ISSUE THREAD

**Issue by chenshun00** [apache/skywalking#5361]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
###  java.lang.NoClassDefFoundError: io/shardingsphere/core/executor/ShardingExecuteDataMap

```text
[nobody@xxxx lib]$ find . |grep sh
./sharding-jdbc-spring-boot-starter-3.0.0.M3.jar
./sharding-core-3.0.0.M3.jar
./sharding-jdbc-3.0.0.M3.jar
```

```java
java.lang.NoClassDefFoundError: io/shardingsphere/core/executor/ShardingExecuteDataMap
        at org.apache.skywalking.apm.plugin.shardingsphere.ExecuteInterceptor.beforeMethod(ExecuteInterceptor.java:42)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:59)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:46)
        at io.shardingsphere.core.executor.ShardingExecuteEngine.syncExecute(ShardingExecuteEngine.java:106)
        at io.shardingsphere.core.executor.ShardingExecuteEngine.execute(ShardingExecuteEngine.java:88)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:75)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:56)
        at io.shardingsphere.core.executor.prepared.MemoryStrictlyPreparedStatementExecutor.executeCallback(MemoryStrictlyPreparedStatementExecutor.java:47)
        at io.shardingsphere.core.executor.prepared.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:108)
        at io.shardingsphere.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:189)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:92)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
        at com.sun.proxy.$Proxy103.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:144)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy109.queryByUserId(Unknown Source)
        at com.example.xxx.xxxxpool.platform.services.Opxxxice.queryCo*****yProfile(OpTradeService.java:292)
        at ************.listOriginTrades(OpTradeService.java:277)
        at ******ice.listTrades(OpTradeService.java:272)
        at ********eService$$FastClassBySpringCGLIB$$876aa16c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by wu-sheng** [comment]
Please report to Shardingsphere community.

**Comment by chenshun00** [comment]
@wu-sheng 
`org/apache/shardingsphere/infra/executor/kernel/ExecutorDataMap.java` was removed in Shardingsphere 4.x, 

But 4.x plugins are still using this class. 

https://github.com/apache/skywalking/blob/629040f5abb98110255083a868013a8785c7db05/apm-sniffer/apm-sdk-plugin/sharding-sphere-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/shardingsphere/v4/ExecuteInterceptor.java#L42
