### ISSUE TITLE
SkyWalking 8.1.0, Mysql8.0, Table doesn't exist;  Not to create table auto!

### ISSUE THREAD

**Issue by DerekHQ** [apache/skywalking#5387]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x]  Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Table doesn't exist;  Not to create table auto!

skywalking7.0.0 mysql8.0 is work ok!
But when upgrade to 8.1.0, the same mysql server ,just a new database instance
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 8.1.0
Linux
JAVA8
Mysql8.0
driver: mysql-connector-java-8.0.21.jar

**Comment by wu-sheng** [comment]
We tested it in the e2e, https://github.com/apache/skywalking/blob/master/.github/workflows/e2e.storages.yaml#L39.

**Comment by wu-sheng** [comment]
- https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/profile/docker-compose.mysql.yml
- https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/storage/docker-compose.mysql.yml
- https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/cluster/docker-compose.zk.mysql.yml

**Comment by DerekHQ** [comment]
Datasource Create is OK!
2020-08-26 15:53:24,945 - com.zaxxer.hikari.HikariDataSource - 80 [main] INFO  [] - HikariPool-1 - Starting...
2020-08-26 15:53:26,019 - com.zaxxer.hikari.HikariDataSource - 82 [main] INFO  [] - HikariPool-1 - Start completed.
.......

2020-08-26 16:06:06,850 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 56 [main] INFO  [] - persistence timer start
2020-08-26 16:06:06,863 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 46 [main] INFO  [] - Cache updateServiceInventory timer start
2020-08-26 16:06:07,101 - org.apache.skywalking.oap.server.core.analysis.worker.ManagementPersistentWorker - 45 [main] ERROR [] - Table 'skywalking_b.ui_template' doesn't exist
java.io.IOException: Table 'skywalking_b.ui_template' doesn't exist
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2ManagementDAO.insert(H2ManagementDAO.java:56) ~[storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.ManagementPersistentWorker.in(ManagementPersistentWorker.java:43) ~[server-core-8.1.0.jar:8.1.0]

**Comment by wu-sheng** [comment]
We are impossible to test on your env. I just posted all test processes. Please take a look. There could be many factors and configurations to affect the result.
