### ISSUE TITLE
When use zpkin receiver pulgin and mysql as backend storage, the oap can't start up

### ISSUE THREAD

**Issue by czs1993** [apache/skywalking#5388]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking-8.1.0 , mysq (mysql-connector-java-8.0.20.jar) 
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
the error logs:
```
org.apache.skywalking.oap.server.library.module.ServiceNotProvidedException: Service org.apache.skywalking.oap.server.analyzer.provider.trace.parser.ISegmentParserService should not be provided, based on moduleDefine define.
	at org.apache.skywalking.oap.server.library.module.ModuleProvider.getService(ModuleProvider.java:121) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.receiver.zipkin.ZipkinReceiverProvider.start(ZipkinReceiverProvider.java:89) ~[zipkin-receiver-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.1.0.jar:8.1.0]
```
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
When using the Zipkin Receiver plugin, the backend storage is  ES6 only in version of 8.1.0, but Skywalking7.0.0+ mysql works normally.

**Comment by wu-sheng** [comment]
We only said it works with the ES6. Nothing more.
