### ISSUE TITLE
Skywalking 8+ causes Elasticsearch 6 failed to parse field [service_id] of type [integer]

### ISSUE THREAD

**Issue by ohworld** [apache/skywalking#5397]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking:8.1.0-es6 and 8.0.1-es6  (docker.io/apache/skywalking-oap-server:8.x.x)
OS :Red Hat 4.8.5-36(Linux version 3.10.0-957.21.3.el7.x86_64)
JRE:OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)

- Which company or project?
Chengdu Eventec Technological Innovation Co.Ltd

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
ES6.6 throws MapperParsingException: failed to parse field [service_id] of type [integer], when skywalking-ui requests the skywalking-oap-server for data, even these causes ES cannot query any data from any index. 
I have made the following efforts several times:
1. Delete ES indexs refer to Skywalking if exists.
2. Deploy the skywalking-oap-server, skywalking-ui and our application.
3.Open skywalking-ui website, then I can see its DashBoard works fine(shows data), but other four Tabs(Topological Diagram, etc.) have no data.(The direct reason is that the network interface requests respond error.)

Our first application written with Springboot uses agent in apache-skywalking-apm-8.x.x.tar.gz to collect infomation. I cannot change SkyWalking version to below 8, because I have application written by Python, whose agent requires SkyWalking 8+.

The problem is urgent. Please contact me if possible , my wechat & mobile is 18551601581, thanks. 

Exceptions of ES are as belows :

1.
[2020-08-27T11:38:16,711][DEBUG][o.e.a.b.TransportShardBulkAction] [node-1] [eventec_endpoint_sla-20200827][0] failed to execute bulk item (index) index {[eventec_endpoint_sla-20200827][type][2020082711_c2VydmljZS1nYXRld2F5LWF1dGhlbn
RpY2F0aW9u.1_L3NlcnZpY2UtanNvbnN5bmMvc3luYy9jb2xsZWN0aW9uL2V2ZW50cw==], source[{"total":3,"service_id":"c2VydmljZS1nYXRld2F5LWF1dGhlbnRpY2F0aW9u.1","percentage":10000,"match":3,"time_bucket":2020082711,"entity_id":"c2VydmljZS1nYXRld2
F5LWF1dGhlbnRpY2F0aW9u.1_L3NlcnZpY2UtanNvbnN5bmMvc3luYy9jb2xsZWN0aW9uL2V2ZW50cw=="}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [service_id] of type [integer]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:303) ~[elasticsearch-6.6.0.jar:6.6.0]
........
Caused by: java.lang.NumberFormatException: For input string: "c2VydmljZS1nYXRld2F5LWF1dGhlbnRpY2F0aW9u.1"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]

2.
[2020-08-27T11:38:16,706][DEBUG][o.e.a.b.TransportShardBulkAction] [node-1] [eventec_endpoint_relation_cpm-20200827][1] failed to execute bulk item (index) index {[eventec_endpoint_relation_cpm-20200827][type][202008271138_VXNlcg==.0
-VXNlcg==-c2VydmljZS1nYXRld2F5LWF1dGhlbnRpY2F0aW9u.1-L3NlcnZpY2UtY2hhc3Npc21vbml0b3IvZGV2aW5mbw==], source[{"child_endpoint_name":"/service-chassismonitor/devinfo","total":1,"service_id":"VXNlcg==.0","child_service_id":"c2VydmljZS1nY
XRld2F5LWF1dGhlbnRpY2F0aW9u.1","time_bucket":202008271138,"entity_id":"VXNlcg==.0-VXNlcg==-c2VydmljZS1nYXRld2F5LWF1dGhlbnRpY2F0aW9u.1-L3NlcnZpY2UtY2hhc3Npc21vbml0b3IvZGV2aW5mbw==","value":1,"source_endpoint_name":"User"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [service_id] of type [integer]

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The index is old version. You can't use it both for v7 and v8.

**Comment by ohworld** [comment]
> The index is old version. You can't use it both for v7 and v8.

But these indexs are built by Skywalking 8.0.1 or 8.1.0 themselves, not other skywalking version.

**Comment by wu-sheng** [comment]
The logs say there is integer id, which is for 7- only.

**Comment by ohworld** [comment]
> > The index is old version. You can't use it both for v7 and v8.
> 
> But these indexs are built by Skywalking 8.0.1 or 8.1.0 themselves, not other skywalking version.

In other words, Skywalking has not works correctly except for 'Dashboard' Tab. And even the worse, ES will not respond to any request after I click 'Topological Diagram' Tab. Every time when I restart new whole installation, I deleted any indexes built by Skywalking.

**Comment by ohworld** [comment]
> The logs say there is integer id, which is for 7- only.

But I've never deployed versions below v8.

**Comment by wu-sheng** [comment]
I could only tell you why the error happens.

**Comment by ohworld** [comment]
I deleted indexes built by skywalking(those index names startwith namespace eventec) and then restart it just now, now I see logs below are printed by oap-server 8.0.1. We can see these indexes are built by v8 indeed:

2020-08-27 15:14:25,839 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -43223 [main] INFO  [] - table: instance_clr_available_worker_threads does not exist
2020-08-27 15:14:25,839 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller -43223 [main] INFO  [] - index eventec_instance_clr_available_worker_threads's columnTypeEsMapping builder str: {type={properties={service_id={type=keyword}, time_bucket={type=long}, entity_id={type=keyword}, value={type=long}}}}
2020-08-27 15:14:26,094 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller -43478 [main] INFO  [] - create instance_clr_available_worker_threads-20200827 index finished, isAcknowledged: true
2020-08-27 15:14:26,477 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -43861 [main] INFO  [] - table: instance_clr_max_completion_port_threads does not exist
2020-08-27 15:14:26,477 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller -43861 [main] INFO  [] - index eventec_instance_clr_max_completion_port_threads's columnTypeEsMapping builder str: {type={properties={service_id={type=keyword}, time_bucket={type=long}, entity_id={type=keyword}, value={type=long}}}}
2020-08-27 15:14:26,770 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller -44154 [main] INFO  [] - create instance_clr_max_completion_port_threads-20200827 index finished, isAcknowledged: true

**Comment by ohworld** [comment]
> I could only tell you why the error happens.

Please help analyzeing this problem, thank you much.

**Comment by wu-sheng** [comment]
There are also templates, not just indexes.

**Comment by ohworld** [comment]
Thanks, I'll try it out.

**Comment by ohworld** [comment]
Great, after I rebuild and deploy all the components dockers completely, all the UI Tab display correctly, although the oap-server still log some "listener timeout after waiting for [30000] ms".
I'm puzzled I've never deloyed skywalking v7.x.x.
Thank you for instruction.

**Comment by lixaviers** [comment]
Switch versions and get ElasticSearch templates
