### ISSUE TITLE
skywalking 6.6.0   ES版本5.6.1 启动问题

### ISSUE THREAD

**Issue by coder8421** [apache/skywalking#5403]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking 6.6.0   ES版本5.6.1 启动问题
skywalking oap服务启动报错 
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6.0 
- Which company or project?
  
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
now
 into DefaultScopeDefine 22.
2020-08-27 20:04:55,495 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider default in alarm module.
2020-08-27 20:04:55,495 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 58 [main] INFO  [] - start the provider elasticsearch in storage module.
2020-08-27 20:04:55,495 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 157 [main] INFO  [] - elasticsearch cluster nodes: localhost:9200
2020-08-27 20:04:55,936 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller - 60 [main] INFO  [] - table: alarm_record does not exist
2020-08-27 20:04:55,937 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller - 73 [main] INFO  [] - index elasticsearch_alarm_record's columnTypeEsMapping builder str: {type={properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}}
2020-08-27 20:04:55,956 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 59 [main] ERROR [] - method [PUT], host [http://localhost:9200], URI [/_template/elasticsearch_alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"},"status":400}
org.apache.skywalking.oap.server.library.module.ModuleStartException: method [PUT], host [http://localhost:9200], URI [/_template/elasticsearch_alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:141) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:47) [server-bootstrap-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:28) [server-starter-6.6.0.jar:6.6.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: method [PUT], host [http://localhost:9200], URI [/_template/elasticsearch_alarm_record], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"},"status":400}
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:100) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.6.0.jar:6.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:136) ~[storage-elasticsearch-plugin-6.6.0.jar:6.6.0]
	... 4 more

**Comment by wu-sheng** [comment]
English only

**Comment by wu-sheng** [comment]
Read document, we never said ES 5.6.1 is supported.

**Comment by coder8421** [comment]
> Read document, we never said ES 5.6.1 is supported.
Elasticsearch version used by our company is 5.6.1 and SkyWalking version is 6.6.0. I got an error when oapService started



20:04:55 2020-08-27, 936 - org. Apache. Skywalking. Oap. Server. The core storage. Model. ModelInstaller - 60 [main] INFO [] - table: alarm_record does not exist

20:04:55 2020-08-27, 937 - org. Apache. Skywalking. Oap. Server storage. The plugin. Elasticsearch. Base. StorageEsInstaller - 73 [main] INFO [] - index elasticsearch_alarm_record 's columnTypeEsMapping builder str: {type={properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}}

help me  , thank you
