### ISSUE TITLE
Deploy skywalking on k8s get some problems

### ISSUE THREAD

**Issue by hantmac** [apache/skywalking#5453]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I deploy skywalking on kubernetes, it is running ok and can access data by accessing ip:12800. But when try to access ip:11800 I got the next error:

```
Sep 07, 2020 9:21:34 AM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: fff4fffd06
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
BTW, the same code that deploy on VM works ok.

Looking forward to your reply.
___

**Comment by wu-sheng** [comment]
Why access 11800? It is grpc port.

**Comment by hantmac** [comment]
> Why access 11800? It is grpc port.

#### The agent access skywalking server through port 11800.  

I start agent locally to test if the skywalking on k8s running ok, I saw the agent can connect with oap server, but the server got errors when agent sending data to it.

**Comment by wu-sheng** [comment]
This error may be caused by your load balancer or proxy, which don't support http2/grpc very well.

**Comment by hantmac** [comment]
> This error may be caused by your load balancer or proxy, which don't support http2/grpc very well.

I agree with your opinions.

SO I did the next operation:

Firstly, the agent connect with oap server by  k8s service(LoadBalancer),  does't work and then I use pod ip as oap server directly but got the same errors.
Anyway, thanks for your timely reply.

**Comment by hantmac** [comment]
I use image `adoptopenjdk/openjdk8` and got the errors above, but I change the image to `1.8.0_131`  everything ok.

**Comment by wu-sheng** [comment]
OK, if you package your own image, then it is hard to tell. You could find the official docker image on the docker hub.
