### ISSUE TITLE
 io.grpc.netty.NettyServerTransport notifyTerminated  Transport failed  io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET / 

### ISSUE THREAD

**Issue by moxm** [apache/skywalking#5464]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking version: 8.1.0
Docker version 19.03.4, build 9013bf583a
OS: centos 7
Application JDK: Oracle JDK 1.8

- Which company or project?

- What happened?
**dashboard:     Issue occurs ( data missing) in the end though the data is correct at the beginning**

Sep 10, 2020 1:29:42 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET / 
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:302)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kezhenxu94** [comment]
From your title and stack trace, I can't see anything that is related to SkyWalking, please provide more context about what you want to ask

**Comment by moxm** [comment]
dashboard: Issue occurs ( data missing) in the end though the data is correct at the beginning

**Comment by moxm** [comment]
![image](https://user-images.githubusercontent.com/10267892/92746125-8e48fe80-f3b5-11ea-86c6-09dcd4aab433.png)
![image](https://user-images.githubusercontent.com/10267892/92746191-9d2fb100-f3b5-11ea-837f-d1ec9ff379d9.png)
![image](https://user-images.githubusercontent.com/10267892/92746275-b6386200-f3b5-11ea-9aa3-967514b08e8e.png)
![image](https://user-images.githubusercontent.com/10267892/92746348-cbad8c00-f3b5-11ea-9738-5c5a8f20a4e9.png)

**Comment by moxm** [comment]
### agent log：


ERROR 2020-09-10 22:24:32:063 SkywalkingAgent-7-JVMService-consume-0 JVMMetricsSender : send JVM metrics to Collector fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at org.apache.skywalking.apm.network.language.agent.v3.JVMMetricReportServiceGrpc$JVMMetricReportServiceBlockingStub.collect(JVMMetricReportServiceGrpc.java:158)
	at org.apache.skywalking.apm.agent.core.jvm.JVMMetricsSender.run(JVMMetricsSender.java:82)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by moxm** [comment]
### oap log:
Sep 10, 2020 1:29:42 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET / 
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:302)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment]
You are sending http data to grpc port.

**Comment by kezhenxu94** [comment]
> io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /


this is the key, Grpc is based on http/2 , but you just tried to communicate with http/1.x

**Comment by moxm** [comment]
一开始用容器启动了skywalking-ui以及oap，也启动了应用，界面展示都正常，后来在测试环境运行了几个星期，再去看就没数据了。

**Comment by moxm** [comment]
然后重启skywalking-ui以及oap都无效，业务应用重启也无效。业务应用采用的springcloud技术，应用容器采用的undertow和netty。

**Comment by moxm** [comment]
skywalking 使用的mysql作为数据源。

**Comment by wu-sheng** [comment]
You are setting wrong ports. There is nothing about rebooting.

**Comment by moxm** [comment]
![image](https://user-images.githubusercontent.com/10267892/92748993-44ade300-f3b8-11ea-990e-8ac0a5cfa185.png)
![image](https://user-images.githubusercontent.com/10267892/92749093-5becd080-f3b8-11ea-98d4-5076ed32544c.png)

**Comment by moxm** [comment]
> You are setting wrong ports. There is nothing about rebooting.

Compatible undertow？

**Comment by wu-sheng** [comment]
Undertow has nothing related to this. You are misunderstanding the whole thing. 
First, this is onnectionconnection between agent and oap. You are saying something about agent plugin.

**Comment by moxm** [comment]
> Undertow has nothing related to this. You are misunderstanding the whole thing.
> First, this is about the connection between agent and oap. You are saying something about agent plugin.

一开始dashboard都是有数据的，也都是好的，后来运行一段时间后，环境没变的情况下就没数据了

**Comment by wu-sheng** [comment]
Please keep the discussion in English. I answered your question based on the logs you provided. I can tell what is really happening on your private env. But the logs are clear.

**Comment by moxm** [comment]
now resolved, thanks!

**Comment by rysinal** [comment]
> now resolved, thanks!
can you share How to solve it ,tks

**Comment by Chasun-fhd** [comment]
> now resolved, thanks!

i have the same problem too..  what's your solution?

**Comment by iris-xie** [comment]
> now resolved, thanks!

could you tell me how you reslove this, I also met this issue

**Comment by iris-xie** [comment]
@moxm could you help me,please

**Comment by ujnzxw** [comment]
@moxm @iris-xie @rysinal @Chasun-fhd I have the same issue, could your please share the solution to this issue?

**Comment by moxm** [comment]
> Follow the diagram and you'll see the data.
![5FB360DB-D1E7-4ef3-BFA4-82D0045F7EE8](https://user-images.githubusercontent.com/10267892/146906265-fd28e2fb-1bc9-486d-8557-340f1cd65646.png)

**Comment by Nabaghan861** [comment]
i have the same problem, what is the steps for this resolution @moxm
