### ISSUE TITLE
skywalking upgrade from 6.5 to 8.1.0

### ISSUE THREAD

**Issue by sky-dail** [apache/skywalking#5482]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
agent version 7.0
oap-server  8.1.0
ui 8.1.0
es 7.9.1
~~~java
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:75) ~[server-alarm-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:188) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:146) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.1.0.jar:8.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.1.0.jar:8.1.0]
~~~
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
A relatively new SkyWalking version can be provided to match the ES version and the OAP version to solve this problem

**Comment by sky-dail** [comment]
A relatively new SkyWalking version can be provided to match the ES version and the OAP version to solve this problem

**Comment by wu-sheng** [comment]
We don't say, the latest SkyWalking 8.x supports the old existing data. We highlighted this is an incompatible upgrade.

**Comment by sky-dail** [comment]
the old existing data we don‘t use ,I just want to redeploy it,but it doesn't work

**Comment by wu-sheng** [comment]
But they are sharing same index names. Remove all old index and templates, if you are using ES.

**Comment by sky-dail** [comment]
thank you ,Let me try

**Comment by landonzeng** [comment]
> thank you ,Let me try

This "Can 't split the instance id into 2 parts" error solved

**Comment by JiGW24** [comment]
> > thank you ,Let me try
> 
> This "Can 't split the instance id into 2 parts" error solved

How you slove this problem? I tried to solve like this but ineffective.  plz reply me when you see this.thanks
