### ISSUE TITLE
AlarmCore -78603097 [pool-2-thread-1] ERROR 

### ISSUE THREAD

**Issue by landonzeng** [apache/skywalking#5508]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why will appear this error message

‘‘
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265],
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265],
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265],
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265],
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265],
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265],
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265],
	at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$start$3(AlarmCore.java:77) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265],
	at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$null$2(AlarmCore.java:77) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
	at org.apache.skywalking.oap.server.core.alarm.provider.slack.SlackhookCallback.doAlarm(SlackhookCallback.java:66) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
java.lang.NullPointerException: null,
2020-09-17 07:04:21,143 - org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore -78603097 [pool-2-thread-1] ERROR [] - null
‘’
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.x ，linux Centos 7

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think this is master branch NPE. @JaredTan95 `SlackhookCallback` seems doesn't check the `SlackSettings == null`

@landonzeng Do you want to submit a pull request to fix this? `SlackhookCallback#L66` should check `this.alarmRulesWatcher.getSlackSettings() != null`.

**Comment by landonzeng** [comment]
> I think this is master branch NPE. @JaredTan95 `SlackhookCallback` seems doesn't check the `SlackSettings == null`
> 
> @landonzeng Do you want to submit a pull request to fix this? `SlackhookCallback#L66` should check `this.alarmRulesWatcher.getSlackSettings() != null`.

I am running in docker environment, I am not very familiar with java, sorry

**Comment by wu-sheng** [comment]
This is a bug of an unreleased feature. I have informed @JaredTan95

**Comment by landonzeng** [comment]
> This is a bug of an unreleased feature. I have informed @JaredTan95

Ok，Thanks！

**Comment by xbkaishui** [comment]
let me fix this, it's easy

**Comment by xbkaishui** [comment]
Done, please reCheck
