### ISSUE TITLE
mongodb  Exit span doesn't include meaningful peer information.

### ISSUE THREAD

**Issue by caochuansong** [apache/skywalking#5520]
ERROR 2020-09-19 11:01:05:293 org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1 InstMethodsInter : class[class com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor] before method[execute] intercept failure
java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
        at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:170)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:150)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:112)
        at org.apache.skywalking.apm.plugin.mongodb.v3.support.MongoSpanHelper.createExitSpan(MongoSpanHelper.java:35)
        at org.apache.skywalking.apm.plugin.mongodb.v3.interceptor.v37.MongoDBOperationExecutorInterceptor.beforeMethod(MongoDBOperationExecutorInterceptor.java:47)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java)
        at com.mongodb.client.internal.MongoCollectionImpl.executeInsertMany(MongoCollectionImpl.java:497)
        at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:479)
        at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:474)
        at org.springframework.data.mongodb.core.MongoTemplate.lambda$insertDocumentList$16(MongoTemplate.java:1468)
        at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:566)
        at org.springframework.data.mongodb.core.MongoTemplate.insertDocumentList(MongoTemplate.java:1461)
        at org.springframework.data.mongodb.core.MongoTemplate.doInsertBatch(MongoTemplate.java:1325)
        at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:1259)
        at com.xinheyun.domainmachine.machinedata.repository.mongo.impl.MachineDataDaoImpl.save(MachineDataDaoImpl.java:50)
        at com.xinheyun.domainmachine.machinedata.repository.mongo.impl.MachineDataDaoImpl$$FastClassBySpringCGLIB$$f5248182.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.xinheyun.domainmachine.machinedata.repository.mongo.impl.MachineDataDaoImpl$$EnhancerBySpringCGLIB$$75734aaa.save(<generated>)
        at com.xinheyun.domainmachine.kafkaConsumer.service.impl.KafkaConsumerImpl.consume(KafkaConsumerImpl.java:88)
        at sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
        at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48)
        at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:329)
        at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.invoke(BatchMessagingMessageListenerAdapter.java:170)
        at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:162)
        at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:58)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:1601)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:1592)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:1550)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:1485)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1378)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1361)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1080)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:988)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)

**Comment by harvies** [comment]
Please see https://github.com/apache/skywalking/issues/5469
