### ISSUE TITLE
invalid_alias_name_exception

### ISSUE THREAD

**Issue by sodared** [apache/skywalking#5536]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking8.1.0 CentOS7 JDK1.8

- What happened?

I just used 3-node elastiseach cluster as skywalking storage and start up skwwalking , however there is an error. I have tried to delete the index and restart , but the same error with another index name happened again . Hence I don't think it is a good solution to delete the index.

2020-09-22 16:48:40,258 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Elasticsearch exception [type=invalid_alias_name_exception, reason=Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=invalid_alias_name_exception, reason=Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:205) ~[library-client-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:92) ~[storage-elasticsearch-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:55) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:88) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:195) ~[storage-elasticsearch-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.1.0.jar:8.1.0]
	Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.9.250.113:9200], URI [/smec-elasticsearch_top_n_database_statement-20200922?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias","index_uuid":"O9t8m1s7RCmvVOx-lCDs7Q","index":"smec-elasticsearch_top_n_database_statement"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias","index_uuid":"O9t8m1s7RCmvVOx-lCDs7Q","index":"smec-elasticsearch_top_n_database_statement"},"status":400}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:205) ~[library-client-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:92) ~[storage-elasticsearch-plugin-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:55) ~[server-core-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:88) ~[server-core-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:195) ~[storage-elasticsearch-plugin-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
		at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.1.0.jar:8.1.0]
	Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.9.250.113:9200], URI [/smec-elasticsearch_top_n_database_statement-20200922?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias","index_uuid":"O9t8m1s7RCmvVOx-lCDs7Q","index":"smec-elasticsearch_top_n_database_statement"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias","index_uuid":"O9t8m1s7RCmvVOx-lCDs7Q","index":"smec-elasticsearch_top_n_database_statement"},"status":400}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

___
### Requirement or improvement
anyone can help me ? thanks!

**Comment by wu-sheng** [comment]
> Elasticsearch exception [type=invalid_alias_name_exception, reason=Invalid alias name [smec-elasticsearch_top_n_database_statement], an index exists with the same name as the alias]

This is not SkyWalking's issue. The elasticsearch has other indecies, maybe created by older versions (6.2 or even older)?. Anyway, we never create a index named `elasticsearch_top_n_database_statement` today.
