### ISSUE TITLE
skywalking artm debug

### ISSUE THREAD

**Issue by MikelPan** [apache/skywalking#5547]
#oal scripts
endpoint_200 = from(Endpoint.*).filter(responseCode like "2.*").percent();

# stdout
line 41:55 no viable alternative at input 'responseCode == 200'
line 41:52 mismatched input '==' expecting {SPACE, '='}
line 41:67 mismatched input '(' expecting {SPACE, '='}
2020-09-23 13:12:39,458 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -5181 [main] ERROR [] - Can't find metrics, null
java.lang.IllegalArgumentException: Can't find metrics, null
	at org.apache.skywalking.oal.rt.parser.MetricsHolder.find(MetricsHolder.java:54) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.parser.DeepAnalysis.analysis(DeepAnalysis.java:38) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.parser.OALListener.exitAggregationStatement(OALListener.java:50) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.grammar.OALParser$AggregationStatementContext.exitRule(OALParser.java:232) ~[oal-grammar-8.1.0.jar:8.1.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:66) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:162) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:60) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.AnalyzerModuleProvider.start(AnalyzerModuleProvider.java:110) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.1.0.jar:8.1.0]

# why 
so skywalking not up，please help me！

**Comment by wu-sheng** [comment]
Why do you add OAL? I don't think the previous release supports `like`.

**Comment by wu-sheng** [comment]
And even it supports `like`, how a number could use on a `like`?

**Comment by MikelPan** [comment]
oal is in https://github.com/apache/skywalking/blob/master/docs/en/concepts-and-designs/oal.md

// Caculate the percent of response code in [200, 299], for each service.
endpoint_200 = from(Endpoint.*).filter(responseCode like "2%").percent()

if not suppotrs，i need to alarm reponseCode status is 200，or 400，and 500，how to configure，please tell me

**Comment by wu-sheng** [comment]
And you should use responseCode > 200, such as `.filter(responseCode >= 200 ).filter(responseCode < 300)`

FYI @arugal Please recheck the master branch doc. I have doubts about what it describes.

**Comment by MikelPan** [comment]
now chaange as endpoint_500 = from(Endpoint.*).filter(responseCode >=500).percent();
but error
2020-09-23 13:47:10,389 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -4822 [main] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oal.rt.parser.DeepAnalysis.analysis(DeepAnalysis.java:119) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.parser.OALListener.exitAggregationStatement(OALListener.java:50) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.grammar.OALParser$AggregationStatementContext.exitRule(OALParser.java:232) ~[oal-grammar-8.1.0.jar:8.1.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at org.apache.skywalking.oal.rt.parser.ScriptParser.parse(ScriptParser.java:66) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:162) ~[oal-rt-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:60) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.AnalyzerModuleProvider.start(AnalyzerModuleProvider.java:110) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.1.0.jar:8.1.0]

**Comment by wu-sheng** [comment]
Because you are using the wrong function. percent function requires the parameter. 

Try this, you are calculating the `resposeCode >=500`/`all requests`. Filter means don't include the >500 requests. Please pay more attention on understanding documents.
> endpoint_500 = from(Endpoint.*).percent(responseCode >=500);

**Comment by MikelPan** [comment]
i change as
endpoint_500 = from(Endpoint.*).percent(responseCode >=500);
but stdout as it
2020-09-23 13:58:28,261 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -54260 [main] INFO  [] - table: endpoint_500 does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later

**Comment by wu-sheng** [comment]
> but stdout as it
2020-09-23 13:58:28,261 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -54260 [main] INFO [] - table: endpoint_500 does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later

Now, this is your part work now, Read the doc. `no-init` is a specific bootstrap mode.
