### ISSUE TITLE
special characters are not allowed

### ISSUE THREAD

**Issue by wuwenrufeng** [apache/skywalking#5651]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1, macos, 1.8.0_261
- Which company or project?
project
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
在 apache-skywalking-apm-bin/config/fetcher-prom-rules目录里新增一个fetcher文件
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wuwenrufeng** [comment]
2020-10-12 16:59:59,300 - org.apache.skywalking.oap.server.core.alarm.provider.AlarmRulesWatcher - 93 [main] INFO  [] - Update alarm rules to Rules(rules=[AlarmRule(alarmRuleName=service_resp_time_rule, metricsName=service_resp_time, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=1000, op=>, period=10, count=3, silencePeriod=5, message=Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.), AlarmRule(alarmRuleName=service_sla_rule, metricsName=service_sla, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=8000, op=<, period=10, count=2, silencePeriod=3, message=Successful rate of service {name} is lower than 80% in 2 minutes of last 10 minutes), AlarmRule(alarmRuleName=service_resp_time_percentile_rule, metricsName=service_percentile, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=1000,1000,1000,1000,1000, op=>, period=10, count=3, silencePeriod=5, message=Percentile response time of service {name} alarm in 3 minutes of last 10 minutes, due to more than one condition of p50 > 1000, p75 > 1000, p90 > 1000, p95 > 1000, p99 > 1000), AlarmRule(alarmRuleName=service_instance_resp_time_rule, metricsName=service_instance_resp_time, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=1000, op=>, period=10, count=2, silencePeriod=5, message=Response time of service instance {name} is more than 1000ms in 2 minutes of last 10 minutes), AlarmRule(alarmRuleName=database_access_resp_time_rule, metricsName=database_access_resp_time, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=1000, op=>, period=10, count=2, silencePeriod=-1, message=Response time of database access {name} is more than 1000ms in 2 minutes of last 10 minutes), AlarmRule(alarmRuleName=endpoint_relation_resp_time_rule, metricsName=endpoint_relation_resp_time, includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, threshold=1000, op=>, period=10, count=2, silencePeriod=-1, message=Response time of endpoint relation {name} is more than 1000ms in 2 minutes of last 10 minutes)], webhooks=[], grpchookSetting=null)
2020-10-12 16:59:59,381 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 88 [main] INFO  [] - Prepare the default provider in prometheus-fetcher module.
2020-10-12 16:59:59,386 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - special characters are not allowed
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[snakeyaml-1.18.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:248) ~[snakeyaml-1.18.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58) ~[snakeyaml-1.18.jar:?]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465) ~[snakeyaml-1.18.jar:?]
	at org.apache.skywalking.oap.server.core.metric.promethues.rule.Rules.lambda$loadRules$0(Rules.java:50) ~[server-core-8.1.0.jar:8.1.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_261]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_261]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_261]
	at org.apache.skywalking.oap.server.core.metric.promethues.rule.Rules.loadRules(Rules.java:59) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.fetcher.prometheus.provider.PrometheusFetcherProvider.prepare(PrometheusFetcherProvider.java:92) ~[prometheus-fetcher-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:95) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:54) ~[library-module-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.1.0.jar:8.1.0]

**Comment by wu-sheng** [comment]
Your error stack is about the dynamic update of the alarm rule. I am not following your context.
Please use English on the GitHub.

**Comment by wu-sheng** [comment]
You are not following the YAML format requirements. That is why snakeyaml reports error.
