### ISSUE TITLE
Not an int32 value error 

### ISSUE THREAD

**Issue by qinhang3** [apache/skywalking#5783]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking in Docker . Image Tag: apache/skywalking-oap-server:8.2.0-es7
SkyWalking Client is skywalking-client-js:0.1.0

- Which company or project?
skywalking-client-js and oap-server

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
After add skywalking-client-js in my package.json. The browser POST data to ``https://myhost.com/browser/perfData`` automatically.
Here comes the request body:
```
{
  "redirectTime": 0,
  "dnsTime": 0,
  "ttfbTime": 18,
  "tcpTime": 0,
  "transTime": 2,
  "domAnalysisTime": 121,
  "fptTime": 23,
  "domReadyTime": 144,
  "loadPageTime": 162,
  "resTime": 18,
  "sslTime": 1604395104446,
  "ttlTime": 144,
  "firstPackTime": 21,
  "fmpTime": 571,
  "pagePath": "https://myhost.com/index.html",
  "serviceVersion": "1.0.0",
  "service": "my-app"
}
```
Then I found error on skywalking-oap-server's log.
```
2020-11-03 09:18:29,629 - org.apache.skywalking.oap.server.receiver.browser.provider.handler.rest.BrowserPerfDataReportServletHandler -1335962 [qtp5563134-37] ERROR [] - Not an int32 value: 1604395104446
com.google.protobuf.InvalidProtocolBufferException: Not an int32 value: 1604395104446
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseInt32(JsonFormat.java:1754) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1961) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1665) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1502) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1342) ~[protobuf-java-util-3.12.4.jar:?]
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477) ~[protobuf-java-util-3.12.4.jar:?]
	at org.apache.skywalking.oap.server.library.util.ProtoBufJsonUtils.fromJSON(ProtoBufJsonUtils.java:45) ~[library-util-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.receiver.browser.provider.handler.rest.BrowserPerfDataReportServletHandler.parseBrowserPerfData(BrowserPerfDataReportServletHandler.java:107) ~[skywalking-browser-receiver-plugin-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.receiver.browser.provider.handler.rest.BrowserPerfDataReportServletHandler.doPost(BrowserPerfDataReportServletHandler.java:86) [skywalking-browser-receiver-plugin-8.2.0.jar:8.2.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) [jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489) [jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.Server.handle(Server.java:500) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```
And nothing about browser data can found on skywalking-ui.

**Comment by wu-sheng** [comment]
Why SSL time so long? `"sslTime": 1604395104446`. Is this real? Or data mock?

**Comment by qinhang3** [comment]
No, it's not data mock and it's not always large.
Is it any possible the client get wrong data?
My page loads normally.

**Comment by wu-sheng** [comment]
Maybe, I am not sure. The author, @Fine0830, is AFK because of family things. :) I recommend you to debug first, try to figure out.

**Comment by wu-sheng** [comment]
At least, provide a demo to replicate the issue, I could ask @Jtrust to debug locally.

**Comment by qinhang3** [comment]
try this url: https://h5.huantangxc.com/me.html?htToken=c9-6f5ce6a3-37cb-45c9-8400-8d9f2021ce74 
Visit this page in chrome. It can reproduce the error in high probability.

**Comment by arugal** [comment]
@qinhang3 Does `typescript` code exist at runtime?

**Comment by arugal** [comment]
![image](https://user-images.githubusercontent.com/26432832/97979743-a9ab1580-1e0a-11eb-86f0-3e4e99b13ff0.png)
https://github.com/apache/skywalking-client-js/blob/3d7177295e55d1db03d3174ca9a3d7615cc44c49/src/performance/perf.ts#L51-L52

@qinhang3 @Jtrust Is this error related to sslTime?

**Comment by qinhang3** [comment]
This error has not reproduce in my chrome. but I notice the ``timing.secureConnectionStart === 0`` , so the sslTime was current timestamp.
https://github.com/apache/skywalking-client-js/blob/3d7177295e55d1db03d3174ca9a3d7615cc44c49/src/performance/perf.ts#L51-L52

**Comment by qinhang3** [comment]
Here is the whole object ``timing`` 
```
{
  "connectStart": 1604486935501,
  "navigationStart": 1604486935499,
  "loadEventEnd": 0,
  "domLoading": 1604486936583,
  "secureConnectionStart": 0,
  "fetchStart": 1604486935501,
  "domContentLoadedEventStart": 1604486936776,
  "responseStart": 1604486936521,
  "responseEnd": 1604486936522,
  "domInteractive": 1604486936776,
  "domainLookupEnd": 1604486935501,
  "redirectStart": 0,
  "requestStart": 1604486935504,
  "unloadEventEnd": 1604486936582,
  "unloadEventStart": 1604486936582,
  "domComplete": 1604486936848,
  "domainLookupStart": 1604486935501,
  "loadEventStart": 1604486936848,
  "domContentLoadedEventEnd": 1604486936776,
  "redirectEnd": 0,
  "connectEnd": 1604486935501
}
```

**Comment by wu-sheng** [comment]
Look like `timing.secureConnectionStart === 0` doesn initial correctly? @arugal @Jtrust Could you help on checking?

**Comment by qinhang3** [comment]
https://www.stevesouders.com/blog/2014/08/21/resource-timing-practical-tips/
https://bugs.chromium.org/p/chromium/issues/detail?id=404501
According to these links, there’s a bug in Chrome that causes secureConnectionStart to be incorrectly set to zero. If a resource is fetched using a pre-existing HTTPS connection then secureConnectionStart is set to zero when it should really be a timestamp.  
Maybe skywalking-client-js shouldn't submit sslTime to the server when `secureConnectionStart === 0`.

**Comment by arugal** [comment]
@qinhang3 The [new version](https://www.npmjs.com/package/skywalking-client-js) has been released, welcome to use :)
