### ISSUE TITLE
Can't split instance id into 2 parts

### ISSUE THREAD

**Issue by hlsc1989** [apache/skywalking#5791]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Can't split instance id into 2 parts

___
### Question
- 我这边的版本是8.2 for es的（之前搭建过老的版本），es的版本是7.4.1，我已经将老版本的es的索引全部删除了，并且新版本的es索引前面加了前缀，但是还是会报 Can't split instance id into 2 parts 这个错误

2020-11-04 15:55:15,421 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker - 192 [pool-6-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:78) ~[server-alarm-plugin-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:199) ~[server-core-8.2.0.jar:8.2.0]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_121]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:199) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:178) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:141) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.2.0.jar:8.2.0]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_121]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.2.0.jar:8.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

___
___
### Requirement or improvement
- 请问这个是为什么？和我的配置有关系吗？

**Comment by wu-sheng** [comment]
Read the FAQ about the upgrade. The short version is, we don't support the old data format.
