### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by guhong1023** [apache/skywalking#5817]
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.spring.mvc.commons.JavaxServletRequestHolder cannot be cast to org.apache.skywalking.apm.plugin.spring.mvc.commons.RequestHolder
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.afterMethod(AbstractMethodInterceptor.java:164)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
	at com.guhong.springboot.simple.apm.skywalking.controller.UserController.get(UserController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke$original$fh6E1G7b(StandardHostValve.java:139)
	at org.apache.catalina.core.StandardHostValve.invoke$original$fh6E1G7b$accessor$fEkpjc1i(StandardHostValve.java)
	at org.apache.catalina.core.StandardHostValve$auxiliary$6X2iTucc.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

**Comment by wu-sheng** [comment]
Could you provide a demo to reproduce the error? It seems there is some case we don't support yet.

**Comment by lihongjie0209** [comment]
@wu-sheng 应该是spring-boot-devtools 的问题, 我把这个依赖删除之后就没有报异常了

**Comment by wu-sheng** [comment]
Then, this is duplicated. Yes, there is a conflict with spring-boot-devtools.

**Comment by zifeihan** [comment]
That is the problem of spring-boot-devtools. When using spring-boot-devtools, spring uses RestartClassLoader to load the org.springframework.web.bind.annotation.RequestMapping class.
But the class org.springframework.web.method.HandlerMethod was loaded by AppClassLoader, so the same plugin was loaded with different AgentClassLoader, which resulted in a conversion exception. The spring-boot-devtools package is to implement similar hot deployment functions. I have not yet figured out how to fix this problem. Here is an explanation of this problem. If someone encounters a similar problem, please remove the dependency of spring-boot-devtools.

**Comment by briup01** [comment]
这个问题还有什么解决方案吗，我的不是因为spring-boot-devtools

**Comment by TerryLam2010** [comment]
@briup01 @wu-sheng me too...How to solve this problem?

**Comment by xu1009** [comment]
i meet the same problem, but i find there is no spring-boot-devtools dependency in my project

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/115873932-1c21b780-a476-11eb-9f8c-71de10c6e794.png)
![image](https://user-images.githubusercontent.com/22722907/115873949-217f0200-a476-11eb-9ab8-8834d18eacd8.png)

JavaxServletRequestHolder class load by classloader like the iamge

**Comment by xu1009** [comment]
> ![image](https://user-images.githubusercontent.com/22722907/115873932-1c21b780-a476-11eb-9f8c-71de10c6e794.png)
> ![image](https://user-images.githubusercontent.com/22722907/115873949-217f0200-a476-11eb-9ab8-8834d18eacd8.png)
> 
> JavaxServletRequestHolder class load by classloader like the iamge

@zifeihan there has other reason ?

**Comment by wu-sheng** [comment]
ExtClassLoader is not supported, as it is not widely used today.

**Comment by zifeihan** [comment]
> > ![image](https://user-images.githubusercontent.com/22722907/115873932-1c21b780-a476-11eb-9f8c-71de10c6e794.png)
> > ![image](https://user-images.githubusercontent.com/22722907/115873949-217f0200-a476-11eb-9ab8-8834d18eacd8.png)
> > JavaxServletRequestHolder class load by classloader like the iamge
> 
> @zifeihan there has other reason ?

Sorry for being late, can you provide a simple demo to reproduce this problem?

**Comment by lujiajing1126** [comment]
This issue has been addressed by PR #6973.

You could try with the master branch or wait for the next release 8.6.0.

Feedback is welcome.
