### ISSUE TITLE
skywakling javaagent  ServiceAndEndpointRegisterClient execute fail

### ISSUE THREAD

**Issue by xinkuang** [apache/skywalking#5822]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 ```
----------------------------
  skywalking server:
   --set oap.image.tag=8.2.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.2.0 \
  --set elasticsearch.imageTag=7.5.1

 --------------------
  javaagent : 8.2.0-es7
  
  javaagent: -javaagent:/agent/skywalking-agent.jar
      -Dskywalking.agent.service_name=abcd
      -Dskywalking.agent.sample_n_per_3_secs=6
      -Dskywalking.collector.backend_service=xxxxxxx:32611
```

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
local Idea env, run success，but in docker（k8s） env, 
**# java -version**
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190205_213 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

**error:**

```
DEBUG 2020-11-10 17:00:37:440 SkyWalkingAgent :  On Transformation class com.mysql.cj.jdbc.StatementImpl. 
DEBUG 2020-11-10 17:00:38:834 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2020-11-10 17:00:38:851 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: Register/doServiceRegister
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
        at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:111)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:813)

DEBUG 2020-11-10 17:00:41:834 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2020-11-10 17:00:41:907 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: Register/doServiceRegister
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
        at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:111)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:813)
```

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Your agent is too old. You need 8+ agent. Please read the changelog.

**Comment by xinkuang** [comment]
> Your agent is too old. You need 8+ agent. Please read the changelog.

use  this  javaagent 

https://archive.apache.org/dist/skywalking/8.2.0/apache-skywalking-apm-es7-8.2.0.tar.gz

 javaagent : 8.2.0-es7
 
 javaagent: -javaagent:/agent/skywalking-agent.jar
     -Dskywalking.agent.service_name=abcd
     -Dskywalking.agent.sample_n_per_3_secs=6
     -Dskywalking.collector.backend_service=xxxxxxx:32611


- in k8s pod ,base image use  centos ,

java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190205_213 (JIT enabled, AOT enabled)
OpenJ9 - 90dd8cb40
OMR - d2f4534b
JCL - d002501a90 based on jdk8u202-b08)

- telnet xxxxxxx 32611  is ok.
- in locak env ,javaagent work is ok.

**Comment by wu-sheng** [comment]
Again, there is no `Register/doServiceRegister` officially. Check your env, there should be 6.x or 7.x again running.
