### ISSUE TITLE
set SW_CORE_GRPC_HOST and SW_CORE_REST_HOST by oap docker says bind error

### ISSUE THREAD

**Issue by bigwalnut** [apache/skywalking#5828]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] RequirementO
- [ ] Feature or performance improvement

___
### Question
- When I use skywakling oap docker and set core grpc host to local host eth0 ip(eg: 100.65.136.30) or core rest host to local host eth0 ip, it always says bind error, I want to know why and how to fix it. I want to set a cluster by zookeeper, so i think i should change core grpc ip to eth0 ip，i have tried the same way by using bin pakage, it is ok, but it is not ok by using docker.

1. set SW_CORE_GRPC_HOST=100.65.136.30,  the error log is as fellow:
```
skyoap    | 2020-11-10 07:38:26,444 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer -8129 [main] INFO  [] - **_Bind handler JVMMetricReportServiceHandler into gRPC server 100.65.136.30:11800_**
skyoap    | 2020-11-10 07:38:26,589 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8274 [main] ERROR [] - **_Failed to bind_**
skyoap    | org.apache.skywalking.oap.server.library.module.ModuleStartException: Failed to bind
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:330) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:55) ~[library-module-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:63) ~[library-module-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.2.0.jar:8.2.0]
skyoap    | Caused by: org.apache.skywalking.oap.server.library.server.grpc.GRPCServerException: Failed to bind
skyoap    | at org.apache.skywalking.oap.server.library.server.grpc.GRPCServer.start(GRPCServer.java:134) ~[library-server-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:327) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | ... 4 more
skyoap    | Caused by: java.io.IOException: Failed to bind
skyoap    | at io.grpc.netty.NettyServer.start(NettyServer.java:264) ~[grpc-netty-1.32.1.jar:1.32.1]
skyoap    | at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[grpc-core-1.32.1.jar:1.32.1]
skyoap    | at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.32.1.jar:1.32.1]
skyoap    | at org.apache.skywalking.oap.server.library.server.grpc.GRPCServer.start(GRPCServer.java:132) ~[library-server-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:327) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | ... 4 more
skyoap    | Caused by: java.net.BindException: Cannot assign requested address
skyoap    | at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
skyoap    | at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
skyoap    | at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
skyoap    | at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
skyoap    | at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
skyoap    | at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

2. set SW_CORE_REST_HOST=100.65.136.30,  the error log is as fellow:

```
skyoap    | 2020-11-10 07:57:23,518 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer -8447 [main] INFO  [] - start server, host: 100.65.136.30, port: 12800
skyoap    | 2020-11-10 07:57:23,525 - org.eclipse.jetty.server.Server -8454 [main] INFO  [] - jetty-9.4.28.v20200408; built: 2020-04-08T17:49:39.557Z; git: ab228fde9e55e9164c738d7fa121f8ac5acd51c9; jvm 11.0.9+11
skyoap    | 2020-11-10 07:57:23,565 - org.eclipse.jetty.server.handler.ContextHandler -8494 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@4f1f2f84{/,null,AVAILABLE}
skyoap    | 2020-11-10 07:57:23,566 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8495 [main] ERROR [] - Failed to bind to /100.65.136.30:12800
skyoap    | org.apache.skywalking.oap.server.library.module.ModuleStartException: Failed to bind to /100.65.136.30:12800
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:330) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:55) ~[library-module-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:63) ~[library-module-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.2.0.jar:8.2.0]
skyoap    | Caused by: org.apache.skywalking.oap.server.library.server.jetty.JettyServerException: Failed to bind to /100.65.136.30:12800
skyoap    | at org.apache.skywalking.oap.server.library.server.jetty.JettyServer.start(JettyServer.java:117) ~[library-server-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:328) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | ... 4 more
skyoap    | Caused by: java.io.IOException: **_Failed to bind to /100.65.136.30:12800_**
skyoap    | at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.Server.doStart(Server.java:385) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.apache.skywalking.oap.server.library.server.jetty.JettyServer.start(JettyServer.java:115) ~[library-server-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:328) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | ... 4 more
skyoap    | Caused by: java.net.BindException: Cannot assign requested address
skyoap    | at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
skyoap    | at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
skyoap    | at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
skyoap    | at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
skyoap    | at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80) ~[?:?]
skyoap    | at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.server.Server.doStart(Server.java:385) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
skyoap    | at org.apache.skywalking.oap.server.library.server.jetty.JettyServer.start(JettyServer.java:115) ~[library-server-8.2.0.jar:8.2.0]
skyoap    | at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:328) ~[server-core-8.2.0.jar:8.2.0]
skyoap    | ... 4 more

```

**Comment by wu-sheng** [comment]
Sorry, `fail to bind` is not a thing we could fix. Please check the Jetty/gRPC document and FAQ, maybe some clues there.

**Comment by bigwalnut** [comment]
> Sorry, `fail to bind` is not a thing we could fix. Please check the Jetty/gRPC document and FAQ, maybe some clues there.

I am not familiar with java. If I don't use skywalking oap docker，try the same config by using skywaking binary package，jetty and grpc server can bind eth0 ip successly, this error only happened in docker. Could you give me some clue? Thanks!

**Comment by kezhenxu94** [comment]
> > Sorry, `fail to bind` is not a thing we could fix. Please check the Jetty/gRPC document and FAQ, maybe some clues there.
> 
> I am not familiar with java. If I don't use skywalking oap docker，try the same config by using skywaking binary package，jetty and grpc server can bind eth0 ip successly, this error only happened in docker. Could you give me some clue? Thanks!

@bigwalnut I don't think you can simply configure `SW_CORE_GRPC_HOST` or `SW_CORE_REST_HOST` to `100.65.136.30` because this IP is in your host machine, what you should do is to just bind `0.0.0.0` in the docker container, and map the port of that container to your host ip `100.65.136.30` and port `11800`, take a quick try on something like `docker run -p 100.65.136.30:11800:11800 -p 100.65.136.30:12800:12800 <the-docker-image-name>`
