### ISSUE TITLE
[Bug]Why does the k8s cluster deployment start an error

### ISSUE THREAD

**Issue by jaredhu** [apache/skywalking#5993]
### Bug
-Use skywalking-kubernetes helm to deploy in k8s

The following error message appears every time you start

`2020-12-11 09:13:56,370 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager -20470 [pool-5-thread-1] ERROR [] - Self remote client invoked to close.
org.apache.skywalking.oap.server.core.UnexpectedException: Self remote client invoked to close.
	at org.apache.skywalking.oap.server.core.remote.client.SelfRemoteClient.close(SelfRemoteClient.java:60) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.lambda$reBuildRemoteClients$8(RemoteClientManager.java:234) ~[server-core-8.3.0.jar:8.3.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.reBuildRemoteClients(RemoteClientManager.java:234) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:137) [server-core-8.3.0.jar:8.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

Is it related to the self.yaml configuration file? If it should be modified

I enabled Self Observability according to the document, this error still exists, but self.yaml is not modified

**Comment by hanahmily** [comment]
Yep, it's a bug, neither relating to SelfObservability nor affecting OAP server main loop, though.
The OAP instance list mix with some null values causes the close method to throw NPE. We should filter null before inserting it into this list.

**Comment by wu-sheng** [comment]
@hanahmily OK, let's fix this in the 8.4.0.

**Comment by wu-sheng** [comment]
@jaredhu Take a look at #5995

**Comment by jaredhu** [comment]
Okay, I will continue to pay attention
