### ISSUE TITLE
apollo配置了，skywalking无法动态拉取

### ISSUE THREAD

**Issue by code-sci** [apache/skywalking#6022]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
启动skywalking时报错：
```
com.ctrip.framework.apollo.internals.RemoteConfigLongPollService - 193 [Apollo-RemoteConfigLongPollService-1] WARN  [] - Long polling failed, will retry in 16 seconds. appId: skywalking, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://106.54.227.205//services/config?appId=skywalking&ip=192.168.88.150 [Cause: Could not complete get operation [Cause: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $ [Cause: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $]]]
```

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by code-sci** [comment]
application.yml的配置：
`configuration:
  selector: ${SW_CONFIGURATION:apollo}
  none:
  grpc:
    host: ${SW_DCS_SERVER_HOST:""}
    port: ${SW_DCS_SERVER_PORT:80}
    clusterName: ${SW_DCS_CLUSTER_NAME:SkyWalking}
    period: ${SW_DCS_PERIOD:20}
  apollo:
    apolloMeta: ${SW_CONFIG_APOLLO:http://106.54.227.205/}
    apolloCluster: ${SW_CONFIG_APOLLO_CLUSTER:default}
    apolloEnv: ${SW_CONFIG_APOLLO_ENV:"DEV"}
    appId: ${SW_CONFIG_APOLLO_APP_ID:skywalking}
    period: ${SW_CONFIG_APOLLO_PERIOD:5}`

**Comment by kezhenxu94** [comment]
@code-sci please always use English to benefit more people.

The `apolloMeta` should be point to the **meta server** of Apollo not the portal, hence `port` should be `8080` instead of `80` (by default)

**Comment by code-sci** [comment]
@kezhenxu94  It's work! but sorry, Now there is a new question:
```
2020-12-17 16:27:43,390 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 46 [main] INFO  [] - start the provider default in receiver-meter module.
2020-12-17 16:27:43,392 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer - 140 [main] INFO  [] - Bind handler MeterServiceHandler into gRPC server 0.0.0.0:11800
2020-12-17 16:27:43,399 - org.apache.skywalking.oap.server.analyzer.provider.trace.UninstrumentedGatewaysConfig - 83 [main] INFO  [] - Updating uninstrumented gateways with: null
2020-12-17 16:27:43,401 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.server.core.alarm.provider.RulesReader.lambda$readRulesConfig$0(RulesReader.java:82) ~[server-alarm-plugin-8.3.0.jar:8.3.0]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_261]
        at org.apache.skywalking.oap.server.core.alarm.provider.RulesReader.readRulesConfig(RulesReader.java:77) ~[server-alarm-plugin-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.alarm.provider.RulesReader.readRules(RulesReader.java:57) ~[server-alarm-plugin-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.alarm.provider.AlarmRulesWatcher.notify(AlarmRulesWatcher.java:73) ~[server-alarm-plugin-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.lambda$null$1(ConfigWatcherRegister.java:99) ~[configuration-api-8.3.0.jar:8.3.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.lambda$configSync$2(ConfigWatcherRegister.java:83) ~[configuration-api-8.3.0.jar:8.3.0]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_261]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.configSync(ConfigWatcherRegister.java:82) ~[configuration-api-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.start(ConfigWatcherRegister.java:67) ~[configuration-api-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.configuration.api.AbstractConfigurationProvider.notifyAfterCompleted(AbstractConfigurationProvider.java:53) ~[configuration-api-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:55) ~[library-module-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:63) ~[library-module-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.3.0.jar:8.3.0]

```

**Comment by kezhenxu94** [comment]
you are using the env that I created to develop the Apollo implementation, so take a look at the history version 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15965696/102465073-2aa33100-4088-11eb-9342-680584f0578c.png">

your YAML format is wrong, the indentations are incorrect

**Comment by code-sci** [comment]
Thank you for your patient guidance！
