### ISSUE TITLE
Gradle+logback 1.2.3+springboot 2.7.7 +apm-toolkit-logback-1.x 6.6.0==> [tid] is not a valid conversion word

### ISSUE THREAD

**Issue by beijingzhangwei** [apache/skywalking#6032]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ java logback tid not valid]

___
### Question
- how to resovle?
2020-12-19 19:48:16]-[ERROR]-[SpringApplication.java : 826]-[ERROR %PARSER_ERROR[tid] main]-[TraceId:]-[Application run failed
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.pattern.parser.Compiler@672872e1 - There is no conversion class registered for conversion word [tid]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@672872e1 - [tid] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@32910148 - There is no conversion class registered for conversion word [tid]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@32910148 - [tid] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@3f56875e - There is no conversion class registered for conversion word [tid]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@3f56875e - [tid] is not a valid conversion word
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	a
###  my configuration : follow 

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}/spring.log}"/>
    <springProfile name="default">
        <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>
    </springProfile>
    <springProfile name="test,prod">
        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <encoder>
                <pattern> %d{yyyy-MM-dd HH:mm:ss}]-[%p]-[%file : %line]-[%-5level %tid %t]-[TraceId:%X{X-B3-TraceId}]-[%m%n</pattern>
                <charset>UTF-8</charset>
            </encoder>
            <file>${LOG_FILE}</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>${LOG_FILE}.%d{yyyyMMdd}.%i</fileNamePattern>
                <maxHistory>365</maxHistory>
                <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                    <maxFileSize>100MB</maxFileSize>
                </timeBasedFileNamingAndTriggeringPolicy>
            </rollingPolicy>
        </appender>

### Bug
- jdk 1.8.0_144 + contos 1.8.1 +logback 1.2.3+springboot 2.7.7 +apm-toolkit-logback-1.x 6.6.0

- 小打卡 微信小程序 TOP 50

**Comment by kezhenxu94** [comment]
Please read [the doc](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md), you need a SkyWalking layout to parse `%tid`

```xml
<layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
    <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%tid] [%thread] %-5level %logger{36} -%msg%n</Pattern>
</layout>
```
