### ISSUE TITLE
skywalking start problem

### ISSUE THREAD

**Issue by yiliaofan** [apache/skywalking#6079]
thank you~

2020-12-25 12:44:46,980 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 71 [main] INFO  [] - Prepare the graphql provider in query module.
2020-12-25 12:44:47,283 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 71 [main] ERROR [] - No method found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  org.apache.skywalking.oap.query.graphql.resolver.Query.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.Query.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.HealthQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.HealthQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopologyQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopologyQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AggregationQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AggregationQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AlarmQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AlarmQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.LogQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.LogQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.ProfileQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.ProfileQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.UIConfigurationManagement.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.UIConfigurationManagement.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.BrowserLogQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.BrowserLogQuery.getGetAllServices(~duration)
com.coxautodev.graphql.tools.FieldResolverError: No method found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  org.apache.skywalking.oap.query.graphql.resolver.Query.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.Query.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.HealthQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.HealthQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopologyQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopologyQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AggregationQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AggregationQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TopNRecordsQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AlarmQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.AlarmQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.LogQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.LogQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.ProfileQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.ProfileQuery.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.UIConfigurationManagement.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.UIConfigurationManagement.getGetAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.BrowserLogQuery.getAllServices(~duration)
  org.apache.skywalking.oap.query.graphql.resolver.BrowserLogQuery.getGetAllServices(~duration)
	at com.coxautodev.graphql.tools.FieldResolverScanner.missingFieldResolver(FieldResolverScanner.kt:51) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.FieldResolverScanner.findFieldResolver(FieldResolverScanner.kt:42) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:227) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.SchemaClassScanner.handleRootType(SchemaClassScanner.kt:122) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:80) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:150) ~[graphql-java-tools-5.2.3.jar:?]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:156) ~[graphql-java-tools-5.2.3.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryProvider.prepare(GraphQLQueryProvider.java:110) ~[classes/:?]
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:96) ~[classes/:?]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:47) ~[classes/:?]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [classes/:?]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [classes/:?]
2020-12-25 12:44:47,289 pool-1-thread-1 DEBUG Stopping LoggerContext[name=368239c8, org.apache.logging.log4j.core.LoggerContext@7502291e]
2020-12-25 12:44:47,289 pool-1-thread-1 DEBUG Stopping LoggerContext[name=368239c8, org.apache.logging.log4j.core.LoggerContext@7502291e]...
2020-12-25 12:44:47,291 pool-1-thread-1 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false
2020-12-25 12:44:47,292 pool-1-thread-1 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false, all resources released: true
2020-12-25 12:44:47,292 pool-1-thread-1 DEBUG Appender Console stopped with status true
2020-12-25 12:44:47,292 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=/Users/fanzhang/work/shuidi/skywalking/skywalking/oap-server/server-bootstrap/target/classes/log4j2.xml] OK
2020-12-25 12:44:47,292 pool-1-thread-1 DEBUG Stopped LoggerContext[name=368239c8, org.apache.logging.log4j.core.LoggerContext@7502291e] with status true

**Comment by wu-sheng** [comment]
We have 100+ e2e testa to make sure there is no issue when boot. If you don't describe anything, we can't help.

**Comment by Z-Beatles** [comment]
update submodule of skywalking/apm-protocol/apm-network/proto, it works for me.
