### ISSUE TITLE
OAP, No files in ui-initialized-templates

### ISSUE THREAD

**Issue by tengwei-lewis** [apache/skywalking#6086]
2020-12-27 19:47:38,408 - org.eclipse.jetty.server.Server - 399 [main] INFO  [] - Started @12240ms
2020-12-27 19:47:38,409 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 56 [main] INFO  [] - persistence timer start
2020-12-27 19:47:38,430 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 46 [main] INFO  [] - Cache updateServiceInventory timer start
2020-12-27 19:47:38,433 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - No files in ui-initialized-templates
java.lang.NullPointerException: No files in ui-initialized-templates
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_101]
	at org.apache.skywalking.oap.server.library.util.ResourceUtils.getPathFiles(ResourceUtils.java:51) ~[library-util-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:342) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:55) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:63) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.3.0.jar:8.3.0]

**Comment by tengwei-lewis** [comment]
版本：8.3.0
环境：Windows10

**Comment by wu-sheng** [comment]
Please use English on the GitHub. My guess, you are using old config folder with latest version.

**Comment by caopengan** [comment]
I had the same problem.The solution is Do not use Chinese paths.
