### ISSUE TITLE
Skywalking 8.3 Mysql8 Plugin  NPE at org.apache.skywalking.apm.plugin.jdbc.JDBCPreparedStatementNullSetterInterceptor.beforeMethod

### ISSUE THREAD

**Issue by Shoothzj** [apache/skywalking#6117]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Question
Why NPE? Does it matter ? If it's matter, how to fix it.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 8.3.0
OS: ubuntu 20
JRE: tried both version 8 and 11

- Which company or project?
- personal demo

- What happened?
agent-param:
```
-javaagent:/home/akkascala/shoothzj/skywalking/agent/skywalking-agent.jar -Dskywalking_config=/home/akkascala/master/demo-iot-device-manage/agent.config -Dskywalking.agent.service_name=device-manage
```
maven dependency:
```xml
<dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>2.3.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.3.4.RELEASE</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.20</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>
```
in agent log
```
ERROR 2021-01-01 21:47:51:909 main InstMethodsInter : class[class com.mysql.cj.jdbc.ClientPreparedStatement] before method[setNull] intercept failure 
java.lang.NullPointerException
	at org.apache.skywalking.apm.plugin.jdbc.JDBCPreparedStatementNullSetterInterceptor.beforeMethod(JDBCPreparedStatementNullSetterInterceptor.java:34)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setNull(ClientPreparedStatement.java)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getTables(DatabaseMetaDataUsingInfoSchema.java:854)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getTables(ProxyDatabaseMetaData.java:69)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getTables(HikariProxyDatabaseMetaData.java)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getTables(InformationExtractorJdbcDatabaseMetaDataImpl.java:333)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.getTablesInformation(DatabaseInformationImpl.java:120)
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:65)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.github.shoothzj.demo.iot.mdevice.manage.MysqlDemo.main(MysqlDemo.java:23)
```
___
### Requirement or improvement
That's my demo
[demo-iot-device-manage.zip](https://github.com/apache/skywalking/files/5759016/demo-iot-device-manage.zip)
And that's agent log
[skywalking-api.log](https://github.com/apache/skywalking/files/5759022/skywalking-api.log)

**Comment by wu-sheng** [comment]
Could you debug to see what causes the NPE? The code shows L34 is this
> final int index = (Integer) allArguments[0];

You don't give the first argument?

**Comment by Shoothzj** [comment]
> Could you debug to see what causes the NPE? The code shows L34 is this
> 
> > final int index = (Integer) allArguments[0];
> 
> You don't give the first argument?

I am in china, it's slow to download the dependency, so I can't open skywalking project now. I am afraid I can download completely tomorrw.
I got this error when I am starting. I don't know what argument should I give. 
I can run well without agent
```
akkascala@akka:~/atom/wrk$ wrk -t 12 -c 400 -d 200s -s post.lua http://127.0.0.1:8182/device-manage/register-device
Running 3m test @ http://127.0.0.1:8182/device-manage/register-device
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   233.18ms   92.34ms   1.99s    94.23%
    Req/Sec   145.91     33.42   282.00     68.10%
  347150 requests in 3.33m, 24.23MB read
Requests/sec:   1734.89
Transfer/sec:    123.97KB

```

**Comment by wu-sheng** [comment]
#6007 added a NULL check in the master check. This is how it looks like now. https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/JDBCPreparedStatementNullSetterInterceptor.java.

You could consider compiling the master and try again.

**Comment by wu-sheng** [comment]
In that PR, he said, the NPE only related the Oracle driver tracing. I am not sure whether you are in a similar case.

**Comment by Shoothzj** [comment]
Ok, I'll try

**Comment by Shoothzj** [comment]
> #6007 added a NULL check in the master check. This is how it looks like now. https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/JDBCPreparedStatementNullSetterInterceptor.java.
> 
> You could consider compiling the master and try again.
![Screenshot from 2021-01-02 08-42-46](https://user-images.githubusercontent.com/12933197/103448585-87345c00-4cd6-11eb-9dd1-9197e6ac9c8a.png)
The NPE exception disappear, there is another exception here.

**Comment by Shoothzj** [comment]
> > #6007 added a NULL check in the master check. This is how it looks like now. https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/JDBCPreparedStatementNullSetterInterceptor.java.
> > You could consider compiling the master and try again.
> > ![Screenshot from 2021-01-02 08-42-46](https://user-images.githubusercontent.com/12933197/103448585-87345c00-4cd6-11eb-9dd1-9197e6ac9c8a.png)
> > The NPE exception disappear, there is another exception here.

And yesterday, I can see my service in here
![Screenshot from 2021-01-02 08-44-51](https://user-images.githubusercontent.com/12933197/103448609-e6926c00-4cd6-11eb-90dd-786918cd0cf9.png)

**Comment by Shoothzj** [comment]
> In that PR, he said, the NPE only related the Oracle driver tracing. I am not sure whether you are in a similar case.

I upgrade both agent and server side to master version. The agent looks work well. But I can not see any data in the web console.

![Screenshot from 2021-01-02 09-10-48](https://user-images.githubusercontent.com/12933197/103448861-6ff76d80-4cda-11eb-8092-6f0fcec00475.png)
I open the debug log for agent, it seems agent already send the data to server.
```
DEBUG 2021-01-02 09:07:47:816 DataCarrier.DEFAULT.Consumer.0.Thread TraceSegmentServiceClient : 1636 trace segments have been sent to collector. 
``` 
Also tried modify cofig, not work
```
# The number of sampled traces per 3 seconds
# Negative or zero means off, by default
agent.sample_n_per_3_secs=1000
```

**Comment by wu-sheng** [comment]
The logs are correct. This is data reported. Maybe your time or timezone on the UI right bottom is not correct. Click reload or choose the right time zone.
