### ISSUE TITLE
Duplicate worker name:endpoint_relation_server_side_rec

### ISSUE THREAD

**Issue by weelet** [apache/skywalking#6128]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
2021-01-04 15:27:31,005 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Duplicate worker name:endpoint_relation_server_side_rec
org.apache.skywalking.oap.server.core.UnexpectedException: Duplicate worker name:endpoint_relation_server_side_rec
        at org.apache.skywalking.oap.server.core.worker.WorkerInstancesService.put(WorkerInstancesService.java:49) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsStreamProcessor.create(MetricsStreamProcessor.java:161) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.analysis.worker.MetricsStreamProcessor.create(MetricsStreamProcessor.java:97) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.analysis.StreamAnnotationListener.notify(StreamAnnotationListener.java:57) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.annotation.AnnotationScan$AnnotationListenerCache.complete(AnnotationScan.java:91) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.annotation.AnnotationScan$AnnotationListenerCache.access$300(AnnotationScan.java:71) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.scan(AnnotationScan.java:67) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.start(CoreModuleProvider.java:295) ~[server-core-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:62) ~[library-module-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.3.0.jar:8.3.0]
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.3.0，centos，jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you do? We don't know this bug, or related things. CI, e2e tests, and local tests passed.
