### ISSUE TITLE
java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping when use elasticsearch7

### ISSUE THREAD

**Issue by bootsrc** [apache/skywalking#6140]
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
apache-skywalking-apm-es7-8.3.0
os:osx-x86_64 10.14
- Which company or project?
my own project
- What happened?
I config in application.yml
 storage.selector: ${SW_STORAGE:elasticsearch}
 storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

exeute command
 apache-skywalking-apm-bin-es7/bin/oapService.sh

see logs in ../logs/skywalking-oap-server.log
`
java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:146) ~[library-client-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:202) ~[storage-elasticsearch-plugin-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:62) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.3.0.jar:8.3.0]
2021-01-06 10:57:59,552 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 81 [pool-5-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
`

Maybe the problem is no method name ping() in elasticsearch-rest-high-level-client-7.5.0.jar

`
ls |grep elastic
elasticsearch-7.5.0.jar
elasticsearch-cli-7.5.0.jar
elasticsearch-core-7.5.0.jar
elasticsearch-geo-7.5.0.jar
elasticsearch-rest-client-7.5.0.jar
elasticsearch-rest-high-level-client-7.5.0.jar
elasticsearch-secure-sm-7.5.0.jar
elasticsearch-x-content-7.5.0.jar
storage-elasticsearch-plugin-8.3.0.jar
storage-elasticsearch7-plugin-8.3.0.jar
`
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
`elasticsearch` means activating ElasticSearch 6 storage.

**Comment by bootsrc** [comment]
I config in application.yml
storage.selector: ${SW_STORAGE:elasticsearch7}
storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

**Comment by tbongiovani** [comment]
> I config in application.yml
> storage.selector: ${SW_STORAGE:elasticsearch7}
> storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

work for me! tks!

**Comment by qinshaokang** [comment]
> I config in application.yml
> storage.selector: ${SW_STORAGE:elasticsearch7}
> storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

work for me！thx!

**Comment by chenguoo** [comment]
> work for me! tks!

**Comment by chenguoo** [comment]
> I config in application.yml storage.selector: ${SW_STORAGE:elasticsearch7} storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

work for me ! tks!

**Comment by chenguoo** [comment]
> I config in application.yml 
> storage.selector: ${SW_STORAGE:elasticsearch7} 
> storage.elasticsearch7.nameSpace: ${SW_NAMESPACE:"elasticsearch"}

work for me ! tks!
