### ISSUE TITLE
OAL supports multiple values when as numeric

### ISSUE THREAD

**Issue by itfinally** [apache/skywalking#6231]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I write this code on **core.oal** file
`endpoint_abnormal = from(Endpoint.responseCode).filter(responseCode in [404, 500, 503]).sum();`

Then throw an exception
```java
2021-01-19 18:20:55,083 - org.apache.skywalking.oal.rt.OALRuntime - 71 [main] ERROR [] - Method body as following
private void doEndpointAbnormal(org.apache.skywalking.oap.server.core.source.Endpoint source) {
org.apache.skywalking.oap.server.core.source.oal.rt.metrics.EndpointAbnormalMetrics metrics = new org.apache.skywalking.oap.server.core.source.oal.rt.metrics.EndpointAbnormalMetrics();

        if (!new org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch().match(source.getResponseCode(), new Object[]{404,500,503})) {
        return;
        }

metrics.setTimeBucket(source.getTimeBucket());
    metrics.setEntityId(source.getEntityId());
    metrics.setServiceId(source.getServiceId());
metrics.combine(
        (long)(source.getResponseCode())

);

org.apache.skywalking.oap.server.core.analysis.worker.MetricsStreamProcessor.getInstance().in(metrics);
}

2021-01-19 18:20:55,083 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 71 [main] ERROR [] - [source error] match(int,java.lang.Object[]) not found in org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch
org.apache.skywalking.oap.server.library.module.ModuleStartException: [source error] match(int,java.lang.Object[]) not found in org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:65) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.analyzer.provider.AnalyzerModuleProvider.start(AnalyzerModuleProvider.java:116) ~[agent-analyzer-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:62) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.3.0.jar:8.3.0]
Caused by: org.apache.skywalking.oap.server.core.oal.rt.OALCompileException: [source error] match(int,java.lang.Object[]) not found in org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch
	at org.apache.skywalking.oal.rt.OALRuntime.generateDispatcherClass(OALRuntime.java:417) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.generateClassAtRuntime(OALRuntime.java:191) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:160) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:60) ~[server-core-8.3.0.jar:8.3.0]
	... 5 more
Caused by: javassist.CannotCompileException: [source error] match(int,java.lang.Object[]) not found in org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch
	at javassist.CtNewMethod.make(CtNewMethod.java:84) ~[javassist-3.25.0-GA.jar:?]
	at javassist.CtNewMethod.make(CtNewMethod.java:50) ~[javassist-3.25.0-GA.jar:?]
	at org.apache.skywalking.oal.rt.OALRuntime.generateDispatcherClass(OALRuntime.java:410) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.generateClassAtRuntime(OALRuntime.java:191) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:160) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:60) ~[server-core-8.3.0.jar:8.3.0]
	... 5 more
Caused by: javassist.compiler.CompileError: match(int,java.lang.Object[]) not found in org.apache.skywalking.oap.server.core.analysis.metrics.expression.InMatch
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:723) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:547) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:619) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.ast.Expr.accept(Expr.java:71) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:260) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:414) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.Javac.compileMethod(Javac.java:175) ~[javassist-3.25.0-GA.jar:?]
	at javassist.compiler.Javac.compile(Javac.java:102) ~[javassist-3.25.0-GA.jar:?]
	at javassist.CtNewMethod.make(CtNewMethod.java:79) ~[javassist-3.25.0-GA.jar:?]
	at javassist.CtNewMethod.make(CtNewMethod.java:50) ~[javassist-3.25.0-GA.jar:?]
	at org.apache.skywalking.oal.rt.OALRuntime.generateDispatcherClass(OALRuntime.java:410) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.generateClassAtRuntime(OALRuntime.java:191) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:160) ~[oal-rt-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:60) ~[server-core-8.3.0.jar:8.3.0]
	... 5 more
```

and this is the function `match`, copy from [InMatch](https://github.com/apache/skywalking/blob/master/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/metrics/expression/InMatch.java)
```java
package org.apache.skywalking.oap.server.core.analysis.metrics.expression;

import java.util.Objects;
import org.apache.skywalking.oap.server.core.analysis.metrics.annotation.FilterMatcher;

@FilterMatcher
public class InMatch {
    public boolean match(Object left, Object[] rights) {
        for (Object right : rights) {
            if (right instanceof String) {
                String r = (String) right;
                if (r.startsWith("\"") && r.endsWith("\"")) {
                    right = r.substring(1, r.length() - 1);
                }
            }
            if (Objects.equals(left, right)) {
                return true;
            }
        }
        return false;
    }
}
```

Should it be cast to Object by autoboxing ? 
Or it is there other way to customize oal ?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

env: Skywalking 8.3.0 / MacOS / Java 11

- Which company or project?

- What happened?

If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
This seems to be a bug

**Comment by wu-sheng** [comment]
I think we support IN when type is String only, today.
@arugal Right?

**Comment by arugal** [comment]
> I think we support IN when type is String only, today.

String and `enum` are currently supported.

**Comment by arugal** [comment]
@itfinally  Fixed, welcome to try :)
