### ISSUE TITLE
Forgot to close http resource cause to ConnectionPoolTimeoutException

### ISSUE THREAD

**Issue by ecyuan** [apache/skywalking#6280]
**Bug detail:**

org.apache.skywalking.oap.server.core.alarm.provider.dingtalk.DingtalkHookCallback -152207495 [pool-3-thread-1] ERROR [] - send dingtalk alarm to https://oapi.dingtalk.com/robot/send?access_token=xxx failure.
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:280) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.7.jar:4.5.7]
        at org.apache.skywalking.oap.server.core.alarm.provider.dingtalk.DingtalkHookCallback.sendAlarmMessage(DingtalkHookCallback.java:144) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at org.apache.skywalking.oap.server.core.alarm.provider.dingtalk.DingtalkHookCallback.lambda$null$0(DingtalkHookCallback.java:88) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
        at org.apache.skywalking.oap.server.core.alarm.provider.dingtalk.DingtalkHookCallback.lambda$doAlarm$1(DingtalkHookCallback.java:83) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
        at org.apache.skywalking.oap.server.core.alarm.provider.dingtalk.DingtalkHookCallback.doAlarm(DingtalkHookCallback.java:82) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$null$3(AlarmCore.java:84) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
        at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$start$4(AlarmCore.java:84) [server-alarm-plugin-8.2.0.jar:8.2.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]

**Reason:**
Forgot to close http response resource. Following file line:
https://github.com/apache/skywalking/blob/master/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/dingtalk/DingtalkHookCallback.java#L144

The "httpResponse" must be close to release the connection, otherwise it will hold the connection resource. When the numbers of connection over the default overhead, next request will throw ConnectionPoolTimeoutException.

All other webhook callback have the same problem.

**Suggestion**
User can define the connection numbers, e.g: 
HTTP_CONNECTION_REQUEST_TIMEOUT 
org.apache.http.impl.client.HttpClientBuilder#setMaxConnPerRoute
etc..
Using env variable is the best.

**Comment by wu-sheng** [comment]
Sorry, I am not familiar with this part, aren't `httpClient#close` enough?

**Comment by ecyuan** [comment]
> Sorry, I am not familiar with this part, aren't `httpClient#close` enough?

Yes, just do that.

**Comment by wu-sheng** [comment]
Are you saying, because there are many messages sent, so the httpClient opened for a long time?

**Comment by ecyuan** [comment]
> Are you saying, because there are many messages sent, so the httpClient opened for a long time?

No. each send action hold a http connection resource, if you don't close it, the connection pool will be full always, so next request can do nothing.

Infact that is an java.util.concurrent.Future.

**Comment by wu-sheng** [comment]
OK, get it. Then the next question is, why do you suggest to open `HTTP_CONNECTION_REQUEST_TIMEOUT` rather than closing the httpResponse in the `try(...)`?

**Comment by ecyuan** [comment]
> OK, get it. Then the next question is, why do you suggest to open `HTTP_CONNECTION_REQUEST_TIMEOUT` rather than closing the httpResponse in the `try(...)`?

For example, some network problem in IDC, 1 second mabey timeout easily, I hope to change it.

**Comment by wu-sheng** [comment]
Agree, we could have both. But the system env (HTTP_CONNECTION_REQUEST_TIMEOUT) should not implement in the codes level, we provide a standard mode by application.yml to do this already, I think you have used it.
Recommend you to add `AlarmSettings#httpTimeout`, and make all notifiers to use it.

We are welcome you to submit pull request(1 or 2 up to you) to submit this. We are closing the 8.4.0, next 2-3 days, if you plan to include this in this release, you need to submit the pull request today.

**Comment by ecyuan** [comment]
OK, I try my best.

**Comment by wu-sheng** [comment]
If you don't have enough time, it is fine. You could submit later, we will loop it in the 8.5.0.

**Comment by ecyuan** [comment]
Nice, so wait for next version.
