### ISSUE TITLE
Protocol message had invalid UTF-8

### ISSUE THREAD

**Issue by andi-souwer** [apache/skywalking#6344]
### - 1/ There is no problem in this environment
- kernel: 5.6.4
- skywalking: 8.3/8.4
- k8s: 1.18
- es: 7.9.0

### - 2/ but this problem will occur, and the following error will appear. I don’t know what is causing it, including using the skywalking7 version. The error is also related to grpc
- kernel: 4.4196
- skywalking: 8.3/8.4
- k8s: 1.15
- es: 7.9.0

``` log
Feb 07, 2021 1:12:50 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@34b37673
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:296)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
        at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:141)
        at com.google.protobuf.Utf8$DecodeUtil.handleTwoBytes(Utf8.java:1909)
        at com.google.protobuf.Utf8$DecodeUtil.access$700(Utf8.java:1883)
        at com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8(Utf8.java:1411)
        at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:340)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:809)
        at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject.<init>(SegmentObject.java:65)
        at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject.<init>(SegmentObject.java:16)
        at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject$1.parsePartialFrom(SegmentObject.java:1649)
        at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject$1.parsePartialFrom(SegmentObject.java:1643)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
        ... 10 more
```

**Comment by wu-sheng** [comment]
We only support UTC-8 message. Including logs, tags/logs of trace/span.

**Comment by andi-souwer** [comment]
How do i need to adjust？

**Comment by wu-sheng** [comment]
That depends on your codes, I don't know how you write codes.

**Comment by andi-souwer** [comment]
3Q
