### ISSUE TITLE
java.lang.OutOfMemoryError when the workdir is "/"

### ISSUE THREAD

**Issue by libinglong** [apache/skywalking#6425]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.x

 java.lang.OutOfMemoryError: Java heap space
        at java.io.UnixFileSystem.resolve(UnixFileSystem.java:110) ~[?:?]
        at java.io.File.<init>(File.java:263) ~[?:?]
        at java.io.File.listFiles(File.java:1226) ~[?:?]
        at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:551) ~[guava-28.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:562) ~[guava-28.1-jre.jar:?]
        at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:562) ~[guava-28.1-jre.jar:?]

when I run the command
sh /${skywalking_home}/bin/startup.sh
The current dir "/" is added to the classpath by this code
> CLASSPATH="$OAP_HOME/config:$CLASSPATH"

Because the CLASSPATH may be empty before.

**Comment by wu-sheng** [comment]
This is new, we never expect you will run in this way.

**Comment by libinglong** [comment]
> This is new, we never expect you will run in this way.

I want to run it in a docker container. I copy the skywalking-home to "/" which causes this problem.

**Comment by wu-sheng** [comment]
We have officer container image, take a look.

**Comment by libinglong** [comment]
> We have officer container image, take a look.

OK, thank u.

**Comment by fankiwu** [comment]
> 

我很好奇为什么会这样，我也遇到了，都怀疑人生了
