### ISSUE TITLE
NPE is thrown in SkyWalking 8.4.0 with gateway plugin

### ISSUE THREAD

**Issue by apple987** [apache/skywalking#6492]
here is the config!

pom.xml
       <dependency>
           <groupId>org.apache.skywalking</groupId>
           <artifactId>apm-toolkit-logback-1.x</artifactId>
           <version>8.4.0</version>
       </dependency>

logback_spring.xml

    <appender name="grpc_log" class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender">
    </appender>
   <root level="info">
        <appender-ref ref="CONSOLE_APPENDER"/>
        <appender-ref ref="ROOT_APPENDER"/>
        <appender-ref ref="grpc_log" />
    </root>

the skywalking  with the default config,but when the gateway startup,the console tips the error like this:

[TID:N/A]  [] 2021-03-05 09:33:02.492:[ERROR] [reactor-http-nio-2:22985] [r.u.Loggers$Slf4JLogger:error:319]--> Operator called default onErrorDropped
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.webclient.WebFluxWebClientInterceptor$1.accept(WebFluxWebClientInterceptor.java:85)
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.webclient.WebFluxWebClientInterceptor$1.accept(WebFluxWebClientInterceptor.java:82)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:262)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:252)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:197)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:406)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:339)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$TcpClientSubscriber.onError(HttpClientConnect.java:353)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onError(PooledConnectionProvider.java:523)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:427)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$5(SimpleDequePool.java:309)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:172)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:304)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:254)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

all the pom.xml like this,need help thanks!

[pom.zip](https://github.com/apache/skywalking/files/6087652/pom.zip)

**Comment by wu-sheng** [comment]
This error log seems don't relate to the log appender. Why do you say NPE is caused by this?

**Comment by apple987** [comment]
![image](https://user-images.githubusercontent.com/21330215/110056131-3655e800-7d99-11eb-97e3-6a01538f8cd0.png)
the appender is work,and the skywaling console can see the log with the treaceId,but the gateway console print this error,seem like the skywalking agent/config webflux.client with error!

**Comment by wu-sheng** [comment]
I mean, this error should exist even you don't add the log appender.

**Comment by apple987** [comment]
how to do? need help thanks!

**Comment by apple987** [comment]
here is the doc! the gateway also print the NPE error,why?
https://skywalking.apache.org/docs/main/v8.4.0/en/setup/service-agent/java-agent/application-toolkit-logback-1.x/

**Comment by wu-sheng** [comment]
This seems a gateway plugin code bug. Again nothing related to the thing you keep repeatedly saying.

**Comment by wu-sheng** [comment]
I you could provide the whole gateway package, I could ask @ascrutae to take a look.

**Comment by apple987** [comment]
ok! here is the code,you need to config the nacos
[code.zip](https://github.com/apache/skywalking/files/6087723/code.zip)

**Comment by apple987** [comment]
here is the gateway.yaml 
[gateway.zip](https://github.com/apache/skywalking/files/6087734/gateway.zip)

**Comment by apple987** [comment]
here is the log stack!
[error.zip](https://github.com/apache/skywalking/files/6088264/error.zip)

**Comment by xzxiaoshan** [comment]
spring-boot -->  2.4.3\2.4.4 、cloud  --> 2020.0.1\2020.0.2
NPE error，Does gateway need to be a  "​apm-spring-cloud-gateway-3.0.x-plugin" ?

**Comment by wu-sheng** [comment]
> spring-boot --> 2.4.3\2.4.4 、cloud --> 2020.0.1\2020.0.2
> NPE error，Does gateway need to be a "​apm-spring-cloud-gateway-3.0.x-plugin" ?

Yes. Please don't submit a duplicated issue.

**Comment by xzxiaoshan** [comment]
> > spring-boot --> 2.4.3\2.4.4 、cloud --> 2020.0.1\2020.0.2
> > NPE error，Does gateway need to be a "​apm-spring-cloud-gateway-3.0.x-plugin" ?
> 
> Yes. Please don't submit a duplicated issue.

3Q，Will this problem be fixed ?

**Comment by wu-sheng** [comment]
> > > spring-boot --> 2.4.3\2.4.4 、cloud --> 2020.0.1\2020.0.2
> > > NPE error，Does gateway need to be a "​apm-spring-cloud-gateway-3.0.x-plugin" ?
> > 
> > 
> > Yes. Please don't submit a duplicated issue.
> 
> 3Q，Will this problem be fixed ?

`will` doesn't exist. If you or anyone submit a pull request, then yes.

**Comment by wallezhang** [comment]
@wu-sheng I found that there are several issue related to spring gateway, e.g. #6237 ,so I tried to use the latest version of `spring-cloud-gateway-starter` with `gateway-2.1.x-plugin`, and it will report NPE when forwarding the request, because the enhancement method of `HttpClientFinalizer` class is no longer applicable. At the same time, I ran the `gateway-2.1.x-scenario` test project, and found that the version it relied on was very old. I think we should create a new plugin to support the new version of `spring-cloud-gateway`. If no one has done it yet, I can try it.

**Comment by wu-sheng** [comment]
> @wu-sheng I found that there are several issue related to spring gateway, e.g. #6237 ,so I tried to use the latest version of `spring-cloud-gateway-starter` with `gateway-2.1.x-plugin`, and it will report NPE when forwarding the request, because the enhancement method of `HttpClientFinalizer` class is no longer applicable. At the same time, I ran the `gateway-2.1.x-scenario` test project, and found that the version it relied on was very old. I think we should create a new plugin to support the new version of `spring-cloud-gateway`. If no one has done it yet, I can try it.

If you found the issue, go for it, please.

**Comment by wu-sheng** [comment]
And add more plugin tests to verify your new codes.

**Comment by wallezhang** [comment]
> And add more plugin tests to verify your new codes.

Of course, tests are important
