### ISSUE TITLE
skywalking nodejs error

### ISSUE THREAD

**Issue by lorgine** [apache/skywalking#6532]
(function (exports, require, module, __filename, __dirname) { import agent from 'skywalking-backend-js';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)

**Comment by kezhenxu94** [comment]
Seems your codes are invalid in terms of NodeJS syntax, non of the SkyWalking's business. Please recheck yourself

**Comment by lorgine** [comment]
is there a complete and runable demo  for nodejs?

**Comment by kezhenxu94** [comment]
https://github.com/apache/skywalking-nodejs/tree/master/tests/plugins here are the runnable tests

**Comment by lorgine** [comment]
ok thankyou
