### ISSUE TITLE
Docker 8.4.0-ES7 failed to boot

### ISSUE THREAD

**Issue by Maijh97** [apache/skywalking#6617]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- es7 + docker image 8.4.0-es7 start error
`

2021-03-24 17:12:46,670 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8657 [main] ERROR [] - 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
java.lang.NoSuchMethodError: 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:146) ~[library-client-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:202) ~[storage-elasticsearch-plugin-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:62) ~[library-module-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.4.0.jar:8.4.0]

`

Start the command
`
docker run --name oap --restart always -d \
--restart=always \
--net esnetwork \
-e TZ=Asia/Shanghai \
-p 12800:12800 \
-p 11800:11800 \
--link es7:es7 \
-e SW_STORAGE=elasticsearch \
-e SW_STORAGE_ES_CLUSTER_NODES=es7:9200 \
apache/skywalking-oap-server:8.4.0-es7
`

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Use `SW_STORAGE=elasticsearch7`.

**Comment by Maijh97** [comment]
@wu-sheng It worked. Thank you
