### ISSUE TITLE
Where can i set proxy info to acces elasticsearch in the outside?

### ISSUE THREAD

**Issue by goooogs** [apache/skywalking#6641]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
my Skywalking OAP Service and elasticsearch are located in different Clouds
OAP Service can only access resources out of its Cloud with corporate layer 7 http proxy.
But, where can i set http proxy for OAP Service to acces elasticsearch in the outside?

```bash
# The curl command works fine with http proxy
curl -x my-proxy:3128 https://my-es.example.com
```

I have tried:
```
# Set the OS system-wide environments
http_proxy=http://my-proxy:3128
https_proxy=http://my-proxy:3128
HTTP_PROXY=http://my-proxy:3128
HTTPS_PROXY=http://my-proxy:3128

# and JAVA_OPTS
JAVA_OPTS="
    -Dhttp.proxySet=true 
    -Dhttp.proxyHost=my-proxy -Dhttp.proxyPort=3128 
    -Dhttps.proxyHost=my-proxy -Dhttps.proxyPort=3128 
    $JAVA_OPTS
"
```
but it without effect.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking: apache-skywalking-apm-es6-8.4.0
JRE: openjdk version "11.0.8" 2020-07-14, 64-Bit
and a http proxy to access the internet (Layer 7 proxy)

- Which company or project?

- What happened?

If possible, provide a way to reproduce the error. e.g. demo application, component version.
```
2021-03-29 08:00:26,105 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -6634 [main] INFO  [] - elasticsearch cluster nodes: my-es.example.com:443
2021-03-29 08:00:27,497 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8026 [main] ERROR [] - null
org.apache.skywalking.oap.server.library.module.ModuleStartException: null
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:207) ~[storage-elasticsearch-plugin-8.4.0.jar:8.4.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.4.0.jar:8.4.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:62) ~[library-module-8.4.0.jar:8.4.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.4.0.jar:8.4.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.4.0.jar:8.4.0]
Caused by: java.io.IOException
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:275) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:146) ~[library-client-8.4.0.jar:8.4.0]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:202) ~[storage-elasticsearch-plugin-8.4.0.jar:8.4.0]
        ... 4 more
Caused by: java.net.ConnectException
        at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
```
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Is there a way to config proxy info?**

**Comment by wu-sheng** [comment]
Not SkyWalking's responsibility
