### ISSUE TITLE
[Python] agent  Question 

### ISSUE THREAD

**Issue by SmileLee123** [apache/skywalking#6713]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
```
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 195, in consume_request_iterator
    request = next(request_iterator)
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\skywalking\agent\protocol\grpc.py", line 114, in generator
    ) for span in segment.spans],
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\skywalking\agent\protocol\grpc.py", line 114, in <listcomp>
    ) for span in segment.spans],
AttributeError: 'int' object has no attribute 'value'
2021-04-08 17:21:56.299 | DEBUG    | ycyj_zhongtai.libs.redis_jsonrpc.base_worker:_process_pool:214 - segment_id is dcff4bc0984b11ebb36a4eebbd934baf
Traceback (most recent call last):
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\skywalking\agent\protocol\grpc.py", line 122, in report
    self.traces_reporter.report(generator())
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\skywalking\client\grpc.py", line 58, in report
    self.report_stub.collect(generator)
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 1011, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\peake\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
```

my code:
```
     config.init(collector='xxxxx:11800', service='Test')
    config.logging_level = 'DEBUG'
    config.pymongo_trace_parameters = True
    agent.start()
```

plugins:

```
_brpop = Redis.brpop
def _sw_brpop(this:Redis, keys, timeout=0):
    context = get_context()
    channel, request = _brpop(this, keys, timeout)
    request_data = json.loads(request)
    with context.new_entry_span(op='RedisBusPull') as span:
        carrier = Carrier()
        logger.debug(request_data['params']['sw8'])
        for item in carrier:
            if item.key in request_data['params']['sw8']:
                item.val = request_data['params']['sw8'][item.key]
        span.extract(carrier)
        span.tag(Tag(key=tags.DbType, val="Redis"))
    return channel, request
```

request_data['params']['sw8']  is superstratum service transmission  data
- Which version of SkyWalking, OS, and JRE?
    - SkyWalking is 8.3.0 
    - Os CentOS Linux release 7.6.1810
   
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
This seems to be your plugin’s issue, but you only pasted part of the codes, I don’t know how the sender produces the context thus it’s impossible for us to diagnose what is wrong. 

If the plugin is for open source Python library, consider contributing the complete plugin so that we can review it, if it’s private, sorry we can’t help for private codes.

**Comment by SmileLee123** [comment]
This problem solved！

**Comment by SmileLee123** [comment]
![image](https://user-images.githubusercontent.com/33251469/114146388-1bebcd00-994a-11eb-8b75-30e33bcec4e0.png)
tornado get request，Why are there two pipe connections？

**Comment by SmileLee123** [comment]
@kezhenxu94

**Comment by SmileLee123** [comment]
![image](https://user-images.githubusercontent.com/33251469/114151393-a551ce00-994f-11eb-9adb-cecfa96f6189.png)
I annotation that this decorator result is normal
