### ISSUE TITLE
Why does the client have so many (64) resident threads in Runnable state?

### ISSUE THREAD

**Issue by vincent2518** [apache/skywalking#6797]
Why does the client have so many (64) resident threads in Runnable state?

thread dumps are like below：
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)           at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)           at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)           at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)           - locked [0x00000006c0c4cf40] (a            org.apache.skywalking.apm.dependencies.io.netty.channel.nio.SelectedSelectionKeySet)           - locked [0x00000006c0c4d030] (a            java.util.Collections$UnmodifiableSet)           - locked [0x00000006c0c4cf58] (a sun.nio.ch.EPollSelectorImpl)           at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)           at            org.apache.skywalking.apm.dependencies.io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)           at            org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)           at            org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)           at            org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)           at            org.apache.skywalking.apm.dependencies.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)           at            org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)           at java.lang.Thread.run(Thread.java:745)
--

**Comment by wu-sheng** [comment]
As log shows, this is related to netty/gRPC.

**Comment by vincent2518** [comment]
emm，can i modify the number of these threads？



---Original---
From: "吴晟 Wu ***@***.***&gt;
Date: Wed, Apr 21, 2021 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/skywalking] Why does the client have so many (64) resident threads in Runnable state? (#6797)




 
As log shows, this is related to netty/gRPC.

**Comment by wu-sheng** [comment]
I think we don't set it manually.
