### ISSUE TITLE
Pulsar Plugin IllegalStateException 

### ISSUE THREAD

**Issue by Shoothzj** [apache/skywalking#6800]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug
Pulsar Plugin IllegalStateException, guess if it's broken ?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SW: 8.5.0
OS: docker on OSX
JRE: server openjdk11, client jdk8

- What happened?
dependency
```
plugins {
    id 'java'
}

group 'com.github.shoothzj'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client-admin
    implementation group: 'org.apache.pulsar', name: 'pulsar-client-admin', version: '2.4.0'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: this.rootProject.springBootVersion

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

test {
    useJUnitPlatform()
}
```
ProducerDemo
```
package com.github.shoothzj.demo.skywalking.pulsar.producer;

import com.github.shoothzj.demo.skywalking.pulsar.PulsarConst;
import com.github.shoothzj.javatool.util.CommonUtil;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.apache.pulsar.client.api.MessageId;
import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.ProducerBuilder;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.Schema;
import org.apache.pulsar.client.api.TypedMessageBuilder;

import java.util.HashMap;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

/**
 * @author hezhangjian
 */
@Slf4j
public class ProducerMain {

    @SneakyThrows
    public static void main(String[] args) {
        PulsarClient pulsarClient = PulsarClient.builder()
                .serviceUrl("http://127.0.0.1:8080")
                .build();
        ProducerBuilder<String> producerBuilder = pulsarClient.newProducer(Schema.STRING).enableBatching(false);
        Producer<String> producer = producerBuilder.topic(PulsarConst.TOPIC).create();
        while (true) {
            final TypedMessageBuilder<String> stringTypedMessageBuilder = producer.newMessage();
            final HashMap<String, String> map = new HashMap<>();
            map.put("1", "2");
            final TypedMessageBuilder<String> value = stringTypedMessageBuilder.key("1").value("2").properties(map);
            final CompletableFuture<MessageId> completableFuture = value.sendAsync();
            completableFuture.exceptionally(new Function<Throwable, MessageId>() {
                @Override
                public MessageId apply(Throwable throwable) {
                    log.error("send error ", throwable.getCause());
                    return null;
                }
            });
            CommonUtil.sleep(TimeUnit.SECONDS, 1);
        }
    }

}

```
```
ERROR 2021-04-21 22:18:06:900 main SkyWalkingAgent : Enhance class org.apache.pulsar.client.impl.ProducerImpl error. 
java.lang.IllegalStateException: Cannot resolve type description for org.apache.pulsar.client.impl.ProducerImpl$auxiliary$fwSQ0ErE
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8383)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7870)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:505)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:221)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10371)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10307)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10073)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10692)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10639)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10230)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:61)
	at com.github.shoothzj.demo.skywalking.pulsar.producer.ProducerMain.main(ProducerMain.java:32)
```

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Ping @codelipenghui

**Comment by codelipenghui** [comment]
Ok, I will find a chance to take a look at the details. @Shoothzj BTW, Have you tried some newer version Pulsar clients, and if you are not the first time to use the Pulsar Plugin, is there a version that can work previously? I want to get more information to locate the problem.

**Comment by Shoothzj** [comment]
@wu-sheng I am pretty sure it's ide problem.
Sorry for my unclear description, my SkyWalking server is run on docker. But my client is run on Idea.
yesterday I use idea2021 + gradle6.1.1 
![image](https://user-images.githubusercontent.com/12933197/115674679-7ccec880-a380-11eb-8903-339fc99d7bf7.png)
Today, I use idea2021 + maven, same code, same dependency.
It works. But I don't know how to fix it on gradle, maybe it's similar to  https://github.com/raphw/byte-buddy/issues/373
The log4j class alose enhance error make me doubt about gradle.
```
ERROR 2021-04-22 11:29:26:056 main SkyWalkingAgent : Enhance class org.apache.logging.log4j.core.impl.Log4jLogEvent error. 
java.lang.IllegalStateException: Cannot resolve type description for org.apache.logging.log4j.core.impl.Log4jLogEvent$auxiliary$i9QaBKQl
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8383)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7870)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:505)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:221)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10371)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10307)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10073)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10692)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10639)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10230)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:635)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at com.github.shoothzj.demo.skywalking.pulsar.producer.ProducerMain.<clinit>(ProducerMain.java:22)
```

**Comment by wu-sheng** [comment]
Sorry, your question is out of the project's scope.

**Comment by enoch1024** [comment]
@Shoothzj Did you solve it？Cannot resolve type description for org.apache.logging.log4j.core.impl.Log4jLogEvent

**Comment by Shoothzj** [comment]
Soory, I don't solve it probleam. I change the demo project to maven. Pretty sure it's casued by ide.
