### ISSUE TITLE
KubernetesCoordinator throws NPE when queryRemoteNodes

### ISSUE THREAD

**Issue by whohasthis** [apache/skywalking#6806]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0 for ES 6, running on kubernetes cluster, 
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

Each time the oap server starts, there is this NPE,

2021-04-22 07:33:21,203 - org.apache.skywalking.oap.server.telemetry.api.HealthCheckMetrics -5667 [pool-4-thread-1] ERROR [] - Health check fails
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.cluster.plugin.kubernetes.KubernetesCoordinator.lambda$queryRemoteNodes$2(KubernetesCoordinator.java:80) ~[cluster-kubernetes-plugin-8.4.0.jar:8.4.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4747) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4755) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.apache.skywalking.oap.server.cluster.plugin.kubernetes.KubernetesCoordinator.queryRemoteNodes(KubernetesCoordinator.java:81) [cluster-kubernetes-plugin-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:128) [server-core-8.4.0.jar:8.4.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-22 07:33:21,211 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager -5675 [pool-4-thread-1] ERROR [] - null
org.apache.skywalking.oap.server.core.cluster.ServiceQueryException: null
	at org.apache.skywalking.oap.server.cluster.plugin.kubernetes.KubernetesCoordinator.queryRemoteNodes(KubernetesCoordinator.java:86) ~[cluster-kubernetes-plugin-8.4.0.jar:8.4.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:128) [server-core-8.4.0.jar:8.4.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please search the issue first.
