### ISSUE TITLE
Method not found: skywalking.v3.LogReportService/collect

### ISSUE THREAD

**Issue by CrytisMT** [apache/skywalking#6817]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I compile from source code.When using agent to collect logs,i got an error:
`
ERROR 2021-04-23 17:29:48:274 grpc-default-executor-0 GRPCLogReportServiceClient : Try to send 1 log data to collector, with unexpected exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: skywalking.v3.LogReportService/collect
	at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:533)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
` 
How to fix it?

**Comment by wu-sheng** [comment]
Backend version is too old

**Comment by CrytisMT** [comment]
@wu-sheng I clone the source code from master again and compiled，but it is always the same error when i use the new backed and agent.
I doubt it's a bug.
I used tookit in my project to collect logs：
`
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.6.0-SNAPSHOT</version>
        </dependency>
`

**Comment by wu-sheng** [comment]
From what I saw, it doesn't exist. The official demo is using this codebase.

**Comment by cuimaolin** [comment]
Has the problem been solved? I also encountered the same problem, my agent and server versions are both 8.5
