### ISSUE TITLE
skywalking cli problem

### ISSUE THREAD

**Issue by mlzxdzl** [apache/skywalking#6826]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Can I ask skywalking cli problem here, Because I can not find the issues tag in skywalking cli.
when I use the following command: 
swctl metrics top 5 --name endpoint_sla
It have an error:
FATAL graphql: Exception while fetching data (/result) : For input string: "1_e1BPU1R9L25lbXNpbnZ0L2NyZWF0ZUJvZHk="
And In the oap server log and find the following error :

```shell
2021-04-25 17:02:52,708 - graphql.execution.SimpleDataFetcherExceptionHandler - 23 [qtp425107133-259] WARN  [] - Exception while fetching data (/result) : For input string: "1_e1BPU1R9L25lbXNpbnZ0L2NyZWF0ZUJvZHk="
java.lang.NumberFormatException: For input string: "1_e1BPU1R9L25lbXNpbnZ0L2NyZWF0ZUJvZHk="
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_212]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_212]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceID.analysisId(IDManager.java:59) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.core.query.AggregationQueryService.lambda$sortMetrics$0(AggregationQueryService.java:68) ~[server-core-8.2.0.jar:8.2.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.query.AggregationQueryService.sortMetrics(AggregationQueryService.java:65) ~[server-core-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.sortMetrics(MetricsQuery.java:140) ~[query-graphql-plugin-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricsQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:8.2.0]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) ~[graphql-java-8.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) ~[graphql-java-8.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) ~[graphql-java-8.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:158) ~[graphql-java-8.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:100) ~[graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:558) ~[graphql-java-8.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) ~[graphql-java-8.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) ~[graphql-java-8.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) ~[graphql-java-8.0.jar:?]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:93) ~[query-graphql-plugin-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:83) ~[query-graphql-plugin-8.2.0.jar:8.2.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:59) ~[library-server-8.2.0.jar:8.2.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:107) ~[library-server-8.2.0.jar:8.2.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:112) ~[library-server-8.2.0.jar:8.2.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489) ~[jetty-servlet-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.Server.handle(Server.java:500) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.28.v20200408.jar:9.4.28.v20200408]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by fgksgf** [comment]
@mlzxdzl  Hi, thanks for your report. 

You can try `swctl metrics top 5 --name endpoint_sla --scope endpoint` as a quick solution. 

I will fix this in the next version.
