### ISSUE TITLE
cannot collect tomcat's metrics

### ISSUE THREAD

**Issue by justfbt** [apache/skywalking#6850]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Cannot collect tomcat's metrics
___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking: apache-skywalking-apm-es7-8.4.0
OS: CentOS  7.4 64bit
JRE: 1.8.0_171

- Which company or project?
tomcat

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

error log:

```
ERROR 2021-04-27 11:15:08:611 http-nio2-8080-exec-6 InstMethodsInter : class[class org.elasticsearch.action.TransportActionNodeProxy] before method[execute] intercept failure
java.lang.NullPointerException
        at org.apache.skywalking.apm.plugin.elasticsearch.v5.TransportActionNodeProxyInterceptor.beforeMethod(TransportActionNodeProxyInterceptor.java:51)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java)
        at org.elasticsearch.client.transport.support.TransportProxyClient$1.doWithNode(TransportProxyClient.java:58)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:202)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:272)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
...
```

**Comment by wu-sheng** [comment]
This log is very clear, that, you are facing some plugins incompatible with ElasticSearch 5. Nothing related to the Tomcat.

**Comment by justfbt** [comment]
thanks, and is there any way to compatible with ElasticSearch 2.x ? we cannot upgrade the ElasticSearch version.

**Comment by wu-sheng** [comment]
> thanks, and is there any way to compatible with ElasticSearch 2.x ? we cannot upgrade the ElasticSearch version.

We have a supported list, and 2.x is clearly too old for a community to support. No way is willing to do that. You could write your own plugin, it is not hard. And remove existing ES 6/7 plugins from your agent/plugins. You should be good.

**Comment by justfbt** [comment]
thanks
