### ISSUE TITLE
docker-compose depoly skywalking-oap error

### ISSUE THREAD

**Issue by kenny5he** [apache/skywalking#6904]
when i deploy skywalking from docker-compose, skywalking-ui api localhost:8080/graphql response 500
docker-compose.yml
version: '3.5'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch-sky
    restart: always
    ports:
      - 19280:9200
    environment:
      discovery.type: single-node
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/workspace/docker/skywalking/data-es:/usr/share/elasticsearch/data
  oap:
    image: apache/skywalking-oap-server:8.5.0-es7
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
  ui:
    image: apache/skywalking-ui:8.5.0
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 18088:8080
    environment:
      SW_OAP_ADDRESS: oap:12800

**Comment by wu-sheng** [comment]
Not well formated, no log, no local debug. We can't process this report.

**Comment by kenny5he** [comment]
Skywalking UI Logs: 
Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to oap:12800 [oap/172.22.0.3] failed: Connection refused (Connection refused)
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
	... 129 common frames omitted
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to oap:12800 [oap/172.22.0.3] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

Skywalking-oap logs:
2021-05-06 12:44:58,527 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8746 [main] ERROR [] - 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
java.lang.NoSuchMethodError: 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:152) ~[library-client-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:214) ~[storage-elasticsearch-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.5.0.jar:8.5.0]

**Comment by kenny5he** [comment]
Skywalking UI Logs: 
Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to oap:12800 [oap/172.22.0.3] failed: Connection refused (Connection refused)
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
	... 129 common frames omitted
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to oap:12800 [oap/172.22.0.3] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

Skywalking-oap logs:
2021-05-06 12:44:58,527 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8746 [main] ERROR [] - 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
java.lang.NoSuchMethodError: 'boolean org.elasticsearch.client.RestHighLevelClient.ping(org.apache.http.Header[])'
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:152) ~[library-client-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:214) ~[storage-elasticsearch-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.5.0.jar:8.5.0]
