### ISSUE TITLE
k8s monitoring setup issue with oap

### ISSUE THREAD

**Issue by AmjadHussainSyed** [apache/skywalking#6957]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I have tried to follow the k8s monitoring in skywalking using the following document. Configured what all the document says but still not able to see the k8s monitoring in UI. From the logs I can say the configuration is loaded. Please advice
https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-infrastructure-monitoring/#setup-1

*`Helm:`*
```
helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=8.5.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.5.0 \
  --set elasticsearch.imageTag=7.5.1 --set oap.env.SW_OTEL_RECEIVER=default --set oap.env.SW_OTEL_RECEIVER_ENABLED_OC_RULES="k8s-cluster\,k8s-service\,k8s-node" \
--set elasticsearch.persistence.enabled=true
```

*`OTEL-LOGS:`*
```
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-05-17 07:54:17.942 +0000 UTC
Value: 0.00000^C     -> cluster: xxx-xxx
     -> failure_domain_beta_kubernetes_io_region: xx-xxxx-1
     -> failure_domain_beta_kubernetes_io_zone: xx-xxxxx-1a
     -> id: /kubepods/podab1be6bf-cea6-47d6-9884-4c2ad3c7e557
     -> instanceType: spotInstance
     -> kubernetes_io_arch: amd64
     -> kubernetes_io_hostname: xx-xxx-xx-xx-node-k8s-xx-xxx-v1
     -> kubernetes_io_os: linux
     -> namespace: default
     -> node: ip-xx-xxx-xx-xxx.xx-xxx-1.compute.internal
     -> node_kubernetes_io_instance_type: m5d.4xlarge
     -> pod: xxx-web-xxx-xxx-xxxxxxx-deployment-54544ff5db-g7lg9
     -> state: stopped
     -> topology_kubernetes_io_region: xx-xxxxx-1
     -> topology_kubernetes_io_zone: xx-xxxxx-1a
```

*`Logs:`*
```
skywalking-oap-684d845ff8-hs77w oap 2021-05-17 07:39:59,767 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -642  [main] INFO  [] - Get a provider define belong to receiver-otel module, provider name: default
skywalking-oap-684d845ff8-hs77w oap 2021-05-17 07:39:59,767 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -642  [main] INFO  [] - Provider=default config=enabledHandlers has been set as oc
skywalking-oap-684d845ff8-hs77w oap 2021-05-17 07:39:59,767 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -642  [main] INFO  [] - Provider=default config=enabledOcRules has been set as k8s-cluster,k8s-service,k8s-node
````

*`NOTE:`*
I was getting the following error in oap so i added the clusterrole permissions to read metadata as per the document,  which fix the following error:

```
skywalking-oap-684d845ff8-wmrt6 oap 2021-05-17 07:25:18,940 - io.kubernetes.client.informer.cache.ReflectorRunnable -102569 [controller-reflector-io.kubernetes.client.openapi.models.V1Service-0] ERROR [] - class io.kubernetes.client.openapi.models.V1Service#Reflector loop failed unexpectedly
skywalking-oap-684d845ff8-wmrt6 oap io.kubernetes.client.openapi.ApiException: Forbidden
skywalking-oap-684d845ff8-wmrt6 oap 	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971) ~[client-java-api-10.0.0.jar:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-10.0.0.jar:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:182) ~[client-java-10.0.0.jar:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:74) [client-java-10.0.0.jar:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
skywalking-oap-684d845ff8-wmrt6 oap 	at java.lang.Thread.run(Thread.java:834) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 2021-05-17 07:25:18,988 - io.kubernetes.client.informer.cache.ReflectorRunnable -102213 [controller-reflector-io.kubernetes.client.openapi.models.V1Pod-0] INFO  [] - class io.kubernetes.client.openapi.models.V1Pod#Start listing and watching...
skywalking-oap-684d845ff8-s8cbv oap 2021-05-17 07:25:18,988 - io.kubernetes.client.informer.cache.ReflectorRunnable -102213 [controller-reflector-io.kubernetes.client.openapi.models.V1Service-0] INFO  [] - class io.kubernetes.client.openapi.models.V1Service#Start listing and watching...
skywalking-oap-684d845ff8-s8cbv oap 2021-05-17 07:25:18,989 - io.kubernetes.client.informer.cache.ReflectorRunnable -102214 [controller-reflector-io.kubernetes.client.openapi.models.V1Pod-0] ERROR [] - class io.kubernetes.client.openapi.models.V1Pod#Reflector loop failed unexpectedly
skywalking-oap-684d845ff8-s8cbv oap io.kubernetes.client.openapi.ApiException: Forbidden
skywalking-oap-684d845ff8-s8cbv oap 	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971) ~[client-java-api-10.0.0.jar:?]
skywalking-oap-684d845ff8-s8cbv oap 	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-10.0.0.jar:?]
skywalking-oap-684d845ff8-s8cbv oap 	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:182) ~[client-java-10.0.0.jar:?]
skywalking-oap-684d845ff8-s8cbv oap 	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:74) [client-java-10.0.0.jar:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 	at java.lang.Thread.run(Thread.java:834) [?:?]
skywalking-oap-684d845ff8-s8cbv oap 2021-05-17 07:25:18,989 - io.kubernetes.client.informer.cache.ReflectorRunnable -102214 [controller-reflector-io.kubernetes.client.openapi.models.V1Service-0] ERROR [] - class io.kubernetes.client.openapi.models.V1Service#Reflector loop failed unexpectedly
skywalking-oap-684d845ff8-s8cbv oap io.kubernetes.client.openapi.ApiException: Forbidden
```

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Not able to see k8s monitoring in UI
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Need to able to see k8s monitoring in UI

**Comment by wu-sheng** [comment]
@wankai123 Do you have anything to share?

**Comment by AmjadHussainSyed** [comment]
**update**: I just checked and don't see the indexes created on elasticsearch with K8s*

**Comment by wu-sheng** [comment]
No index seems you don't have init-task running.

**Comment by AmjadHussainSyed** [comment]
ok. how to run it from helm charts?

**Comment by wu-sheng** [comment]
Read this, https://github.com/apache/skywalking/blob/master/.github/workflows/e2e.istio.yaml#L88

**Comment by AmjadHussainSyed** [comment]
while checking i just seen the error in **_skywalking-es-init-jjbwk_**
```2021-05-17 07:40:08,756 - io.kubernetes.client.informer.cache.ReflectorRunnable -9207 [controller-reflector-io.kubernetes.client.openapi.models.V1Service-0] ERROR [] - class io.kubernetes.client.openapi.models.V1Service#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971) ~[client-java-api-10.0.0.jar:?]
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-10.0.0.jar:?]
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:182) ~[client-java-10.0.0.jar:?]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:74) [client-java-10.0.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-05-17 07:40:08,757 - io.kubernetes.client.informer.cache.ReflectorRunnable -9208 [controller-reflector-io.kubernetes.client.openapi.models.V1Pod-0] ERROR [] - class io.kubernetes.client.openapi.models.V1Pod#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleRespo
	```

**Comment by wu-sheng** [comment]
@kezhenxu94 Do you know what could cause this?

**Comment by kezhenxu94** [comment]
The exception should be fixed by https://github.com/apache/skywalking-kubernetes/pull/71 but I feel like it should not affect the indices creation.

Also, to apply the cluster role, you can simply `--set oap.envoy.als.enabled=true` instead of manually apply the role. @wu-sheng now, since the cluster role is not only applied when als is enabled, I'm wondering whether or not we should have another condition (such as `clusterRole.enabled=true`) to apply the cluster role.

**Comment by AmjadHussainSyed** [comment]
thanks for your reply guys. I tried the option which was provided and its not helping @kezhenxu94 still i don't see the k8s in UI. Following is my configuration:

```
helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=8.5.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.5.0 \
  --set elasticsearch.imageTag=7.5.1 --set oap.env.SW_OTEL_RECEIVER=default --set oap.env.SW_OTEL_RECEIVER_ENABLED_OC_RULES="k8s-cluster\,k8s-service\,k8s-node" --set oap.envoy.als.enabled=true \
--set elasticsearch.persistence.enabled=true
```

**Comment by kezhenxu94** [comment]
> **update**: I just checked and don't see the indexes created on elasticsearch with K8s*

do you only mean indices start with `k8s*`? Or not even an index is created? There is no such kind of indices start with `k8s*` I think.

**Comment by AmjadHussainSyed** [comment]
> > **update**: I just checked and don't see the indexes created on elasticsearch with K8s*
> 
> do you only mean indices start with `k8s*`? Or not even an index is created? There is no such kind of indices start with `k8s*` I think.

yes noted.

**Comment by AmjadHussainSyed** [comment]
> thanks for your reply guys. I tried the option which was provided and its not helping @kezhenxu94 still i don't see the k8s in UI. Following is my configuration:
> 
> ```
> helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
>   --set oap.image.tag=8.5.0-es7 \
>   --set oap.storageType=elasticsearch7 \
>   --set ui.image.tag=8.5.0 \
>   --set elasticsearch.imageTag=7.5.1 --set oap.env.SW_OTEL_RECEIVER=default --set oap.env.SW_OTEL_RECEIVER_ENABLED_OC_RULES="k8s-cluster\,k8s-service\,k8s-node" --set oap.envoy.als.enabled=true \
> --set elasticsearch.persistence.enabled=true
> ```
> 
> indices are still not created.

is there anything which i'm missing to get k8s working?

**Comment by wankai123** [comment]
Is there still any error logs？ In OTEL and OAP.

**Comment by AmjadHussainSyed** [comment]
no errors

**Comment by wankai123** [comment]
If there are no data shown on the k8s pannels, I think the OAP may not have received the metrics from the OTEL.
You could check the logs.

**Comment by AmjadHussainSyed** [comment]
i dont think there's an issue with otel exporting metrics. because i tested its exporting metrics. I tested by stopping oap and started back so its able to reconnect and successfully export metrics. Please see the logs for reference. 

**_Note:_** I enabled logs from **DEBUG** to _INFO_ just for clean representation. other wise there's no issue in printing metrics
```
2021-05-17T12:13:46.846Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:13:46.846Z	warn	batchprocessor/batch_processor.go:184	Sender failed	{"kind": "processor", "name": "batch", "error": "MetricsServiceClient: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.158.180:11800: connect: connection refused\""}
2021-05-17T12:13:47.848Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:13:47.848Z	warn	batchprocessor/batch_processor.go:184	Sender failed	{"kind": "processor", "name": "batch", "error": "MetricsServiceClient: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.158.180:11800: connect: connection refused\""}
2021-05-17T12:13:50.654Z	error	exporterhelper/queued_retry.go:243	Exporting failed. Try enabling retry_on_failure config option.	{"kind": "exporter", "name": "opencensus", "error": "MetricsServiceClient: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.158.180:11800: connect: connection refused\""}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:243
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:119
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
	go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:171
go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter.func2
	go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:103
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeMetricsFunc.ConsumeMetrics
	go.opentelemetry.io/collector/consumer/consumerhelper/metrics.go:29
go.opentelemetry.io/collector/consumer/fanoutconsumer.metricsConsumer.ConsumeMetrics
	go.opentelemetry.io/collector/consumer/fanoutconsumer/consumer.go:51
go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).export
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:285
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:183
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:144
2021-05-17T12:13:50.655Z	error	exporterhelper/queued_retry.go:173	Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures.	{"kind": "exporter", "name": "opencensus", "dropped_items": 6559}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
	go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:173
go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter.func2
	go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:103
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeMetricsFunc.ConsumeMetrics
	go.opentelemetry.io/collector/consumer/consumerhelper/metrics.go:29
go.opentelemetry.io/collector/consumer/fanoutconsumer.metricsConsumer.ConsumeMetrics
	go.opentelemetry.io/collector/consumer/fanoutconsumer/consumer.go:51
go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).export
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:285
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:183
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
	go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:144
2021-05-17T12:13:50.655Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 96}
2021-05-17T12:13:50.655Z	warn	batchprocessor/batch_processor.go:184	Sender failed	{"kind": "processor", "name": "batch", "error": "MetricsServiceClient: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.158.180:11800: connect: connection refused\""}
2021-05-17T12:13:53.102Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 175}
2021-05-17T12:13:54.539Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:13:57.980Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:13:59.215Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:14:01.240Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:14:01.864Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
2021-05-17T12:14:02.884Z	INFO	loggingexporter/logging_exporter.go:56	MetricsExporter	{"#metrics": 59}
```

This is how my current UI looks like no **_K8S_** option 
![image](https://user-images.githubusercontent.com/35757291/118487892-3aed3400-b72c-11eb-8f11-470f63434983.png)

**Comment by wankai123** [comment]
It seems UI template doesn't to be loaded.  you should clear the browser's local storage and refresh it.

**Comment by kezhenxu94** [comment]
Well, @AmjadHussainSyed you meant there is no k8s tab on UI at all. Please clear the browser cache (or even open in private tab) to recheck. If that still doesn’t work, check the UI template in ElasticSearch to see whether they are correct.

**Comment by AmjadHussainSyed** [comment]
thank you @kezhenxu94 @wu-sheng @wankai123 . this seems to be a cache issue working when i open in private window.
is this an expected behaviour? for browser cache?

**Comment by kezhenxu94** [comment]
> is this an expected behaviour? for browser cache?

Yes

**Comment by jiangxiaobai** [comment]
> Read this, https://github.com/apache/skywalking/blob/master/.github/workflows/e2e.istio.yaml#L88

this page is not found

**Comment by kezhenxu94** [comment]
> > Read this, https://github.com/apache/skywalking/blob/master/.github/workflows/e2e.istio.yaml#L88
> 
> this page is not found

@jiangxiaobai https://github.com/apache/skywalking/blob/439f843d897d679e1e9886be0d4880491e7166cd/test/e2e-v2/cases/istio/als/e2e.yaml#L50-L70
