### ISSUE TITLE
Agent log file showing error java.lang.NoSuchMethodError: org.springframework.web.bind.annotation.RequestMapping.path()[Ljava/lang/String;

### ISSUE THREAD

**Issue by whohasthis** [apache/skywalking#6960]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 8.4.0 running on K8S 1.12 cluster, JRE 1.8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

In the agent log file, this error keeps showing :

```
ERROR 2021-05-17 08:02:14:928 http-nio-4187-exec-4730 InstMethodsInter : class[class c.i.a.i.w.c.WeatherController] before method[queryWeatherList] intercept failure 
**java.lang.NoSuchMethodError: org.springframework.web.bind.annotation.RequestMapping.path()[Ljava/lang/String;
	at** org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.RequestMappingMethodInterceptor.lambda$getRequestURL$0(RequestMappingMethodInterceptor.java:40)
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.ParsePathUtil.recursiveParseMethodAnnotation(ParsePathUtil.java:33)
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.RequestMappingMethodInterceptor.getRequestURL(RequestMappingMethodInterceptor.java:34)
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.beforeMethod(AbstractMethodInterceptor.java:91)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)

```

along with this error 

```
ERROR 2021-05-17 08:02:14:943 http-nio-4187-exec-4730 InstMethodsInter : class[class c.i.a.i.w.c.WeatherController] after method[queryWeatherList] intercept failure 
**org.apache.skywalking.apm.plugin.spring.mvc.commons.exception.IllegalMethodStackDepthException: Please submit an new issue to Apache Skywalking if this Exception was happened.**
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.afterMethod(AbstractMethodInterceptor.java:169)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
```

Please advise on how to resolve this error

**Comment by wu-sheng** [comment]
I think your Spring version is not supported.

**Comment by whohasthis** [comment]
we are using spring 4.1.4 RELEASE version, in which the  @RequestMapping annotation indeed does not have path() method.

But when I read into the source code of RequestMappingMethodInterceptor, 
https://github.com/apache/skywalking/blob/bf8574b07f01dcff681994e5fec599fe2bb7887b/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-commons/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/commons/interceptor/RequestMappingMethodInterceptor.java#L31-L46

the code should not enter the else-if branch as we have the value defined in the @RequestMapping annotation like this
```
 @RequestMapping(name = "getWeatherHourly", value = "/hourly", method = RequestMethod.GET)
    public Object queryWeatherList(@RequestParam(required = false) String province,
                                   @RequestParam(required = false) String city,
                                   @RequestParam(required = false) String area,
                                   @RequestParam(required = false) String startHour,
                                   @RequestParam(required = false) String endHour)
```

**Comment by wu-sheng** [comment]
Check AbstractMethodInterceptor first, if it doesn't execute, then check the intercept point definition.
