### ISSUE TITLE
java.lang.RuntimeException: got ERROR event and its status: class V1Status

### ISSUE THREAD

**Issue by queenns** [apache/skywalking#6999]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/dynamic-config.md
___
### Bug
- Which version of SkyWalking, OS, and JRE?
oap.images.tag: 8.5.0-es7
oap.images.storageType: elasticsearch7

helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}"
-f ./skywalking/values-my-es.yaml
--set oap.env.SW_CLUSTER=kubernetes
--set oap.env.SW_CLUSTER_K8S_NAMESPACE=sky
--set oap.env.SW_KAFKA_FETCHER=default
--set oap.env.SW_KAFKA_FETCHER_SERVERS=xxx:9092
--set oap.env.SW_KAFKA_FETCHER_PARTITIONS=4
--set oap.env.SW_KAFKA_FETCHER_IS_SHARDING=true
--set oap.env.SW_NAMESPACE=pre
--set oap.env.SW_CONFIGURATION=**k8s-configmap**

- What happened?

**Is it necessary to create a configmap? I haven't created it yet.**

2021-05-24 08:28:48,205 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client -5420695 [pool-13-thread-1] INFO  [] - Synchronous bulk took time: 26878 millis, size: 543
2021-05-24 08:28:50,109 - io.kubernetes.client.informer.cache.ReflectorRunnable -5422599 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-0] ERROR [] - got ERROR event and its status: class V1Status {
    apiVersion: v1
    code: 410
    details: null
    kind: Status
    message: too old resource version: 7183268058 (7183334694)
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: Expired
    status: Failure
}
2021-05-24 08:28:50,109 - io.kubernetes.client.informer.cache.ReflectorRunnable -5422599 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-0] ERROR [] - class io.kubernetes.client.openapi.models.V1ConfigMap#Reflector loop failed unexpectedly
java.lang.RuntimeException: got ERROR event and its status: class V1Status {
    apiVersion: v1
    code: 410
    details: null
    kind: Status
    message: too old resource version: 7183268058 (7183334694)
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: Expired
    status: Failure
}
	at io.kubernetes.client.informer.cache.ReflectorRunnable.watchHandler(ReflectorRunnable.java:172) [client-java-10.0.0.jar:?]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:108) [client-java-10.0.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-05-24 08:28:51,110 - io.kubernetes.client.informer.cache.ReflectorRunnable -5423600 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-0] INFO  [] - class io.kubernetes.client.openapi.models.V1ConfigMap#Start listing and watching...

**Comment by wu-sheng** [comment]
Please search issues before submitting a duplicate issue. https://github.com/apache/skywalking/issues/6955
