### ISSUE TITLE
ClassCastException after #6966

### ISSUE THREAD

**Issue by Simbafa** [apache/skywalking#7008]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
    - Bug

### Bug
- Which version of SkyWalking, OS, and JRE?
    - SkyWalking master version

- What happened?

After #6966, following error occurs:
```
ERROR 2021-05-25 15:16:55:543 http-nio-8080-exec-3 InstMethodsInter : class[class manager.controller.ServiceManagerController] after method[listAuthorizeMenu] intercept failure 
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.StackDepth cannot be cast to org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.StackDepth
        at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.afterMethod(AbstractMethodInterceptor.java:201)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
        at manager.controller.ServiceManagerController.listAuthorizeMenu(ServiceManagerController.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$2oODx7a6(InvocableHandlerMethod.java:133)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$2oODx7a6$accessor$JTkKFCAu(InvocableHandlerMethod.java)
        at org.springframework.web.method.support.InvocableHandlerMethod$auxiliary$FTod0ROe.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
```
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
cc @lujiajing1126

@Simbafa We need a demo code to reproduce the error.

**Comment by Simbafa** [comment]
I used java-agent in Tomcat 8

**Comment by lujiajing1126** [comment]
Pls assign me for this issue.

**Comment by wu-sheng** [comment]
> I used java-agent in Tomcat 8

We tested Tomcat8, this is not a common case. Please provide demo codes.

**Comment by lujiajing1126** [comment]
> I used java-agent in Tomcat 8

It must not be related to Tomcat, but only Spring. Which spring version are you using? 4 or lower I guess?

Are you using with `devtools`?

**Comment by Simbafa** [comment]
devtools is not used.
Our modules are jarslink modules

**Comment by Simbafa** [comment]
Spring 4.3.7

**Comment by lujiajing1126** [comment]
> devtools is not used.
> Our modules are jarslink modules

Can you provide a simplest demo to reproduce this issue? I am not familiar with JarsLink.

**Comment by Simbafa** [comment]
JarsLink module has its own class loader. I guess this is the issue

**Comment by lujiajing1126** [comment]
> JarsLink module has its own class loader. I guess this is the issue

Sure. Similar to devtools.

How about your experiment with Spring5?

**Comment by Simbafa** [comment]
The test is failed with Spring 5.3.6. But it is not caused by Skywalking. Our system has some conflicts with new Spring version. I will try again later

**Comment by wu-sheng** [comment]
No update for 20 days
