### ISSUE TITLE
oap: DefaultController#processLoop get interrupted null java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by AmjadHussainSyed** [apache/skywalking#7010]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I have a running skywalking setup with metrics and data after the eks upgrade since I have to upgrade all the nodes. 
My skywalking oap is comming up and throwing the following error.

Note:  all the other services running on the eks are fine and only this is failing
**helm setup:**
```
helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=8.5.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.5.0 \
  --set elasticsearch.imageTag=7.5.1 --set oap.env.SW_OTEL_RECEIVER=default --set oap.env.SW_OTEL_RECEIVER_ENABLED_OC_RULES="k8s-cluster\,k8s-service\,k8s-node" --set oap.envoy.als.enabled=true \
--set elasticsearch.persistence.enabled=true
```

oap keeps crashing with this error and not coming up both the pods same issue.

```
2021-05-25 10:25:09,515 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -56391 [main] INFO  [] - table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.
2021-05-25 10:25:12,335 - io.kubernetes.client.informer.cache.Controller -59211 [informer-controller-V1Pod] ERROR [] - DefaultController#processLoop get interrupted null
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090) ~[?:?]
	at io.kubernetes.client.informer.cache.DeltaFIFO.pop(DeltaFIFO.java:318) ~[client-java-10.0.0.jar:?]
	at io.kubernetes.client.informer.cache.Controller.processLoop(Controller.java:161) [client-java-10.0.0.jar:?]
	at io.kubernetes.client.informer.cache.Controller.run(Controller.java:130) [client-java-10.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
i have ran the es-init again but still the issue persists.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We haven't run the init container like you used to do

**Comment by AmjadHussainSyed** [comment]
@wu-sheng i tried to fix it since it say its not able find the data. anything leads on how to bring the oap up
right now its down.

**Comment by wu-sheng** [comment]
Check why init container doesn't work. All indecies created by it.

**Comment by AmjadHussainSyed** [comment]
init container ran fine at first setup and oap was up and running fine, after the oap nodes got refreshed and the oap cluster went down its not coming up with showing the error
