### ISSUE TITLE
CompressionType unusable in kafka-reporter-plugin

### ISSUE THREAD

**Issue by myfairys** [apache/skywalking#7061]
### when i use kafka-reporter-plugin,i have some problems about kafka producer config.
when i set config : -Dskywalking.plugin.kafka.producer_config[compression.type]=snappy, the agent is also error, as follow:
```
ERROR 2021-06-03 10:27:16:442 SkywalkingAgent-8-ServiceManagementClientKafkaProducer-0 KafkaServiceManagementServiceClient : unexpected exception. 
org.apache.skywalking.apm.dependencies.org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyNative.maxCompressedLength(I)I
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.CompressionType$3.wrapForOutput(CompressionType.java:83)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.MemoryRecordsBuilder.<init>(MemoryRecordsBuilder.java:134)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.MemoryRecordsBuilder.<init>(MemoryRecordsBuilder.java:170)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:508)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:490)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:438)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.internals.RecordAccumulator.recordsBuilder(RecordAccumulator.java:253)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:229)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:965)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:886)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:774)
	at org.apache.skywalking.apm.agent.core.kafka.KafkaServiceManagementServiceClient.run(KafkaServiceManagementServiceClient.java:110)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyNative.maxCompressedLength(I)I
	at org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyNative.maxCompressedLength(Native Method)
	at org.apache.skywalking.apm.dependencies.org.xerial.snappy.Snappy.maxCompressedLength(Snappy.java:380)
	at org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:99)
	at org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:91)
	at org.apache.skywalking.apm.dependencies.org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:81)
	at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.CompressionType$3.wrapForOutput(CompressionType.java:81)
	... 19 more
```
when i analysis the source code of  'org.xerial.snappy.SnappyNative.maxCompressedLength(I)I' ,i can find some code 
![image](https://user-images.githubusercontent.com/36197452/120578400-52305f00-c458-11eb-8f89-b143e7103b6e.png)
the kafka producer compression type class is fixed，when use maven-shade-plugin to resolve conflict, it's only modify import class,but can not modify these fixed className。

### Bug
I use skywalking 8.1.0, windows,and jdk8

Is this a bug or other？
Do you have any ideas？Please ask me，thanks。

**Comment by wu-sheng** [comment]
I am not sure whether we included `compression` of Kafka. @dmsolr Any idea?

**Comment by wu-sheng** [comment]
We added `org.apache.skywalking.apm.dependencies.` to all Kafka codes for avoiding class conflict.

**Comment by kezhenxu94** [comment]
I think it's because it uses reflection (class name in literal strings), which shade plugin can't cover that case

**Comment by wu-sheng** [comment]
> I think it's because it uses reflection (class name in literal strings), which shade plugin can't cover that case

I can see a lot of same cases in `org.apache.kafka.common.record.CompressionType`. In my mind, only solution is adding a patch plugin in the Kafka reporter for `org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.CompressionType#findConstructor`, and manipulate the input. This is hacking work, but should work.

**Comment by myfairys** [comment]
> > I think it's because it uses reflection (class name in literal strings), which shade plugin can't cover that case
> 
> I can see a lot of same cases in `org.apache.kafka.common.record.CompressionType`. In my mind, only solution is adding a patch plugin in the Kafka reporter for `org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.CompressionType#findConstructor`, and manipulate the input. This is hacking work, but should work.

But How to do that?

**Comment by wu-sheng** [comment]
> > > I think it's because it uses reflection (class name in literal strings), which shade plugin can't cover that case
> > 
> > 
> > I can see a lot of same cases in `org.apache.kafka.common.record.CompressionType`. In my mind, only solution is adding a patch plugin in the Kafka reporter for `org.apache.skywalking.apm.dependencies.org.apache.kafka.common.record.CompressionType#findConstructor`, and manipulate the input. This is hacking work, but should work.
> 
> But How to do that?

What I gave is development work, not a simple setting. This requires you already know SkyWalking plugin mechanism.

**Comment by myfairys** [comment]
> What I gave is development work, not a simple setting. This requires you already know SkyWalking plugin mechanism

But i'm sorry, i'm no idea do that.
