### ISSUE TITLE
load plugin [org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation] failure

### ISSUE THREAD

**Issue by linjm1** [apache/skywalking#7172]
client agent started ,looked log 
ERROR 2021-06-25 16:52:53:469 main PluginBootstrap : load plugin [org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation] failure. 
java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation
	at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.skywalking.apm.agent.core.plugin.PluginBootstrap.loadPlugins(PluginBootstrap.java:66)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

**Comment by wu-sheng** [comment]
This is not how community works.
A exception stack doesn't help.
