### ISSUE TITLE
Cannot send after the producer is closed

### ISSUE THREAD

**Issue by isyj** [apache/skywalking#7198]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

skywalking-agent.jar:8.2.0-SNAPSHOT
kafka-clients-1.1.1.jar!

java.lang.IllegalStateException: Cannot send after the producer is closed.
        at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:198) ~[kafka-clients-1.1.1.jar!/:?]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend$original$xy2AWG1p(KafkaProducer.java:830) ~[kafka-clients-1.1.1.jar!/:?]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend$original$xy2AWG1p$accessor$P4rZkFwo(KafkaProducer.java) ~[kafka-clients-1.1.1.jar!/:?]
        at org.apache.kafka.clients.producer.KafkaProducer$auxiliary$tffsiJH9.call(Unknown Source) ~[kafka-clients-1.1.1.jar!/:?]
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:85) ~[skywalking-agent.jar:8.2.0-SNAPSHOT]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java) ~[kafka-clients-1.1.1.jar!/:?]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar!/:?]
        at com.keep.commons.queue.kafka.producer.ProducerProxy.send(ProducerProxy.java:121) ~[keep-commons-queue-0.7.7.jar!/:?]
        at com.keep.commons.queue.kafka.producer.DefaultKProducer.send(DefaultKProducer.java:84) ~[keep-commons-queue-0.7.7.jar!/:?]
        at com.keep.commons.queue.kafka.producer.DefaultKProducer.send(DefaultKProducer.java:77) ~[keep-commons-queue-0.7.7.jar!/:?]
        at com.keep.social.common.message.KafkaMsgProducer.send(KafkaMsgProducer.java:90) ~[social-common-1.0.59-RELEASE.jar!/:?]
        at com.keep.social.user.core.message.KafkaMessageProducer.sendUserStatisticMsg(KafkaMessageProducer.java:35) [social-user-core-0.0.1-SNAPSHOT.jar!/:?]
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
`8.2.0-SNAPSHOT` is not our release. And we have many releases after that.
