### ISSUE TITLE
Kubernetes java client 11.0.0 causes RuntimeException

### ISSUE THREAD

**Issue by ericjee** [apache/skywalking#7244]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking: 8.6.0

- What happened?
```
2021-07-05 09:21:55,653 - io.kubernetes.client.informer.cache.ReflectorRunnable -343591722 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] ERROR [] - class io.kubernetes.client.openapi.models.V1ConfigMap#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException: Gone
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993) ~[client-java-api-11.0.0.jar:?]
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905) ~[client-java-api-11.0.0.jar:?]
        at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:207) ~[client-java-11.0.0.jar:?]
        at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:77) [client-java-11.0.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Hi, I'm getting this error message repeats forever in oap server after upgraded to 8.6.0, I think it's from k8s Java client 11.0.0, They had a discussion at https://github.com/kubernetes-client/java/issues/1533, Since they fixed it at 11.0.x, How about bumping up the k8s client dependency from the next release?

**Comment by wu-sheng** [comment]
Do they release a new version?

**Comment by wu-sheng** [comment]
We are using 12.0.1, https://github.com/apache/skywalking/blob/master/oap-server-bom/pom.xml#L52. Please check.

**Comment by ericjee** [comment]
> We are using 12.0.1, https://github.com/apache/skywalking/blob/master/oap-server-bom/pom.xml#L52. Please check.

The trace shows the version is from 11.0.0
```
at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993) ~[client-java-api-11.0.0.jar:?]
```

And there is one release note with skywalking 8.6.0
```
Upgrade Kubernetes Java client dependency to 11.0.
```

So I'm a little confused.

**Comment by kezhenxu94** [comment]
12.0 is upgraded in master branch, which is not yet released.
