### ISSUE TITLE
OAP server has many NPE error

### ISSUE THREAD

**Issue by CrytisMT** [apache/skywalking#7257]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The oap server has many NPE errors.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalkng:8.6.0
JRE: java8 
OS:centOS 7.2

- What happened?
The oap server NPE error:
`2021-07-07 17:50:24,242 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsRemoteWorker - 48 [DataCarrier.METRICS_L1_AGGREGATION.BulkConsumePool.9.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.remote.grpc.proto.RemoteData$Builder.addDataStrings(RemoteData.java:887) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.event.Event.serialize(Event.java:192) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.remote.client.GRPCRemoteClient.push(GRPCRemoteClient.java:142) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:84) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsRemoteWorker.in(MetricsRemoteWorker.java:46) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsRemoteWorker.in(MetricsRemoteWorker.java:32) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsAggregateWorker.lambda$onWork$1(MetricsAggregateWorker.java:101) ~[server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_144]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsAggregateWorker.onWork(MetricsAggregateWorker.java:96) [server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsAggregateWorker.access$100(MetricsAggregateWorker.java:44) [server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsAggregateWorker$AggregatorConsumer.consume(MetricsAggregateWorker.java:113) [server-core-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:80) [apm-datacarrier-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:51) [apm-datacarrier-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]`

**Comment by wu-sheng** [comment]
First of all, you are not using the release version, due to `snapshot` suffix. And you report a NPE, which never found by PMC's env. This kind of issue is impossible to resolve.
