### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 59

### ISSUE THREAD

**Issue by java-yun** [apache/skywalking#7265]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
After I upgraded my project from jdk8 to jdk15, and also upgraded skywalking from 6.4.0 to 8.6.0, I found that the latest skywalking does not support jdk15. The skywalking-agent logs will print “java.lang.IllegalArgumentException: Unsupported class file major version 59”。
Below is the detailed log of skywalking:
java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:195)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:176)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:162)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:681)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:667)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:747)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:845)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getInterfaces(TypeDescription.java:8038)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getInterfaces(TypeDescription.java:3636)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:66)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:31)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking 8.6.0     jdk 15
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I have no idea why you are using a NOT widely used JDK release.

> OpenJDK 15 reached General Availability on 15 September 2020

We never down grade the JDK support, you are upgrading the version, that is all.

**Comment by java-yun** [comment]
> I have no idea why you are using a NOT widely used JDK release.
> 
> > OpenJDK 15 reached General Availability on 15 September 2020
> 
> We never down grade the JDK support, you are upgrading the version, that is all.

We chose jdk15 because we want to use some of its new features to improve performance
Features：
339: | Edwards-Curve Digital Signature Algorithm (EdDSA)
360: | Sealed Classes (Preview)
371: | Hidden Classes
372: | Remove the Nashorn JavaScript Engine
373: | Reimplement the Legacy DatagramSocket API
374: | Disable and Deprecate Biased Locking
375: | Pattern Matching for instanceof (Second Preview)
377: | ZGC: A Scalable Low-Latency Garbage Collector
378: | Text Blocks
379: | Shenandoah: A Low-Pause-Time Garbage Collector
381: | Remove the Solaris and SPARC Ports
383: | Foreign-Memory Access API (Second Incubator)
384: | Records (Second Preview)
385: | Deprecate RMI Activation for Removal

**Comment by wu-sheng** [comment]
> > I have no idea why you are using a NOT widely used JDK release.
> > > OpenJDK 15 reached General Availability on 15 September 2020
> > 
> > 
> > We never down grade the JDK support, you are upgrading the version, that is all.
> 
> We chose jdk15 because we want to use some of its new features to improve performance
> Features：
> 339: | Edwards-Curve Digital Signature Algorithm (EdDSA)
> 360: | Sealed Classes (Preview)
> 371: | Hidden Classes
> 372: | Remove the Nashorn JavaScript Engine
> 373: | Reimplement the Legacy DatagramSocket API
> 374: | Disable and Deprecate Biased Locking
> 375: | Pattern Matching for instanceof (Second Preview)
> 377: | ZGC: A Scalable Low-Latency Garbage Collector
> 378: | Text Blocks
> 379: | Shenandoah: A Low-Pause-Time Garbage Collector
> 381: | Remove the Solaris and SPARC Ports
> 383: | Foreign-Memory Access API (Second Incubator)
> 384: | Records (Second Preview)
> 385: | Deprecate RMI Activation for Removal

First of all, we never tested, but we also don't remove supports.

**Comment by java-yun** [comment]
> > > I have no idea why you are using a NOT widely used JDK release.
> > > > OpenJDK 15 reached General Availability on 15 September 2020
> > > 
> > > 
> > > We never down grade the JDK support, you are upgrading the version, that is all.
> > 
> > 
> > We chose jdk15 because we want to use some of its new features to improve performance
> > Features：
> > 339: | Edwards-Curve Digital Signature Algorithm (EdDSA)
> > 360: | Sealed Classes (Preview)
> > 371: | Hidden Classes
> > 372: | Remove the Nashorn JavaScript Engine
> > 373: | Reimplement the Legacy DatagramSocket API
> > 374: | Disable and Deprecate Biased Locking
> > 375: | Pattern Matching for instanceof (Second Preview)
> > 377: | ZGC: A Scalable Low-Latency Garbage Collector
> > 378: | Text Blocks
> > 379: | Shenandoah: A Low-Pause-Time Garbage Collector
> > 381: | Remove the Solaris and SPARC Ports
> > 383: | Foreign-Memory Access API (Second Incubator)
> > 384: | Records (Second Preview)
> > 385: | Deprecate RMI Activation for Removal
> 
> First of all, we never tested, but we also don't remove supports.



> I have no idea why you are using a NOT widely used JDK release.
> 
> > OpenJDK 15 reached General Availability on 15 September 2020
> 
> We never down grade the JDK support, you are upgrading the version, that is all.



> > > I have no idea why you are using a NOT widely used JDK release.
> > > > OpenJDK 15 reached General Availability on 15 September 2020
> > > 
> > > 
> > > We never down grade the JDK support, you are upgrading the version, that is all.
> > 
> > 
> > We chose jdk15 because we want to use some of its new features to improve performance
> > Features：
> > 339: | Edwards-Curve Digital Signature Algorithm (EdDSA)
> > 360: | Sealed Classes (Preview)
> > 371: | Hidden Classes
> > 372: | Remove the Nashorn JavaScript Engine
> > 373: | Reimplement the Legacy DatagramSocket API
> > 374: | Disable and Deprecate Biased Locking
> > 375: | Pattern Matching for instanceof (Second Preview)
> > 377: | ZGC: A Scalable Low-Latency Garbage Collector
> > 378: | Text Blocks
> > 379: | Shenandoah: A Low-Pause-Time Garbage Collector
> > 381: | Remove the Solaris and SPARC Ports
> > 383: | Foreign-Memory Access API (Second Incubator)
> > 384: | Records (Second Preview)
> > 385: | Deprecate RMI Activation for Removal
> 
> First of all, we never tested, but we also don't remove supports.

I'm very sorry, because I only upgraded the agent version to 8.6.0 before, and did not upgrade the oap version at the same time, so the above problem will occur, and it has been solved now.
