### ISSUE TITLE
Apache Skywalking Java agent not able to address -dhttp.noproxyhost settings and always trying to connect using http proxy.

### ISSUE THREAD

**Issue by RohanGupta1985** [apache/skywalking#7268]
Please answer these questions before submitting your issue.
Requirement
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
Question
___
### Question
- What do you want to know?
Does Java agent can read -dhhtp.noproxyhost settings from environment variable and can connect to controller with in domain without http proxy
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5
- Which company or project?
Travelport

- What happened?

Java agent is trying to connect to controller machine Servername.domainname, but agent is always trying through proxy server defined in Dhttps.proxyHost environment variable, it is not addressing the -dhttp.noproxyhost system property, we have defined all intranet domain in -dhttp.noproxyhost variables and ideally Skywalking java agent should not use proxy server to connect to make connection to controller machines which are in intranet domain defined in -dhttp.noproxyhost system property.

If possible, provide a way to reproduce the error. e.g. demo application, component version.
yes
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by RohanGupta1985** [comment]
these are the error logs captured while starting the agent .
INFO 2021-07-07 16:30:31:573 main PluginBootstrap : no plugin files (skywalking-plugin.def) found, continue to start application.
ERROR 2021-07-07 16:30:33:725 grpc-default-executor-1 EventReportServiceClient : Failed to report starting event.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:533)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.skywalking.apm.dependencies.io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, atlproxy.tvlport.com/172.31.17.171:8080 => 10.12.120.150:12800, status: 403 Tunnel or SSL Forbidden
        at org.apache.skywalking.apm.dependencies.io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200)
        at org.apache.skywalking.apm.dependencies.io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at org.apache.skywalking.apm.dependencies.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at org.apache.skywalking.apm.dependencies.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at org.apache.skywalking.apm.dependencies.io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at org.apache.skywalking.apm.dependencies.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more

**Comment by wu-sheng** [comment]
I think this question is related to Netty or gRPC project. SkyWalking doesn't touch anything about HTTP proxy settings.

**Comment by wu-sheng** [comment]
I do some research, it seems this is a gRPC java client-related thing. You could reference from here, https://github.com/grpc/grpc-java/issues/7043.

I can't see a setting called `http.noproxyhost`. If this is a proxy, I would recommend you to use a proxy server to have a better capability to bypass and forward traffic.
