### ISSUE TITLE
Does SW Full Support InfluxDB as backend storage if collect logs?

### ISSUE THREAD

**Issue by StayTherapy** [apache/skywalking#7300]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Many tour use ES as backend storage, but I want try to use InfluxDB. When all things running up, `topology`,`trace`, `dashboard` is fine , but **Log** can not collect.

- What happened?
When POST log to OAP, and flush `Log` of SW-UI, `Java NPE ` happend:
```
sw-ui     | 2021-07-14 16:57:54.609  WARN 1 --- [nio-8080-exec-4] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/log] in DispatcherServlet with name 'dispatcherServlet'
sw-oap    | 2021-07-14 16:57:54,936 - graphql.execution.SimpleDataFetcherExceptionHandler -450977 [qtp1744273262-28] WARN  [] - Exception while fetching data (/queryLogs) : null
sw-oap    | java.lang.NullPointerException: null
sw-oap    | 	at org.apache.skywalking.oap.server.storage.plugin.influxdb.query.LogQuery.queryLogs(LogQuery.java:149) ~[storage-influxdb-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.server.core.query.LogQueryService.queryLogs(LogQueryService.java:83) ~[server-core-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.resolver.LogQuery.queryLogs(LogQuery.java:65) ~[query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.resolver.LogQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:8.6.0]
sw-oap    | 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
sw-oap    | 	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:88) [query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:78) [query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:38) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:38) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:46) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.Server.handle(Server.java:516) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at java.lang.Thread.run(Thread.java:834) [?:?]
sw-oap    | 2021-07-14 17:01:47,149 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer -683190 [pool-8-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
sw-ui     | 2021-07-14 17:01:54.831  WARN 1 --- [nio-8080-exec-3] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/log] in DispatcherServlet with name 'dispatcherServlet'
sw-oap    | 2021-07-14 17:01:55,205 - graphql.execution.SimpleDataFetcherExceptionHandler -691246 [qtp1744273262-51] WARN  [] - Exception while fetching data (/queryLogs) : null
sw-oap    | java.lang.NullPointerException: null
sw-oap    | 	at org.apache.skywalking.oap.server.storage.plugin.influxdb.query.LogQuery.queryLogs(LogQuery.java:149) ~[storage-influxdb-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.server.core.query.LogQueryService.queryLogs(LogQueryService.java:83) ~[server-core-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.resolver.LogQuery.queryLogs(LogQuery.java:65) ~[query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.resolver.LogQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:8.6.0]
sw-oap    | 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
sw-oap    | 	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
sw-oap    | 	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:88) [query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:78) [query-graphql-plugin-8.6.0.jar:8.6.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:38) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:38) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
sw-oap    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:46) [library-server-8.6.0.jar:8.6.0]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) [jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.Server.handle(Server.java:516) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
sw-oap    | 	at java.lang.Thread.run(Thread.java:834) [?:?]
sw-oap    | 2021-07-14 17:06:46,808 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer -982849 [pool-8-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
sw-oap    | 2021-07-14 17:11:46,475 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer -1282516 [pool-8-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
sw-oap    | 2021-07-14 17:16:46,138 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer -1582179 [pool-8-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
```

**Comment by StayTherapy** [comment]
That's on me 😭

`log-analyzer` is import, I change the `lalFiles` different from `default`, maybe `default` is the best.

```
log-analyzer:
  selector: ${SW_LOG_ANALYZER:default}
  default:
    lalFiles: ${SW_LOG_LAL_FILES:default}
    #lalFiles: ${SW_LOG_LAL_FILES:demo}
    malFiles: ${SW_LOG_MAL_FILES:""
```
