### ISSUE TITLE
500 Server Error for HTTP GET "/graphql"

### ISSUE THREAD

**Issue by easayliu** [apache/skywalking#7416]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
- I have get 500 at UI log.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
- 8.7.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Use Helm deploy this,  get the 500 error in the website.
and the log is like. If i change the UI image to 8.6.0，it work.
```
2021-08-06 06:16:35.394 ERROR 1 --- [or-http-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [a20a4287-1]  500 Server Error for HTTP GET "/graphql"
java.net.UnknownHostException: failed to resolve 'http:' after 2 queries
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/graphql" [ExceptionHandlingWebHandler]
Stack trace:
		at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
		at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966)
		at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
		at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:938)
		at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:63)
		at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
		at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
		at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
		at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:201)
		at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:193)
		at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1264)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:616)
		at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:651)
		at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56)
		at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:490)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wu-sheng** [comment]
Your network setup issue. I think.

**Comment by easayliu** [comment]
i have a try.
```
curl localhost:8080/graphql
```
it looks same error 
![image](https://user-images.githubusercontent.com/54569917/128465772-edf516c4-4a24-4dd9-bf3a-a9f2c77eecfb.png)
error log is same. 
i dont think this is network program

**Comment by kezhenxu94** [comment]
@easayliu if you are using 8.7.0, please make sure to update your UI docker image **again** because of https://github.com/apache/skywalking/issues/7401

**Comment by kezhenxu94** [comment]
@easayliu Also, the following error log might be a clue that you configure the OAP address incorrectly

```
java.net.UnknownHostException: failed to resolve 'http:' after 2 queries
```

**Comment by easayliu** [comment]
@kezhenxu94  I checkout the image . the entrypoint is true 
and also add 
```
http://
```
It works . we should change ui-deployment.yaml.
it works like this code
```        env:
        - name: SW_OAP_ADDRESS
          value: http://{{ template "skywalking.oap.fullname" . }}:{{ .Values.oap.ports.rest }}
```
And THANKS
![image](https://user-images.githubusercontent.com/54569917/128471115-14ecd20a-0f68-4e03-b9f0-feda133ece4e.png)

**Comment by kezhenxu94** [comment]
@easayliu our latest codes are what you showed, so maybe you were using an older version of helm 

https://github.com/apache/skywalking-kubernetes/blob/f17232c608c51a760035fb5183e47555426a5fdf/chart/skywalking/templates/ui-deployment.yaml#L74

**Comment by tristan-tsl** [comment]
maybe we should update the dockerhub image's README file to `docker run --name oap-ui --restart always -d -e SW_OAP_ADDRESS=http://oap:12800 apache/skywalking-ui`
