### ISSUE TITLE
While using the SkyWalking monitoring service, an error was reported while calling a third party interface

### ISSUE THREAD

**Issue by YeJiL** [apache/skywalking#7442]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

While using the SkyWalking monitoring service, an error was reported while calling a third party interface

`15:32:24.423 [http-nio-11010-exec-6] ERROR c.e.c.s.h.GlobalExceptionHandler - [handleException,56] - HTTP 502 Error: 
com.dtflys.forest.exceptions.ForestNetworkException: HTTP 502 Error: 
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleError(MethodLifeCycleHandler.java:128)
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSyncWithException(MethodLifeCycleHandler.java:60)
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSync(MethodLifeCycleHandler.java:46)
	at com.dtflys.forest.backend.AbstractBackendResponseHandler.handleSync(AbstractBackendResponseHandler.java:36)
	at com.dtflys.forest.backend.okhttp3.response.OkHttp3ResponseHandler.handleSync(OkHttp3ResponseHandler.java:29)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.retryOrDoError(AbstractOkHttp3Executor.java:280)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.execute(AbstractOkHttp3Executor.java:257)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.execute(AbstractOkHttp3Executor.java:288)
	at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:1687)
	at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:1704)
	at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1175)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

Trying restemplate, OkHTTP, httpClint is the same case
Attempted to disable SkyWalking monitoring, and the interface resumed fetching
The interface returns to normal when these monitoring plug-ins are removed
An attempt was made to filter the endpoint using Trace, and the interface was normal without error
But treating symptoms does not cure the root cause
What is the reason for this?

When I used the same method to call the local interface, everything worked...

**Comment by wu-sheng** [comment]
This is your codes, we can't tell what are you going on. The only thing could say, the plugin isn't compatible with yours.

**Comment by wu-sheng** [comment]
Why header affects your codes? If you don't allow that, SkyWalking tracing is not working.

**Comment by YeJiL** [comment]
Because the interface does header verification.
thank you for your help

> 为什么标题会影响您的代码？如果您不允许这样做，SkyWalking 跟踪将不起作用。

Because the interface does header verification.
thank you for your help

**Comment by YeJiL** [comment]
> OK, then it is your responsibility to change. We have 3 header keys.

When I use the Trace plugin, does it filter only the starting endpoint?

I now have A situation where my microservices are interdialing, and the trace plug-in filters the endpoints that service A needs to filter, but when the link that service B came in is traced to service A, the trace plug-in is invalid

**Comment by wu-sheng** [comment]
I don't know what is special from your describing. A->B->A is very common. We don't limit it.

**Comment by YeJiL** [comment]
> 我不知道你的描述有什么特别之处。A->B->A 很常见。我们不限制它。

Does SkyWalking's Trace plugin filter only starting endpoints? The incoming link of service A is traced to B, but B cannot filter the endpoint

**Comment by wu-sheng** [comment]
> > 我不知道你的描述有什么特别之处。A->B->A 很常见。我们不限制它。
> 
> Does SkyWalking's Trace plugin filter only starting endpoints? The incoming link of service A is traced to B, but B cannot filter the endpoint

We don't limit this.
