### ISSUE TITLE
setting the log storage in mysql : Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by qiuhuanhen** [apache/skywalking#7449]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 将存储日志方式修改为mysql, 在mysql5.5版本中  中 ,即使我把innodb_large_prefix开启 ,仍报了索引过长错误

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking version : 8.5
- Which company or project?
oap
- What happened?
错误：
org.apache.skywalking.oap.server.core.storage.model.ModelInstaller - 55 [main] INFO  [] - table: alarm_record does not exist
2021-08-12 18:14:40,303 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Index column size too large. The maximum column size is 767 bytes.
org.apache.skywalking.oap.server.library.module.ModuleStartException: Index column size too large. The maximum column size is 767 bytes.
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider.start(MySQLStorageProvider.java:181) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.5.0.jar:8.5.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: Index column size too large. The maximum column size is 767 bytes.
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2TableInstaller.createTable(H2TableInstaller.java:91) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:56) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:90) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider.start(MySQLStorageProvider.java:179) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	... 4 more
Caused by: org.apache.skywalking.oap.server.library.client.jdbc.JDBCClientException: Index column size too large. The maximum column size is 767 bytes.
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.execute(JDBCHikariCPClient.java:89) ~[library-client-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2TableInstaller.createTable(H2TableInstaller.java:87) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:56) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:90) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider.start(MySQLStorageProvider.java:179) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	... 4 more
Caused by: java.sql.SQLException: Index column size too large. The maximum column size is 767 bytes.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.execute(JDBCHikariCPClient.java:85) ~[library-client-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2TableInstaller.createTable(H2TableInstaller.java:87) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:56) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:90) ~[server-core-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider.start(MySQLStorageProvider.java:179) ~[storage-jdbc-hikaricp-plugin-8.5.0.jar:8.5.0]
	... 4 more
2021-08-12 18:14:40,308 - com.alibaba.nacos.common.http.HttpClientManager - 108 [Thread-1] WARN  [] - [HttpClientBeanFactory] Start destroying NacosRestTemplate
2021-08-12 18:14:40,308 - com.alibaba.nacos.common.http.HttpClientManager - 116 [Thread-1] WARN  [] - [HttpClientBeanFactory] Destruction of the end

___
### Requirement or improvement
请问能否将oap自动建表语句开放 让用户可以自定义配置呢?

**Comment by wu-sheng** [comment]
We require English on Github discussion.
