### ISSUE TITLE
oap connect es refused when startup

### ISSUE THREAD

**Issue by ravenfu** [apache/skywalking#7465]
- Which version of SkyWalking, OS, and JRE?
elasticsearch:7.14.0
apache/skywalking-oap-server:8.6.0-es7
apache/skywalking-ui:8.6.0
os: mac os catalina 10.15.7
run on docker desktop

- Which company or project?

my local test project

- What happened?

my docker compose file:
```
version: "3"

services:
  es:
    image: elasticsearch:7.14.0
    container_name: sw-es
    # restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=120s&pretty"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 8
    deploy:
     resources:
        limits:
           memory: 1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - monitor

  oap:
    image: apache/skywalking-oap-server:8.6.0-es7
    container_name: sw-oap
    depends_on:
      - es
    links:
      - es
    # restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: es:9200
      TZ: Asia/Shanghai
    networks:
      - monitor

  ui:
    image: apache/skywalking-ui:8.6.0
    container_name: sw-ui
    depends_on:
      - oap
    links:
      - oap
    # restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
    networks:
      - monitor

networks:
  monitor:
    driver: bridge
```

after I ran `docker compose up -d`, oap server cannot not startup, log say:
```
2021-08-16 13:57:22,246 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -9304 [main] INFO  [] - start the provider default in alarm module.
2021-08-16 13:57:22,246 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -9304 [main] INFO  [] - start the provider default in event-analyzer module.
2021-08-16 13:57:22,247 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -9305 [main] INFO  [] - start the provider elasticsearch7 in storage module.
2021-08-16 13:57:22,248 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -9306 [main] INFO  [] - elasticsearch cluster nodes: es:9200
2021-08-16 13:57:22,965 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -10023 [main] ERROR [] - Connection refused
org.apache.skywalking.oap.server.library.module.ModuleStartException: Connection refused
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:228) ~[storage-elasticsearch7-plugin-8.6.0.jar:8.6.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.6.0.jar:8.6.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.6.0.jar:8.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.6.0.jar:8.6.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.6.0.jar:8.6.0]
Caused by: java.net.ConnectException: Connection refused
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:823) ~[elasticsearch-rest-client-7.5.0.jar:7.5.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248) ~[elasticsearch-rest-client-7.5.0.jar:7.5.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-7.5.0.jar:7.5.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1514) ~[elasticsearch-rest-high-level-client-7.5.0.jar:7.5.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1499) ~[elasticsearch-rest-high-level-client-7.5.0.jar:7.5.0]
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:720) ~[elasticsearch-rest-high-level-client-7.5.0.jar:7.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:112) ~[storage-elasticsearch7-plugin-8.6.0.jar:8.6.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:223) ~[storage-elasticsearch7-plugin-8.6.0.jar:8.6.0]
	... 4 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

then I restart oap server, it would be work.
so how to fix it?

**Comment by wu-sheng** [comment]
Health check is commented, why this kind of question should be answered by SkyWalking.

**Comment by ravenfu** [comment]
health does not work, 
the same situation when i open the health check

**Comment by wu-sheng** [comment]
We can't debug on your local env, this should be your local docker compose. You could check how we run e2e through docker compose, https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/storage/docker-compose.es7.10.yml.
But to be honest, I don't know what we can do for an ElasticSearch connectivity issue.

**Comment by pengrobin** [comment]
> health does not work, the same situation when i open the health check

in oap part, uncomment "restart: always" item, maybe first time es not ready to serve
