### ISSUE TITLE
[Bug] Hystrix plugins bug

### ISSUE THREAD

**Issue by wuguanyu** [apache/skywalking#7824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

```
java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of protected abstract java.lang.Object com.netflix.hystrix.HystrixCommand.run() throws java.lang.Exception to public java.lang.String java.lang.Object.toString() or public native int java.lang.Object.hashCode()
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:662)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.resolve(MethodDelegationBinder.java:611)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1098)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1346)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:600)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitEnd(TypeWriter.java:5110)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.utility.visitor.MetadataAwareClassVisitor.visitEnd(MetadataAwareClassVisitor.java:370)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:715)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:394)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:250)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10371)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10307)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10073)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10766)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10704)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
    at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
    at java.lang.ClassLoader.defineClass1(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:458)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:452)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:451)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.lang.ClassLoader.defineClass1(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:458)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:452)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:451)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

### What you expected to happen

no exception

### How to reproduce

When i use the following java code,the exception occcured in bytebuddy 

I extend HystrixCommand class and add new constructor in child class 

```
public abstract class MyselfHystrixCommand extends HystrixCommand {

    private final String myselfHystrixCommandCommandKey;

    /**
     */
    protected RedisHystrixCommand(String myselfHystrixCommandCommandKey) {
        super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("wuguanyu")));
        this.redisCommandKey = redisCommandKey;
    }
}

public class MyselfHystrixCommand2 extends MyselfHystrixCommand {

    protected MyselfHystrixCommand2(String myselfHystrixCommandCommandKey) {
        super(myselfHystrixCommandCommandKey);
    }
    @Override
    protected Object run() throws Exception {
        return null;
    }
}
```

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't support private extension for now, I think.

**Comment by wuguanyu** [comment]
> We don't support private extension for now, I think.

skwalking not support or byte-buddy-not support?

**Comment by wuguanyu** [comment]
> > We don't support private extension for now, I think.
> 
> skywalking not support or byte-buddy-not support?

**Comment by wu-sheng** [comment]
It is about how to use byte buddy API in plugin. Your private codes are not expected by existing plugin codes, so exception shows up.

**Comment by wuguanyu** [comment]
Our company developers extends HystrixCommand by themselves to resolve specially fallback logic
ok I need to see skywalking how to use byte buddy. In above exception stack info, I find some byte buddy source has skywalking prefix flag. just like 
  `  at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:662)`

**Comment by wu-sheng** [comment]
All of them are shaded. Yes.

**Comment by wuguanyu** [comment]
I  wanted debug MethodDelegationBinder in target application,But finally I find could't debug in this line 
![image](https://user-images.githubusercontent.com/24486917/135029632-5b272a96-ab1f-4143-9a9f-0b4fe4dd1dc4.png)

**Comment by wu-sheng** [comment]
Sorry, private debug is out of community's hands.
