### ISSUE TITLE
oapService elasticsearch7 start error Root mapping definition has unsupported parameters 

### ISSUE THREAD

**Issue by 844700118** [apache/skywalking#7960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

**skywalking version: 8.8**
**elasticsearch  version: 7.13**
**What should I do ?**

**[root@k8s-master ~]# ./oapService.sh**

    2021-10-19 19:27:06,438 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_default_]: Root mapping definition has unsupported parameters:  [_all : {enabled=false}]]
    org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_default_]: Root mapping definition has unsupported parameters:  [_all : {enabled=false}]]
	    at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[elasticsearch-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1911) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1888) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1645) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1584) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:145) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.createIndex(ElasticSearch7Client.java:122) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createNormalTable(StorageEsInstaller.java:99) ~[storage-elasticsearch-plugin-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:90) ~[storage-elasticsearch-plugin-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:56) ~[server-core-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:91) ~[server-core-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:226) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.7.0.jar:8.7.0]
	    at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.7.0.jar:8.7.0]
	    Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.168.1.214:9200], URI [/elasticsearch_ui_template?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
    Warnings: [Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.]
    {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_all : {enabled=false}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Root mapping definition has unsupported parameters:  [_all : {enabled=false}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_all : {enabled=false}]"}},"status":400}
		    at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1584) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
		    at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:145) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
		    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.createIndex(ElasticSearch7Client.java:122) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createNormalTable(StorageEsInstaller.java:99) ~[storage-elasticsearch-plugin-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:90) ~[storage-elasticsearch-plugin-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:56) ~[server-core-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:91) ~[server-core-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:226) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.7.0.jar:8.7.0]
		    at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.7.0.jar:8.7.0]
    Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [_all : {enabled=false}]]
	    at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) ~[elasticsearch-7.10.2.jar:7.10.2]
	    at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[elasticsearch-7.10.2.jar:7.10.2]
	    at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437) ~[elasticsearch-7.10.2.jar:7.10.2]
	    at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603) ~[elasticsearch-7.10.2.jar:7.10.2]
	    at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:179) ~[elasticsearch-7.10.2.jar:7.10.2]
	    ... 16 more

### What you expected to happen

Incompatible with ElasticSearch 7

### How to reproduce

 ./bin/oapService.sh

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
>Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.

Read the log first before submitting an issue.
