### ISSUE TITLE
[Bug] org.influxdb.InfluxDBException: java.lang.ClassCastException: org.msgpack.value.impl.ImmutableLongValueImpl

### ISSUE THREAD

**Issue by liangxp** [apache/skywalking#8163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

run startup.sh exception

### What you expected to happen

`
2021-11-21 20:20:26,394 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - java.lang.ClassCastException: org.msgpack.value.impl.ImmutableLongValueImpl cannot be cast to org.msgpack.value.ImmutableMapValue
org.influxdb.InfluxDBException: java.lang.ClassCastException: org.msgpack.value.impl.ImmutableLongValueImpl cannot be cast to org.msgpack.value.ImmutableMapValue
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:191) ~[influxdb-java-2.15.jar:?]
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:806) ~[influxdb-java-2.15.jar:?]
        at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:795) ~[influxdb-java-2.15.jar:?]
        at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:552) ~[influxdb-java-2.15.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.influxdb.InfluxClient.connect(InfluxClient.java:77) ~[storage-influxdb-plugin-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.storage.plugin.influxdb.InfluxStorageProvider.start(InfluxStorageProvider.java:140) ~[storage-influxdb-plugin-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.1.jar:8.8.1]
Caused by: java.lang.ClassCastException: org.msgpack.value.impl.ImmutableLongValueImpl cannot be cast to org.msgpack.value.ImmutableMapValue
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:187) ~[influxdb-java-2.15.jar:?]
        ... 9 more

`

### How to reproduce

storage with InfluxDB
version: v8.8.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which InfluxDB version are you using? We have tested this in every PRs. No error shows up.

https://github.com/apache/skywalking/blob/7b2d91a3d7e8925794573038f971472500f4ddc8/test/e2e-v2/cases/storage/influxdb/docker-compose.yml?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L20

**Comment by wu-sheng** [comment]
No update in 3 weeks.

**Comment by leeyxq** [comment]
me too, version of influxdb 2.1.1
