### ISSUE TITLE
[Feature] java.lang.NoSuchMethodError occurred when I use pulsar plugin with pulsar client v2.8.1

### ISSUE THREAD

**Issue by huailide** [apache/skywalking#8175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I use pulsar plugin with pulsar client v2.8.1 in my application. I've got java.lang.NoSuchMethodError such as below.
The  root cause is in pulsar client v2.8.1, org.apache.pulsar.client.impl.MessageImpl has changed the code.

In pulsar client V2.8.1: org.apache.pulsar.client.impl.MessageImpl
    private final MessageMetadata msgMetadata;
    public static <T> MessageImpl<T> create(MessageMetadata msgMetadata, ByteBuffer payload, Schema<T> schema) {
         //...... other code
    }
In pulsar client other version such as v2.7.1
    private MessageMetadata.Builder msgMetadataBuilder;
    public static <T> MessageImpl<T> create(MessageMetadata.Builder msgMetadataBuilder, ByteBuffer payload, Schema<T> schema) {
      //...... other code
    }

ERROR 2021-11-18 22:46:35:070 XNIO-1 task-16 InstMethodsInter : class[class org.apache.pulsar.client.impl.ProducerImpl] before method[sendAsync] intercept failure 
java.lang.NoSuchMethodError: org.apache.pulsar.client.impl.MessageImpl.getMessageBuilder()Lorg/apache/pulsar/common/api/proto/PulsarApi$MessageMetadata$Builder;
	at org.apache.skywalking.apm.plugin.pulsar.PulsarProducerInterceptor.beforeMethod(PulsarProducerInterceptor.java:75)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:292)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendWithTxnAsync(ProducerImpl.java:363)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendWithTxnAsync(PartitionedProducerImpl.java:191)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:167)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:103)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:82)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:63)
	at com.yumchina.payhub.writedb.producer.WriteDataUtils.writeDB(WriteDataUtils.java:69)
	at com.yumchina.payhub.core.service.impl.BillOrderServiceImpl.saveBillOrderInfo(BillOrderServiceImpl.java:200)
	at com.yumchina.payhub.core.service.impl.BillOrderServiceImpl$$FastClassBySpringCGLIB$$4169bb1a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.yumchina.payhub.core.service.impl.BillOrderServiceImpl$$EnhancerBySpringCGLIB$$940b1e43.saveBillOrderInfo(<generated>)
	at com.yumchina.payhub.core.controller.BillOrderController.saveBillOrderInfo$original$eMC0LdiO(BillOrderController.java:98)
	at com.yumchina.payhub.core.controller.BillOrderController.saveBillOrderInfo$original$eMC0LdiO$accessor$ioTRKrn1(BillOrderController.java)

### Use case

Pulsar plugin can work normally.
It can support pulsar client v2.8.1.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
According to the history, only 2.2 to 2.7 are on the tested list. Check this. https://github.com/apache/skywalking-java/blob/a7a4faabb158ea8322170e3c7cae0210a8c4e7b4/test/plugin/scenarios/pulsar-scenario/support-version.list

@codelipenghui Would you like to take a look here?

**Comment by wallezhang** [comment]
I will take a look, please assign to me.

**Comment by codelipenghui** [comment]
@wallezhang Thanks, please ping me if need help on this part.

**Comment by wallezhang** [comment]
> @wallezhang Thanks, please ping me if need help on this part.

Pulsar client has changed protocol code generator, so `MessageMetadata` class doesn't have `Builder` inner class. I decide to create two new modules, one is called `pulsar-common` that is used for extracting the same logic between v2.7 and v2.8, and another is called `pulsar-2.8.x-plugin` that is used for supporting pulsar client of version 2.8.x. Old `pulsar-plugin` module is only for v2.7. What do you think?

**Comment by wu-sheng** [comment]
Generally, unless they are really common, we don't recommend adding this kind of package.
This is not about technology, just because users may ignore this package should br included, or confuse about when should exclude, which could cause false bug report.

**Comment by wallezhang** [comment]
> Generally, unless they are really common, we don't recommend adding this kind of package.
> This is not about technology, just because users may ignore this package should br included, or confuse about when should exclude, which could cause false bug report.

The only difference between v2.7 and v2.8 is the logic of adding properties on the producer side. On version 2.7.x we can add properties by `MessageMetadata.Builder` class, but the class was removed on version 2.8, so we should use other method to add properties.

**Comment by wu-sheng** [comment]
OK, if this is the only gap, then common module seems making sense.

**Comment by wallezhang** [comment]
> OK, if this is the only gap, then common module seems making sense.

OK, thanks for your advice.

**Comment by huailide** [comment]
> > OK, if this is the only gap, then common module seems making sense.
> 
> OK, thanks for your advice.
Hi there, I'd like to know the planned completion time of pulsar-2.8.x-plugin, therefore I can make a upgrade plan for pulsar client(I rollback to pulsar client 2.7.1 for now).

**Comment by wallezhang** [comment]
> > OK, if this is the only gap, then common module seems making sense.
> 
> OK, thanks for your advice. Hi there, I'd like to know the planned completion time of pulsar-2.8.x-plugin, therefore I can make a upgrade plan for pulsar client(I rollback to pulsar client 2.7.1 for now).

I think this depends on when `skywalking-java` releases version 8.9.0. I will finish it in this week and submit a PR.
