### ISSUE TITLE
[Bug] 8.8.1 execute sh oapService.sh failed to start

### ISSUE THREAD

**Issue by BertOnline** [apache/skywalking#8201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

An error occurs when starting oapService.sh
```text
2021-11-29 14:27:47,577 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in receiver-browser module.
2021-11-29 14:27:47,578 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
2021-11-29 14:27:47,580 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 113 [main] WARN  [] - nameSpace setting is not supported in elasticsearch provider of storage module
2021-11-29 14:27:47,647 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the standalone provider in cluster module.
2021-11-29 14:27:47,648 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the default provider in core module.
2021-11-29 14:27:47,654 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - path not found: openapi-definitions
org.apache.skywalking.oap.server.library.module.ModuleStartException: path not found: openapi-definitions
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:175) ~[server-core-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:96) ~[library-module-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:46) ~[library-module-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.1.jar:8.8.1]
Caused by: java.io.FileNotFoundException: path not found: openapi-definitions
        at org.apache.skywalking.oap.server.library.util.ResourceUtils.getDirectoryFilesRecursive(ResourceUtils.java:84) ~[library-util-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.core.config.group.openapi.EndpointGroupingRuleReader4Openapi.parseFromDir(EndpointGroupingRuleReader4Openapi.java:96) ~[server-core-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.core.config.group.openapi.EndpointGroupingRuleReader4Openapi.<init>(EndpointGroupingRuleReader4Openapi.java:54) ~[server-core-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.core.config.group.openapi.EndpointNameGroupingRule4OpenapiWatcher.<init>(EndpointNameGroupingRule4OpenapiWatcher.java:40) ~[server-core-8.8.1.jar:8.8.1]
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:171) ~[server-core-8.8.1.jar:8.8.1]
        ... 4 more
```

### What you expected to happen

This problem did not occur when I used v8.7.0 for elasticsearch 6. 

### How to reproduce

This error occurs when sh oapservice.sh is executed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It seems you missed the latest config files of latest release.
