### ISSUE TITLE
[Bug] ProfileTaskChannelService.snapshotQueue full then Notify profile task finish to backend fail

### ISSUE THREAD

**Issue by chanjarster** [apache/skywalking#8221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Write a simple spring mvc controller to test SkyWalking profiling, it just sleep for 1 sec and nothing else:

```java
  @GetMapping("/slow")
  public String index() {
    TimeUnit.SECONDS.sleep(1L);
    return "slow/index";
  }
```

Create profile task in SkyWalking UI, and then `curl http://<...>/slow`, and wait, no profile data show.

Looking into agent's log found:

```
ERROR 2021-12-01 15:13:24:484 SkywalkingAgent-4-PROFILING-TASK-0 ProfileThread : Profiling task fail. taskId:1638342771580_ZGVmYXVsdDo6ZGVtbw==.1 
java.lang.IllegalStateException: Queue full
        at java.util.AbstractQueue.add(AbstractQueue.java:98)
        at org.apache.skywalking.apm.agent.core.profile.ProfileTaskChannelService.addProfilingSnapshot(ProfileTaskChannelService.java:182)
        at org.apache.skywalking.apm.agent.core.profile.ProfileThread.profiling(ProfileThread.java:95)
        at org.apache.skywalking.apm.agent.core.profile.ProfileThread.run(ProfileThread.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

ERROR 2021-12-01 15:13:24:485 SkywalkingAgent-4-PROFILING-TASK-0 ProfileTaskChannelService : Notify profile task finish to backend fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at org.apache.skywalking.apm.network.language.profile.v3.ProfileTaskGrpc$ProfileTaskBlockingStub.reportTaskFinish(ProfileTaskGrpc.java:306)
        at org.apache.skywalking.apm.agent.core.profile.ProfileTaskChannelService.notifyProfileTaskFinish(ProfileTaskChannelService.java:199)
        at org.apache.skywalking.apm.agent.core.profile.ProfileTaskExecutionService.stopCurrentProfileTask(ProfileTaskExecutionService.java:153)
        at org.apache.skywalking.apm.agent.core.profile.ProfileThread.run(ProfileThread.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$ThreadlessExecutor.throwIfInterrupted(ClientCalls.java:749)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:725)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
        ... 9 more
```

Meanwhile, OAP server log:

```
Dec 01, 2021 7:13:24 AM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 8731
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:152)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:628)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:253)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I also noticed that in [Config.java][1]:

> public static int SNAPSHOT_TRANSPORT_BUFFER_SIZE = 500; 

But in [agent.config][2] and [doc][3] default value is `50`.

[1]: https://github.com/apache/skywalking-java/blob/c49c9d3f52ed9ca99e758733755553b8cd052d76/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java#L232
[2]: https://github.com/apache/skywalking-java/blob/c49c9d3f52ed9ca99e758733755553b8cd052d76/apm-sniffer/config/agent.config#L160
[3]: https://github.com/apache/skywalking-java/blob/c49c9d3f52ed9ca99e758733755553b8cd052d76/docs/en/setup/service-agent/java-agent/configurations.md#L56

### What you expected to happen

Profile task successfully reported to oap server.

### How to reproduce

Provided.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@mrproliu Could you take a look about this?
Personally, I think currently 50 seems not a big issue, unless OAP server or network performance is low.

**Comment by mrproliu** [comment]
This depends on the Profile Task configuration at the time. It may happen if the number of threads to be monitored is large and the monitoring time is short. 
The Java Agent will retrieve data from this queue every `500` milliseconds and upload it to the OAP. The value of this configuration item can be adjusted higher. The default ‘50’ in the configuration is a bit low because it can only support monitoring one thread and dump it every 10ms.

**Comment by wu-sheng** [comment]
OK then, what is recommended value? We could change to it accordingly.

**Comment by chanjarster** [comment]
@mrproliu thanks. So let me summarize:

* queue size `50` with `10ms` dump interval = max `500ms` window size
* and Java Agent drain the queue every `500ms`

Maybe these 2 values are too close, it's a big chance to meet `Queue full`?

Besides, `ProfileTaskChannelService`  use `BlockingQueue.add`:

```java
    public void addProfilingSnapshot(TracingThreadSnapshot snapshot) {
        snapshotQueue.add(snapshot);
    }
```

According to javadoc:

> Inserts the specified element into this queue if it is possible to do so immediately without violating capacity restrictions, returning true upon success and throwing an IllegalStateException if no space is currently available. When using a capacity-restricted queue, it is generally preferable to use offer.

I think use `BlockingQueue.offer` is more appropriate.

More, because of `Queue full` exception thrown, `ProfileThread` will exited prematurely:

```java
ProfileThread.run() {
  ProfileThread.profiling() {
    while(...) {
      ProfileTaskChannelService.addProfilingSnapshot() {
          Queue full exception throws
      }
    }
  }
}
```

**Comment by mrproliu** [comment]
> Maybe these 2 values are too close, it's a big chance to meet `Queue full`?

Yes, So I think we could increase this value. Your calculations above are also single-threaded, and I recommend monitoring a maximum of nine threads, `9 Thread * 10ms dump interval * 50times per thread` = `4500`. What is calculated here is the maximum possible number of a Java Agent in 500 milliseconds.

> I think use `BlockingQueue.offer` is more appropriate.

Make sense to me. If the queue is full due to network or configuration problems, the data should be discarded instead of monitoring.
