### ISSUE TITLE
[Bug]  Kafka cleint 2.7.1  NullPointerException

### ISSUE THREAD

**Issue by ylywyn** [apache/skywalking#8252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Kafka cleint 2.7.1  error:

ERROR 2021-12-06 16:50:52:132 org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1 InstMethodsInter : class[class org.apache.kafka.clients.consumer.KafkaConsumer] before method[pollForFetches] intercept failure 
java.lang.NullPointerException
        at org.apache.skywalking.apm.plugin.kafka.KafkaConsumerInterceptor.beforeMethod(KafkaConsumerInterceptor.java:52)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1233)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1410)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke$original$v2aR8G5X(KafkaMessageListenerContainer.java:1249)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke$original$v2aR8G5X$accessor$F3laxlBe(KafkaMessageListenerContainer.java)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$auxiliary$MY5S9ikz.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1161)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:829)

### What you expected to happen

Kafka cleint 2.7.1  error:

### How to reproduce

Kafka cleint 2.7.1  error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is how we tested. https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/kafka-scenario

You don't provide anything, we don't have responsibility to follow.

**Comment by wu-sheng** [comment]
You should compare your case with existing test cases, and it is better to find out why NPE happens. 
Our plugins are contributed by hundreds of people globally, we are welcome the patch and enhancement for different cases, but we can't afford to debug for everyone.
