### ISSUE TITLE
[Bug] default h2 database column too short

### ISSUE THREAD

**Issue by kennedy-han** [apache/skywalking#8272]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When start a eureka server with java agent, logs got an error.
log file path:
apache-skywalking-apm-bin/skywalking-oap-server.log

```
org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "ENDPOINT_ID VARCHAR(200)": "'bWljcm8tcmVnaXN0ZXI=.1_b3JnLnNwcmluZ2ZyYW1ld29yay5jbG91ZC5hdXRvY29uZmlndXJlLlJlZnJlc2hBdXRvQ29uZmlndXJhdGlvbiRSZWZyZXNoU2NvcGVC... (203)"; SQL statement:
INSERT INTO segment VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22001-196]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1234) ~[h2-1.4.196.jar:1.4.196]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.executeBatch(BatchSQLExecutor.java:69) ~[storage-jdbc-hikaricp-plugin-8.9.0.jar:8.9.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:62) ~[storage-jdbc-hikaricp-plugin-8.9.0.jar:8.9.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.lambda$flush$0(H2BatchDAO.java:72) ~[storage-jdbc-hikaricp-plugin-8.9.0.jar:8.9.0]
	at java.util.HashMap.forEach(HashMap.java:1288) [?:1.8.0_144]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.flush(H2BatchDAO.java:68) [storage-jdbc-hikaricp-plugin-8.9.0.jar:8.9.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO$H2BatchConsumer.consume(H2BatchDAO.java:107) [storage-jdbc-hikaricp-plugin-8.9.0.jar:8.9.0]
	at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:75) [library-datacarrier-queue-8.9.0.jar:8.9.0]
	at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:53) [library-datacarrier-queue-8.9.0.jar:8.9.0]
```

### What you expected to happen

h2 database column too short

### How to reproduce

Start a eureka server with java agent. Use default h2 database.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This looks like endpoint name is too long. Do you use some specific chars in the URI?

**Comment by wu-sheng** [comment]
Could you decode the endpoint ID?

**Comment by wu-sheng** [comment]
No update in months.
