### ISSUE TITLE
[Bug][LAL] Percentage strategy should be added, `Math.random`(Math.*) is not allowed to be called in LAL script.

### ISSUE THREAD

**Issue by WuChang-GitHub** [apache/skywalking#8572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I  want to  control the logs sampling rate ,so i use LAL to filter my logs.then i read this [document](https://github.com/apache/skywalking/blob/1b8dbd3fb3645e91708adab9579bd78513c697a0/docs/en/concepts-and-designs/lal.md#enforcer) and test according to the case.However,I find my skywalking progress report some errors.
```2022-02-22 18:41:55,766 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 60 [main] ERROR [] - Failed to create LAL listener.
org.apache.skywalking.oap.server.library.module.ModuleStartException: Failed to create LAL listener.
        at org.apache.skywalking.oap.log.analyzer.provider.LogAnalyzerModuleProvider.start(LogAnalyzerModuleProvider.java:64) ~[log-analyzer-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.9.1.jar:8.9.1]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during semantic analysis: Method calls not allowed on [java.lang.Math]

java.lang.SecurityException: Method calls not allowed on [java.lang.Math]
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitMethodCallExpression(SecureASTCustomizer.java:1217)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBinaryExpression(SecureASTCustomizer.java:1263)
        at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:58)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBooleanExpression(SecureASTCustomizer.java:1284)
        at org.codehaus.groovy.ast.expr.BooleanExpression.visit(BooleanExpression.java:40)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitIfElse(SecureASTCustomizer.java:1126)
        at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBlockStatement(SecureASTCustomizer.java:1098)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitClosureExpression(SecureASTCustomizer.java:1291)
        at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:46)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.lambda$visitListOfExpressions$0(GroovyCodeVisitor.java:202)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.visitListOfExpressions(GroovyCodeVisitor.java:202)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitTupleExpression(SecureASTCustomizer.java:1302)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitArgumentlistExpression(SecureASTCustomizer.java:1482)
        at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:73)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitMethodCallExpression(SecureASTCustomizer.java:1224)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitExpressionStatement(SecureASTCustomizer.java:1134)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBlockStatement(SecureASTCustomizer.java:1098)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitClosureExpression(SecureASTCustomizer.java:1291)
        at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:46)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.lambda$visitListOfExpressions$0(GroovyCodeVisitor.java:202)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.visitListOfExpressions(GroovyCodeVisitor.java:202)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitTupleExpression(SecureASTCustomizer.java:1302)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitArgumentlistExpression(SecureASTCustomizer.java:1482)
        at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:73)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitMethodCallExpression(SecureASTCustomizer.java:1224)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitExpressionStatement(SecureASTCustomizer.java:1134)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBlockStatement(SecureASTCustomizer.java:1098)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitClosureExpression(SecureASTCustomizer.java:1291)
        at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:46)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.lambda$visitListOfExpressions$0(GroovyCodeVisitor.java:202)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.codehaus.groovy.ast.GroovyCodeVisitor.visitListOfExpressions(GroovyCodeVisitor.java:202)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitTupleExpression(SecureASTCustomizer.java:1302)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitArgumentlistExpression(SecureASTCustomizer.java:1482)
        at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:73)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitMethodCallExpression(SecureASTCustomizer.java:1224)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitExpressionStatement(SecureASTCustomizer.java:1134)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.visitBlockStatement(SecureASTCustomizer.java:1098)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.control.customizers.SecureASTCustomizer.call(SecureASTCustomizer.java:890)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:570)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:565)
        at org.apache.skywalking.oap.log.analyzer.dsl.DSL.of(DSL.java:84)
        at org.apache.skywalking.oap.log.analyzer.provider.log.listener.LogFilterListener$Factory.<init>(LogFilterListener.java:70)
        at org.apache.skywalking.oap.log.analyzer.provider.LogAnalyzerModuleProvider.start(LogAnalyzerModuleProvider.java:62)
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49)
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60)
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44)
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23)

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.control.ErrorCollector.addException(ErrorCollector.java:143) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:976) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163) ~[groovy-3.0.8.jar:3.0.8]
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyShell.parse(GroovyShell.java:538) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyShell.parse(GroovyShell.java:570) ~[groovy-3.0.8.jar:3.0.8]
        at groovy.lang.GroovyShell.parse(GroovyShell.java:565) ~[groovy-3.0.8.jar:3.0.8]
        at org.apache.skywalking.oap.log.analyzer.dsl.DSL.of(DSL.java:84) ~[log-analyzer-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.log.analyzer.provider.log.listener.LogFilterListener$Factory.<init>(LogFilterListener.java:70) ~[log-analyzer-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.log.analyzer.provider.LogAnalyzerModuleProvider.start(LogAnalyzerModuleProvider.java:62) ~[log-analyzer-8.9.1.jar:8.9.1]
        ... 4 more
```

My code is just like this document,then i use this document's case but progress still report the same problem.
```
filter {
    // ... parser

    sink {
        sampler { // simulate a probabilistic sampler with sampler rate 30% (not accurate though)
            if (Math.abs(Math.random()) > 0.3) {
                enforcer {}
            } else {
                dropper {}
            }
        }
    }
}
```

### What you expected to happen

Please help me check whether it is because of the document or my problem, or whether it is a bug.
It would be best if you could provide a solution.

### How to reproduce

Use this code to create a rule.
```
rules:
  - name: envoy-als
    dsl: |
      filter {
        sink {
          sampler {
                   if(Math.abs(Math.random()) > 0.3) {
                      enforcer{}
                   }else{
                      dropper{}
                  }
          }
        }

      }
```

### Anything else

When i start my skywalking project.This error will happen.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 I noticed 2 issues here.
1. It seems random is not supported. Is this a doc error or code bug?
2. NextRandom should have performance issue AFAIK. Current thread random should be better.
3. With security concern, I think we should set native Util APIs to bridge all supported methods, if (1) is limited to call Java method directly(Not sure).

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I noticed 2 issues here.
> 
> 1. It seems random is not supported. Is this a doc error or code bug?

I'd say this is by design, we never allow users to call arbitrary Java methods in LAL.

> 3. With security concern, I think we should set native Util APIs to bridge all supported methods, if (1) is limited to call Java method directly(Not sure).

For this specific case, I'd rather provide a dedicated sampler (for example called `percentage`), letting users to call `Math.*` methods is easy but in LAL I don't see there are many other applicable cases, and I'm concerned users might overuse them (performance issues).

What do you think @WuChang-GitHub @wu-sheng if we provide a dedicated sampler (`percentage`) and hold for a while to add those bridge methods?

**Comment by wu-sheng** [comment]
> java.lang.SecurityException: Method calls not allowed on [java.lang.Math]

My question is about, should be allowed or not? Because from the error stack, this is not allowed.

**Comment by kezhenxu94** [comment]
> > java.lang.SecurityException: Method calls not allowed on [java.lang.Math]
> 
> My question is about, should be allowed or not? Because from the error stack, this is not allowed.

As I said, this is by design, we never allow users to call arbitrary Java methods in LAL

**Comment by kezhenxu94** [comment]
> > > java.lang.SecurityException: Method calls not allowed on [java.lang.Math]
> > 
> > 
> > My question is about, should be allowed or not? Because from the error stack, this is not allowed.
> 
> As I said, this is by design, we never allow users to call arbitrary Java methods in LAL

Technically we can do that though.

**Comment by wu-sheng** [comment]
> > > java.lang.SecurityException: Method calls not allowed on [java.lang.Math]
> > 
> > 
> > My question is about, should be allowed or not? Because from the error stack, this is not allowed.
> 
> As I said, this is by design, we never allow users to call arbitrary Java methods in LAL

Then I think this is a doc issue, we documented this officially. We should fix this one way or another. https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/lal/#enforcer

We don't need to expose this to the user. `percentage` strategy is reasonable.

**Comment by kezhenxu94** [comment]
> > > > java.lang.SecurityException: Method calls not allowed on [java.lang.Math]
> > > 
> > > 
> > > My question is about, should be allowed or not? Because from the error stack, this is not allowed.
> > 
> > 
> > As I said, this is by design, we never allow users to call arbitrary Java methods in LAL
> 
> Then I think this is a doc issue, we documented this officially. We should fix this one way or another. https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/lal/#enforcer
> 
> We don't need to expose this to the user. `percentage` strategy is reasonable.

OK, I didn't modify this accordingly when enforcing the security of LAL (via compiling the LAL to static byte code), will fix this soon

**Comment by kezhenxu94** [comment]
@WuChang-GitHub this is a documentation error, see 👆, I'll fix this

**Comment by wu-sheng** [comment]
Once this is a document error, let's fix this first. Then provide a way to provide a percentage sampling function without breaking the security.

**Comment by WuChang-GitHub** [comment]
Thank you very much.If i still want to sample logs,are there some way to implement.Or I need to wait until the next version is updated?

**Comment by wu-sheng** [comment]
> Thank you very much.If i still want to sample logs,are there some way to implement.Or I need to wait until the next version is updated?

Right now, you only have `rpm` option. https://skywalking.apache.org/docs/main/v8.9.1/en/concepts-and-designs/lal/#sampler.

**Comment by WuChang-GitHub** [comment]
I see. Thank you very much for your patience. Now I'm going to use ```rpm``` option.
