### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yiwenzhang666999** [apache/skywalking#8625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

I am using skywalking in the springcloud project. The database I use is ignige. When I call the interface, I get an error: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement

### What you expected to happen

ERROR ,, http-nio-8086-exec-8 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is javax.cache.CacheException: class org.apache.ignite.IgniteCheckedException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement] with root cause
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement
	at org.apache.ignite.internal.processors.query.h2.sql.GridSqlQueryParser.extractCommand(GridSqlQueryParser.java:601)
	at org.apache.ignite.internal.processors.query.h2.sql.GridSqlQueryParser.preparedWithRemaining(GridSqlQueryParser.java:585)
	at org.apache.ignite.internal.processors.query.h2.QueryParser.parseH2(QueryParser.java:376)
	at org.apache.ignite.internal.processors.query.h2.QueryParser.parse0(QueryParser.java:234)
	at org.apache.ignite.internal.processors.query.h2.QueryParser.parse(QueryParser.java:147)
	at org.apache.ignite.internal.processors.query.h2.IgniteH2Indexing.querySqlFields(IgniteH2Indexing.java:1119)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor$2.applyx(GridQueryProcessor.java:2884)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor$2.applyx(GridQueryProcessor.java:2880)
	at org.apache.ignite.internal.util.lang.IgniteOutClosureX.apply(IgniteOutClosureX.java:36)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.executeQuery(GridQueryProcessor.java:3482)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.lambda$querySqlFields$3(GridQueryProcessor.java:2900)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.executeQuerySafe(GridQueryProcessor.java:2935)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.querySqlFields(GridQueryProcessor.java:2874)
	at org.apache.ignite.internal.processors.query.GridQueryProcessor.querySql(GridQueryProcessor.java:3031)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxyImpl.query(IgniteCacheProxyImpl.java:836)
	at org.apache.ignite.internal.processors.cache.GatewayProtectedCacheProxy.query(GatewayProtectedCacheProxy.java:418)
	at org.apache.ignite.springdata.proxy.IgniteCacheProxyImpl.query(IgniteCacheProxyImpl.java:90)
	at org.apache.ignite.springdata22.repository.query.IgniteRepositoryQuery.execute(IgniteRepositoryQuery.java:346)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy160.findByAccount(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy160.findByAccount(Unknown Source)
	at com.custsp.bp.auth.service.TerminalAccountServiceImpl.login(TerminalAccountServiceImpl.java:36)
	at com.custsp.bp.auth.controller.UserController.login$original$IMJe64zG(UserController.java:24)
	at com.custsp.bp.auth.controller.UserController.login$original$IMJe64zG$accessor$mQXXat3o(UserController.java)
	at com.custsp.bp.auth.controller.UserController$auxiliary$AzGOqgh7.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)

### How to reproduce

When the database used in the springcloud project is changed to ignite, the previous interface call will have this error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please make sure you have a suitable title, rather than a blank BUG. And ignite is not on the supported list.
