### ISSUE TITLE
[Bug] java.lang.InternalError: Memory Pool not found

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/skywalking#8734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

report the error per second

ERROR 2022-03-24 10:51:56:698 SkywalkingAgent-4-JVMService-produce-0 JVMService : JVMService produces metrics failure.
java.lang.InternalError: Memory Pool not found
        at sun.management.MemoryPoolImpl.getUsage0(Native Method)
        at sun.management.MemoryPoolImpl.getUsage(MemoryPoolImpl.java:96)
        at org.apache.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolModule.getMemoryPoolMetricsList(MemoryPoolModule.java:57)
        at org.apache.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolProvider.getMemoryPoolMetricsList(MemoryPoolProvider.java:48)
        at org.apache.skywalking.apm.agent.core.jvm.JVMService.run(JVMService.java:101)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

don't report error

### How to reproduce

version 8.3.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
I found you've also issued a ticket there https://github.com/alibaba/arthas/issues/2120

Does the same solution work this time?

**Comment by wu-sheng** [comment]
We are just accessing through JDK XBean. 
This looks like a JVM internal error. Not sure what we can do.

**Comment by Oliverwqcwrw** [comment]
I solved the problem of increasing memory ago in arthas ,but this The remaining memory is 200M, still report error，I'll try updating a JDK version and observe
