### ISSUE TITLE
kafka-fetcher gson Exception

### ISSUE THREAD

**Issue by younglicode** [apache/skywalking#8740]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I use kafka-fetcher, get a exception
`2022-03-25 11:33:54,858 - org.apache.skywalking.oap.server.analyzer.agent.kafka.provider.handler.LogHandler - 84 [KafkaConsumer-1-thread-2] ERROR [] - com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $.
com.google.protobuf.InvalidProtocolBufferException: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $.
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1343) ~[protobuf-java-util-3.17.3.jar:?]
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:476) ~[protobuf-java-util-3.17.3.jar:?]
	at org.apache.skywalking.oap.server.library.util.ProtoBufJsonUtils.fromJSON(ProtoBufJsonUtils.java:54) ~[library-util-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.analyzer.agent.kafka.provider.handler.JsonLogHandler.parseConsumerRecord(JsonLogHandler.java:53) ~[kafka-fetcher-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.analyzer.agent.kafka.provider.handler.LogHandler.handle(LogHandler.java:80) ~[kafka-fetcher-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.analyzer.agent.kafka.KafkaFetcherHandlerRegister.lambda$run$0(KafkaFetcherHandlerRegister.java:128) ~[kafka-fetcher-plugin-8.9.1.jar:8.9.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]`

### What you expected to happen

gson parse kafka message exception

### How to reproduce

raw message:

`{
    "timestamp":1618161813371,
    "service":"Your_ApplicationName",
    "serviceInstance":"3a5b8da5a5ba40c0b192e91b5c80f1a8@192.168.1.8",
    "traceContext":{
        "traceId":"ddd92f52207c468e9cd03ddd107cd530.69.16181331190470001",
        "spanId":"0",
        "traceSegmentId":"ddd92f52207c468e9cd03ddd107cd530.69.16181331190470000"
    },
    "tags":{
        "data":[
            {
                "key":"level",
                "value":"INFO"
            },
            {
                "key":"logger",
                "value":"com.example.MyLogger"
            }
        ]
    },
    "body":{
        "text":{
            "text":"log message"
        }
    }
}
`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Waiting for your fix. And please submit a pull request with a new UT to verify your new case.

**Comment by wu-sheng** [comment]
@younglicode Any update or you have resolved locally?
