### ISSUE TITLE
[Bug] Java agent cause high CPU usage

### ISSUE THREAD

**Issue by happyycm** [apache/skywalking#8741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Java agent cause high CPU usage for a long time。
Process ”SkywalkingAgent“ Take up to 80% CPU
![image](https://user-images.githubusercontent.com/3304325/160082579-0893c101-45c9-4da5-9727-af0ed3237611.png)

### What you expected to happen

Process ”SkywalkingAgent“ Take up to 80% CPU for a long time.

### How to reproduce

`"SkywalkingAgent-5-JVMService-consume-0" #8 daemon prio=5 os_prio=0 tid=0x00007fd6c47e0800 nid=0x10 runnable [0x00007fd69f278000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c0061bb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Cool-Coding** [comment]
@happyycm  In my opionion, when a thread parks, it won't occupy cpu. Can you provide more detailed information and tell us how to reproduce this?

**Comment by wu-sheng** [comment]
Diagnosis is not community's responsibility.  You need to do research first. Moving to the discussion.
