### ISSUE TITLE
[Bug]  9.0.0 版本运行报java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/skywalking#8870]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

java.lang.NullPointerException: null
 at org.apache.skywalking.oap.server.core.management.ui.template.UITemplateInitializer.verifyNameConflict(UITemplateInitializer.java:106) ~[server-core-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.core.management.ui.template.UITemplateInitializer.initTemplate(UITemplateInitializer.java:91) ~[server-core-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.core.management.ui.template.UITemplateInitializer.initAll(UITemplateInitializer.java:74) ~[server-core-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:384) ~[server-core-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:52) ~[library-module-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:61) ~[library-module-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-9.0.0.jar:9.0.0]
 at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-9.0.0.jar:9.0.0]

### What you expected to happen

修复bug 或提供下最新版镜像

### How to reproduce

8.9.1 版本正常 镜像版本升级到 9.0.0 运行报错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Use English on GitHub, and this is duplicated with https://github.com/apache/skywalking/issues/8864

**Comment by wu-sheng** [comment]
Clean your templates of ES. Your env is not clean. And check upgrate doc.

**Comment by wu-sheng** [comment]
All GitHub discussion must be in English. This is going to be locked.
