### ISSUE TITLE
[Feature] Can add field in table 'segment'?

### ISSUE THREAD

**Issue by danzi516** [apache/skywalking#8912]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I'm using Mysql database

### Use case

I'm using Mysql database, I want to add a new field to the segment table, parse the data_binary so that I can query it.
The field data_binary is useful to me
Now when I add a field, the log prompts

org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [DataCarrier.H2_ASYNCHRONOUS_BATCH_PERSISTENT.Consumer.0.Thread] ERROR [] - Column count doesn't match value count at row 1
java.sql.BatchUpdateException: Column count doesn't match value count at row 1
	at sun.reflect.GeneratedConstructorAccessor400.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_281]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1641) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.executeBatch(BatchSQLExecutor.java:69) ~[storage-jdbc-hikaricp-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.BatchSQLExecutor.invoke(BatchSQLExecutor.java:62) ~[storage-jdbc-hikaricp-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.lambda$flush$0(H2BatchDAO.java:72) ~[storage-jdbc-hikaricp-plugin-8.9.1.jar:8.9.1]
	at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_281]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.flush(H2BatchDAO.java:68) [storage-jdbc-hikaricp-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO$H2BatchConsumer.consume(H2BatchDAO.java:107) [storage-jdbc-hikaricp-plugin-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:75) [library-datacarrier-queue-8.9.1.jar:8.9.1]
	at org.apache.skywalking.oap.server.library.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:53) [library-datacarrier-queue-8.9.1.jar:8.9.1]
Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1602) ~[mysql-connector-java-5.1.48.jar:5.1.48]

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you change something, it is your own responsibility, not community.
