### ISSUE TITLE
Python: Error installing packages with latest version of Python agent

### ISSUE THREAD

**Issue by tom-pytel** [apache/skywalking#9146]
```
$ pip install -r requirements.txt

...

Collecting mysqlclient==2.1.0
  Using cached mysqlclient-2.1.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rnv1f4jm/mysqlclient_48b8558df20a401997c7d351a009a80e/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-rnv1f4jm/mysqlclient_48b8558df20a401997c7d351a009a80e/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-rnv1f4jm/mysqlclient_48b8558df20a401997c7d351a009a80e/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by Superskyyy** [comment]
I just tried and didn't meet the same problem on a Windows machine. From the PyPI site, I think there are extra system-level dependencies before it can be properly installed. 

```
Linux
Note that this is a basic step. I can not support complete step for build for all environment. If you can see some error, you should fix it by yourself, or ask for support in some user forum. Don't file a issue on the issue tracker.

You may need to install the Python 3 and MySQL development headers and libraries like so:

$ sudo apt-get install python3-dev default-libmysqlclient-dev build-essential # Debian / Ubuntu
% sudo yum install python3-devel mysql-devel # Red Hat / CentOS
Then you can install mysqlclient via pip now:
```

**Comment by tom-pytel** [comment]
```
sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
```

Thad did it thx. I had python3-dev installed but not the mysql stuff.
