### ISSUE TITLE
Browser Monitoring not see logs in the UI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9210]
### Discussed in https://github.com/apache/skywalking/discussions/9208

<div type='discussions-op-text'>

<sup>Originally posted by **Terni** June 13, 2022</sup>
Hello skywalking team,

I have a small problem with skywalking-ui with "Browser Monitoring" from our web user interface.
I'm trying to add some data via this protocol
https://skywalking.apache.org/docs/main/latest/en/protocols/browser-http-api-protocol/

I have data in the database, but I still don't see any data in skywalking-ui:
![image](https://user-images.githubusercontent.com/1767477/173352073-8d7382e3-a5e6-4ffe-ab50-49a7070621fc.png)

I have this error inside the skywalking-oap server.

Please help me how to solve this. Some ideas?

```
25T13:47:37.221Z(1653486457221659), length=47B, duration=1048µs(1048400ns), totalDuration=10169µs(10169700ns), cause=graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'keywordsOfContent' that is not defined for input object type 'BrowserErrorLogQueryCondition' , headers=[:status=500, content-type=text/plain; charset=utf-8, content-length=47]}

graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'keywordsOfContent' that is not defined for input object type 'BrowserErrorLogQueryCondition' 

at graphql.execution.ValuesResolver.externalValueToInternalValueForObject(ValuesResolver.java:545) ~[graphql-java-17.3.jar:?]

at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:510) ~[graphql-java-17.3.jar:?]

at graphql.execution.ValuesResolver.externalValueToInternalValueForVariables(ValuesResolver.java:412) ~[graphql-java-17.3.jar:?]

at graphql.execution.ValuesResolver.coerceVariableValues(ValuesResolver.java:94) ~[graphql-java-17.3.jar:?]

at graphql.analysis.QueryTraverser.coerceVariables(QueryTraverser.java:64) ~[graphql-java-17.3.jar:?]

at graphql.analysis.QueryTraverser.<init>(QueryTraverser.java:60) ~[graphql-java-17.3.jar:?]

at graphql.analysis.QueryTraverser.<init>(QueryTraverser.java:40) ~[graphql-java-17.3.jar:?]

at graphql.analysis.QueryTraverser$Builder.build(QueryTraverser.java:297) ~[graphql-java-17.3.jar:?]

at graphql.analysis.MaxQueryComplexityInstrumentation.newQueryTraverser(MaxQueryComplexityInstrumentation.java:133) ~[graphql-java-17.3.jar:?]

at graphql.analysis.MaxQueryComplexityInstrumentation.lambda$beginValidation$4(MaxQueryComplexityInstrumentation.java:85) ~[graphql-java-17.3.jar:?]

at graphql.execution.instrumentation.SimpleInstrumentationContext.onCompleted(SimpleInstrumentationContext.java:51) ~[graphql-java-17.3.jar:?]

at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.lambda$onCompleted$1(ChainedInstrumentation.java:238) ~[graphql-java-17.3.jar:?]

at graphql.com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405) ~[graphql-java-17.3.jar:?]

at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.onCompleted(ChainedInstrumentation.java:238) ~[graphql-java-17.3.jar:?]

at graphql.GraphQL.validate(GraphQL.java:600) ~[graphql-java-17.3.jar:?]

at graphql.GraphQL.parseAndValidate(GraphQL.java:562) ~[graphql-java-17.3.jar:?]

at graphql.GraphQL.lambda$parseValidateAndExecute$10(GraphQL.java:531) ~[graphql-java-17.3.jar:?]

at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.getDocument(NoOpPreparsedDocumentProvider.java:15) ~[graphql-java-17.3.jar:?]

at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:533) ~[graphql-java-17.3.jar:?]

at graphql.GraphQL.executeAsync(GraphQL.java:502) ~[graphql-java-17.3.jar:?]

at com.linecorp.armeria.server.graphql.DefaultGraphqlService.execute(DefaultGraphqlService.java:99) ~[armeria-graphql-1.14.1.jar:?]

at com.linecorp.armeria.server.graphql.DefaultGraphqlService.executeGraphql(DefaultGraphqlService.java:91) ~[armeria-graphql-1.14.1.jar:?]

at com.linecorp.armeria.server.graphql.protocol.AbstractGraphqlService.lambda$doPost$0(AbstractGraphqlService.java:116) ~[armeria-graphql-protocol-1.14.1.jar:?]

at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]

at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]

at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]

at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100) ~[armeria-1.14.1.jar:?]

at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]

at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]

at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]

at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]

at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:291) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:283) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:420) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:363) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:319) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:305) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:427) ~[armeria-1.14.1.jar:?]

at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:276) ~[armeria-1.14.1.jar:?]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:216) ~[armeria-1.14.1.jar:?]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.68.Final.jar:4.1.68.Final]

at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[netty-handler-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [netty-handler-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.68.Final.jar:4.1.68.Final]

at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar:4.1.68.Final]

at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar:4.1.68.Final]

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar:4.1.68.Final]

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.68.Final.jar:4.1.68.Final]

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.68.Final.jar:4.1.68.Final]

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]

at java.lang.Thread.run(Unknown Source) [?:?]
```
</div>

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-booster-ui/pull/106

**Comment by Terni** [comment]
Thank you for answer. I saw it was fixed. Which will the release date be version 9.2.0?
