### ISSUE TITLE
[Bug] java agent tranform logs with apm-toolkit-logback-1.x-activation.jar failed

### ISSUE THREAD

**Issue by guangdashao** [apache/skywalking#9244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

java agent 8.10.0 : support , apm-toolkit-logback-1.x-activation.jar 
my application  use logback-core 1.1.11.
when start application , logs transform failed . agent's log is ;

ERROR 2022-06-17 15:18:22:418 http-nio-8083-exec-54 InstMethodsInter : class[class org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender] before method[subAppend] intercept failure 
java.lang.NoSuchMethodError: ch.qos.logback.core.encoder.Encoder.encode(Ljava/lang/Object;)[B
        at org.apache.skywalking.apm.toolkit.activation.log.logback.v1.x.log.GRPCLogAppenderInterceptor.transformLogText(GRPCLogAppenderInterceptor.java:125)
        at org.apache.skywalking.apm.toolkit.activation.log.logback.v1.x.log.GRPCLogAppenderInterceptor.transform(GRPCLogAppenderInterceptor.java:114)
        at org.apache.skywalking.apm.toolkit.activation.log.logback.v1.x.log.GRPCLogAppenderInterceptor.beforeMethod(GRPCLogAppenderInterceptor.java:60)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender.subAppend(GRPCLogClientAppender.java)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)

java agent plugin  apm-toolkit-logback-1.x-activation.jar , class GRPCLogAppenderInterceptor:

  `java
  private String transformLogText(final OutputStreamAppender<ILoggingEvent> appender, final ILoggingEvent event) {
        if (ToolkitConfig.Plugin.Toolkit.Log.TRANSMIT_FORMATTED) {
            return new String(appender.getEncoder().encode(event));
        } else {
            return event.getMessage();
        }
    }

`
but in  logback-core 1.1.11 , interface Encoder doesn't has method encode

`java

//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package ch.qos.logback.core.encoder;

import ch.qos.logback.core.spi.ContextAware;
import ch.qos.logback.core.spi.LifeCycle;
import java.io.IOException;
import java.io.OutputStream;

public interface Encoder<E> extends ContextAware, LifeCycle {
    void init(OutputStream var1) throws IOException;

    void doEncode(E var1) throws IOException;

    void close() throws IOException;
}

`

### What you expected to happen

transform logs success

### How to reproduce

java agent 8.10.0 : support , apm-toolkit-logback-1.x-activation.jar 
my application  use logback-core 1.1.11.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is a typical breaking change in the logback level. There is no bug about this.
Just need to adopt new logback version, if community wants. 
We support newer version, may break old dependency users.
