### ISSUE TITLE
[Bug] Apache Shenyu plugin NPE

### ISSUE THREAD

**Issue by always-web** [apache/skywalking#9250]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

```
ERROR 2022-06-20 12:09:13:558 shenyu-work-threads-11 InstMethodsInter : class[class org.apache.shenyu.plugin.global.GlobalPlugin] before method[execute] intercept failure
java.lang.NullPointerException
        at org.apache.skywalking.apm.plugin.shenyu.v24x.GlobalPluginExecuteMethodInterceptor.beforeMethod(GlobalPluginExecuteMethodInterceptor.java:77)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
        at org.apache.shenyu.plugin.global.GlobalPlugin.execute(GlobalPlugin.java)
        at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain.lambda$execute$0(ShenyuWebHandler.java:134)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Skywalking java agent version is 8.10.0

### What you expected to happen

My Project uses `Apache Shenyu`, so I turned on the `apm-shenyu-2.4.x-plugin-8.10.0.jar` plugin for the Skywalking java agent.At the same time I also enabled the `apm-trace-ignore-plugin-8.10.0.jar` plugin.

Since I use the `apm-trace-ignore-plugin-8.10.0.jar` plugin, the `ContextManager` will create an `IgnoredTracerContext` if the reported path matches the filter criteria. This causes the `apm-shenyu-2.4.x-plugin-8.10.0.jar` plugin to throw a null pointer exception.

```
#org.apache.skywalking.apm.plugin.shenyu.v24x.GlobalPluginExecuteMethodInterceptor.java , line 77
exchange.getAttributes().put(SHENYU_AGENT_TRACE_ID, snapshot.getTraceId().getId());
```

`snapshot.getTraceId()` is `NULL`, and `ContextManager` cannot execute the 'stopSpan' method.

### How to reproduce

Enable both the `apm-shenyu-2.4.x-plugin-8.10.0.jar` and `apm-trace-ignore-plugin-8.10.0.jar` plugins, and set the `\` path to ignore reporting

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please report to Shenyu community. We just hold their contributed plugin, and release with our agent.

**Comment by hutaishi** [comment]
Sorry for not fully considering a type context like IgnoredTracerContext.
A fix PR has now been submitted：https://github.com/apache/skywalking-java/pull/215
