### ISSUE TITLE
[Bug] skywalking 8.9.1 ： create task occur Exception while fetching data (/getProfileTaskList) : Can't split service id into 2 parts

### ISSUE THREAD

**Issue by 52learn** [apache/skywalking#9269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalking ：8.9.1 ,  run with docker-compose.yml
when I  create task for profiling , exception occurred  ： Exception while fetching data (/getProfileTaskList) : Can't split service id into 2 parts
![image](https://user-images.githubusercontent.com/1314055/175428217-6e8ab7ff-b79d-46cd-9b14-412220b79349.png)
![image](https://user-images.githubusercontent.com/1314055/175428302-b46a3445-11d2-4da5-b3c8-28c72c6d8891.png)

the backend service of skywalking-oap output error logs：
![image](https://user-images.githubusercontent.com/1314055/175428585-3d3377e9-9990-4d5d-90f1-1778f0846eaa.png)

### What you expected to happen

**skywalking ui web error tips：**
` Exception while fetching data (/getProfileTaskList) : Can't split service id into 2 parts `

 **the backend service of skywalking-oap output error logs：**

 `2022-06-22 21:45:55,054 org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer 91 [pool-8-thread-1] INFO  [] - Beginning to inspect data boundaries.
2022-06-22 21:49:46,799 graphql.execution.SimpleDataFetcherExceptionHandler 23 [qtp290509937-366] WARN  [] - Exception while fetching data (/getProfileTaskList) : Can't split service id into 2 parts,
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split service id into 2 parts,
        at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceID.analysisId(IDManager.java:55) ~[server-core-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.core.query.ProfileTaskQueryService.getTaskList(ProfileTaskQueryService.java:139) ~[server-core-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.query.graphql.resolver.ProfileQuery.getProfileTaskList(ProfileQuery.java:57) ~[query-graphql-plugin-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.query.graphql.resolver.ProfileQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:8.9.1]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) ~[graphql-java-8.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) ~[graphql-java-8.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) ~[graphql-java-8.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:158) ~[graphql-java-8.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:100) ~[graphql-java-8.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:558) ~[graphql-java-8.0.jar:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) ~[graphql-java-8.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:470) ~[graphql-java-8.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:401) ~[graphql-java-8.0.jar:?]
        at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:88) ~[query-graphql-plugin-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:78) ~[query-graphql-plugin-8.9.1.jar:8.9.1]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:38) ~[library-server-8.9.1.jar:8.9.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:38) ~[library-server-8.9.1.jar:8.9.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.oap.server.library.server.jetty.JettyHandler.service(JettyHandler.java:46) ~[library-server-8.9.1.jar:8.9.1]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at java.lang.Thread.run(Unknown Source) [?:?]
`

### How to reproduce

1. open skywalking ui
2. click profile tab
3. click new task
4. fill the info of task
5. click create task

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
8.x is not maintained by community. And this usually ix caused by you have data generated before 8.0 somehow.

**Comment by 52learn** [comment]
> 8.0 somehow.

so it means that any bug found in skywalking 8.x will not been fixed by community?  could you tell me which version of skywalking for using  much better ?   ths a lot
the previous version is 8.2.0 , I don't use skywalking before 8.0 .

**Comment by 52learn** [comment]
> 8.0 somehow.

so it means that any bug found in skywalking 8.x will not been fixed by community?  could you tell me which version of skywalking for using  much better ?   ths a lot
the previous version is 8.2.0 , I don't use skywalking before 8.0 .

**Comment by wu-sheng** [comment]
> so it means that any bug found in skywalking 8.x will not been fixed by community? could you tell me which version of skywalking for using much better ? ths a lot

All committer team is focusing on the latest version as always. 
At the same time, SkyWalking usually depends on global contributors to fix bugs, not several committers. It has been unrealistic for years, it would only overload the committer team.

> the previous version is 8.2.0 , I don't use skywalking before 8.0 .

Even so, this looks like dirty data. SkyWalking only promises the telemetry data collecting protocol forward compatibility, not all data in the storage. You can't just upgrade from 8.2 to 8.9.1 without setting a new database, unless you have read the source codes, and know all details.

**Comment by wu-sheng** [comment]
Showcase 8.x is still provided, and there is no bug with this feature. 
All change logs could be found in the docs, https://skywalking.apache.org/docs/main/latest/en/changes/changes-9.1.0/

There are 100+ changes for every release, even more. So, don't think skywalking 8.2 to 8.9 is a small upgrade. There are huge differences

**Comment by 52learn** [comment]
> > so it means that any bug found in skywalking 8.x will not been fixed by community? could you tell me which version of skywalking for using much better ? ths a lot
> 
> All committer team is focusing on the latest version as always. At the same time, SkyWalking usually depends on global contributors to fix bugs, not several committers. It has been unrealistic for years, it would only overload the committer team.
> 
> > the previous version is 8.2.0 , I don't use skywalking before 8.0 .
> 
> Even so, this looks like dirty data. SkyWalking only promises the telemetry data collecting protocol forward compatibility, not all data in the storage. You can't just upgrade from 8.2 to 8.9.1 without setting a new database, unless you have read the source codes, and know all details.

I did as you say , first down: 
`docker-compose -f docker-compose-8.9.1.yml  down`
then up :
`docker-compose -f docker-compose-8.9.1.yml up -d`  
and  the function of create task is ok , however another issue is :  profile is not working .  
![image](https://user-images.githubusercontent.com/1314055/175455824-2e108887-3fea-4b2f-840c-8df4be60f146.png)

My profile task as below :  
![image](https://user-images.githubusercontent.com/1314055/175455919-77f99071-3e95-4ab1-b3fc-f52c72fb98cb.png)

Traces as below :
![image](https://user-images.githubusercontent.com/1314055/175456056-0713541f-3501-4905-b63c-286f70c0a20f.png)

So I trigger a request : http://127.0.0.1:8080/slowProfile  between the Profile Monitor startTime and endTime , why **no profile data be collected**  or **not uploaded to skywalking-aop** or **not be stored into ES** or **something else exception**?   tks a lot !!!

**Comment by wu-sheng** [comment]
Again, using the latest version could make things easier.
Your endpoint is wrong. get... is a part of endpoint too.

**Comment by 52learn** [comment]
> Again, using the latest version could make things easier. Your endpoint is wrong. get... is a part of endpoint too.

thanks for your reply !  endpoint change to "GET:/slowProfile", then profile works.   but find one issue of trace that I can not search trace by endpoint name . that is terrible :  
![image](https://user-images.githubusercontent.com/1314055/175472267-4a14814e-a64a-421b-a85e-84471bfc4db2.png)


I plan to change the latest version  :  V9.1.0   , wish to have a good using experience ！

**Comment by 52learn** [comment]
> Again, using the latest version could make things easier. Your endpoint is wrong. get... is a part of endpoint too.

thanks for your reply !  endpoint change to "GET:/slowProfile", then profile works.   but find one issue of trace that I can not search trace by endpoint name . that is terrible :  
![image](https://user-images.githubusercontent.com/1314055/175472267-4a14814e-a64a-421b-a85e-84471bfc4db2.png)


I plan to change the latest version  :  V9.1.0   , wish to have a good using experience ！

**Comment by wu-sheng** [comment]
You should read what is an endpoint, and all docs, rather than keep asking questions.
Open source is not a customer service.
