### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by guan-mian** [apache/skywalking#9286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalk-webapp error when I use startup script startup.bat.

My JDK version is 11.0.3

### What you expected to happen

The contents of skywalking-oap-server.log are as follows 

2022-06-30 11:39:31,163 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 71 [main] ERROR [] - no provider found for module cluster, if you're sure it's not required module and want to remove it, set the selector to -
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: no provider found for module cluster, if you're sure it's not required module and want to remove it, set the selector to -
	at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.selectConfig(ApplicationConfigLoader.java:154) ~[server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.loadConfig(ApplicationConfigLoader.java:62) ~[server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.load(ApplicationConfigLoader.java:51) ~[server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:42) [server-bootstrap-8.5.0.jar:8.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.5.0.jar:8.5.0]

The contents of webapp.log are as follows 

2022-06-30 11:39:32.701  INFO 10412 --- [main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@346d61be: startup date [Thu Jun 30 11:39:32 CST 2022]; root of context hierarchy
2022-06-30 11:39:33.698  INFO 10412 --- [main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2022-06-30 11:39:33.791  INFO 10412 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3b4116e6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-06-30 11:39:34.916  INFO 10412 --- [main] o.a.s.apm.webapp.ApplicationStartUp      : No active profile set, falling back to default profiles: default
2022-06-30 11:39:35.023  INFO 10412 --- [main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@30c93896: startup date [Thu Jun 30 11:39:35 CST 2022]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@346d61be
2022-06-30 11:39:36.543  INFO 10412 --- [main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'counterFactory' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration$ZuulMetricsConfiguration; factoryMethodName=counterFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration$ZuulMetricsConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration$ZuulCounterFactoryConfiguration; factoryMethodName=counterFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration$ZuulCounterFactoryConfiguration.class]]
2022-06-30 11:39:37.030  INFO 10412 --- [main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=5c90c110-a47c-3c99-a38e-b0ff002b7284
2022-06-30 11:39:37.076  INFO 10412 --- [main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2022-06-30 11:39:37.696  INFO 10412 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration' of type [org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration$$EnhancerBySpringCGLIB$$5153ba2a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-06-30 11:39:38.409  INFO 10412 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3b4116e6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-06-30 11:39:39.666  INFO 10412 --- [main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2022-06-30 11:39:39.714  INFO 10412 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-06-30 11:39:39.714  INFO 10412 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.29
2022-06-30 11:39:39.941  INFO 10412 --- [localhost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-06-30 11:39:39.942  INFO 10412 --- [localhost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4919 ms
2022-06-30 11:39:41.146  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2022-06-30 11:39:41.148  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'zuulServlet' to [/zuul/*]
2022-06-30 11:39:41.153  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2022-06-30 11:39:41.154  INFO 10412 --- [localhost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2022-06-30 11:39:41.335  WARN 10412 --- [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2022-06-30 11:39:41.335  INFO 10412 --- [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-06-30 11:39:41.359  INFO 10412 --- [main] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@757194dc
2022-06-30 11:39:42.334  WARN 10412 --- [main] o.s.c.n.a.ArchaiusAutoConfiguration      : No spring.application.name found, defaulting to 'application'
2022-06-30 11:39:42.334  WARN 10412 --- [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2022-06-30 11:39:42.334  INFO 10412 --- [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-06-30 11:39:43.154  INFO 10412 --- [main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@30c93896: startup date [Thu Jun 30 11:39:35 CST 2022]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@346d61be
2022-06-30 11:39:43.507  INFO 10412 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2022-06-30 11:39:43.508  INFO 10412 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/index.html] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/css/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/img/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/js/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.666  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/logo.png] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.705  INFO 10412 --- [main] .m.m.a.ExceptionHandlerExceptionResolver : Detected @ExceptionHandler methods in notFoundHandler
2022-06-30 11:39:43.782  INFO 10412 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2022-06-30 11:39:43.869  INFO 10412 --- [main] oConfiguration$WelcomePageHandlerMapping : Adding welcome page: class path resource [public/index.html]
2022-06-30 11:39:45.028  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/refresh || /manage/refresh.json],methods=[POST]}" onto public java.lang.Object org.springframework.cloud.endpoint.GenericPostableMvcEndpoint.invoke()
2022-06-30 11:39:45.029  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/heapdump || /manage/heapdump.json],methods=[GET],produces=[application/octet-stream]}" onto public void org.springframework.boot.actuate.endpoint.mvc.HeapdumpMvcEndpoint.invoke(boolean,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException,javax.servlet.ServletException
2022-06-30 11:39:45.030  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/beans || /manage/beans.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.035  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/routes || /manage/routes.json],methods=[POST]}" onto public java.lang.Object org.springframework.cloud.netflix.zuul.RoutesMvcEndpoint.reset()
2022-06-30 11:39:45.035  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/routes || /manage/routes.json],methods=[GET],params=[format],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.cloud.netflix.zuul.RoutesMvcEndpoint.invokeRouteDetails(java.lang.String)
2022-06-30 11:39:45.036  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/routes || /manage/routes.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.036  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/hystrix.stream/**]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.cloud.netflix.endpoint.ServletWrappingEndpoint.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception
2022-06-30 11:39:45.037  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/filters || /manage/filters.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.038  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/env],methods=[POST]}" onto public java.lang.Object org.springframework.cloud.context.environment.EnvironmentManagerMvcEndpoint.value(java.util.Map<java.lang.String, java.lang.String>)
2022-06-30 11:39:45.038  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/env/reset],methods=[POST]}" onto public java.util.Map<java.lang.String, java.lang.Object> org.springframework.cloud.context.environment.EnvironmentManagerMvcEndpoint.reset()
2022-06-30 11:39:45.039  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/env/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint.value(java.lang.String)
2022-06-30 11:39:45.039  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/env || /manage/env.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.046  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/trace || /manage/trace.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.048  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/autoconfig || /manage/autoconfig.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.049  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/configprops || /manage/configprops.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.050  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/auditevents || /manage/auditevents.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public org.springframework.http.ResponseEntity<?> org.springframework.boot.actuate.endpoint.mvc.AuditEventsMvcEndpoint.findByPrincipalAndAfterAndType(java.lang.String,java.util.Date,java.lang.String)
2022-06-30 11:39:45.051  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/mappings || /manage/mappings.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.052  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/logfile || /manage/logfile.json],methods=[GET || HEAD]}" onto public void org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint.invoke(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws javax.servlet.ServletException,java.io.IOException
2022-06-30 11:39:45.054  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/loggers/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.LoggersMvcEndpoint.get(java.lang.String)
2022-06-30 11:39:45.054  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/loggers/{name:.*}],methods=[POST],consumes=[application/vnd.spring-boot.actuator.v1+json || application/json],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.LoggersMvcEndpoint.set(java.lang.String,java.util.Map<java.lang.String, java.lang.String>)
2022-06-30 11:39:45.057  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/loggers || /manage/loggers.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.058  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/info || /manage/info.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.059  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/archaius || /manage/archaius.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.060  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/features || /manage/features.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.061  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/dump || /manage/dump.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:45.061  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/health || /manage/health.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(javax.servlet.http.HttpServletRequest,java.security.Principal)
2022-06-30 11:39:45.062  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/metrics/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.MetricsMvcEndpoint.value(java.lang.String)
2022-06-30 11:39:45.063  INFO 10412 --- [main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/manage/metrics || /manage/metrics.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2022-06-30 11:39:46.042  INFO 10412 --- [main] o.s.c.n.zuul.ZuulFilterInitializer       : Starting filter initializer
2022-06-30 11:39:46.192  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2022-06-30 11:39:46.214  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2022-06-30 11:39:46.216  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
2022-06-30 11:39:46.220  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshEndpoint' has been autodetected for JMX exposure
2022-06-30 11:39:46.222  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'routesEndpoint' has been autodetected for JMX exposure
2022-06-30 11:39:46.222  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'routesMvcEndpoint' has been autodetected for JMX exposure
2022-06-30 11:39:46.223  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'filtersEndpoint' has been autodetected for JMX exposure
2022-06-30 11:39:46.224  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
2022-06-30 11:39:46.231  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2022-06-30 11:39:46.255  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'routesEndpoint': registering with JMX server as MBean [org.springframework.cloud.netflix.zuul:name=routesEndpoint,type=RoutesEndpoint]
2022-06-30 11:39:46.263  WARN 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with key 'routesEndpoint' has been registered as an MBean but has no exposed attributes or operations
2022-06-30 11:39:46.265  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'routesMvcEndpoint': registering with JMX server as MBean [org.springframework.cloud.netflix.zuul:name=routesMvcEndpoint,type=RoutesMvcEndpoint]
2022-06-30 11:39:46.301  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'filtersEndpoint': registering with JMX server as MBean [org.springframework.cloud.netflix.zuul:name=filtersEndpoint,type=FiltersEndpoint]
2022-06-30 11:39:46.302  WARN 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with key 'filtersEndpoint' has been registered as an MBean but has no exposed attributes or operations
2022-06-30 11:39:46.307  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2022-06-30 11:39:46.332  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=30c93896,type=ConfigurationPropertiesRebinder]
2022-06-30 11:39:46.347  INFO 10412 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshEndpoint': registering with JMX server as MBean [org.springframework.cloud.endpoint:name=refreshEndpoint,type=RefreshEndpoint]
2022-06-30 11:39:46.387  INFO 10412 --- [main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2022-06-30 11:39:46.463  INFO 10412 --- [main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2022-06-30 11:39:46.469  INFO 10412 --- [main] ration$HystrixMetricsPollerConfiguration : Starting poller
2022-06-30 11:39:46.567  INFO 10412 --- [main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2022-06-30 11:39:46.579  INFO 10412 --- [main] o.a.s.apm.webapp.ApplicationStartUp      : Started ApplicationStartUp in 16.236 seconds (JVM running for 18.179)
2022-06-30 11:41:32.588  INFO 10412 --- [Thread-6] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@30c93896: startup date [Thu Jun 30 11:39:35 CST 2022]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@346d61be
2022-06-30 11:41:32.592  INFO 10412 --- [Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2022-06-30 11:41:32.594  INFO 10412 --- [Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2022-06-30 11:41:32.594  INFO 10412 --- [Thread-6] o.s.c.n.zuul.ZuulFilterInitializer       : Stopping filter initializer
2022-06-30 11:41:32.596  INFO 10412 --- [Thread-6] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2022-06-30 11:41:32.596  INFO 10412 --- [Thread-6] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2022-06-30 11:41:32.613  WARN 10412 --- [Thread-6] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2022-06-30 11:41:32.613  INFO 10412 --- [Thread-6] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.

### How to reproduce

I modified the /config/application.yml file in Windows.

The changes are as follows

cluster:
  selector: ${SW_CLUSTER:mysql}

And modify the corresponding mysql attributes

Then start the startup.bat file

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Please never use such a title, it's not a good practice. Update according to the context, please.
And you are using the wrong value for the config, what is MySQL there for, it's not even a valid option. Please check here https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-cluster.md
