### ISSUE TITLE
[Bug] JVMService-produce high cpu 100%

### ISSUE THREAD

**Issue by wangkang007** [apache/skywalking#9308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

<img width="752" alt="image" src="https://user-images.githubusercontent.com/15212116/177289439-fea9f57b-275a-4175-946f-7b7f9f4c3118.png">

After the service runs for a period of time, SkywalkingAgent-5-JVMService-produce-0 will occupy 100% CPU

"SkywalkingAgent-5-JVMService-produce-0" #9 daemon prio=5 os_prio=0 cpu=199370183.56ms elapsed=606196.06s tid=0x00007feb31359800 nid=0x7c5 runnable [0x00007feae9e99000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000700399d28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

nothing

### How to reproduce

Not all services will happen, only one can be seen。

environment：
jdk: openjdk version "1.8.0_312"
runtime: k8s-container

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We can't do an analysis from a CPU usage, especially you just posts a stack showing queue blocked.
