### ISSUE TITLE
[Bug] `frozen class (cannot edit)` exception is thrown after modifying `oal` and starting

### ISSUE THREAD

**Issue by saber-wang** [apache/skywalking#9318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

```
2022-07-06 17:08:58,407 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 60 [main] ERROR [] - [9.1.0-f1f519c] org.apache.skywalking.oap.server.core.source.oal.rt.metrics.InstanceClrCpuMetrics: frozen class (cannot edit)
java.lang.RuntimeException: org.apache.skywalking.oap.server.core.source.oal.rt.metrics.InstanceClrCpuMetrics: frozen class (cannot edit)
        at javassist.ClassPool.checkNotFrozen(ClassPool.java:587) ~[javassist-3.25.0-GA.jar:?]
        at javassist.ClassPool.makeClass(ClassPool.java:829) ~[javassist-3.25.0-GA.jar:?]
        at org.apache.skywalking.oal.rt.OALRuntime.generateMetricsClass(OALRuntime.java:223) ~[oal-rt-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oal.rt.OALRuntime.generateClassAtRuntime(OALRuntime.java:198) ~[oal-rt-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oal.rt.OALRuntime.start(OALRuntime.java:172) ~[oal-rt-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.core.oal.rt.OALEngineLoaderService.load(OALEngineLoaderService.java:65) ~[server-core-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.receiver.clr.provider.CLRModuleProvider.start(CLRModuleProvider.java:65) ~[skywalking-clr-receiver-plugin-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) ~[library-module-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-9.1.0.jar:9.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-9.1.0.jar:9.1.0]
```

### What you expected to happen

Start and compile `core.oal`

### How to reproduce

Use configmap in k8s and mount it to ` /skywalking/config/oal/core.oal`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't use duplicate variable name in OAL.
