### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by h-mx** [apache/skywalking#9363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The version I installed is 9.1.0.   No error was reported when the agent was started.   The oapServer reported NullPointerExceptionr when the agent was started

### What you expected to happen

2022-07-21 09:59:45,513 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler - 75 [grpcServerPool-1-thread-111] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.source.EndpointRelation.prepare(EndpointRelation.java:101) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.core.analysis.DispatcherManager.forward(DispatcherManager.java:59) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.core.source.SourceReceiverImpl.receive(SourceReceiverImpl.java:36) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.lambda$build$0(EndpointDepFromCrossThreadAnalysisListener.java:130) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.build(EndpointDepFromCrossThreadAnalysisListener.java:124) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.notifyListenerToBuild(TraceAnalyzer.java:75) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.doAnalysis(TraceAnalyzer.java:71) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.SegmentParserServiceImpl.send(SegmentParserServiceImpl.java:40) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:72) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:63) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.46.0.jar:1.46.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### How to reproduce

The version I installed is 9.1.0.   No error was reported when the agent was started.   The oapServer reported NullPointerExceptionr when the agent was started

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicated https://github.com/apache/skywalking/issues/9297#issuecomment-1173057480 and fixed by https://github.com/apache/skywalking/pull/9300

Next time, please make sure you at least have a good issue title.

**Comment by xiaoniankang** [comment]
Hello, could you tell me how to solve this problem

**Comment by wu-sheng** [comment]
Can't you simply read the milestone of PR? https://github.com/apache/skywalking/pull/9300. Why you put comments everywhere.
