### ISSUE TITLE
[Bug] ThreadPoolExecutor can not be enhanced

### ISSUE THREAD

**Issue by tjzheng1002** [apache/skywalking#9425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When i import jdk-threadpool-plugin，ScheduledThreadPoolExecutor, ThreadPoolExecutor can not be enhanced，it happens error：
```
ERROR 2022-08-04 16:27:09:689 main SkyWalkingAgent : index=0, batch=[class java.util.concurrent.ScheduledThreadPoolExecutor, class java.util.concurrent.ThreadPoolExecutor], types=[class java.util.concurrent.ScheduledThreadPoolExecutor, class java.util.concurrent.ThreadPoolExecutor] 
java.lang.IllegalStateException: Error invoking java.lang.instrument.Instrumentation#retransformClasses
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6918)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7189)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:7034)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4870)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:9507)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9428)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SiriusAgent.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6910)
	... 12 more
```

### What you expected to happen

I expecte that ThreadPoolExecutor can be enhanced without any errors.

### How to reproduce

Agent version:8.6.0
JDK Plugin：jdk-threadpool-plugin

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Check the thread pool plugin test, it is tested in the CI.

https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/jdk-threadpool-scenario

**Comment by wu-sheng** [comment]
And this plugin is added in https://github.com/apache/skywalking-java/pull/95 which is 8.10 release. 
I don't know why you said 8.6.0 agent could support this.
