### ISSUE TITLE
[Bug][java-agent] pulsar plugin `ClassCastException`

### ISSUE THREAD

**Issue by HendSame** [apache/skywalking#9464]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

java.lang.ClassCastException: org.apache.pulsar.client.impl.TopicMessageImpl cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance

```
Message listener error in processing message: 48168:21:0
java.lang.ClassCastException: org.apache.pulsar.client.impl.TopicMessageImpl cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
at com.idanchuang.skywalking.agent.plugin.pulsar.common.PulsarConsumerListenerInterceptor.lambda$afterMethod$cf935be7$1(PulsarConsumerListenerInterceptor.java:59)
at org.apache.pulsar.client.impl.ConsumerBase.callMessageListener(ConsumerBase.java:945)
at org.apache.pulsar.client.impl.ConsumerBase.lambda$triggerListener$7(ConsumerBase.java:924)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

Pulsar-plugin working well

### How to reproduce

Using pulasr-plugin on pulsar2.8.x

### Anything else

![image](https://user-images.githubusercontent.com/9264192/184083249-5ec2c6a8-9453-49ae-8181-5d30f7c2a52a.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please report to the Pulsar community if you have used the latest Java agent(8.11). I can see 2.8.1 has been tested when they contributed this plugin, https://github.com/apache/skywalking-java/blob/main/test/plugin/scenarios/pulsar-scenario/support-version.list

We are just hosting the source codes, and they are maintaining how this works.
