### ISSUE TITLE
[Bug] maven+logback 1.2.3+springboot parent 2.3.12.RELEASE +apm-toolkit-logback-1.x 8.12.0==> [tid] is not a valid conversion word

### ISSUE THREAD

**Issue by xl-0909** [apache/skywalking#9654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

follow [document](https://skywalking.apache.org/docs/skywalking-java/v8.12.0/en/setup/service-agent/java-agent/application-toolkit-logback-1.x/)

my maven pom.xml
`<dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-logback-1.x</artifactId>
                <version>8.12.0</version>
            </dependency>`
my logback.xml
`<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [${APP_NAME}] [%tid] [%thread] %-5level %logger{50} \r\n - %msg%n</pattern>
            </layout>
        </encoder>
    </appender>`

### What you expected to happen

when my springboot app start, will print exception stack
`java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.pattern.parser.Compiler@7d2a58f2 - There is no conversion class registered for conversion word [tid]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@7d2a58f2 - [tid] is not a valid conversion word
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:149)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:126)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at com.csi.GatewayApplication.main(Application.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)`

### How to reproduce

Create a new springboot project with a version number of 2.3.12. RELEASE and introduce the `apm-toolkit-logback-1. x `dependency, version number of 8.12.0 ,

### Anything else

I found that `TraceIdPatternLogbackLayout` will run after `PatternLayout`, resulting in no `tid` when parsing `defaultConverterMap`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 I think our showcase is using logback? 

@xl-0909 We can't and wouldn't test plugins for every versions. So, you have to verify why layout would not invoke before.

**Comment by wu-sheng** [comment]
Yes, the test services are using logback, and showcase seems working well. 

https://github.com/apache/skywalking/blob/master/test/e2e-v2/java-test-service/e2e-service-provider/pom.xml#L39

You may check what happens in your case, maybe something different.
