### ISSUE TITLE
[Bug] Report data through v3/logs. But an error occurred while searching

### ISSUE THREAD

**Issue by hellopeath** [apache/skywalking#9658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

version：9.1.0

2022-09-21 08:27:10,601 com.linecorp.armeria.server.logging.LoggingService 186 [armeria-eventloop-epoll-4-8] WARN  [] - [sreqId=4a7bb94b, chanId=63bb71c0, raddr=172.22.0.93:46584, laddr=172.22.0.19:12800][h1c://skywalking-oap-7f65b68969-4xvdf/graphql#POST] Response: {startTime=2022-09-21T08:27:10.600Z(1663748830600515), length=47B, duration=217µs(217674ns), totalDuration=1994µs(1994021ns), cause=graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'serviceInstanceId' that is not defined for input object type 'BrowserErrorLogQueryCondition' , headers=[:status=500, content-type=text/plain; charset=utf-8, content-length=47]}
graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'serviceInstanceId' that is not defined for input object type 'BrowserErrorLogQueryCondition' 
	at graphql.execution.ValuesResolver.externalValueToInternalValueForObject(ValuesResolver.java:545) ~[graphql-java-17.3.jar:?]
	at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:510) ~[graphql-java-17.3.jar:?]
	at graphql.execution.ValuesResolver.externalValueToInternalValueForVariables(ValuesResolver.java:412) ~[graphql-java-17.3.jar:?]
	at graphql.execution.ValuesResolver.coerceVariableValues(ValuesResolver.java:94) ~[graphql-java-17.3.jar:?]
	at graphql.analysis.QueryTraverser.coerceVariables(QueryTraverser.java:64) ~[graphql-java-17.3.jar:?]

### What you expected to happen

data can be found

### How to reproduce

It can be reproduced by passing in data through the rest http interface v3/logs
Part of the data is as follows:

  -H 'sw8: 1-ZDcxNzdhNmItZDcwNC00OGI2LTlhOTQtNTljY2IyZjcxZjAw-M2UwNDUxNjgtYTUzZC00ODBlLWE1ZWUtNzBlY2NmZmExNmJk-0-TTEtYnJvd3Nlci1hcHA=-djEuMC4w-aHR0cDovLzAuMC4wLjA6ODA4OC8jL2hvbWUvc3VibWl0LXJlcXVlc3Q/dGFza19pZD02MzJhYTRiNDYyYjUxNGU0NDRiNjU2ZGM=-MC4wLjAuMDo4MDg4' \
  --data-raw '[{"timestamp":1663740352802,"service":"M2-browser-app","serviceInstance":"222222","layer":"BROWSER","traceContext":{"traceId":"traceid-cne_c-7oSAbToZmsgy5_-","spanId":"0","traceSegmentId":"tracesegmentid-GC6d48moNh8X0YZQ492Jc"},"tags":{"data":[{"key":"level","value":"Info"},{"key":"module","value":"FEP_InputFile"},{"key":"username","value":"1456291335@qq.com"}]},"body":{"text":{"text":"visiting inputfile"}}}]' \
  --compressed \
  --insecure

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I don't know, you could check the change log or try. SkyWalking has over 680 code contributors, no one could tell what fixed what not.
