### ISSUE TITLE
[Bug] skywalking-java can not coexist with other agents.

### ISSUE THREAD

**Issue by SLAMDUNK7** [apache/skywalking#9698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

The following error occurs when I use both another JavaAgent and skywalking-java：
```
ERROR 2022-09-27 15:32:09:546 main SkyWalkingAgent : index=0, batch=[class com.google.common.eventbus.Dispatcher$LegacyAsyncDispatcher], types=[class com.google.common.eventbus.Dispatcher$LegacyAsyncDispatcher] 
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6910)
	... 12 more
```

### What you expected to happen

I expect that "class com.google.common.eventbus.Dispatcher" can be enhanced without any errors. And i expect skywalking-java  can coexist with other agents.

### How to reproduce

Agent version:8.11.0
Plugin：apm-guava-eventbus-plugin
The command is like '-javaagent:xxxx-agent.jar -javaagent:skywalking-agent.jar'.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am afraid we don't guarantee that. Also, as your agent is not open source, we can't know either.

You could try to put the skywalking agent as the first one.
