### ISSUE TITLE
[BanyanDB][Bug] Sync index writing and shard closing

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

Closing a shard might raise below errors related to index writings:

```console
2022-11-13T12:25:57-08:00 | ERROR | ***encounter some errors when generating indices**** error="failed to open normal store: Cannot acquire directory lock on \"/tmp/banyandb-test-3730832528/stream/default/shard-0/seg-20221113/index\".  Another process is using this Badger database. error: resource temporarily unavailable" module:STREAM.INDEX-WRITER
2022-11-13T12:25:57-08:00 | ERROR | ***encounter some errors when generating indices**** error="failed to open normal store: Cannot acquire directory lock on \"/tmp/banyandb-test-3730832528/stream/default/shard-1/seg-20221113/index\".  Another process is using this Badger database. error: resource temporarily unavailable" module:STREAM.INDEX-WRITER
2022-11-13T12:25:57-08:00 | ERROR | ***encounter some errors when generating indices**** error="error persisting segment: open /tmp/banyandb-test-3730832528/stream/default/shard-1/seg-20221113/block-06/inverted/00000000025f.seg: no such file or directory; failed to open normal store: Cannot acquire directory lock on \"/tmp/banyandb-test-3730832528/stream/default/shard-0/seg-20221113/index\".  Another process is using this Badger database. error: resource temporarily unavailable" module:STREAM.INDEX-WRITER
2022-11-13T12:25:58-08:00 | ERROR | ***encounter some errors when generating indices**** error="open /tmp/banyandb-test-3730832528/stream/default/shard-1/seg-20221113/block-06/inverted/000000000261.seg: no such file or directory; failed to open normal store: Cannot acquire directory lock on \"/tmp/banyandb-test-3730832528/stream/default/shard-0/seg-20221113/index\".  Another process is using this Badger database. error: resource temporarily unavailable" module:STREAM.INDEX-WRITER
2022-11-13T12:25:58-08:00 | ERROR | ***encounter some errors when generating indices**** error="open /tmp/banyandb-test-3730832528/stream/default/shard-1/seg-20221113/block-06/inverted/000000000602.seg: no such file or directory" module:STREAM.INDEX-WRITER
2022-11-13T12:25:58-08:00 | ERROR | ***encounter some errors when generating indices**** error="open /tmp/banyandb-test-3730832528/stream/default/shard-1/seg-20221113/block-06/inverted/000000000b03.seg: no such file or directory" module:STREAM.INDEX-WRITER
2022-11-13T12:25:58-08:00 | ERROR | ***encounter some errors when generating indices**** error="error persisting segment: open /tmp/banyandb-test-3730832528/stream/default/shard-0/seg-20221113/block-06/inverted/0000000000b0.seg: no such file or directory" module:STREAM.INDEX-WRITER
```

found from https://github.com/apache/skywalking-banyandb/actions/runs/3456730645/jobs/5769676271#step:10:796

### What you expected to happen

There is no error in closing a sharding

### How to reproduce

Run slow test cases defined in https://github.com/apache/skywalking-banyandb/actions/workflows/slow-test.yml

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
More error:
```
  panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbbf4ab]

goroutine 10125 [running]:
github.com/dgraph-io/badger/v3.(*memTable).IncrRef(...)
    /go/pkg/mod/github.com/!sky!a!p!m/badger/v3@v3.0.0-20220817114744-b3711444d876/memtable.go:231
github.com/dgraph-io/badger/v3.(*DB).getMemTables(0xc000470000)
    /go/pkg/mod/github.com/!sky!a!p!m/badger/v3@v3.0.0-20220817114744-b3711444d876/db.go:712 +0x12b
github.com/dgraph-io/badger/v3.(*TSet).Get(0xc001252a58, {0xc0d6e2c1a0, 0x19, 0x19}, 0x172a3ac2bf324800)
    /go/pkg/mod/github.com/!sky!a!p!m/badger/v3@v3.0.0-20220817114744-b3711444d876/tset.go:81 +0xa5
github.com/apache/skywalking-banyandb/banyand/tsdb.(*item).Family(0xc0c7b6f220, {0xc0cd4a3d88?, 0xc00049a020?, 0x9?})
    /src/banyand/tsdb/series_seek.go:132 +0x53
github.com/apache/skywalking-banyandb/banyand/measure.(*measure).ParseTagFamily(0xc003e22f00, {0xc06f842110, 0x7}, {0x193de38, 0xc0c7b6f220})
    /src/banyand/measure/measure_query.go:117 +0xac
github.com/apache/skywalking-banyandb/pkg/query/logical.ProjectItem({0x7fcb6b1b4f38, 0xc003e22f00}, {0x193de38, 0xc0c7b6f220}, {0xc0b4973110, 0x2, 0x0?})
    /src/pkg/query/logical/common.go:75 +0x126
github.com/apache/skywalking-banyandb/pkg/query/logical/measure.transform({0x193de38, 0xc0c7b6f220}, {{0x7fe73c03ef20, 0xc003e22f00}, {0xc0b4973110, 0x2, 0x2}, {0xc15508c988, 0x1, 0x1}})
    /src/pkg/query/logical/measure/measure_plan_indexscan_local.go:297 +0x92
github.com/apache/skywalking-banyandb/pkg/query/logical/measure.(*indexScanIterator).Next(0xc0c3508000)
    /src/pkg/query/logical/measure/measure_plan_indexscan_local.go:220 +0xc6
github.com/apache/skywalking-banyandb/pkg/query/logical/measure.(*limitIterator).Next(0xc0d5c205e0)
    /src/pkg/query/logical/measure/measure_plan.go:114 +0x78
github.com/apache/skywalking-banyandb/banyand/query.(*measureQueryProcessor).Rev(0xc000382570, {0x172a4a34367748e3?, {0x14ca100?, 0xc0595da900?}})
    /src/banyand/query/processor.go:171 +0x9a5
github.com/apache/skywalking-banyandb/pkg/bus.(*Bus).Subscribe.func1({0x1926460, 0xc000382570}, 0x0?)
    /src/pkg/bus/bus.go:224 +0xaf
created by github.com/apache/skywalking-banyandb/pkg/bus.(*Bus).Subscribe
    /src/pkg/bus/bus.go:220 +0x38b

 
```
